### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [beautify-web/js-beautify#1008]
Hi @einars @bitwiseman ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
Now I guess the files need to be added in cdnjs as following:
- js/lib/beautify.js
- js/lib/beautify-css.js
- js/lib/beautify-html.js

Could you please confirm if there is any other files need to be added in cdnjs? 
Thank you.

https://github.com/cdnjs/cdnjs/issues/8518

**Comment by bitwiseman** [comment]
@pvnr0082t - Yes, those are the three files that need to be added. 

Thanks for taking the time to do this.  If there's anything I can do to help, just say so.
