### ISSUE TITLE
First of all thank you

### ISSUE THREAD

**Issue by wangjkRD** [beautify-web/js-beautify#1011]
When I use python jsbeautify. My js code with ' \" 'and' \n' , but all of '\'will be converted into' \\"' and '\\n'.Would you help me .

**Comment by bitwiseman** [comment]
You're welcome.  Please do the following: 
* describe how you called jsbeautify (command-line or part of another product).  
* provide a copy of your settings.
* provide a sample of your input, expected output, and actual output
* Please try your input on http://jsbeautifier.org.

**Comment by bitwiseman** [comment]
@WJK1992 Ping?
