### ISSUE TITLE
Support editorconfig for stdin

### ISSUE THREAD

**Issue by maksimr** [beautify-web/js-beautify#1012]
This allow use option '--editorconfig' in vim and emacs for formatting only part of the file.
Also, in emacs web-beautify [uses `stdin`](https://github.com/yasuyk/web-beautify/blob/master/web-beautify.el#L73) for beautifying

https://github.com/beautify-web/js-beautify/pull/969/files#diff-8c7aefb8e544b3bdebcdac9ce6f0e770R342

https://github.com/beautify-web/js-beautify/pull/969 relates

**Comment by bitwiseman** [comment]
See #1072 for good example. 

@maksimr - How does if you look at #1072, you'll see the only part of the editorconfig that would be supported would be the `[*]` type.
