### ISSUE TITLE
Bad output generator function in class

### ISSUE THREAD

**Issue by Verdier** [beautify-web/js-beautify#1013]
# Description

The shorthand object notation of generator functions is badly formatted since version 1.6.3
# Input

``` js
let a = {
 * myFunction() {
 }
}
```
# Expected Output

``` js
let a = {
 * myFunction() {
 }
}
```
# Actual Output

``` js
let a = {
 *
 myFunction() {
 }
}
```
## Settings

```
{
                spaceAfterAnonFunction: true,
                indentCase: false,
                braceStyle: 'collapse-preserve-inline'
}
```

**Comment by bitwiseman** [comment]
@Verdier - Have you tried v1.6.4.  This should be fixed there.

**Comment by Verdier** [comment]
@bitwiseman yes you are true, the case with object notation is fixed, but the following remain in 1.6.4:

```js
class A {
    fn() {
        return true;
    }

    * gen() {
        return true;
    }
}
```
result in:
```js
class A {
    fn() {
        return true;
    }

    *
    gen() {
        return true;
    }
}
```

**Comment by bitwiseman** [comment]
Thanks!

**Comment by jwhitmarsh** [comment]
Does anyone have a work around for this?

**Comment by bitwiseman** [comment]
@jwhitmarsh - One work around is to set `operator_position` to `preserve-newline`.  
The beautifier is treating the `*` in this case as a multiply operator, so that setting will make it leave operators where they are.  But the side effect is other operators are not repositioned.
