### ISSUE TITLE
New issue template

### ISSUE THREAD

**Issue by retan** [beautify-web/js-beautify#1019]
Your new issue template has a little mistake, but one that could lead to some serious misunderstandings.
```
# Expected Output
<INSERT CODE HERE>

# Actual Output
The beautified code should have looked like:
<INSERT CODE HERE>
``` 

I think that `The beautified code should have looked like:` should be below Expected Output, and not Actual Output. ;)

**Comment by bitwiseman** [comment]
@retan - you can create a pull request for this. 😄

**Comment by retan** [comment]
@bitwiseman I've never done that. :stuck_out_tongue_closed_eyes:  
Not today. I'm under a deadline and still hell of lot work ahead of me.
