### ISSUE TITLE
if else statement without curly brace gives a line break after else

### ISSUE THREAD

**Issue by Bram-Zijp** [beautify-web/js-beautify#1022]
Original image:
https://cloud.githubusercontent.com/assets/20819332/18256428/8a911112-73b5-11e6-8966-8941bcdd157e.png

Edit:
text input:
```
    $('.search-field').on('focus blur', e => {
        const par = $(e.target).parent();
        if( e.type === 'focus' )
            par.addClass('toggled')
        else
            par.removeClass('toggled')
    })
```

expected output:
```
    $('.search-field').on('focus blur', function(e) {
        var par = $(e.target).parent();
        if (e.type === 'focus')
            par.addClass('toggled');
        else
            par.removeClass('toggled');
    });
```

actual output:
```
    $('.search-field').on('focus blur', function(e) {
        var par = $(e.target).parent();
        if (e.type === 'focus')
            par.addClass('toggled');
        else

            par.removeClass('toggled');
    });
```

**Comment by bitwiseman** [comment]
@Bram-Zijp - Please replace your screenshots with text for input, expected output and actual output.

**Comment by bitwiseman** [comment]
@Bram-Zijp - Thanks for the update.  
When I try this on http://jsbeautifier.org/ , I do not get a repro.
What editor are you using that gets this output?

**Comment by Bram-Zijp** [comment]
@bitwiseman 
I use Atom and gulp+babel. Your comment got me thinking and after some testing i found out babel is the reason with the option retainLines: true. I should have tested this before posting.

From here on i think all that i would like to achief is a mather of personal preference and might have to be directed towards Stackoverflow.

e.g.

input:
```
daisy.chain().like().this();

if (bla === blabla) hello.world;else goodbye.world;
```
output with 'break lines on chained methods' option:
```
daisy.chain()
    .like()
    .this();

if (bla === blabla) hello.world;
else goodbye.world;
```

expected output:

```
daisy
    .chain()
    .like()
    .this();

if (bla === blabla)
    hello.world;
else
    goodbye.world;
```
