### ISSUE TITLE
The object with spread object formatted not correctly

### ISSUE THREAD

**Issue by lawrsp** [beautify-web/js-beautify#1023]
# Description

the object spread formatted not correctly
# Input

```
const item = { a:1, b:2 };
const m = {  ...item, c:3 };
```
# Expected Output

```
const item = { a: 1, b: 2 };
const m = { ...item, c: 3 };
```
# Actual Output

```
const item = { a: 1, b: 2 };
const m = {...item, c: 3 };
```

lost a space between`{`  and `...item`
# Steps to Reproduce

I user sublime text with jsformat, set format on save

wirte the code and save
# Environment

OS: MacOS 
Program: Sublime text 3
# Settings

```
{
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 4,
    "space_in_paren": false,
    "jslint_happy": false,
    "brace_style": "collapse-preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "eval_code": false,
    "unescape_strings": false,
    "break_chained_methods": false,
    "e4x": true,
    "wrap_line_length": 0,
    "end_with_newline": true,
    "editorconfig": true,

    // jsformat options
    "format_on_save": true,
    "format_selection": true,
    "jsbeautifyrc_files": true,
    "ignore_sublime_settings": true,
    "format_on_save_extensions": ["js", "json", "jsx"]
}
```

has no jsbeautifyrc

**Comment by bitwiseman** [comment]
es6 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by lawrsp** [comment]
yes, 
that is not in es6 standard and just a proposal now...
however, it is very common in React + Redux development
In the document of Redux, it is suggested to use this pattern.

As Redux is becoming more and more popular, is it great to support that ?

**Comment by bitwiseman** [comment]
@lawrsp - Yes, I see that here:
http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html

Thanks.

**Comment by luckyyang** [comment]
+1
I also got this error:

`      <Component {...newProps} />`
will into:

```
      < Component {...newProps }
      />
```
if do format for the entire file, will get: 
```
<
      Component {...newProps }
      />
```

**Comment by luckyyang** [comment]
add `e4x: true` into js and jsx part of `config.cson` file will solve the problem
