### ISSUE TITLE
indent_with_tabs not working on JS file.

### ISSUE THREAD

**Issue by CarlosMed** [beautify-web/js-beautify#1029]
# Description

What seems to happen is that in the JS file it keeps on beautifying in spaces when i have indent_with_tabs enabled but it works with HTML. Can't seem to find the issue as to whats causing it to keep indentation with spaces instead of tabs. 
# Expected Output

The code should have looked like this after beautification:

```
Indentation with tab instead of spaces
```
# Actual Output

The  code actually looked like this after beautification:

```
indentented with spaced instead of tabs
```
# Steps to Reproduce
## Environment

OS: Mac Yosemite in conjunction with Sublime Text 3
## Settings

Example:

``` json
  "js": {
    "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],

    "break_chained_methods": false,
    "e4x": false,
    "end_with_newline": false,
    "indent_char": " ", 
    "indent_level": 0,
    "indent_size": 4,
    "indent_with_tabs": true,
    "jslint_happy": false, 
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "max_preserve_newlines": 4,
    "preserve_newlines": true,
    "space_after_anon_function": false,
    "space_before_conditional": true,
    "space_in_empty_paren": true,    
    "space_in_paren": true,
    "unescape_strings": false,    
     "wrap_line_length": 0 
  }
```

**Comment by HookyQR** [comment]
Can not replicate with js-beautify `1.6.12`

**Comment by bitwiseman** [comment]
Thanks @HookyQR.

**Comment by lovespy** [comment]
This bug is not solved yet!

**Comment by bitwiseman** [comment]
@lovespy
This post is not helpful without more information.  Please describe how you were able to  reproduce the problem.
