### ISSUE TITLE
space_after_anon_function doesn't work with anon async functions

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1034]
Expected:

```
var c = async () {}
```
#608 related?

**Comment by bitwiseman** [comment]
Kinda related, but not really.  Functionally, this is an anonymous function so it should still be treated as such.  Is `async` es6?

**Comment by laggingreflex** [comment]
I like [ESLint's "space-before-function-paren"](http://eslint.org/docs/rules/space-before-function-paren) which covers all these (anon, named, anon async, named async) under one setting. Thoughts?

**Comment by bitwiseman** [comment]
@laggingreflex - seems reasonable.  We could use your help with this if you have the  time.

**Comment by xueqingxiao** [comment]
+1. Related: https://github.com/HookyQR/VSCodeBeautify/issues/129

**Comment by MacKLess** [comment]
I ran this in v1.8.6 and it appears to force a space between "async" and the following parens as default. @laggingreflex  and @xueqingxiao, please feel free to review this and let me know if you disagree. In the meantime, I'm going to mark this as resolved.
