### ISSUE TITLE
Update years in LICENSE

### ISSUE THREAD

**Issue by jseminck** [beautify-web/js-beautify#1038]
Hello,

License file is currently out of date:
`Copyright (c) 2007-2013 Einar Lielmanis and contributors.`
Could you please update to include recent years?

Thanks,

**Comment by bitwiseman** [comment]
Thanks for the issue.  I've been meaning to update, now I have an issue tracking it. 😄

**Comment by bitwiseman** [comment]
Updated license to next year and added myself to it.
