### ISSUE TITLE
HTML formatting wraps ending block tag for no reason with nested inline elements

### ISSUE THREAD

**Issue by garretwilson** [beautify-web/js-beautify#1041]
js-beautify leaves the following single HTML5 `<aside>` element untouched, as it should:

``` html
<aside><span class="foo">foo</span></aside>
```

If another inline element such as `<span>` is nested, it is expected that js-beautify should continue to leave the HTML touched, because nothing about the inline elements should cause newlines to be added:

``` html
<aside><span class="foo">foo <span class="bar">bar</span></span></aside>
```

However js-beautify incorrectly adds a newline before the `</aside>` end-tag:

``` html
<aside><span class="foo">foo <span class="bar">bar</span></span>
</aside>
```

There is no reason for such behavior; it is a bug. It can be verified merely by pasting and formatting in the main input field at http://jsbeautifier.org/ .

(Note that syntax highlighter on that page can't correctly show formatting colors for this simple sequence of elements, but that likely is a separate issue and may not relate to this bug.)

**Comment by bitwiseman** [comment]
The syntax highlight is provided by another product.

**Comment by HookyQR** [comment]
This is the double span issue mentioned elsewhere. It's not actually `span`s fault. It's caused by unformatted tags not identifying nested tags of the same name. The outer `<span>` considers the first `</span>` to be it's closing tag. You can duplicate the problem by replacing `span` with `output` for instance.

**Comment by bitwiseman** [comment]
@HookyQR - Oh.  Yeah. Good catch, thanks. That'll help.
