### ISSUE TITLE
end brace with next comment line make bad indent

### ISSUE THREAD

**Issue by luobotang** [beautify-web/js-beautify#1043]
# Input

The code looked like this before beautification:

```
var o = {
    k: 0
}
// ...
foo(o)
```
# Expected Output

```
var o = {
    k: 0
}
// ...
foo(o)
```
# Actual Output

```
var o = {
        k: 0
    }
    // ...
foo(o)
```
## Settings

Example:

``` json
{
    "brace_style": "collapse"
}
```

**Comment by bitwiseman** [comment]
The proposed fix for #1069 would also handle this.  The comment would stick to the element below and match the indent there.  It would also not be part of the preceding statement, fixing the over-indent there.
