### ISSUE TITLE
Explaination of 'operator_position' is absent from README.md

### ISSUE THREAD

**Issue by abbotto** [beautify-web/js-beautify#1047]
# Description
- An explaination of [operator_position](https://github.com/beautify-web/js-beautify/pull/735/commits/d83308d87e4055ba1c0f7f6f87bb57e707732ac0) and it's options are absent fom the [readme](https://github.com/beautify-web/js-beautify/blob/master/README.md) file.
- Options can be found in [beautify.js#L212](https://github.com/beautify-web/js-beautify/blob/d8315c9d41ae5314b459bab1b1c11f51a2839030/js/lib/beautify.js#L212)

**Comment by bitwiseman** [comment]
@abbotto  or @olsonpm - Could you provide a PR with the update?

**Comment by olsonpm** [comment]
@bitwiseman for sure.  Give me a couple days to find some time.  I'm knee deep in some react code atm.

**Comment by bitwiseman** [comment]
@olsonpm - Thanks! No hurry.

**Comment by olsonpm** [comment]
Ah - this is why I left it out in the readme:

https://github.com/beautify-web/js-beautify/pull/735#issuecomment-179407967

>  I looked at the readme and couldn't figure out why some cli options were left out so I'll leave it be for now.

Sorry for not putting a reminder to get that in prior to the merge @abbotto .  I appreciate the issue because I do try to prioritize documentation.

I'll have a PR soon
