### ISSUE TITLE
[Errno 12] Not enough space

### ISSUE THREAD

**Issue by AydinChavez** [beautify-web/js-beautify#1048]
Hi,

when running the js-beautifier on a 64 bit windows 7 machine with 8 gb ram, I get following on a 55 kb js file:

`C:\Users\X\python27\Scripts>python js-beautify my.js
``**[Errno 12] Not enough space**`

On a smaller 26 kb file however it works.

**Comment by bitwiseman** [comment]
Is your version of python 32-bit or 64-bit? 
Have you tried this with python 3?
