### ISSUE TITLE
Allow different styles for Javascript and JSON

### ISSUE THREAD

**Issue by lbssousa** [beautify-web/js-beautify#1051]
# Description
Currently [js-beautify](https://github.com/beautify-web/js-beautify) seems to treat `*.js` and `*.json` files equally in `.jsbeautifyrc` config file (there's a single `"js"` section for both Javascript and JSON formats).

I would like to set different options for Javascript and JSON, like the example below:

```json
{
  "js": {
    "indent_size": 4,
  },
  "json": {
    "indent_size": 2,
  }
}
```

**Comment by bitwiseman** [comment]
See #729
