### ISSUE TITLE
Issue with Browser Instructions

### ISSUE THREAD

**Issue by CodeLenny** [beautify-web/js-beautify#1053]
Hi,
README.md points to the following scripts for loading js-beautify in the browser:

```html
<script src="https://cdn.rawgit.com/beautify-web/js-beautify/1.6.4/js/lib/beautify.js"></script>
<script src="https://cdn.rawgit.com/beautify-web/js-beautify/1.6.4/js/lib/beautify-css.js"></script>
<script src="https://cdn.rawgit.com/beautify-web/js-beautify/1.6.4/js/lib/beautify-html.js"></script>
```

I think the URL should have `v1.6.4` for the branch name instead of `1.6.4`.

In addition, I think it would be helpful to mention that the scripts load `function html_beautify`, etc. as that wasn't obvious to me when I was trying to use the scripts.  (I ended up reading the source to find the function name).

**Comment by bitwiseman** [comment]
Cool, could you put in a PR with those changes?
