### ISSUE TITLE
String breakline for # String

### ISSUE THREAD

**Issue by halallahh** [beautify-web/js-beautify#1061]
How can I prevent breakline for hashtag with string? (eg: # pen apple)

# Input
The code looked like this before beautification:
```
# string
```

# Expected Output
The code should have looked like this after beautification:
```
# string
```

# Actual Output
The  code actually looked like this after beautification:
```
#
string
```

**Comment by bitwiseman** [comment]
Which language?  What is the code around this?

**Comment by halallahh** [comment]
Javascript. code Template literals like this:

```javascript
const demo = `
# demo
# demo1
`;
```

**Comment by bitwiseman** [comment]
I cannot reproduce this  issue on http://jsbeautifier.org/.  Closing.
