### ISSUE TITLE
Suggestion/Feature: Implement settings the Sublime way

### ISSUE THREAD

**Issue by stdedos** [beautify-web/js-beautify#1067]
Hello.

I just trying to offer my .02c regarding the settings. The way they are implemented right now is kinda tricky and kinda time-consuming to use.

Could you move to a more "Sublime" way of the settings?

TL;DR:
Preferences --> Settings opens a split wihdow, defaults on the right, user-editable settings on the left side.
Settings should be saved as *.sublime-settings file to ensure color formatting (or as a JSON file at least).
Require of user to do nothing (ie "find" his personal settings folder) or manually open/save files (refers to 1. mostly)

**Comment by bitwiseman** [comment]
It sounds like you're using a sublime plugin that uses this library.  Probably something they need to implement.

**Comment by stdedos** [comment]
Oh shoot .... I am terribly sorry, I totally mixed Git links :/
