### ISSUE TITLE
Breaks if html file starts with comment

### ISSUE THREAD

**Issue by DorukUlucay** [beautify-web/js-beautify#1068]
# Breaks if the first line of html is a comment
> Having a comment at the start of an html file may be unusual but in this case i have. And when i wanted to format it, the html file code became corrupt.

> I could just format and add the comment later, or i could carry comment elsewhere but after all, a bug is a bug and here i am.

# Input
The code looked like this before beautification:
```
<!--sample comment -->
<html>
<body>
  <span>a span</span>
</body>
</html>
```

# Expected Output
```
<!--sample comment -->
<html>
<body>
  <span>a span</span>
</body>
</html>
```

# Actual Output
The  code actually looked like this after beautification:
```
<!--sample comment -->
<
html >
    <
    body >
    <
    span > a span < /span> <
    /body> <
    /html>
```

**Comment by bitwiseman** [comment]
This only happens on http://jsbeautifier.org/, in the the beautifier core.  

It is caused by `looks_like_html` [here](https://github.com/beautify-web/js-beautify/blob/master/index.html#L301).
