### ISSUE TITLE
How to make js-beautify --editorconfig work well when using bash pipeline.

### ISSUE THREAD

**Issue by hujianxin** [beautify-web/js-beautify#1072]
# Description
In my project, there is a `.editorconfig` file and a `.jsbeautifyrc` file. 

The content of  `.editorconfig` is:
```
root = true

[*]
indent_style = space 
indent_size = 2
```

The content of `.jsbeautifyrc` is:
```
{
  "editorconfig": true
}
```

If I use command `js-beautify app.js`, the output code will be indented with 2 space.
If I use command `cat app.js | js-beautify`, the output code will not change to 2 space. Same that when using shell pipeline, js-beautify won't read `.editorconfig` file.

# Input
The code looked like this before beautification:
```
if (true) {
    something;
}
```

# Expected Output
The code should have looked like this after beautification:
```
if (true) {
  something;
}
```

# Actual Output
The  code actually looked like this after beautification:
```
if (true) {
    something;
}
```

# Steps to Reproduce

## Environment
OS:
ubuntu 16.04 64bit

**Comment by bitwiseman** [comment]
Duplicates #1012.
