### ISSUE TITLE
Wrong indentation for comment after nested unbraced control constructs

### ISSUE THREAD

**Issue by gagern** [beautify-web/js-beautify#1079]
# Description
When nesting multiple control constructs (like `if` or `for`) nesting increases with each of them. When there is a comment following that, it gets indented at the level of the last control construct. Which in my opinion is even stranger than if it were indented with the level of the final leaf statement that is not a control construct.

# Input and Expected Output
The code looked like this before beautification, and should have looked like this after beautification as well:

```js
if (console.log)
    for (var i = 0; i < 20; ++i)
        if (i % 3)
            console.log(i);
// all done
console.log("done");
```

# Actual Output
The  code actually looked like this after beautification:

```js
if (console.log)
    for (var i = 0; i < 20; ++i)
        if (i % 3)
            console.log(i);
        // all done
console.log("done");
```

# Steps to Reproduce

I first observed this using the js-beautify@1.6.4 npm package.
But I can reproduce this on http://jsbeautifier.org/ right now, with default settings.

**Comment by bitwiseman** [comment]
So many ways comments can go off the rails.

**Comment by gagern** [comment]
Thanks for the quick fix here, particularly at this time of the year! ❤️

Although https://github.com/beautify-web/js-beautify/issues/1090#issuecomment-269631990 suggests that unfortunately this is not the end of the story yet, since the fix here made issues reported there considerably more severe. 😢
