### ISSUE TITLE
Extra newline is inserted after beautifying code with anonymous function

### ISSUE THREAD

**Issue by alundiak** [beautify-web/js-beautify#1085]
# Description
Beautifying introduce extra new line in code. But I'm not sure it's bug.

# Input
The code looked like this before beautification:
```
this.model.myMethod().then(function() {
	// code
}).catch(
	function() {
		// code
	}
);
```

1 empty line after `catch(` and before `function() {`

# Expected Output
Now I am not sure what is expected.

# Actual Output
The  code actually looked like this after beautification:

```
this.model.myMethod().then(function() {
	// code
}).catch(

	function() {
		// code
	}
);
```

# FYI 
Such code is not changed by Beautifying:

```
this.model.myMethod().then(function() {
    // code
}).catch(function() {
    // code
});
```

# Steps to Reproduce
* Install usage of grunt-jqbeautifier v 0.2.7 (it has dependency written in form `"js-beautify": ">=1.4.2",`)
* Verifiy that jsbeautifer installed 1.6.6

## Environment
OS: Windows. 
NodeJS 4.4.0, npm 2.4.12, grunt v 0.4.5

## Settings
Example:
default by jsbeautify `jsbeautifyrc`
```
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

My codebase grunt task:

```
jsbeautifier: {
	files: [srcDir + '/**/*.js', '!' + bowerDir + '/**', testDir + '/**/*.js'],
	options: {
		js: {
			indentWithTabs: true
		}
	}
},

```

Not sure, but maybe it's somehow related to the same cause as in #1060 or  described.

**Comment by wcarmon** [comment]
+1  (we are experiencing the same)

**Comment by bitwiseman** [comment]
@alundiak -
Thank you for the high-quality bug report. 

`function` declarations that are not on the same line as the parenthesis are suppose to have a blank line before them.   

For example, In a statement block:
```js
a();

function a() {
    // Do stuff
}

function b() {
    // Do stuff
}

function c() {
    // Do stuff
}
```

I can see how, as a parameter of a method call, this might not be ideal.  

@wcarmon - I see the same behavior between 1.6.6 and 1.6.4 for the given input.  Please clarify.

**Comment by gagern** [comment]
Another use case where I'd rather avoid newlines is when writing fallback functions like this:

```js
var transformer =
    options.transformer ||
    globalSettings.transformer ||
    function(x) {
        return x;
    };
```

I'd say a function should have a preceding newline if it is either declared in a statement, or used in an expression which is of the simple form `‹LHS› = function(…) {…}`. Everything else should have newlines as given in the original code. This should cover uses of a function as an argument, or inside expressions like my `||` chain.

By the way, I too see this issue here and #1090 in our actual code base with 1.6.7 while 1.6.2 has no such issues. I've not yet worked out what aspect of the surrounding code makes this a new problem.

**Comment by gagern** [comment]
I did a quick git bisect. Both the original example and my test case got broken by 5fb9542908de25b9d8fef22f4c66dfce8c25eb4b for 1.6.5.

**Comment by alundiak** [comment]
@bitwiseman Can we assume/treat mentioned SHA by @gagern as a bug in jsbeautify and it will be fixed in nearest release? Or this described behavior by me is closer to standard behavior pf new jsBeautifier?

PS: How I spotted on this. I had setup of node modules, including grunt-jsbeautifier, and based on version setting of jsbeautify as dependency I receive new release when I did my project clean setup. Image my surprise, when a few files were beautified in a bit different way. So now I decide what the standard is/should be.

**Comment by bitwiseman** [comment]
@gagern - Again, good example and well said. 
@alundiak - between your and gagern's examples, this case is definitely a bug, but I want to make sure we don't break related cases while fixing this.  

Just to clarify, you'd like this to be unchanged:  
```js
this.model.myMethod().then(function() {
	// code
}).catch(
	function() {
		// code
	},
	function() {
		// code
	}
);
```
