### ISSUE TITLE
Formatting breaks apart unquoted attribute

### ISSUE THREAD

**Issue by yerlaser** [beautify-web/js-beautify#1094]
# Description
In my HTML file I have a div with id attribute with a space after equal sign.
After format the id gets tears off the first letter and joins to the equal sign.
# Input
The code looked like this before beautification:
```
<div id= someid>
```

# Expected Output
The code should have looked like this after beautification:
```
<div id=someid>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div id=s omeid>
```

# Steps to Reproduce

Create any HTML with an div like above and format.

## Environment
OS: Linux

## Settings
Example:
```json
{
}
```

**Comment by bitwiseman** [comment]
Unquoted attribute?  What specification is that part of?

**Comment by yerlaser** [comment]
I don't know about the spec, but it works.
After running through js-beautify, however, it breaks.
I think a code formatter should never break a working code.
Luckily, in this case the bug was easy to spot, but if it were a larger file, it could've been harder.

**Comment by bitwiseman** [comment]
https://www.w3.org/TR/html51/introduction.html#ref-for-unquoted-1

**Comment by bitwiseman** [comment]
Not fixed in rc6, but no longer completely broken.  This remains unchanged:
```
<div id= someid>
```
