### ISSUE TITLE
Need comment line breaking help

### ISSUE THREAD

**Issue by therakib7** [beautify-web/js-beautify#1096]
Hello,
This is an awesome plugin to beautify but I need a help.
When beautify any HTML file, Comment beautify like this.
```
</div>
<!--/.container-->
```
But I need this beautify like this 
```
</div><!--/.container-->
```
That's mean I don't need line break before comment.

Is there any way to solve my problem?
Advance Thanks

**Comment by bitwiseman** [comment]
@therakib7 
When I enter the value above on http://jsbeautifier.org/ it remains unchanged.

**Comment by barrywise** [comment]
He means when you enter this:

`</div><!--/.container-->`

He wants it maintained. Instead it adds a newline before the comment, so it beautifies to this:

```
</div>
<!--/.container-->
```

 I was going to ask this same question, is there anyway to prevent the newline before the comment?

**Comment by bitwiseman** [comment]
See #1337
