### ISSUE TITLE
invalid indentation for html code

### ISSUE THREAD

**Issue by ChandraKantPaliwal** [beautify-web/js-beautify#1098]
# Description
when i indent code then wrong indentation done in html. In this end tag keep in same line

The results of beautification are not what I expect.
proper indetation like with end tag
# Input Before Beautification

This is what the code looked like before:

```
<lil-spinner ng-show="mycoursesCtrl.isAPICall"></lil-spinner>
<div ng-if="mycoursesCtrl.courses.length > 0">
  <div class="lil-card-fluid-container"
    ng-repeat="_c in mycoursesCtrl.courses">
      <lil-card ng-click="mycoursesCtrl.openCourse(_c.id, _c.type, _c.microCourseType)" thumbnail="_c.thumbnail.thumb"
        course-title="_c.title"
        curator="_c.name"
        meta-information="_c.metaInformation"
        avg-rating="_c.avgRating"
        course-type="_c.courseType || _c.microCourseType"
        published-date="_c.publishedDate">
        </lil-card>
      </div>
</div>

```

# Expected Output

The beautified code should have looked like this:

```
<lil-spinner ng-show="mycoursesCtrl.isAPICall"></lil-spinner>
<div ng-if="mycoursesCtrl.courses.length > 0">
  <div class="lil-card-fluid-container"
    ng-repeat="_c in mycoursesCtrl.courses">
    <lil-card ng-click="mycoursesCtrl.openCourse(_c.id, _c.type, _c.microCourseType)" thumbnail="_c.thumbnail.thumb"
      course-title="_c.title"
      curator="_c.name"
      meta-information="_c.metaInformation"
      avg-rating="_c.avgRating"
      course-type="_c.courseType || _c.microCourseType"
      published-date="_c.publishedDate">
      </lil-card>
    </div>
</div>
```

# Actual Output

The beautified code actually looked like this:

```
<lil-spinner ng-show="mycoursesCtrl.isAPICall"></lil-spinner>
<div ng-if="mycoursesCtrl.courses.length > 0">
  <div class="lil-card-fluid-container"
    ng-repeat="_c in mycoursesCtrl.courses">
    <lil-card ng-click="mycoursesCtrl.openCourse(_c.id, _c.type, _c.microCourseType)"
  
      thumbnail="_c.thumbnail.thumb"
      course-title="_c.title"
      curator="_c.name"
      meta-information="_c.metaInformation"
      avg-rating="_c.avgRating"
      course-type="_c.courseType || _c.microCourseType"
      published-date="_c.publishedDate">
      </lil-card>
</div>
</div>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ChandraKantPaliwal/7de186605549618072eb7c08478f48c5

# Checklist

I have:
- [true] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [true] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [true] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [true] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [true] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by HookyQR** [comment]
is fixed in #1131
