### ISSUE TITLE
Missing space between "else" and "if".

### ISSUE THREAD

**Issue by marinabilles** [beautify-web/js-beautify#1107]
# Description

I use emscripten and [binaryen](https://github.com/WebAssembly/binaryen) to produce a js file that includes an interpreter for WebAssembly for testing WebAssembly code in node.js. When beautifying the generated JavaScript file with js-beautify, an `else if` construct in the code is rendered as `elseif` in the output.

Using js-beautify version `1.6.8`.

# Input
The code looked like this before beautification:
```javascript
function f(a) {c: do if (x) {} else if (y) {} while(0); return 0;}
```

# Expected Output
The code should have looked like this after beautification:
```javascript
function f(a) {
    c: do
        if (x) {}
        else if (y) {}
    while (0);
    return 0;
}
```

# Actual Output
The  code actually looked like this after beautification:
```javascript
function f(a) {
    c: do
        if (x) {} elseif (y) {}
    while (0);
    return 0;
}
```

# Steps to Reproduce

## Environment
OS: Ubuntu 16.04

## Settings
Default settings

**Comment by bitwiseman** [comment]
A couple problems: 
1. I don't the same output using the website.  
```
function f(a) {
    c: do
            if(x) {}
        else
        if(y) {}while(0);
    return 0;
}
```
2. Is this valid javascript? That `c:` looks out of place.

**Comment by marinabilles** [comment]
When copying my code from above to http://jsbeautifier.org/, I actually see the incorrect output, not the one you posted. What could be different?

![jsbeautifier org](https://cloud.githubusercontent.com/assets/5391834/21889767/d9dbe16e-d8ca-11e6-8056-7c3c43dedccc.png)


The `c:` is a [label](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label), used for jumping out of nested loops.

**Comment by bitwiseman** [comment]
Label, got it.  In this case that label is never used, but okay. 
I can reproduce this now, so that's good.  Thanks!
Added to the next release.

**Comment by marinabilles** [comment]
The label was used in the larger context, but I simplified the code down so it was more easily readable. Sorry about the confusion.

**Comment by bitwiseman** [comment]
@marinabilles - no problem.  Thanks for the simpler example.  😄
