### ISSUE TITLE
Nunjucks / Jinja / Django {% templates %} correct support?

### ISSUE THREAD

**Issue by softshape** [beautify-web/js-beautify#1110]
Right now the code like:

```
      </div>
      {% endfor %}
      {% if json.length == 5 %}
      <div class="col steps">&nbsp;</div>
      {% endif %}
    </div>
```

losts its linebreaks between template tags after formatting:

```
      </div>
      {% endfor %} {% if json.length == 5 %}
      <div class="col steps">&nbsp;</div>
      {% endif %}
    </div>
```

Any way to avoid that? This affects all {% %}, {# #}, and {{ }} tags.

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/pull/1104 might address your issue. Try it locally.

**Comment by softshape** [comment]
I'm using js-beautify via Visual Studio Code extension https://github.com/lonefy/vscode-js-css-html-formatter. So I've updated the source in C:\Users\username\.vscode\extensions\lonefy.vscode-JS-CSS-HTML-formatter-0.2.2\node_modules\js-beautify\ to the one downloaded from GitHub. 

No any changes, it still removes linebreak between two template tags.

**Comment by rtpm** [comment]
Any progress on this?

Tried with vscode as of today (26.09.2017) and the problem still exists 

If you need more info/debug let me know.

**Comment by bitwiseman** [comment]
No progress.  This needs someone to implement it.

**Comment by eromoe** [comment]
I have same problem
https://github.com/victorporof/Sublime-HTMLPrettify/issues/360#issuecomment-311429982

**Comment by york-xtrem** [comment]
I'm desperate! I've tried everything, I've tried things for Jinja2 and Twig but nothing. I don't know what to do...

**Comment by zellwk** [comment]
@bitwiseman any hints on how to implement something like this?

**Comment by koshkin-kna** [comment]
https://github.com/bennettaur/HTML-Template-Beautifier

**Comment by bitwiseman** [comment]
@koshkin-kna - no, sorry.  The project your referred to is *4 years* out of date from the current version of beautifier.

**Comment by Viscmad** [comment]
I am having this issue as well... :(

**Comment by MacKLess** [comment]
I just tried this code in v1.8.6 and it appears to no longer be an issue. @softshape do you want to double-check and let me know what you find? It does remove the indentation, but as that was not the issue with the original filed bug, I think it might be resolved.

**Comment by dancaron** [comment]
I am getting a linebreak after a {% in my django templates.

**Comment by bitwiseman** [comment]
@dancaron What input are you providing?  What version are you using?

**Comment by dancaron** [comment]
Input:
~~~
<div class="form-check form-check">
   <label class="form-check-label">
     <input class="radio" type="radio" v-model="jobPosition" value="1" {% if job.position.id == 1 %}checked{% endif %}>Full-Time
  </label>
</div>
~~~
Output:
~~~
<div class="form-check form-check">
    <label class="form-check-label">
        <input class="radio" type="radio" v-model="jobPosition" value="1" {% if
            job.position.id==1 %}checked{% endif %}>Full-Time
    </label>
</div>
~~~

Version: js-beautify 1.8.8 (vscode)

However: I noticed that if I use "format selection" the output does not include a line-break, and works as expected. If I use "format document" you will see the output as above.

**Comment by bitwiseman** [comment]
@dancaron  Try this on https://beautifier.io  (v1.9.0-beta 3).   It should be fixed now.
