### ISSUE TITLE
Space in paren behaviour (JSX files)

### ISSUE THREAD

**Issue by FacundoGFlores** [beautify-web/js-beautify#1112]
I have set "beautify on change", and I am currently using a linter for React (airbnb). So I have the following line in my code:

`import { Link } from 'react-router';`

But when I save the file it changes to:

`import {Link} from 'react-router';`

so, no spaces between curly braces. I tried to search some setting in atom and the only one that appear is "Space in paren" but if I activate it then I have another problem:

`const Error404 = () =>`

changes to:

`const Error404 = ( ) =>` 

and my linter warnings me.

How can I set up correctly it?

**Comment by bitwiseman** [comment]
When I enter this code in http://jsbeautifier.org/ (with "Preserve inline braces/code blocks?" checked), the input remains unchanged. 

What editor are you using?  It is likely that it is using an outdated version of the beautifier.

**Comment by FacundoGFlores** [comment]
I am using atom 1.13.0

**Comment by bitwiseman** [comment]
And what version of the beautifier plugin?

**Comment by FacundoGFlores** [comment]
js-beautify 1.6.3

**Comment by bitwiseman** [comment]
Current version is 1.6.8.  Update and this should be fixed.
