### ISSUE TITLE
js-beautify adds a space between # and include

### ISSUE THREAD

**Issue by ghost** [beautify-web/js-beautify#1114]
I'm using js-beautify when coding for Adobe After Effects that uses Javascript. The problem is that when I write #include js-beautify changes it to # include and breaks the code.
Is there a way to ignore # signs or another way to fix this or will it need to be done in the source-code?

Thanks!

**Comment by bitwiseman** [comment]
The ignore directive might work: 
https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only

Please provide an example input, expected output and actual output.

**Comment by utjduo** [comment]
# Input
The code looked like this before beautification:
```
#include "settings.jsxinc"
```

# Expected Output
The code should have looked like this after beautification:
```
#include "settings.jsxinc"
```

# Actual Output
The  code actually looked like this after beautification:
```
# include "settings.jsxinc"
```

Putting my includes between beautify preserve fixed the problem! I searched for a good hour but for some reason I missed beautify preserve.
Thanks!

**Comment by bitwiseman** [comment]
Note: the above is definitely not valid JavaScript, so it's not really a surprise that the beautifier doesn't handle it.   Where can I find the spec for this language?

**Comment by utjduo** [comment]
Here you have all documented info about Extendscript:http://download.macromedia.com/pub/developer/aftereffects/scripting/JavaScript-Tools-Guide-CC.pdf
I have used js-beautify for years with this language without problem except now with the #include

**Comment by bitwiseman** [comment]
I've pulled this into the next milestone.  Getting the #include back is a minor change.
