### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by kindkaktus** [beautify-web/js-beautify#1120]
# Description

Every now and then I get the following error. Js-beautify is used by the app implicitly by express-beautify 0.1.3 (as npm package)

```
 TypeError: Cannot read property 'replace' of undefined
 node_modules/js-beautify/js/lib/beautify-html.js:199
         html_source = html_source.replace(allLineBreaks, '\n');
```

## Environment
OS: Linux Debian 8.6 x64 (jessie)
js-beautify v1.6.3
node.js v4.7.0
npm v4.0.5

**Comment by bitwiseman** [comment]
What was your input?  
Also, note current version of beautifier is 1.6.8.

**Comment by kindkaktus** [comment]
Surprisingly is that the error is not reproducible on the same pages, but still happens now and then for different pages. 

js-beautify v1.6.3 is used by express-beautify 0.1.3 so I can't directly influence the version of js-beautify I use.
Still the fix seems simple: just surround the statement in question with if (...) guards:

```
if (html_source ) {
    html_source = html_source.replace(allLineBreaks, '\n');
 }
```

I applied this fix by hand and my webserver stopped crashing. But ofc it would be better it in the upstream.
