### ISSUE TITLE
New Object notations in ECMAScript 2015

### ISSUE THREAD

**Issue by IgorNovozhilov** [beautify-web/js-beautify#1121]
# Description
source: [developer.mozilla.org](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Object_initializer)

I propose to make whiter beautiful "Shorthand property names"

# Input
The code looked like this before beautification:
```js
/*jshint esnext:true */

// Shorthand property names (ES2015)
var a = "foo", b = 42, c = {};
var o = { a, b, c };

// example Array
var a = [ a, b, c ];
```

# Expected Output
The code should have looked like this after beautification:
```js
/*jshint esnext:true */
// Shorthand property names (ES2015)
var a = "foo",
    b = 42,
    c = {};
var o = {a, b, c};

// example Array
var a = [a, b, c];
```

Or use as "developer.mozilla.org":
```js
var o = { a, b, c };
```

# Actual Output
The  code actually looked like this after beautification:
```js
/*jshint esnext:true */
// Shorthand property names (ES2015)
var a = "foo",
    b = 42,
    c = {};
var o = {
    a,
    b,
    c
};

// example Array
var a = [a, b, c];
```

## Environment
OS: linux mint

js-beautify@1.6.8

## Settings
defaults from http://jsbeautifier.org

**Comment by bitwiseman** [comment]
On http://jsbeautifier.org check "Preserve inline braces/code blocks?" 

Then output is basically what you described: 
```js
/*jshint esnext:true */

// Shorthand property names (ES2015)
var a = "foo",
    b = 42,
    c = {};
var o = { a, b, c };

// example Array
var a = [a, b, c];
```

**Comment by IgorNovozhilov** [comment]
Thank you!
