### ISSUE TITLE
HTML: add an option to preserve manual wrapping of attributes

### ISSUE THREAD

**Issue by Andikki** [beautify-web/js-beautify#1125]
`--wrap-attributes` option has these possible values: `auto|force|force-aligned|force-expand-multiline`
This allows to whether condense all attributes into one line or auto-wrap each of them. 

Would it be possible to just maintain the initial wrapping?

**Comment by Robula** [comment]
This is a great idea, none of the options allow for wrapping manually.

It would be great to have an option that would perform `force|force-aligned|force-expand-multiline` only if the wrap line length (default 120) has been hit as `auto` wraps only as many attributes as it needs to. Something like `auto-expand-multiline|auto-aligned` options?

**Comment by bitwiseman** [comment]
@Robula 
Please open a new issue for what you have in your second paragraph.

**Comment by Montago** [comment]
i have a suggestion to expand this:

"auto-align" would only align those that are already manually wrapped.

**Comment by bitwiseman** [comment]
@Montago, @Andikki - what you are describing is an option named something like `unchanged` or `preserve`, correct?

**Comment by Montago** [comment]
@bitwiseman no, just another option like "Force-Aligned" ... but instead "auto-aligned"

What it should do, is simply to align all attributes that have been manually wrapped. 
all other elements / attributes are untouched.

**Comment by bitwiseman** [comment]
@Montago - Ah, so more like `align-only`.

**Comment by Montago** [comment]
yeah that makes sense :)

**Comment by roderickfung** [comment]
bump for this!

**Comment by neilshah2000** [comment]
Would be great to manually have some attributes on a new line and some on the same line. Then i can decide which one i want and everything else is automatically formatted. Thanks

**Comment by Andikki** [comment]
@bitwiseman I don't think aligning is necessary, but if it is, there have to be two options - one to apply the usual indent_size, another to align — all while keeping the initial line breaks.

**Example**
Source:
```html
<input type="text"     class="form-control"  autocomplete="off" 
      [(ngModel)]="myValue"          [disabled]="isDisabled" [placeholder]="placeholder" 
  [typeahead]="suggestionsSource" [typeaheadOptionField]="suggestionValueField" [typeaheadItemTemplate]="suggestionTemplate"   [typeaheadWaitMs]="300"
                        (typeaheadOnSelect)="onSuggestionSelected($event)" />
```

Forcing indentation only:
```html
<input type="text" class="form-control" autocomplete="off" 
  [(ngModel)]="myValue" [disabled]="isDisabled" [placeholder]="placeholder" 
  [typeahead]="suggestionsSource" [typeaheadOptionField]="suggestionValueField" [typeaheadItemTemplate]="suggestionTemplate" [typeaheadWaitMs]="300"
  (typeaheadOnSelect)="onSuggestionSelected($event)" />
```

Forcing alignment only:
```html
<input type="text" class="form-control" autocomplete="off" 
       [(ngModel)]="myValue" [disabled]="isDisabled" [placeholder]="placeholder" 
       [typeahead]="suggestionsSource" [typeaheadOptionField]="suggestionValueField" [typeaheadItemTemplate]="suggestionTemplate" [typeaheadWaitMs]="300"
       (typeaheadOnSelect)="onSuggestionSelected($event)" />
```

**Comment by waldnercharles** [comment]
Not sure if this is the right issue to request this, but I feel like the `auto-align` option should act like auto; wrapping after a certain column cutoff, and if a line wraps, it treats the tag like force-align.

**Example**
Force-align when line length is greater than wrapLineLength:
```html
<div [isWrapped]="false" [attributesAligned]="false"></div>

<really-long-angular-component-that-would-force-wrapping class="wrapped"
                                                         [isWrapped]="true"
                                                         [attributesAligned]="true">
```

**Comment by kaankucukx** [comment]
Almost surfed 5 or 6 topics where people looking forward to this feature to be implemented. Since its not, it would be great to have this on vscode with if wrap requries and force-alignment for this corresponding row vs.

😞

**Comment by bitwiseman** [comment]
@kaankucukx  Not sure what you mean?  Is it covered in previous examples?

**Comment by brokenalarms** [comment]
+1 for this, I currently have the best results with `force` for handlebars, but it still results in unwanted wrapping within my handlebars block:

```
   </label>
        {{#artdeco-hoverable-trigger placement="right"
          as
          |card|}}
```
and
```
  <ul class="text-ad-edit-panel__dropdown-list">
                {{#each yourCompanyPageTypes
                  as
                  |companyPageType
                  index|}}
```

**Comment by rwwagner90** [comment]
FWIW this does not work in any editor, that I have found, except for Intellij. Would love to see this implemented though!

**Comment by aimitservicesdev** [comment]
> FWIW this does not work in any editor, that I have found, except for Intellij. Would love to see this implemented though!

Works in Netbeans as well.

**Comment by rwwagner90** [comment]
@christoferd that's what this issue is about. It does not work. js-beautify is not capable of keeping the line breaks. It's going to always set it to one line.

I keep going back to using WebStorm because they have their own formatter and it works with line breaks.

**Comment by MacKLess** [comment]
Related to #1404

**Comment by rwwagner90** [comment]
Thanks for working on a fix @MacKLess! I'm anxiously awaiting a new release, so I can try it out 😃
