### ISSUE TITLE
newline after the end tag that was expected to formatted.

### ISSUE THREAD

**Issue by PYangDizzle** [beautify-web/js-beautify#1132]
# Input
The code looked like this before beautification:
```
<body>
    blah<h1>head</h1>blah
</body>
```

# Expected Output
The code should have looked like this after beautification:
```
<body>
    blah
    <h1>head</h1>
    blah
</body>
```

# Actual Output
The  code actually looked like this after beautification:
```
<body>
    blah
    <h1>head</h1>blah
</body>
```

# Steps to Reproduce
1. Write a tag that is supposed to be formatted. ( in the above case, the header 1 tag )
2. Surround the tag with plain text
3. Apply js-beautify

## Environment
OS: http://jsbeautifier.org/

## Settings
Any Settings

I was in the middle of testing vscode that I downloaded and noticed (personally) unexpected behavior. I'm not sure if this was intended or not.

I went through beautify-html.js and figured out that I could simply print newline after printing the tag_end, because unformatted tags or texts are considered to be comments.

I'm hoping I can request a pull. It will be my first GitHub contribution if I do.

Any thoughts are welcome.

**Comment by bitwiseman** [comment]
Pulll requests are welcome.  I don't think that is for sure correct behavior.  If that was a `<span>` or an `<a>`.  You would definitely not want a newline after it unless there was a space between the text and tag:

```
<body>
    blah <span>head</span> blah
</body>
```

Take a look at #841 for a discussion of the underlying problem.

**Comment by PYangDizzle** [comment]
@bitwiseman inline tags like <a> and <span> are defaulted to be "unformatted" and is inline. The link you provided me claims that "unformatted" and "inline" are different concept but I think they will end up with same behavior, unless we want all newline characters removed from the beginning of "inline" tags. However, if a user inserted a newline character, that should mean that the user wants it to be there.

**Comment by HookyQR** [comment]
If you manually insert a new line after the `<\h1>` tag, it will be kept there. If you don't, the code won't insert it for you. I think this is the best behaviour as any tag can be set as `inline` for the developer's particular use case, and adding white space could affect the presentation in that case.

**Comment by bitwiseman** [comment]
@HookyQR @PYangDizzle 

Inline elements are the name we've used for elements with [phrasing content model](https://www.w3.org/TR/html5/dom.html#phrasing-content-1) in html.  

See https://www.w3.org/TR/html5/dom.html#concept-html-contents
https://www.w3.org/TR/html5/dom.html#paragraph

Inline means the first two inputs produce the same layout in html, but the third does not:
```html
<!-- Note the space after 'Hello'. -->
<p><span>Hello <a>World</a>!<span></p>

<p>
     <!-- The 'p' tag uses flow content so ignores leading and trailing whitespace. -->
     <!-- Even though there is no space between p and span in the first example  -->
     <!-- the output for this second examle is unchanged. --> 
    <span>Hello
    <!-- Since there a space after 'Hello', any amount of whitespace can be added -->
    <!-- between it and the following 'a' tag. Phasing content  can  --> 
    <!-- still be reformatted by the beautifier, but with slightly different rules than  -->
    <!-- other content models. -->  
    <a>World</a>!<span>
</p>

<p><span>Hello 
    <a>World
    <!-- This output will differ from the previous two.  We added a whitespace to the a -->
    <!-- element contents.  The layout will show space between 'World' and '!' where -->
    <!-- there wasn't one before. --> 
    </a>!<span>
</p>

```

And all of the above differ from the concept of "unformatted" or "preformatted" elements. 

To go back to something like the original example, these two produce the same output:

```html
<body>blah<h1>head</h1><h2><a>hello</a></h2>blah</body>

<body>
    blah
    <h1>head</h1>
    <h2><a>hello</a></h2>
    blah
</body>
```

Heading tags flow content that contains phrasing content, but they are phrasing content themselves.


All this means this request is somewhere between a bug and an enhancement.  It's not correct behavior, but there are also some design and implementation details that make this a more involved undertaking to fix/improve.

**Comment by HookyQR** [comment]
While I agree with what you've said, the issue is around formatting the text _after_ the tag:
```html
<p><a>World</a>!</p>
<p><a>World</a>
!</span></p>
```
These two produce different output, and that is what I'm saying would cause a problem.

**Comment by bitwiseman** [comment]
@HookyQR  That's what I said above. 😄

**Comment by PYangDizzle** [comment]
I never really continued using VSCode and came back to this. I tried the same input in https://beautifier.io/ and it seems like the behavior changed to keep all the new line characters as possible and just fix indentation. I don't see any reason to keep this issue open.
