### ISSUE TITLE
Treats // in strings as a comment

### ISSUE THREAD

**Issue by gsechan** [beautify-web/js-beautify#1135]
I used the beautifier at jsbeuatifier.org  to beautify some minified JS for debugging.  Part of my input was

...long array here..., "//", "some other string", //another 3000 lines of code

The // and everything after it were taken as a comment.  // inside a string should not be.

Awesome tool though, just wish it didn't have that one bug that's killing me.

**Comment by bitwiseman** [comment]
@gsechan - Could you give an example?  (maybe not 3000 lines long) 😄
