### ISSUE TITLE
Mangled HTML tags with command line/python library

### ISSUE THREAD

**Issue by jbeukelman** [beautify-web/js-beautify#1136]
# Description
When using the command line js-beautifier or python library, HTML tags get mangled.  newlines are created immediately after the HTML opening tag.  Strange.  
This does not happen when pasting into the box on www.jsbeautifier.org website.  

# Input
The code looked like this before beautification:
snippet below taken from www.example.com
```
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;

```

# Actual Output
The  code actually looked like this after beautification:
```
< !doctype html >
    <
    html >
    <
    head >
    <
    title > Example Domain < /title>

<
meta charset = "utf-8" / >
    <
    meta http - equiv = "Content-type"
content = "text/html; charset=utf-8" / >
    <
    meta name = "viewport"
content = "width=device-width, initial-scale=1" / >
    <
    style type = "text/css" >
    body {
        background - color: # f0f0f2;

```

# Steps to Reproduce
1- go to www.example.com
2- view source and copy to local file. 
3- run js-beautifier <filename>

## Environment
OS: Linuxmint 17.3 with python 2.7.6.  have also tried a debian stretch machine with python 2.7.13 with the same result.  both with jsbeautifier 1.6.9

**Comment by bitwiseman** [comment]
There is not python version of the html beautifier.  See #205.
