### ISSUE TITLE
how to fix space-before-function-paren ?

### ISSUE THREAD

**Issue by 643364103** [beautify-web/js-beautify#1139]
# Description
> how to fix space-before-function-paren ?
> function foo (){}
the same as
#1077

**Comment by bitwiseman** [comment]
What do you mean by fix?  Please provide input, output, and expected.

**Comment by 643364103** [comment]
the same as 
https://github.com/beautify-web/js-beautify/issues/1077

**Comment by bitwiseman** [comment]
Cool, thanks.  Resolving as duplicate.
