### ISSUE TITLE
Omit newline before/after <head>/<body> tag

### ISSUE THREAD

**Issue by xuld** [beautify-web/js-beautify#1150]
Is there an option to omit newline before/after <head>/<body> tag?

# Input
```
<html>
<head></head>
<body></body>
</html>
```

# Expected Output
```
<html>
<head></head>
<body></body>
</html>
```

# Actual Output
```
<html>

<head></head>

<body></body>

</html>
```

if `indent_head_inner_html`/`indent_body_inner_html` is true, the new line seems useless.

**Comment by thilomaurer** [comment]
> -E, --extra_liners                 List of tags (defaults to [head,body,/html] that should have an extra newline before them.
```js
var options={
    html: {
        extra_liners: []
    }
}
```

**Comment by bitwiseman** [comment]
@thilomaurer - Thanks for pointing that out!
