### ISSUE TITLE
New line before next CSS selector every beautify run

### ISSUE THREAD

**Issue by ram-you** [beautify-web/js-beautify#1152]
Sorry for commenting on a closed issue.
Regression: The same as https://github.com/beautify-web/js-beautify/issues/1142 error occurred with the new version 0.8.9

**Comment by HookyQR** [comment]
This VSCodeBeautify version 0.8.9 which includes v1.6.11 of js-beautify

**Comment by ram-you** [comment]
https://github.com/octref/vetur/issues/82
