### ISSUE TITLE
Space after Function Name, Call Function.

### ISSUE THREAD

**Issue by EmpireWorld** [beautify-web/js-beautify#1161]
Hi. 

JS-Beautify does not supports indentation after after function names and called functions such as below:

**After Function Definition**:

```javascript
function sample() {}
//             ^ Should be one white space.
```

**Call Function**:

```javascript
console.log( "Example" );
//         ^ Should be one white space
```

Please add this option.

Thanks .
All the bests.

**Comment by bitwiseman** [comment]
The first item is already filed as issue #940.
The second is already implemented as `space-in-paren` option.

**Comment by EmpireWorld** [comment]
Thanks.
I wish a successful attempt for you and whole team.
