### ISSUE TITLE
SCSS Comment Issue

### ISSUE THREAD

**Issue by rgfx** [beautify-web/js-beautify#1165]
Comments in SCSS are getting sent to line before after update. Expected output? Is there a setting I need to change?

# Input
The code looked like this before beautification:
```
text-align: center;
    // height: auto;
// display: flex;
```

# Expected Output
The code should have looked like this after beautification:
```
text-align: center;
// height: auto;
// display: flex;
```

# Actual Output
The  code actually looked like this after beautification:
```
text-align: center;//height: auto;
// display: flex;
```

## Environment
OS: Windows 7 
Vscode 

## Settings
Everything is default. It didn't do this before.

**Comment by rgfx** [comment]
Found [vscode-stylesheet-beautify](https://marketplace.visualstudio.com/items?itemName=n23.vscode-stylesheet-beautify) for a temp fix.

**Comment by bitwiseman** [comment]
@rgfx - interesting.  That tool is using js-beautify `^1.6.8` internally.

**Comment by bitwiseman** [comment]
Got the following when running on jsbeautifier.org:
Start:
```
<style>
    text-align: center;
//height: auto;
    // display: flex;
</style>
```
First output:
```
<style>
    text-align: center;
    //height: auto;
    // display: flex;
</style>
```
Second output (when beautify called on first output):
```
<style>
    text-align: center; //height: auto;
    // display: flex;
</style>
```

**Comment by rgfx** [comment]
The extension I found before that was using ^1.6.8 updated :( Found this as a replacement for now. https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode you will have to regex your files. 

find: ; //
replace: ; \n //

**Comment by webberwang** [comment]
Getting this issue as well
