### ISSUE TITLE
Tags in javascript are being destroyed

### ISSUE THREAD

**Issue by irsdl** [beautify-web/js-beautify#117]
Hi,
I grabbed this sample from www.bbc.co.uk website (cookie confirmation section on top):

&lt;script type=&quot;text/html&quot; id=&quot;test&quot;&gt;
  &lt;![CDATA[ &lt;div id=&quot;mytag&quot;&gt; &lt;h2&gt; Test &lt;/h2&gt; &lt;p&gt; We use cookies&lt;/p&gt;&lt;/div&gt; ]]&gt;
&lt;/script&gt; 

These tags will be completely destroyed if you try it in http://jsbeautifier.org/

**Comment by pdf** [comment]
Looks like this is broken (still/again?)

**Comment by irsdl** [comment]
I haven't changed the plugin but I will probably update it soon with new
features and new patches. Hopefully all the open issues will be resolved.
