### ISSUE TITLE
JS格式化问题

### ISSUE THREAD

**Issue by xiaoyunet** [beautify-web/js-beautify#1177]
在JS 里面 
 var goods_price = {$goods.shop_price}; // 商品起始价
格式化后 变成了 
 var goods_price = { $goods.shop_price }; // 商品起始价
｛和$之间多了一个空格。然后还得手动更改

**Comment by bitwiseman** [comment]
I'm sorry, I don't know what you're saying.  Please translate.

**Comment by xueqingxiao** [comment]
@bitwiseman you can close this one.  This guy take wrong configuration, and is lazy to read docs or search it on stackoverflow.
