### ISSUE TITLE
CLI -r changes the charset of the file

### ISSUE THREAD

**Issue by joelharkes** [beautify-web/js-beautify#1180]
# Description

Running the CLI tool on files changes their charset

I found this to be true for .less files.

# Steps to Reproduce

`run js-beautify -r -f yourfile.less` on a file with UTF8-BOM encoding

The encoding will change to ASCII, even though i expect it to keep the same encoding.

## Environment
OS: Win10x64

**Comment by joelharkes** [comment]
To comment on this: i dont see this as a big issue to me but i'd expect this not to happen?

**Comment by bitwiseman** [comment]
@joelharkes 
Is this for the python or nodejs version?

**Comment by joelharkes** [comment]
This goes for the nodejs version
