### ISSUE TITLE
JS Beautifier expands all JS object declarations into multiple lines, even though brace style is set to collapse-preserve-inline.

### ISSUE THREAD

**Issue by djoaquing** [beautify-web/js-beautify#1182]
This 

https://i.gyazo.com/2831254cc47d08c879c7d36a7f1a30d0.png

happens when this code 

this.blueprints = [{ name: 'Granary', val: 0, col: 1}, 
{name: 'Water Tower', val: 0, col: 1},
...etc

is beautified

My brace style is collapse-preserve-inline. Already restarted Atom, just in case, and nothing.

I would like the object to not be expanded completely.

This thread talks about this, but I couldn't find a solution:

https://github.com/beautify-web/js-beautify/issues/315

**Comment by bitwiseman** [comment]
I'm sorry, I can't really make sense of what you're reporting.  Please use the [ISSUE_TEMPLATE.md](https://github.com/beautify-web/js-beautify/blob/master/ISSUE_TEMPLATE.md) to show what is happening.

**Comment by djoaquing** [comment]
No problem.

Input:

var q = { x: "a", b: "c" }

It "beautifies" to:

var q = {
    x: "a",
    b: "c"
}

I would like it not to expand - to stay as the original input. 

The solution in the linked thread was to set Brace Style to collapse-preserve-inline, however this doesn't change the behaviour. 

Thank you,

**Comment by bitwiseman** [comment]
This works on http://jsbeautifier.org/ with "Preserve inline braces/code blocks?" checked.  Not sure why it isn't working on atom in your case, but it is not a beautifier issue.  Sorry.

**Comment by ifgx** [comment]
Witch the option "Preserve inline braces/code blocks?" ON, and es6 syntax, my "map" type is still being cut 

Input:
`myVar: { [key: string]: myClass.myType };`

Output
```
myVar: {
	[key: string]: myClass.myType };
```

Second output (if I apply again from the last output):
```
myVar: {
	[key: string]: myClass.myType
};
```

Expected result : no changes from input.

**Comment by bitwiseman** [comment]
@ifgx 
Interesting

Please do the following:
1. Please verify you syntax from the above is valid es6.  Find the part of the es6 spec that defines this and link to it.
2. If possible, rewrite your above examples in the form: `var a = <your code>`. It is unclear what part of the the syntax `myvar:` corresponds to.
3. Open a new issue with the (now modified) information you from the comment above.

**Comment by ifgx** [comment]
@bitwiseman 

1.  Syntax was from https://stackoverflow.com/questions/30019542/es6-map-in-typescript?answertab=active#tab-top
I ignore if it is an officia valid es6 syntax, but it is used with typescript as a hashmap.

2. I changed my syntax to `var a = myClass.myType[]`

3. Not personally concerned anymore by this issue.

Thanks for your interest.
