### ISSUE TITLE
JSON Formatting looks different then expected

### ISSUE THREAD

**Issue by hulu1522** [beautify-web/js-beautify#1183]
The JSON formatting is coming out weird and gets hard to read when it comes to the alignment of arrays.  Normally the array would close lined up with the beginning key but after running this it formats them farther back then expected.  Here is an example of what I mean:

#### Current output:
```json
{
    "default_attributes": {
        "system": {
            "packages": {
                "install": [
          "iftop",
          "mc",
          "ngrep",
          "htop"
        ]
            }
        }
    }
}
```

#### Expected output:
```json
{
    "default_attributes": {
        "system": {
            "packages": {
                "install": [
                    "iftop",
                    "mc",
                    "ngrep",
                    "htop"
                ]
            }
        }
    }
}
```

Is this wrong to think the array should be on the same line as the key?  Thanks for the help

**Comment by bitwiseman** [comment]
Doesn't repro on on http://jsbeautifier.org/.  
Actual output:
```
{
    "default_attributes": {
        "system": {
            "packages": {
                "install": [
                    "iftop",
                    "mc",
                    "ngrep",
                    "htop"
                ]
            }
        }
    }
}
```

**Comment by Hirse** [comment]
This is a matter of the [options](https://github.com/beautify-web/js-beautify#options):
With `"keep_array_indentation": true`, it is formatted as expected.
