### ISSUE TITLE
HTML text content formatted incorrectly

### ISSUE THREAD

**Issue by methyl** [beautify-web/js-beautify#1184]
# Description

Text content in HTML is not formatted correctly. The end tag should be prepended with a new line.

# Input
The code looked like this before beautification:
```
<div><div></div>Connect</div>
```

# Expected Output
The code should have looked like this after beautification:
```
<div>
  <div></div>Connect
</div>
```
or
```
<div>
  <div></div>
  Connect
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div>
    <div></div>Connect</div>
```

# Steps to Reproduce
Go to http://jsbeautifier.org/, paste the code, format.

## Environment
http://jsbeautifier.org/

## Settings

Default online settings.

**Comment by bitwiseman** [comment]
Yeah, `div` behaves like `p` in the output.
