### ISSUE TITLE
Missing space between anonymous async function and first paren

### ISSUE THREAD

**Issue by prettydiff** [beautify-web/js-beautify#1187]
https://github.com/Glavin001/atom-beautify/issues/1654

After searching the JS Beautify code it looks like there are tests in place for this, but none of them make use of fat arrows.  The primary difference is the test samples all expect the *function* keyword which isn't needed when working with fat arrow.

**Comment by TwoAbove** [comment]
Hey guys! 
Any updates on this?

**Comment by bitwiseman** [comment]
@TwoAbove 
This feature is not assigned an needs someone to write tests and implement it.

**Comment by TwoAbove** [comment]
@bitwiseman I can try. It needs both js and python implementations, right?

**Comment by bitwiseman** [comment]
@TwoAbove - yes.  You can pick which ever language is easier for you and then translate.

**Comment by bitwiseman** [comment]
#896
