### ISSUE TITLE
css-beautify formats 'display: inline-block' in the wrong way

### ISSUE THREAD

**Issue by dedoyle** [beautify-web/js-beautify#1190]
OS: win7

cssfile.css
`
.rule {
    display: inline-block;
}
`

Then run 
`css-beautify -L -N -q -f cssfile.css`

And get this
`
.rule {
    display: inline - block;
}
`

**Comment by dedoyle** [comment]
my file is cssfile.js, and so the result is wrong. and now I change it to cssfile.css, then the result is right.

**Comment by bitwiseman** [comment]
@dedoyle This is still a bug.  You ran `css-beautify` so it probably should have ignored the the extension on the file.  Thanks for reporting this.

**Comment by MacKLess** [comment]
This appears to have been resolved as of v1.8.0-rc13. @dedoyle  please double check and let me know if you disagree.
