### ISSUE TITLE
Cannot pass file using pipe

### ISSUE THREAD

**Issue by meain** [beautify-web/js-beautify#1192]
Trying to run `cat test.css | js-beautify --file - --type css`

results in

```sh
Unable to open path "/Users/abinsimon/--wrap_attributes_indent_size"
Run `js-beautify -h` for help.
```

## Environment
OS: Mac OS X 10.12.3 16D32
js-beautify version: 1.6.14

**Comment by Manc** [comment]
Having the same problem using the `--file` option with any relative or absolute path:

    Unable to open path "/[...path-to-current-directory...]/--wrap_attributes_indent_size"
    Run `js-beautify -h` for help.

**Comment by bitwiseman** [comment]
@Manc 
What is the command line you're running?
