### ISSUE TITLE
Malware? Clamav scan found infected file in your repo

### ISSUE THREAD

**Issue by rodrev** [beautify-web/js-beautify#1195]
Hello,
I'm using js-beautify as part of the atom-beautify package.  I like good looking code too.  But I've just run a scan with Clamav and it marked a file in your repo as malware.  Can you pls have a look and let me know if I should report this as a false positive or if there is possibly some security flaw in the code that you can find.  Thank you.

This is the filename and output from clamscan:
```
~/.atom/packages/atom-beautify/node_modules/js-beautify/js/lib/unpackers/p_a_c_k_e_r_unpacker.js
Sanesecurity.Malware.26193.JsHeur.PUA.UNOFFICIAL FOUND
```

**Comment by bitwiseman** [comment]
It is not a virus, it is a false positive. It is an unpacker for a format that javascript viruses have been know use.

**Comment by rodrev** [comment]
Thank you very much for your reply.  I really appreciate your explanation.  Keep on beautifying!
