### ISSUE TITLE
Do not modify built-in objects

### ISSUE THREAD

**Issue by wKich** [beautify-web/js-beautify#1205]
https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L93-L107

Your library is not polyfill and it should not modify environment.
1. May be you don't need `Object.values` at all in your code. I found only one place where it use and can be simply replaced to `Object.keys` equivalent.
1. Or you can notify users, that them need to import `Object.values` polyfill manually.

I think first option is better.

**Comment by bitwiseman** [comment]
@wKich - It doesn't quite work as Object.keys, but adding an array is fine.
