### ISSUE TITLE
HTML beautify breaks code with spaces

### ISSUE THREAD

**Issue by emanuel1025** [beautify-web/js-beautify#1210]
HTML prettify modifies below code from:

` <select id="mentoringGrade" multiple="multiple" ng-model="userMentoringGrade">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                            <option value="7">7</option>
                                            <option value="8">8</option>
                                            <option value="9">9</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>`

to: 

`<select id="mentoringGrade " multiple="multiple " ng-model="userMentoringGrade ">
                                            <option value="1 ">1</option>
                                            <option value="2 ">2</option>
                                            <option value="3 ">3</option>
                                            <option value="4 ">4</option>
                                            <option value="5 ">5</option>
                                            <option value="6 ">6</option>
                                            <option value="7 ">7</option>
                                            <option value="8 ">8</option>
                                            <option value="9 ">9</option>
                                            <option value="10 ">10</option>
                                            <option value="11 ">11</option>
                                            <option value="12 ">12</option>
                                        </select>`

This leads to incorrect values sent to the server. This only happens when I try to beautify the entire page and does not happen if I beautify just the above text. Maybe values, ids and classes should be left as is?

**Comment by bitwiseman** [comment]
Have you tried this on http://jsbeautifier.org/  ?   I can't repro it there.
