### ISSUE TITLE
js-beautify produces invalid code for variables with Unicode escape sequences

### ISSUE THREAD

**Issue by CapacitorSet** [beautify-web/js-beautify#1211]
js-beautify produces invalid code when beautifying code that has Unicode escape sequences in identifiers. "In the wild", I found it to break on code containing the following statement: `var \u0053\u0074\u0072\u0069\u006e\u0067\u0033\u0034\u0035\u0036={...}`.

A minimal test case is `var \u0053`, which should be left untouched but is instead transformed to `var\ u0053`.

**Comment by bitwiseman** [comment]
@CapacitorSet 
Thanks for the bug report.   
This bug is here: https://github.com/beautify-web/js-beautify/blob/2009d250914ba865e81b20b264aa40736e38bf86/js/src/javascript/tokenizer.js#L239
The beautifier assumes unicode characters for identifiers, not escape sequences.
