### ISSUE TITLE
sublime Stylus semicolon problem

### ISSUE THREAD

**Issue by thisVioletHydra** [beautify-web/js-beautify#1212]
who i can fix this? 

>before
 
> //SECTION
> section {
>   overflow hidden
>   position relative
> }
> 

 
> after

> //SECTION
> section {
>   overflow hidden position relative
> }
>  

its old themes: https://github.com/victorporof/Sublime-HTMLPrettify/issues/373 
I do not understand why he sent me here.
my code -is stylus  example and at the output it is css

**Comment by bitwiseman** [comment]
@mrG0bliN 
What is stylus?

**Comment by mrG0bliN** [comment]
http://stylus-lang.com/

**Comment by mrG0bliN** [comment]
like a SASS preprocessor

**Comment by bitwiseman** [comment]
Ah, okay, so it is not CSS but another templating/variant.  That would explain when it doesn't work as you would like.

**Comment by mrG0bliN** [comment]
dead issues 
close

**Comment by thisVioletHydra** [comment]
Twenty twenty years in the yard, leave the dead man ⚰️
