### ISSUE TITLE
Improper spacing and escaping of backticks in template strings

### ISSUE THREAD

**Issue by zawadzkip** [beautify-web/js-beautify#1214]
# Description
When writing SQL queries using a template string, there are some issues with how the beautifier cleans up template strings containing escaped backticks, especially next to an expression.
> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue. 

# Input
The code looked like this before beautification:
```
const result = await sqlDb.query(`insert into \`${tableName}\` set :sqlObject`, {
          sqlObject,
        });
```

# Expected Output
The code should have looked like this after beautification:
```
const result = await sqlDb.query(`insert into \`${tableName}\` set :sqlObject`, {
          sqlObject,
        });
```

# Actual Output
The  code actually looked like this after beautification:
```
const result = await sqlDb.query(`insert into `
$ { tableName }
` set :sqlObject`, {
          sqlObject,
        });
```

# Steps to Reproduce

## Environment
OS: macOS Sierra 10.12.5
grunt-jsbeautifier: ^0.2.13,

## Settings
```

{
  "brace_style": "collapse-preserve-inline",
  "break_chained_methods": false,
  "end_with_newline": true,
  "eval_code": false,
  "indent_char": " ",
  "indent_level": 0,
  "indent_size": 2,
  "indent_with_tabs": false,
  "jslint_happy": false,
  "keep_array_indentation": false,
  "keep_function_indentation": false,
  "max_preserve_newlines": 10,
  "preserve_newlines": true,
  "space_after_anon_function": true,
  "space_before_conditional": true,
  "space_in_empty_paren": false,
  "space_in_paren": false,
  "unescape_strings": false,
  "wrap_line_length": 0
}

```

Let me know if there is anymore clarifying information you need.

**Comment by zawadzkip** [comment]
Sorry for the formatting issues, unfortunately the backticks used in the error are the same as code comments in markdown

**Comment by bitwiseman** [comment]
@zawadzkip - When I put your input into http://jsbeautifier.org/ ,  it formats as you were wanting it to.

**Comment by zawadzkip** [comment]
@bitwiseman Thanks for checking, actually wasn't aware of that tool. I will try to see if I can get more information about it and post it. Thanks for your help.

**Comment by MacKLess** [comment]
This is an old issue that hasn't been updated.
