### ISSUE TITLE
Adds excess spaces in tags and attributes

### ISSUE THREAD

**Issue by mattixittam** [beautify-web/js-beautify#1221]
# Description
When using the npm package on the command line, it adds a whole lot of extra spaces everywhere.

Related to: https://github.com/beautify-web/js-beautify/issues/976?

# Input
The code looked like this before beautification:
```
<ui-input heading="Heading" placeholder="Error input" invalid error="Error text"><div></div></ui-input>
```

# Expected Output
The code should have looked like this after beautification:
```
<ui-input heading="Heading"
placeholder="Error input"
invalid error="Error text">
    <div></div>
</ui-input>
```
Or something like this

# Actual Output
The  code actually looked like this after beautification:
```
< ui - input heading = "Heading"
placeholder = "Error input"
invalid error = "Error text" > < div > < /div></ui - input >
```

# Steps to Reproduce
```
// input.txt contains the above input
js-beautify input.txt
```

## Environment
OS: macOS 10.12.5

## Settings
default

**Comment by bitwiseman** [comment]
Change file extension to ".html" or run "html-beautify".
