### ISSUE TITLE
Line break happenes too soon in some cases

### ISSUE THREAD

**Issue by RoHePu** [beautify-web/js-beautify#1224]
# Description
Hi js-beautify team,
we would love to use js-beautify as formatter for our web-projects, but in our tests it shows some strange behavior. When we set the `wrap_line_length` to 120, some lines break at 110 or even less.

We debugged into the `beautify.js` and realized, that the newlines are calculated based on `flags. indentation_level`. The current `OutputLine.__character_count` is set to `_character_count = parent.baseIndentLength + level * parent.indent_length;` 
Afterwards some redundant indentions are removed again by `OutputLine.remove_redundant_indentation `, but the accidentally line break will not be fixed.

Do you plan to change this behavior in any future release or do you see a monkey patch we could apply to fix the accidentally added newlines?

Thanks in advance,
Robin

# Input
The code looked like this before beautification:
```javascript
function(){
    snoop.key(function(){
        foo.forEach(function(bar){
            testline("the first parameter is veeeeeeeery long", "but the line is not longer than 110 chars");
        });
    });
}
```

# Expected Output
The code should have looked like this after beautification:
```javascript
function(){
    snoop.key(function(){
        foo.forEach(function(bar){
            testline("the first parameter is veeeeeeeery long", "but the line is not longer than 110 chars");
        });
    });
}
```

# Actual Output
The  code actually looked like this after beautification:
```javascript
function(){
    snoop.key(function(){
        foo.forEach(function(bar){
            testline("the first parameter is veeeeeeeery long", 
                "but the line is not longer than 110 chars");
        });
    });
}
```

# Steps to Reproduce
Run js-beautify with the given configuration.

## Environment
OS: all

## Settings
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false,
    "eol": "\n",
    "end_with_newline": false,
    "indent_level": 0,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "space_in_paren": false,
    "space_in_empty_paren": false,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "break_chained_methods": false,
    "keep_array_indentation": false,
    "unescape_strings": false,
    "wrap_line_length": 120,
    "e4x": false,
    "comma_first": false,
    "operator_position": "before-newline",
    "space_before_conditional": true
}
```

**Comment by bitwiseman** [comment]
Thanks you for the bug report, this is a the same issue reported in #700.  Slightly different input, but the underlying cause is the same.

This is a long standing issue open issue that is difficult to solve without significant changes to the underlying data structures.  We intend to fix it at some point but it is not scheduled for a specific release.  If you'd like to contribute a fix, I'd be happy to discuss it with you.
