### ISSUE TITLE
await import(...)

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1228]
Expected: 

```js
const module = await import('...')
```

Actual:

```js
const module = await 
import ('...')      ^
      ^
```

* newline between `await` and `import`
* space between `import` and `('...')`

**Comment by laggingreflex** [comment]
Webpack uses this syntax for [importing modules lazily](https://webpack.js.org/guides/code-splitting/#dynamic-imports). Not sure if this is (or going to be) a [standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) though.

**Comment by LiPinghai** [comment]
+1

**Comment by bitwiseman** [comment]
@laggingreflex  #1393 Partially addresses this.
