### ISSUE TITLE
Formatting slow when line wrap is set

### ISSUE THREAD

**Issue by aeschli** [beautify-web/js-beautify#1231]
- Paste the following [html sample]( https://jsfiddle.net/chrisxue815/hot1g5nw/) to http://jsbeautifier.org/
- set "Wrap lines near 80 characters"
- formatter takes around 10 seconds to complete
- set "Do not wrap lines".
- formatetr happens instantly

**Comment by bitwiseman** [comment]
@aeschli  This seems significantly better than 10 seconds now.
