### ISSUE TITLE
Extra space in pseudo-elements and pseudo-classes selectors

### ISSUE THREAD

**Issue by foulmetal** [beautify-web/js-beautify#1233]
## Description
When using rule with a pseudo-elements or pseudo-classes selectors inside a :not() selector and this rule is nested in another rule, less beautify add extra space after the first colon

# Input
```
.one {
    color: #FFF;
    span:not(*::selection) { // pseudo-element
        margin-top: 0;
    }
}

.two {
    color: #000;
    span:not(*:active) { // pseudo-class
        margin-top: 0;
    }
}
```

# Expected Output
The code should have looked like this after beautification:
```
.one {
    color: #FFF;
    span:not(*::selection) {
        // pseudo-element
        margin-top: 0;
    }
}

.two {
    color: #000;
    span:not(*:active) {
        // pseudo-class
        margin-top: 0;
    }
}
```

# Actual Output
The  code actually looked like this after beautification:
```
.one {
    color: #FFF;
    span:not(*: :selection) {
        // pseudo-element
        margin-top: 0;
    }
}

.two {
    color: #000;
    span:not(*: active) {
        // pseudo-class
        margin-top: 0;
    }
}
```

# Steps to Reproduce

## Environment
OS:
Ubuntu, MacOSX

## Settings
default one

**Comment by shinrabansyou** [comment]
I have the same problem
