### ISSUE TITLE
cli tool will not start

### ISSUE THREAD

**Issue by jrialland** [beautify-web/js-beautify#1235]
I have installed the jsbeautify cli tool with 
```
$ npm install -g jsbeautify
```
```
>└─┬ jsbeautify@0.3.6 
  └─┬ optimist@0.6.1 
    ├── minimist@0.0.10 
    └── wordwrap@0.0.3 
```
And then 

```
$ jsbeautify gulpfile.js 
```

```
>/usr/bin/env: «node\r»: No such file or directory
```

I had to remove the \r character from the launcher script:
```
sudo apt-get install dos2unix
dos2unix ~/.nvm/versions/node/v7.3.0/lib/node_modules/jsbeautify/bin/jsbeautify
```

## Environment
OS: Ubuntu 16.04
node v7.3.0, through nvm

**Comment by bitwiseman** [comment]
@jrialland - this is try `npm install -g js-beautify". The current version is 1.6.14, not 0.3.6.

**Comment by jrialland** [comment]
oops my bad, thank you for your time.
