### ISSUE TITLE
Add test and tools folder to npmignore

### ISSUE THREAD

**Issue by simondel** [beautify-web/js-beautify#1239]
Hi! I noticed that the npmignore does not exclude the test and tools folder. There are also some other files that you don't need in a release such as your .travis.yml. The test and tools folder in the lastest release are almost half the size of js-beautify (if you don't count dependencies).

**Comment by bitwiseman** [comment]
@simondel - Please submit a PR.

**Comment by simondel** [comment]
I created PR #1241
