### ISSUE TITLE
Tagged Template literals

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1244]
# Description

Are there any rules that apply to [Tagged Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals)? 

Specifically:

* # Case 1:

    ## Input
    ```
    fn`tagged`
    ```
    ## Expected: no change
    ```
    fn`tagged`
    ```
    ## Actual: space inserted
    ```
    fn `tagged`
      ^ space inserted
    ```

* # Case 2:

    ## Input
    ```
    fn()`tagged`
    ```
    ## Expected: no change
    ```
    fn()`tagged`
    ```
    ## Actual: newline inserted
    ```
    fn()
    `tagged`
    ^ newline inserted
    ```

**Comment by bitwiseman** [comment]
Not currently supported.  Didn't even know this existed. Thanks!

**Comment by JuanFML** [comment]
Hello everyone, I am new here, is there a chance I can try this as my first issue?

**Comment by bitwiseman** [comment]
@JuanFML 
You are welcome to give it a try.  You'll probably want to make the change in this method: 

https://github.com/beautify-web/js-beautify/blob/97caa308491e1379b226c514f677fa4f278e15d4/js/src/javascript/beautifier.js#L1059-L1077

If the `STRING` token that is about to be processed is a backtick string and  is preceded by a literal with no space in between, then do not add a space or newline.

**Comment by JuanFML** [comment]
Ok! I will be trying it out, thank you! If I get stuck I will let you know

**Comment by JuanFML** [comment]
Hi @bitwiseman, I've been working on this, but I would like to know if I am doing it right, so far I figure out a condition and added it in the method you mentioned, like so: 
```
Beautifier.prototype.handle_string = function(current_token) {

  if (/^[`][^`]+[`]$/gm.test(current_token.text) && (this._flags.last_token.type === 'TK_END_EXPR' || this._flags.last_token.type === 'TK_WORD') && current_token.whitespace_before === '') {
  } else if (this.start_of_statement(current_token)) {
    // The conditional starts the statement if appropriate.
    // One difference - strings want at least a space before
    this._output.space_before_token = true;
  } else {
    this.handle_whitespace_and_comments(current_token);
    if (this._flags.last_token.type === TOKEN.RESERVED || this._flags.last_token.type === TOKEN.WORD || this._flags.inline_frame) {
      this._output.space_before_token = true;
    } else if (this._flags.last_token.type === TOKEN.COMMA || this._flags.last_token.type === TOKEN.START_EXPR || this._flags.last_token.type === TOKEN.EQUALS || this._flags.last_token.type === TOKEN.OPERATOR) {
      if (!this.start_of_object_property()) {
        this.allow_wrap_or_preserved_newline(current_token);
      }
    } else {
      this.print_newline();
    }
  }
  this.print_token(current_token);
};
```
Then I added two tests, which are the cases mentioned, in `name: "more random test"` line 1660, in `/test/data/*/test.js`  and when I run make js everything passes, but when I run `make jstest` I get the following errors: 

```
======================================================================
FAIL: test_beautifier (jsbeautifier.tests.generated.tests.TestJSBeautifier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Documents\Academy\AcademyEncora\OpenSourcePhase\js-beautify\python\jsbeautifier\tests\generated\tests.py", line 2982, in test_beautifier
    bt('fn`tagged`')
  File "D:\Documents\Academy\AcademyEncora\OpenSourcePhase\js-beautify\python\jsbeautifier\tests\generated\tests.py", line 9581, in bt
    self.decodesto(input, expectation)
  File "D:\Documents\Academy\AcademyEncora\OpenSourcePhase\js-beautify\python\jsbeautifier\tests\generated\tests.py", line 9543, in decodesto
    self.assertMultiLineEqual(
AssertionError: 'fn `tagged`' != 'fn`tagged`'
- fn `tagged`
?   -
+ fn`tagged`

```

**Comment by JuanFML** [comment]
I am now working in to fix the issue with the implementations https://github.com/beautify-web/js-beautify/blob/97caa308491e1379b226c514f677fa4f278e15d4/python/jsbeautifier/javascript/beautifier.py#L1186-L1212

**Comment by JuanFML** [comment]
I have solved the remaining tests and fixed errors that appeared on my PR in Azure DevOps, please let me know if the changes are ok
