### ISSUE TITLE
Add install tests for packages

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#1254]
1.7.0 Release showed why full install tests are needed.  
Implement tests that the built packages will successfully install and run.

**Comment by szeck87** [comment]
I would suggest adding MacOS as an OS in the Travis build as well.

**Comment by bitwiseman** [comment]
@szeck87 - Didn't know they'd added that option. Perhaps you could do a pull request for that?
(See #1256)

**Comment by bitwiseman** [comment]
@szeck87  Travisci's MacOS support is pretty spotty.  We now have tests that cover python and node packages.  The website is what I use when testing locally so it gets plenty of coverage.
