### ISSUE TITLE
The first line is incorrect when formatting an array.

### ISSUE THREAD

**Issue by xuchenchenBoy** [beautify-web/js-beautify#1265]
# Description
The first line is incorrect when formatting an array.

# Input
The code looked like this before beautification:
```
import { js_beautify as beautify } from 'js-beautify';

const template = [
    { param: 'params' }
];
const templateStr = JSON.stringify(template);
const output = beautify(templateStr, { indent_size: 2 });
```

# Expected Output
The code should have looked like this after beautification:
```
[
    { param: 'param' }
]
```

# Actual Output
The  code actually looked like this after beautification:
```
                [
    { param: 'param' }
]
```

# Steps to Reproduce

## Environment
OS: mac0s 10.12.3

## Settings
Example:
```json
{
    "indent_size": 2
}
```

**Comment by bitwiseman** [comment]
I can't reproduce this on the jsbeautifier website.  Is there more code around the example you gave?

**Comment by xuchenchenBoy** [comment]
@bitwiseman See https://codepen.io/chenxu/pen/boLKRW?editors=1111

**Comment by bitwiseman** [comment]
@xuchenchenBoy 
Change the HTML in the linked paged to:

```html
<div id="app">
  <pre>
    <code>
{{codes}}
    </code>
  </pre>
</div>  
```

And the formatting is fixed.

**Comment by xuchenchenBoy** [comment]
@bitwiseman Thanks.
