### ISSUE TITLE
Generate js-beautify executable properly on windows when installed from PIP

### ISSUE THREAD

**Issue by brupelo** [beautify-web/js-beautify#1266]
Hi,

After installing js-beautify on a python virtualenv (i.e `pip install jsbeautifier`) one file js-beautify with no extension has been created on the scripts folder, which contains:

    #!d:\software\sublim~2\data\packages\miscel~1\test\scripts\python.exe
    #
    # Stub script to run jsbeautifier
    #
    import sys
    from jsbeautifier import main
    sys.exit(main())

This file, even if it's found in the path (`where js-beautify`) won't work on windows, it doesn't know anything neither about shebangs nor files without extension... so, could you please fix the setup.py properly so a windows executable will be created instead (like flake8, pep8, youtube-dl, ...). For more info about it take a look to here [http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation). One real example here [https://github.com/altendky/st/blob/lib/setup.py#L14](https://github.com/altendky/st/blob/lib/setup.py#L14).

Thanks in advance.

**Comment by brupelo** [comment]
The good solution would be this one:

    setup(name='jsbeautifier',
          version=__version__,
          description='JavaScript unobfuscator and beautifier.',
          long_description=('Beautify, unpack or deobfuscate JavaScript. '
                            'Handles popular online obfuscators.'),
          author='Einar Lielmanis, Stefano Sanfilippo et al.',
          author_email='einar@jsbeautifier.org',
          url='http://jsbeautifier.org',
          entry_points={
              'console_scripts': [
                  'jsbeautifier-test = jsbeautifier:main'
              ]
          },
          packages=['jsbeautifier',
                    'jsbeautifier.tests', 'jsbeautifier.tests.generated',
                    'jsbeautifier.core',
                    'jsbeautifier.javascript',
                    'jsbeautifier.unpackers', 'jsbeautifier.unpackers.tests'],
          install_requires=["six>=1.6.1", "editorconfig>=0.12.0"],
          license='MIT',
          test_suite='pytest.collector',
          cmdclass = {'test': PyTest},

         )

And of course, delete js-beautify file from the repo. After this the installation/uninstallation should be clean. Not doing a PR cos i've justed tested on win.

**Comment by bitwiseman** [comment]
@brupelo Please do a PR.  At very least that will give a better understanding of what you believe the fix should be.  Also, as part of the PR you can add tests to verify the new behavior which will further show what your fix does.

**Comment by vivainio** [comment]
@brupelo solution is correct. I created pull request for it:

https://github.com/beautify-web/js-beautify/pull/1455
