### ISSUE TITLE
How to skip return new line with declare var on typescript

### ISSUE THREAD

**Issue by leduong** [beautify-web/js-beautify#1268]
Hi

How to skip return new line with declare var on typescript
```typescript
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
declare var $: any;
.
.
.
```

then Ctrl + Shift + H

```typescript
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
declare 
var $: any;
.
.
.
```

Thank you. This plugin is helpful

**Comment by bitwiseman** [comment]
@leduong 
Typescript is not fully supported at this time. See #1147. 

We do point-wise fixes to address particularly poor behavior when possible.  If you would be interested in working on this, please look at the CONTRIBUTING.md.

**Comment by 1011178l** [comment]
I think this issue has been solved by https://github.com/beautify-web/js-beautify/issues/1544

**Comment by bitwiseman** [comment]
Thanks for pointing this out.  Sometimes explanations of how severe an issue is result in faster turnaround. 😄
