### ISSUE TITLE
Option: "max_preserve_newlines" from command line doesn't work

### ISSUE THREAD

**Issue by xavikortes** [beautify-web/js-beautify#1276]
Hi,

I have downloaded the Python-lib via PIP, v1.7.4.
I tried to add "max_preserve_newlines" option from command line, but it failed. It doesn't appear in the help.

I look for it in the code and the functionality is done. Can you tell me why I can't use it?

Thanks

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/blob/master/ISSUE_TEMPLATE.md
