### ISSUE TITLE
Weird indentation for nested case statements

### ISSUE THREAD

**Issue by RockyTV** [beautify-web/js-beautify#1282]
I'm using `js-beautify` and the following code

```javascript
switch (a) {
  default:
  case 0:
    return;
  case 1:
    return;
}
```

turns to:

```javascript
switch (a) {
  default:
    case 0:
    return;
  case 1:
    return;
}
```

This creates confusion while reading a code because you may think the `case` statement is not a statement at all.

**Comment by MacKLess** [comment]
So, I just ran this with v1.8.3-rc3 and it's gotten much worse. Here's the current actual output:
```
switch (a) {
    default:
        case 0:
        return;
    case 1:
            return;
```

Weirdly, when you swap the position of the default line, it sorts itself out:
```
switch (a) {
    case 0:
        return;
    default:
    case 1:
        return;
}
```
