### ISSUE TITLE
Function parameters indentation

### ISSUE THREAD

**Issue by ronzeidman** [beautify-web/js-beautify#1289]
# Description
A common pattern of using composable functions instead of function chain needs better indentation. 
Examples include the new RxJS lettable operators, Ramda pipe/compose and more

# Input
The code looked like this before beautification:
```
return param
.getObservable()
.pipe(
map(...),
filter(...),
tap(...),
);
```

# Expected Output
The code should have looked like this after beautification:
```
return param
    .getObservable()
    .pipe(
        map(...),
        filter(...),
        tap(...),
    );
```

# Actual Output
The  code actually looked like this after beautification:
```
return param
    .getObservable()
    .pipe(
    map(...),
    filter(...),
    tap(...),
    );
```

## Settings
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by bitwiseman** [comment]
I can't repro this on http://jsbeautifier.org/.  Could you try it there?

**Comment by ronzeidman** [comment]
Sorry for the fuss... I'm using vscode and there was some collision between the internal beautifier and the plugin...
