### ISSUE TITLE
[BUG] HTML - format documment "fracture" Subresource Integrity (3rd part libs)

### ISSUE THREAD

**Issue by Mlocik97-issues** [beautify-web/js-beautify#1296]
Orriginal issues:

https://github.com/Microsoft/vscode/issues/38077

Ideal expected result is second because If I use "Indent using Tabs" as tabs (not 4 spaces),...

Now it will do some problems, and Subresource integrity is "fractured"..

```
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va
+PmSTsz/K68vbdEjh4u"
	 crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
	 crossorigin="anonymous"></script>
```

integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va ↵
+PmSTsz/K68vbdEjh4u"

**Comment by bitwiseman** [comment]
@Mlocik97-issues  
Can you reproduce this issue on http://jsbeautifier.org/ ?

**Comment by Mlocik97-issues** [comment]
I want format it like as:

![screenshot_12](https://user-images.githubusercontent.com/31345346/32670571-777685d4-c644-11e7-8a08-ec707b59c189.png)

**Comment by bitwiseman** [comment]
@Mlocik97-issues  it looks like #1297 is working towards this.

**Comment by Mlocik97-issues** [comment]
force-aligned is not solution, because it force all tags with all attributes... I need force only attributes with long value as integrity key

**Comment by bitwiseman** [comment]
@Mlocik97-issues  
`aligned-multiple`?
