### ISSUE TITLE
Simplify html encoded text

### ISSUE THREAD

**Issue by jyn514** [beautify-web/js-beautify#1309]
# Description
HTML encodings should be turned into UTF-8 text

# Input
The code looked like this before beautification:
```
var x = ["\x74\x65\x73\x74"]
alert(x)
```

# Expected Output
The code should have looked like this after beautification:
```
alert("test")
```

# Actual Output
The  code actually looked like this after beautification:
```
var x = ["\x74\x65\x73\x74"]
alert(x)
```
## Settings
Website defaults as of [latest commit](https://github.com/beautify-web/js-beautify/commit/cebf32b2e3474aa307b0d8651cbcf8f01e779752)

## Note
By the way, I'm interested in submitting a pull request if you'll show me where to start. This looks fairly simple to implement.

**Comment by bitwiseman** [comment]
See the contributing.md document.  If instructions there are not clear, submit updates to those instructions.

**Comment by bitwiseman** [comment]
@jyn514  If you set `"unescape_strings": true`, this is the output:

```
var x = ["test"]
alert(x)
```

That is all that is in scope for the beautifier at this time.
