### ISSUE TITLE
Note that `gsort` is GNU sort

### ISSUE THREAD

**Issue by jyn514** [beautify-web/js-beautify#1314]
I have sort installed, but because it's not called 'gsort'. Because of this,  tools/generate-changelog.sh fails with the following message:

```
./generate-changelog.sh: line 22: gsort: command not found
Required tool 'gsort' missing.  Failed.
````
Fix: Add documentation.

**Comment by bitwiseman** [comment]
How do you have it installed?  I'm working on OSX.  Please submit a PR that fixes this for your OS.

**Comment by jyn514** [comment]
I'm working on Debian 9 stretch; on my system it's just called `sort`. Might be a while before I get around to a PR.

**Comment by jyn514** [comment]
Fixed in https://github.com/beautify-web/js-beautify/pull/1321#event-1414185801
