### ISSUE TITLE
syntax highlighting?

### ISSUE THREAD

**Issue by ORESoftware** [beautify-web/js-beautify#1320]
It would nice if the README makes it clear whether this library attempts any syntax highlighting or not...doesn't seem like it after experimenting with it. Not sure why I thought it did syntax highlighting but..

**Comment by bitwiseman** [comment]
@ORESoftware 
Please submit a PR.  This library is used by a number of editor plugins where the editor does syntax highlighting.  Also, the website uses a web editing component that does syntax highlighting.

**Comment by ORESoftware** [comment]
yeah, I think this can be closed - for some reason I was confused that this library does both formatting and highlighting, but that was a dumb assumption on my part. It makes sense that this library does just the formatting and does not take on syntax highlighting.
