### ISSUE TITLE
Option to put destructured values on the same line

### ISSUE THREAD

**Issue by ORESoftware** [beautify-web/js-beautify#1325]
With the following in mind:

```js
const {Test} = suman.init(module);

Test.create((b, it, describe, before, after, beforeEach, afterEach) => {

    const {
        Builder, 
        By,
        Key,
        until 
    } = require('selenium-webdriver');

});
```

Is there a way to put the destructured args on the same line by default? So it would be:

```js
const {Test} = suman.init(module);

Test.create((b, it, describe, before, after, beforeEach, afterEach) => {

    const { Builder, By, Key, until } = require('selenium-webdriver');

});
```

**Comment by bitwiseman** [comment]
There is no option to force this for this yet, but if they are already on one line they will be kept that way by `brace_style: preserve_inline`.

**Comment by ORESoftware** [comment]
I think you mean `brace_style:"preserve_inline"` right? thx

**Comment by ORESoftware** [comment]
@bitwiseman why not do this for the programmatic API?

`var beautify = require('js-beautify').beautify,
`
so that users can do this:

`const {beautify} = require('js-beautify');
`
or

`import {beautify} from 'js-beautify';`

**Comment by bitwiseman** [comment]
@ORESoftware  - Please file this as a separate issue and we can discuss there.

**Comment by ORESoftware** [comment]
@bitwiseman yeah I tried this:

```js
   this.formattedCode = js_beautify(this.rawGeneratedCode, {
      brace_style: 'preserve_inline',
      max_preserve_newlines: 2
    });
```

I still got this in the output:

```js
 const {
        Builder,
        By,
        Key,
        until
    } = require('selenium-webdriver');
```

even though the input looked like this:

```js
 'builder': {
    left: `const {Builder, By, Key, until} = require('selenium-webdriver');`
  },
```

**Comment by bitwiseman** [comment]
@ORESoftware 
Oh, my bad it's `preserve-inline`.  😱  The option names are underscored, but the values aren't.   😱  Sorry.

**Comment by ORESoftware** [comment]
ahhh let me try it

**Comment by ORESoftware** [comment]
thanks that worked!
