### ISSUE TITLE
HTML: indentation fails after 2nd consecutive layer of tags

### ISSUE THREAD

**Issue by jasjuang** [beautify-web/js-beautify#1326]
# Input
The code looked like this before beautification:
```
<A>
    <IMG>/home/ubuntu/A.jpg</IMG>
</A>
<B>
<IMG>/home/ubuntu/B.jpg</IMG>
</B>
```

# Expected Output
The code should have looked like this after beautification:
```
<A>
    <IMG>/home/ubuntu/A.jpg</IMG>
</A>
<B>
    <IMG>/home/ubuntu/B.jpg</IMG>
</B>
```

# Actual Output
The  code actually looked like this after beautification:
```
<A>
    <IMG>/home/ubuntu/A.jpg</IMG>
</A>
<B>
<IMG>/home/ubuntu/B.jpg</IMG>
</B>
```

Nothing changes. However, if I alter the `<IMG>` tag inside of `<A>` it always snaps back to the correct indentation.

# Steps to Reproduce
copy paste the above code and see the result in http://jsbeautifier.org/

## Settings
default setup in http://jsbeautifier.org/

**Comment by bitwiseman** [comment]
@jasjuang Thanks for filing an issue. 

In the above example the `B` is an "unformatted" tag.  What you are seeing is a bug, but is already heavily reported.  See #840, #841, and the issues linked from them.
