### ISSUE TITLE
How may I tell the formatter, not to send my comments to a new line?

### ISSUE THREAD

**Issue by pillaiindu** [beautify-web/js-beautify#1337]
## [Originally requested VSCode](https://github.com/Microsoft/vscode/issues/43102) to implement this feature.

I put comments on ending divs like the following

```
<div class="col">
  <div class="row">
    <div class="card">

      <h1>Some heading</h1>
      <p>Some text for the card.</p>
      <img src="some/image.jpg" alt="">

    </div> <!-- /.card -->
  </div> <!-- /.row -->
</div> <!-- /.col -->
```
I have also configured my emmet to put the closing div tag comments on the same line as the closing tag.

### The problem:
When I format the document inside VSCode (my editor of choice) which uses js-beautify under the hood, it sends all of my closing div comments to the new line like the following,

```
<div class="col">
  <div class="row">
    <div class="card">

      <h1>Some heading</h1>
      <p>Some text for the card.</p>
      <img src="some/image.jpg" alt="">

    </div>
    <!-- /.card -->
  </div>
  <!-- /.row -->
</div>
<!-- /.col -->
```

Which is a problem for me, and I have to manually backspace them back to the closing div tags.
I [requested VSCode](https://github.com/Microsoft/vscode/issues/43102) team to provide a setting like "html.format.commentOnNewLine": true, which I set to false to get the desired effect, but [they replied](https://github.com/Microsoft/vscode/issues/43102#issuecomment-363811211) that they're using js-beautify under the hood which is doing the work, so I should file the feature here, which I did. :)

Thank You for the nice beautifier and the awesome work!

**Comment by gunther3613** [comment]
I agree with pillaiindu. I have the same problem. I would like to see this implemented.

**Comment by bitwiseman** [comment]
@gunther3613 
Please review the CONTRIBUTING.md and submit a PR.

**Comment by pillaiindu** [comment]
I stopped using js-beautify because of this issue.

**Comment by BrianLeishman** [comment]
@pillaiindu Same, I came from Netbeans, where the *only* formatting it did was (mainly) alter indentation, but it seems like this just tries to do too much, and altering my newlines is as annoying as it gets. It's too bad Netbeans just isn't as all around a good editor as VS Code, but since then I've just manually been formatting my code and I haven't looked back to either

**Comment by bitwiseman** [comment]
#426

**Comment by gkarapeev** [comment]
I still have the problem. I've been looking for a solution for two hours because it's driving me nuts, but still no luck. Below are my version specs.

![version](https://user-images.githubusercontent.com/45083324/55246626-429ca680-524e-11e9-8a2e-5ee4677655f7.JPG)

**Comment by bitwiseman** [comment]
@gkarapeev 
Not sure why that would be.  Please reproduce on beautifier.io and/or show examples of your inputs.

**Comment by gcjuan** [comment]
Using VSCode (1.37.1) with Beautify plugin installed (1.5.0) and set to default formatter on Linux it only works properly for me if I rewrite the comments next to the tag I want to have them.

If I open a file having previously written comments and try to format it, HTML one-line comments move to the next line which is absolutely undesirable and annoying cause it "breaks" my already formatted file =(

**Comment by gcjuan** [comment]
> @gcjuan Please reproduce this on https://beautifier.io using the HTML beautifier. If it does happen there, please not the settings here.

I cannot reproduce it on [https://beautifier.io](https://beautifier.io) the way I do it in VSCode. It should mean there's a problem in the plugin implementation on the code editor cause it works time to time and depending if you've opened a file having already written comments or you write them afterwards.

Thanks for all!
