### ISSUE TITLE
preserve-newline doesn't work for text blocks inside tags

### ISSUE THREAD

**Issue by Nxt3** [beautify-web/js-beautify#1352]
# Input
The code looked like this before beautification:
```
<div *ngIf="someCondition">
  <div class="group">
    <div>
      <field-display>
        {{livedInAddress.addressLineOneText}}
        <br/>
        {{livedInAddress.cityName}}
        {{livedInAddress.countrySubdivisionLevel1TypeID}}
        {{livedInAddress.postalCode}}
      </field-display>
    </div>
    <div>
      <field-display></field-display>
    </div>
  </div>
</div>
```

# Expected Output
The code should have looked like this after beautification:
```
<div *ngIf="someCondition">
  <div class="group">
    <div>
      <field-display>
        {{livedInAddress.addressLineOneText}}
        <br/>
        {{livedInAddress.cityName}}
        {{livedInAddress.countrySubdivisionLevel1TypeID}}
        {{livedInAddress.postalCode}}
      </field-display>
    </div>
    <div>
      <field-display></field-display>
    </div>
  </div>
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div *ngIf="someCondition">
  <div class="group">
    <div>
      <field-display>
        {{livedInAddress.addressLineOneText}}
        <br/> {{livedInAddress.cityName}} {{livedInAddress.countrySubdivisionLevel1TypeID}} {{livedInAddress.postalCode}}
      </field-display>
    </div>
    <div>
      <field-display></field-display>
    </div>
  </div>
</div>
```

# Steps to Reproduce
The lines inside of `field-display` should remain on new lines; otherwise, the linter I'm using complains about how the maximum line length was exceeded. While I can wrap each of those lines inside of a `<div>` to keep them on new lines--I shouldn't have to. `preserve_newlines` should respect this since the `wrap_line_length` value is the same as the maximum line length my linter uses.

## Environment
OS: Mac OS 10.12.6

## Settings
Using the `atom-beautify` package which uses `JS Beautify` for it's beautifier.

<img width="802" alt="screen shot 2018-03-01 at 11 06 50 am" src="https://user-images.githubusercontent.com/2940826/36855278-0b5e876c-1d41-11e8-86a6-ea1612f7b5da.png">
```

**Comment by MacKLess** [comment]
@Nxt3 

If you add `"indent_handlebars": true` to the options in the Additional Settings on the editor (http://jsbeautifier.org/), that should fix the issue for *your* input example. Please note this is v1.8.0-rc4. 

However, your issue is still present in the absence of handlebars.
Input:
```
<div *ngIf="someCondition">
  <div class="group">
    <div>
      <field-display>
        {{livedInAddress.addressLineOneText}}
        <br/>
        {{livedInAddress.cityName}}
        Hello
        World
        
        {{livedInAddress.countrySubdivisionLevel1TypeID}}
        {{livedInAddress.postalCode}}
      </field-display>
    </div>
    <div>
      <field-display></field-display>
    </div>
  </div>
</div>
```

Actual Output:
```
<div *ngIf="someCondition">
  <div class="group">
    <div>
      <field-display>
        {{livedInAddress.addressLineOneText}}
        <br />
        {{livedInAddress.cityName}} Hello World

        {{livedInAddress.countrySubdivisionLevel1TypeID}}
        {{livedInAddress.postalCode}}
      </field-display>
    </div>
    <div>
      <field-display></field-display>
    </div>
  </div>
</div>
```
