### ISSUE TITLE
Does this extension still supports applying Allman style to CSS?

### ISSUE THREAD

**Issue by gusbemacbe** [beautify-web/js-beautify#1353]
Hello,

Referring to https://github.com/beautify-web/js-beautify/issues/1259. I would like to apply Allman style (expand) to CSS, I hate the KNK style. I applied it and it doesn't work. Observation: The indent size didn't work either. 

## Environment
**OS verison:** macOS 10.13.3
**VSCode version:** Insider 1.21.0

## Settings
```json
"beautify.options":
{
        "brace_style": "expand",
        "indent_size": 2,
        "css": 
        {
            "brace_style": "expand",
            "indent_size": 1
        },
}
```

**Comment by bitwiseman** [comment]
This is not currently supported.  I've added this to the backlog.

**Comment by gusbemacbe** [comment]
I am waiting yet...

**Comment by bitwiseman** [comment]
@proimage 
As with so many features of the project, this is awaiting someone to take ownership of it and drive it to completion.  Looking at it, it is probably something that someone could add with relative ease.  You interested?

**Comment by gusbemacbe** [comment]
Hi @bitwiseman !

I am ready to be a collaborator as I got graduated in computer science and received a diploma yesterday. But I am not totally advanced in JavaScript and in Nodejs. I am studying them in the moment. May I take?

**Comment by proimage** [comment]
If I knew how to program, I might. Sorry!

**Comment by bitwiseman** [comment]
@gusbemacbe 
Go right ahead.  You don't need to be advanced.  
The change will be in this area: https://github.com/beautify-web/js-beautify/blob/master/js/src/css/beautifier.js#L286-L310

Come over to the project gitter channel if you want to chat.

**Comment by gusbemacbe** [comment]
Better to fork and git-clone this repository and test it manually before to pull request. I have to run `node run` inside the git-cloned folder.

**Comment by gusbemacbe** [comment]
It seems to give a small error.

**Comment by bitwiseman** [comment]
@gusbemacbe 
We use `make` to run build and test.  
See https://github.com/beautify-web/js-beautify/blob/master/CONTRIBUTING.md
