### ISSUE TITLE
FR: Support for Standard

### ISSUE THREAD

**Issue by mesqueeb** [beautify-web/js-beautify#1356]
I would love to use this with the [Standard](https://github.com/standard/standard) ruleset.

Does anyone have a config file with as close to Standard as possible?

**Comment by bitwiseman** [comment]
We don't specifically, but we'd be happy to see one if you come up with it.

**Comment by jimmywarting** [comment]
You asked this already in #1356

close as dublicate

**Comment by mesqueeb** [comment]
@jimmywarting You are pointing to the same issue...

**Comment by jimmywarting** [comment]
lol, meant #1332

**Comment by mesqueeb** [comment]
@jimmywarting Oh man! I'm so embarrassed! I opened the same issue twice!!!! I'm desperate!! : D
Closed the other ❤
