### ISSUE TITLE
Add function default_options() to beautifier.js

### ISSUE THREAD

**Issue by tkrotoff** [beautify-web/js-beautify#1364]
You can retrieve Beautifier default options using Python: `opts = jsbeautifier.default_options()`, not with JavaScript.

This would be useful for "complex" default options, example with [beautifier.js source code for `unformatted`](https://github.com/beautify-web/js-beautify/blob/v1.7.5/js/src/html/beautifier.js#L93):

```JavaScript
// beautifier.js simplified source code for unformatted
// https://github.com/beautify-web/js-beautify/blob/v1.7.5/js/src/html/beautifier.js#L93
defaultOptions.unformatted = [
  'a', 'abbr', 'area', 'audio', 'b', 'bdi', 'bdo', 'br', 'button', 'canvas', 'cite'
  // ...
];
```

If I want to remove (or add) some tags from the unformatted option I would like to write something like:
```JavaScript
import { html_beautify, defaultOptions } from 'js-beautify';

const excludeButton = defaultOptions.unformatted.filter(tag => tag !== 'button');
const niceHtml = html_beautify(uglyHtml, { unformatted: excludeButton });
```

**Comment by bitwiseman** [comment]
Fixed by #1568.
