### ISSUE TITLE
HTML format, no break after <label>?

### ISSUE THREAD

**Issue by hstig** [beautify-web/js-beautify#1365]
# Input
The code looked like this before beautification:
```
<div class="col-xs-2">
  <input type="radio" class="control-label" ng-disabled="!col" ng-model="col" value="2" class="form-control" id="coli" name="coli" />
  <label for="coli" class="control-label">Collision</label></div>


```

# Expected Output
The code should have looked like this after beautification:
```
<div class="col-xs-2">
  <input type="radio" class="control-label" ng-disabled="!col" ng-model="col" value="2" class="form-control" id="coli" name="coli" />
  <label for="coli" class="control-label">Collision</label>
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div class="col-xs-2">
  <input type="radio" class="control-label" ng-disabled="!col" ng-model="col" value="2" class="form-control" id="coli" name="coli" />
  <label for="coli" class="control-label">Colision</label></div>
```

# Steps to Reproduce

js-beautify --html -r -s 2 -b collapse 
## Environment
OS: debian etch
js-beautify 1.7.5

```

**Comment by gabrielhfgomes** [comment]
Is this bug solved. I got the same formatting problem!

**Comment by bitwiseman** [comment]
@gabrielhfgomes 
Nope, still there.  Help welcome.

**Comment by gabrielhfgomes** [comment]
I was having this problem with beautify in VSCode, I solved it now by rolling back the extension to a 2 year behind version, the 1.0.2 and than the formatting worked perfectly as expected.

**Comment by bitwiseman** [comment]
@gabrielhfgomes 
Not impossible, the code from two years ago was completely different and probably didn't even test properly.  Thanks for trying.

**Comment by bitwiseman** [comment]
This line will cause tags like that `</div>` to be moved to a new line:
https://github.com/beautify-web/js-beautify/blob/master/js/src/html/beautifier.js#L706

However blocks like this are what set that flag: 
https://github.com/beautify-web/js-beautify/blob/333710642f1fdf1fddd65ab8e7fe9ace483ca4c5/js/src/html/beautifier.js#L728-L733

That is obviously not getting set in some key scenarios.
