### ISSUE TITLE
Python version fails to properly beautify packed code

### ISSUE THREAD

**Issue by swan46** [beautify-web/js-beautify#1367]
# Description
Python version fails to properly beautify packed code
# Input
The code looked like this before beautification:
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('$(k).j(i(){$(\'.g\').0(h);$(\'.l\').0(m);$(\'.r\').0(q);$(\'.p\').0(n);$(\'.o\').0(f);$(\'.e\').0(5);$(\'.4\').0(7);$(\'.3\').0(1);$(\'.2\').0(6);$(\'.8\').0(d);$(\'.c\').0(b);$(\'.9\').0(a);$(\'.s\').0(V);$(\'.t\').0(M);$(\'.L\').0(J);$(\'.K\').0(O);$(\'.P\').0(U);$(\'.T\').0(S);$(\'.Q\').0(R);$(\'.I\').0(H);$(\'.y\').0(z);$(\'.x\').0(w);$(\'.u\').0(v);$(\'.A\').0(B);$(\'.G\').0(F);$(\'.E\').0(C);$(\'.D\').0(N)});',58,58,'html|3130|rf82d|r9d0b|r103f|53281|53005|8118|rc5a3|r8ce6|52136|62225|rc366|55555|re4c8|65309|r5e57|8080|function|ready|document|r1655|80|8888|r39b0|r6ae9|3128|rc15b|rfab0|rb0de|r15e2|3129|45169|rd493|r1952|53282|r4a74|8181|9999|r7d8f|r25ce|1080|r9250|63909|r24e3|65103|r860c|r542c|555|45619|41496|r5adc|r8909|8383|65301|r80b7|8123|8088'.split('|'),0,{}))

# Expected Output
$(document).ready(function(){$('.r5e57').html(8080);$('.r1655').html(80);$('.rc15b').html(3128);$('.r6ae9').html(8888);$('.r39b0').html(65309);$('.re4c8').html(53281);$('.r103f').html(8118);$('.r9d0b').html(3130);$('.rf82d').html(53005);$('.rc5a3').html(55555);$('.rc366').html(62225);$('.r8ce6').html(52136);$('.rfab0').html(8088);$('.rb0de').html(555);$('.r542c').html(65103);$('.r860c').html(41496);$('.r5adc').html(8123);$('.r80b7').html(65301);$('.r8909').html(8383);$('.r24e3').html(63909);$('.r1952').html(53282);$('.rd493').html(45169);$('.r15e2').html(3129);$('.r4a74').html(8181);$('.r9250').html(1080);$('.r25ce').html(9999);$('.r7d8f').html(45619)});

# Actual Output
eval(function(p, a, c, k, e, d) {
    e = function(c) {
        return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36))
    };
    if (!''.replace(/^/, String)) {
        while (c--) {
            d[e(c)] = k[c] || e(c)
        }
        k = [function(e) {
            return d[e]
        }];
        e = function() {
            return '\\w+'
        };
        c = 1
    };
    while (c--) {
        if (k[c]) {
            p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c])
        }
    }
    return p
}('$(k).j(i(){$(\'.g\').0(h);$(\'.l\').0(m);$(\'.r\').0(q);$(\'.p\').0(n);$(\'.o\').0(f);$(\'.e\').0(5);$(\'.4\').0(7);$(\'.3\').0(1);$(\'.2\').0(6);$(\'.8\').0(d);$(\'.c\').0(b);$(\'.9\').0(a);$(\'.s\').0(V);$(\'.t\').0(M);$(\'.L\').0(J);$(\'.K\').0(O);$(\'.P\').0(U);$(\'.T\').0(S);$(\'.Q\').0(R);$(\'.I\').0(H);$(\'.y\').0(z);$(\'.x\').0(w);$(\'.u\').0(v);$(\'.A\').0(B);$(\'.G\').0(F);$(\'.E\').0(C);$(\'.D\').0(N)});', 58, 58, 'html|3130|rf82d|r9d0b|r103f|53281|53005|8118|rc5a3|r8ce6|52136|62225|rc366|55555|re4c8|65309|r5e57|8080|function|ready|document|r1655|80|8888|r39b0|r6ae9|3128|rc15b|rfab0|rb0de|r15e2|3129|45169|rd493|r1952|53282|r4a74|8181|9999|r7d8f|r25ce|1080|r9250|63909|r24e3|65103|r860c|r542c|555|45619|41496|r5adc|r8909|8383|65301|r80b7|8123|8088'.split('|'), 0, {}))

# Steps to Reproduce
beautify

## Environment
OS: linux mint 17

## Settings
Example:
detect packers and obfuscators

**Comment by swan46** [comment]
It is very important, that the input is one single line. There are no newlines in it. If there are newlines in it, also jsbeautifier.org would fail to decode it properly.

**Comment by swan46** [comment]
found the solution, please add to github.
Old code, unpackers, packer.py, line 82:
--------------------------------------------------------------------------------------------------
    ALPHABET  = {
        53 : '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ',
        59 : '0123456789abcdefghijklmnopqrstuvwABCDEFGHIJKLMNOPQRSTUVWXYZ',
        62 : '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
        95 : (' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ'
              '[\]^_`abcdefghijklmnopqrstuvwxyz{|}~')
    }

    def __init__(self, base):
        self.base = base

        # If base can be handled by int() builtin, let it do it for us
        if 2 <= base <= 36:
            self.unbase = lambda string: int(string, base)
        else:
            # Build conversion dictionary cache
            try:
-------------------------------------------------------------------------------
new code, packer.py, line 82:
-------------------------------------------------------------------------------
    ALPHABET  = {
        62 : '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
        95 : (' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ'
              '[\]^_`abcdefghijklmnopqrstuvwxyz{|}~')
    }

    def __init__(self, base):
        self.base = base

        # fill elements 36...61, if necessary
        if 36 <= base < 62: 
            if not hasattr(self.ALPHABET, self.ALPHABET[62][:base]):
                      self.ALPHABET[base] =  self.ALPHABET[62][:base]
            #attrs = self.ALPHABET
            #print ', '.join("%s: %s" % item for item in attrs.items())
        # If base can be handled by int() builtin, let it do it for us
        if 2 <= base <= 36:
            self.unbase = lambda string: int(string, base)
        else:
            # Build conversion dictionary cache
            try:
--------------------------------------------------------------------------------------------------------
Thank you in advance.

**Comment by bitwiseman** [comment]
Please submit a PR. You took the time to write the code.  Submit a PR.

**Comment by swan46** [comment]
Added a pull request.

2018-04-09 20:44 keltezéssel, Liam Newman írta:

**Comment by bitwiseman** [comment]
#1368
