### ISSUE TITLE
function parameters merged into single line when starting with ! or [

### ISSUE THREAD

**Issue by dominikschreiber** [beautify-web/js-beautify#1374]
# Description
Function parameters are merged into a single line when they start with `!` (as in `!1`) or `[` (as in `[1,2,3]`). See below. I experience this behavior in [VSCode](https://code.visualstudio.com/) via the [HookyQR.beautify](https://github.com/HookyQR/VSCodeBeautify) extension while editing JavaScript, but it is reproducible via http://jsbeautifier.org/ as well, with any configuration selected.

# Input
The code looked like this before beautification:
```
fn(
  1,
  !1,
  1,
  [1]
)
```

# Expected Output
The code should have looked like this after beautification (same as [Input](#Input)):
```
fn(
  1,
  !1,
  1,
  [1]
)
```

# Actual Output
The  code actually looked like this after beautification:
```
fn(
  1, !1,
  1, [1]
)
```

# Steps to Reproduce
Paste the [Input](#Input) into http://jsbeautifier.org/ and hit [CTRL][ENTER].

## Environment
OS: Windows 10 (10.0.15063 Build 15063)

## Settings
```json
{
    "indent_with_tabs": true,
    "max_preserve_newlines": 2,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": true,
    "keep_function_indentation": true,
    "operator_position": "preserve-newline"
}
```
But the behavior is reproducible with any configuration on http://jsbeautifier.org that I tried.

**Comment by bitwiseman** [comment]
Likely the same as #1288.
