### ISSUE TITLE
unindent_chained_methods breaks indentation for if statements without brackets 

### ISSUE THREAD

**Issue by hstig** [beautify-web/js-beautify#1378]
# Input
The code looked like this before beautification:
```JavaScript
      var g = 0;
      if (g === 1)
        g = 0;
      else
        g = 1; 
```

# Expected Output
The code should have looked like this after beautification:
```JavaScript
      var g = 0;
      if (g === 1)
        g = 0;
      else
        g = 1; 
```
# Actual Output
The  code actually looked like this after beautification:
```JavaScript
      var g = 0;
      if (g === 1)
      g = 0;
      else
      g = 1; 
```

# Steps to Reproduce

## Environment
OS: Debian GNU/Linux 9 (stretch) 64-bit
CLI: js-beutify Ver: 1.7.5

## Settings
js-beautify -u -s 2 -a -b collapse,preserve-inline

**Comment by bitwiseman** [comment]
I can't reproduce this on http://jsbeautifier.org/  Not sure what would cause that to happen.

**Comment by hstig** [comment]
I've used the command line tool of js-beutify, ver: 1.7.5.

**Comment by bitwiseman** [comment]
@hstig 
What is the full command line you're using? (Including file name)

**Comment by hstig** [comment]
`js-beautify -u -s 2 -a -b collapse,preserve-inline \#1378.js
`

**Comment by bitwiseman** [comment]
@hstig 
Ah, I see you only get it with `unindent_chained_methods`.  I see it now. Thanks!
