### ISSUE TITLE
Where is the config documentation?

### ISSUE THREAD

**Issue by mcshaman** [beautify-web/js-beautify#1392]
I have been looking for abkour 20 mins now and can't find where the documentation for configuring is. While I'm sure it must be somewhere can you point me towards it and I also recommend improving it's visibility.

**Comment by bitwiseman** [comment]
What do you want to configure?  This has a good example of passing option when called node.
https://github.com/beautify-web/js-beautify#javascript

Command-line options are directly below that.

**Comment by GitStorageOne** [comment]
Can't change any options from VSCODE user settings.
What's wrong with defined options?

```
"beautify.options": {
        "end-with-newline": true,
        "max_preserve_newlines": 10,
        "preserve-newlines": true
    }
```

**Comment by GitStorageOne** [comment]
Seems it's vscode plugin (by michelemelluso) issue.
Options that defined in VSCODE user settings not applied.
If plugin is not maintained by this project, then please close discussion)

**Comment by bitwiseman** [comment]
@GitStorageOne That plugin is not maintained by this project.
