### ISSUE TITLE
Running js-beautify under cron

### ISSUE THREAD

**Issue by cnmcdee** [beautify-web/js-beautify#1395]
Simple script..

script.sh

runs fine under command line, 

does not run under cron...

Any suggestions?

**Comment by bitwiseman** [comment]
unclear what you're asking.
 
In complete information.

Please be more specific.

Give examples.

Include more detail.

**Comment by cnmcdee** [comment]
Command line : /stock/day01_scalp.sh run as root runs find..

crontab -e 

*/5 13-20 * * 1-5 /stock/day01_scalp.sh >> /stock/process.log 

will run all parts of script except 
 js-beautify -o /stock/data_beautify/$ss $ss >> /stock/process.log

js-beautify will not run when called from a cron timing..

**Comment by rickeyski** [comment]
Does running the following help?

``` sh
#env - HOME="$HOME" LOGNAME="$USER" PATH="/usr/bin:/bin" SHELL="$(which sh)" js-beautify -o /stock/data_beautify/$ss $ss >> /stock/process.log
```
js-beautify probably isn't on cron's path

**Comment by cnmcdee** [comment]
Solution was found to sudo js-beautify so it had root environment.. Thanks..
