### ISSUE TITLE
merge this code to support blade template

### ISSUE THREAD

**Issue by FaridAghili** [beautify-web/js-beautify#1396]
Hi, there is hack which adds the support for Laravel's blade template, it works good but the hack need to edit js-beautify source code.

Check this out:
https://gist.github.com/mpryvkin/0c46e2493b450f92492e8e9a46ad5d97

**Comment by bitwiseman** [comment]
Moving to #845

**Comment by bitwiseman** [comment]
Moving to #845

**Comment by bitwiseman** [comment]
Moving to #845

**Comment by bitwiseman** [comment]
Closing

**Comment by bitwiseman** [comment]
moved to #845
