### ISSUE TITLE
JS: Reserved keyword as function name leads to syntax errors

### ISSUE THREAD

**Issue by Hirse** [beautify-web/js-beautify#1397]
# Description
When formatting JavaScript code with functions named like keywords, a space is inserted between the name and the opening `(`. This leads to broken code.

Using keywords as function names is not ideal, but apparently the case for Polymer, see https://github.com/brackets-beautify/brackets-beautify/issues/262 (and https://github.com/Hirse/brackets-beautify/issues/26).

# Input
The code looked like this before beautification:
```js
import('file.js');
```

# Expected Output
The code should have looked like this after beautification:
```js
import('file.js');
```

# Actual Output
The  code actually looked like this after beautification:
```js
import ('file.js');
```

**Comment by bitwiseman** [comment]
See #1393 
Already in the next version.

**Comment by Hirse** [comment]
Awesome, no wonder I couldn't find it in the list of open issues. :+1: 

That is the same user that reported the bug in my repos, but didn't link them. :disappointed:
