### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by lgarron** [beautify-web/js-beautify#1399]
https://jsbeautifier.org/ shows a certificate error for me. I have Javascript disabled for HTTP, so I cannot use `jsbeautifier.org` without hacking around the fact that it is insecure.

Now that GitHub [supports HTTPS for custom domains](https://help.github.com/articles/using-a-custom-domain-with-github-pages/), it would be nice to see the project served over HTTPS. :-)

**Comment by bitwiseman** [comment]
The support in github doesn't work on the jsbeautifier.org site for some reason.  I need to look into why.

**Comment by Crystal-RainSlide** [comment]
Maybe we can use Let's Encrypt directly?

https://github.com/Neilpang/acme.sh

**Comment by bitwiseman** [comment]
https://beautifier.io works. Working on redirecting.

**Comment by Crystal-RainSlide** [comment]
That's great.
