### ISSUE TITLE
HTML: wrap_line_length is handled incorrectly

### ISSUE THREAD

**Issue by vvs** [beautify-web/js-beautify#1401]
# Description
js-beautify doesn't handle `wrap_line_length` properly. Say, I have set it to 40. But the beautifier breaks the line not on 40th character. In my case it is on 50th character. In fact, the text content of the span tag is broken exactly on 40th character, but the setting should be related to the whole line, not to the length of the content inside the tag.

# Input
The code looked like this before beautification:
```
<html lang="en">
<head>Test</head>
<body>
  <span>1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24</span>
</body>
</html>
```

# Expected Output
The code should have looked like this after beautification:
```
<html lang="en">

<head>Test</head>

<body>
  <span>1 2 3 4 5 6 7 8 9 10 11 12 13
    14 15 16 17 18 19 20 21 22 23 24</span>
</body>

</html>
```

# Actual Output
The  code actually looked like this after beautification:
```
<html lang="en">

<head>Test</head>

<body>
  <span>1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
    17 18 19 20 21 22 23 24</span>
</body>

</html>
```

## Environment
OS: Windows 10

## Settings
Example:
```json
{
    "html": {
        "indent_size": 2,
        "unformatted": [],
        "wrap_line_length": 40
    }
}
```

**Comment by vvs** [comment]
This is a smallest test case I could come up with, but I am seeing this problem A LOT, in side VS Code, when reformatting some long lines. The setting is set to 80, but I am seeing lines up to 150 characters!

When I set it to 40, I see lines up to 100, etc.

My expectations are that if the max limit is set to some value, then js-beautify should try to honor that value and produce longer lines only if there is no other way.

**Comment by bitwiseman** [comment]
@vvs The beautifier doesn't have sufficient information to do line wrapping correctly in all cases, but this is definitely a bug.

**Comment by bitwiseman** [comment]
I think https://github.com/beautify-web/js-beautify/commit/35dc66afa36a90ce1aababa0f15fb84ff4552ee6 may address this issue, but I haven't written tests to check.   Thanks for the good examples above, they will make good tests.

**Comment by bitwiseman** [comment]
This is improved (see #1432) but still not really right.

**Comment by MacKLess** [comment]
I ran this on v1.8.0-rc4, with the following settings:
```
{
  "indent_size": "2",
  "wrap_line_length": "40",
}
```

And the actual output was this:
```
<html lang="en">

<head>Test</head>

<body>
  <span>1 2 3 4 5 6 7 8 9 10 11 12 13 14
    15 16 17 18 19 20 21 22 23 24</span>
</body>

</html>
```
It hasn't resolved the issue, but the line wraps after '14' instead of '16' so there seems to have been a shift closer to correct.
