### ISSUE TITLE
Idea: a setting to do nothing / dry-run

### ISSUE THREAD

**Issue by amenadiel** [beautify-web/js-beautify#1405]
I have been playing with config options and I cannot find a combination that actually does nothing. 

For example, when beautifying a partial html template (Vue or Angular component) using the "unformatted" option to ignore custom components (`v-flex`, `v-layout`, etc) they get formatted (or at least indented) anyway, and it seems the tokenizer doesn't fully understand its structure, no the output isn't nested the way it should be.

I was wondering if there could be a setting to actually tell the script to ignore all tags, or perform no analysis whatsoever.

Just my 2 cents

**Comment by bitwiseman** [comment]
@amenadiel  Could you describe the behavior you'd like to see in a different way than that above?  I'm not sure I understand what you're looking for.

**Comment by amenadiel** [comment]
Ok. Let's say I have a folder with N projects, and I run an automated task to navigate inside each one and perform beautifying of js, html and css files.

Each project has its own .jsbeautifyrc file and there are slight difference between each other.

Now, if I have a project where I do not want to beautifying for HTML files, I have no way of disabling the process for that file type on that project.

The only way I can deal with this right now is to manually enter blacklisted folders in the automated task. It would be ideal if I could set a flag in each project . jsbeautifyrc to tell the library to don't touch a given file type.

**Comment by bitwiseman** [comment]
Ah, you'd like to have a setting in .jsbeautifyrc called "ignore" or "dry_run" setting that you could put under the file type. 

```
{
  "html": {
    "ignore": true
  }
}
```

**Comment by amenadiel** [comment]
That's it, exactly.

**Comment by bitwiseman** [comment]
@amenadiel This functionality currently exists in the Javascript beautifier for testing purposes as `test_output_raw`.  It is not implemented for the CSS or HTML beautifier.  They do not use the same input parsing and output handling routines.

**Comment by amenadiel** [comment]
@bitwiseman regarding "skip_file_extensions" yes, that would be a pretty decent solution :+1:

**Comment by bitwiseman** [comment]
Implemented as `disabled` option.
