### ISSUE TITLE
No newline after @import

### ISSUE THREAD

**Issue by LoganDark** [beautify-web/js-beautify#1406]
No matter what I try, CSS always ends up like this:
```css
@import url('bla bla bla...');
body {
    ...
}
```

But that does _**not**_ look beautiful. Why? Because the `@import` is all squished up against the `body` selector, there's no whitespace.

There is no option to fix this.

**Comment by bitwiseman** [comment]
There is a preserve_newlines option in the next release.  Would that meet your need?

**Comment by LoganDark** [comment]
There is a `preserve_newlines` option right now. But I don't want to preserve _all_ newlines.

**Comment by bitwiseman** [comment]
@LoganDark 
Okay, setting this as an enhancement.

**Comment by MacKLess** [comment]
Input correction for testing purposes:
(don't forget the semicolons!)
```
@import url('bla bla bla...');
body {
    ...
};
```

**Comment by LoganDark** [comment]
You... what? You don't put semicolons after a closing brace in CSS...

**Comment by bitwiseman** [comment]
@LoganDark  Yeah,  but semicolon after @import is needed.  

```
@import url('bla bla bla...');
body {
    ...
}
```

**Comment by LoganDark** [comment]
@bitwiseman yes? That's basic CSS...

The code I typed in my issue is not the actual CSS, I typed it in the textbox in 10 seconds without a second though.

**Comment by bitwiseman** [comment]
@LoganDark  Updated the example in the original description now.
