### ISSUE TITLE
elContainer.style.flex - direction = 'column';

### ISSUE THREAD

**Issue by TudorHulban** [beautify-web/js-beautify#1410]
# Description
using Brackets with the beautifier plugin wanted to set in Javascript the container display to flex with direction column.
```
elContainer.style.flex-direction = 'column'; 
```

transforms to:
```
elContainer.style.flex - direction = 'column';
```

# Input
The code looked like this before beautification:
```
elContainer.style.flex-direction = 'column'; 
```

# Expected Output
The code should have looked like this after beautification:
```
elContainer.style.flex-direction = 'column'; 
```

# Actual Output
The  code actually looked like this after beautification:
```
elContainer.style.flex - direction = 'column';
```

# Steps to Reproduce
beautify Javascript file

## Environment
OS: Brackets 1.12 with Linux Mint 18.3

**Comment by bitwiseman** [comment]
I think this is accurate for javascript.  Dashes are not allowed as part of identifier names.

**Comment by user-9826342** [comment]
@TudorHulban 

Your code snippet is not a valid JavaScript syntax. You probably want to use

```js
elContainer.style.flexDirection = 'column';
```

**Comment by TudorHulban** [comment]
thank you!
