### ISSUE TITLE
Issue while formatting handlebars

### ISSUE THREAD

**Issue by rastogiachyut** [beautify-web/js-beautify#1415]
This code:

		{{#isDealLink}}
		&nbsp;&nbsp;<a target="_blank" href="{{dealLink}}" class="weak">See offer details</a>
		{{/isDealLink}}

Is formatted to:

                {{#isDealLink}} &nbsp;&nbsp;
                    <a target="_blank" href="{{dealLink}}" class="weak">See offer details</a> {{/isDealLink}}

I'd like it to be:

                {{#isDealLink}} &nbsp;&nbsp;
                    <a target="_blank" href="{{dealLink}}" class="weak">See offer details</a>
                {{/isDealLink}}

are there some formatting options available for this? Please ignore indentation differences, what is want is for `{{/isDealLink}}` to be on a separate line. There seems to be a problem in the regex used, it looks for `{{` instead of `{{/` when indenting for the end.

**Comment by bitwiseman** [comment]
#660

**Comment by MacKLess** [comment]
Per version v.1.8.0-rc2, the output looks like this:
```
{{#isdeallink}}
    &nbsp;&nbsp;<a target="_blank" href="{{dealLink}}" class="weak">See offer details</a>
{{/isdeallink}}
```
Probably worth calling this fixed.
