### ISSUE TITLE
Each attribute on its line

### ISSUE THREAD

**Issue by affanshahid** [beautify-web/js-beautify#1416]
I am aware of `wrap_attributes: 'force'`, which puts the first attribute on the same line then every following attribute on its own line. Is there an option to have **all** attributes on their own lines, like the following:

![image](https://user-images.githubusercontent.com/17955210/41435566-ac8f2dd6-7038-11e8-94d1-a29dea6b4061.png)

**Comment by bitwiseman** [comment]
Try `wrap_attributes: 'force-expand-multiline'`.
