### ISSUE TITLE
How can I add space left and right to css/scss operator?

### ISSUE THREAD

**Issue by MOONLIGHTV** [beautify-web/js-beautify#1418]
How can I add space left and right to css/scss operator?
Operator like "+","-","*","/" doesn't work if has no space in calc();

![0](https://user-images.githubusercontent.com/14039419/41457097-1f7db084-70b5-11e8-82d2-a06f37ff5e08.gif)

**Comment by bitwiseman** [comment]
Please fix your description to not use screenshots.

**Comment by MacKLess** [comment]
Unfortunately, we do not work with screen shots. If you would like to reopen this issue, please copy and paste code using triple back-tick format.
