### ISSUE TITLE
Where is the jsbeautifyrc file

### ISSUE THREAD

**Issue by asaadmahmood** [beautify-web/js-beautify#1420]
I have a very basic question. Where is the `.jsbeautifyrc`. I'm trying to find it for long but can't.

I'd like to give `preserve_newlines` somewhere, but I don't know where I should place it. I tried finding the `.jsbeautifyrc` on my whole mac, but was not able to find a global file.

Really stuck.

```
"css": {
  "preserve_newlines": true
}

**Comment by bitwiseman** [comment]
You probably don't want to edit the config built into the package. 
Add a `.jsbeautifyrc` file to your project directory or any containing folder.
