### ISSUE TITLE
I have an idea about the "wrap-attributes: force-expand-multiline"

### ISSUE THREAD

**Issue by win7killer** [beautify-web/js-beautify#1423]
# Description
> About the `"wrap-attributes: force-expand-multiline"` 's bugs, I have an idea to try

# Steps
1. Beautify the html string by the `"wrap-attributes: auto"` at first
2. Just replace the whitespace between the tag's attributes to ` '\s' * indent_size + '\n'`

Maybe it work...
@bitwiseman

**Comment by bitwiseman** [comment]
@win7killer Please submit a PR or commit with change you think should work.

**Comment by bitwiseman** [comment]
@win7killer 
The issue is "wrap-attributes" -> "wrap_attributes".
