### ISSUE TITLE
page scrolls after pasting code

### ISSUE THREAD

**Issue by ShadyNawara** [beautify-web/js-beautify#143]
Hi i realy love js-beautify and i use it a lot but when i paste a lot of code so it exceeds the are of the text box and has to scroll the page also scrolls to the end and this is really annoying

**Comment by stephanoshadjipetrou** [comment]
Hello @einars @bitwiseman 

Is there any way to disable the codemirror effects mentioned above while using the package in a React project?

Thanks in advance :)

**Comment by bitwiseman** [comment]
@stephanoshadjipetrou 
This is only present on the homepage.  If you're not including the homepage you don't get these effects.  Are you embedding the page in your project?

**Comment by stephanoshadjipetrou** [comment]
Hi @bitwiseman and thanks for fast reply!

So yes, using `js-beautify` in a React project.

```
import beautify from 'js-beautify';

export const beautifyCode = (code: string) => {
  return beautify.html(code, {
    indent_size: '4',
    indent_char: ' ',
    max_preserve_newlines: '5',
    preserve_newlines: true,
    keep_array_indentation: false,
    break_chained_methods: false,
    indent_scripts: 'normal',
    brace_style: 'expand',
    space_before_conditional: true,
    unescape_strings: false,
    jslint_happy: false,
    end_with_newline: false,
    wrap_line_length: '80',
    indent_inner_html: true,
    comma_first: false,
    e4x: false,
    wrap_attributes: 'preserve',
  });
};
```

How could I include the homepage while using the `js-beautify` npm package?

**Comment by bitwiseman** [comment]
I don't know.  As such, there are no CodeMirror effects in the npm package.
