### ISSUE TITLE
Commenting code and then beautifying removes line breaks

### ISSUE THREAD

**Issue by pmattke** [beautify-web/js-beautify#1440]
# Description

I use beautify via the VSCode extension and, at least in scss files (did not try for other types yet), it removes line breaks before commented rules. Sometimes, I just want to comment a few lines, save it (I have format on save turned on), see the result on the web page and then go on. But this behaviour is quite annoying for this scenario

# Input
The code looked like this before beautification. Notice that the height property is commented, because I quickly wanted to see the result without it.
```
        #search-text {
            width: 43%;
            max-width: 270px;
            // height: 100%;
            border: none;
            border-radius: 5px;
            padding-left: 0.5rem;
            font-size: 1.1rem;
            color: $main-color;
        }
```

# Expected Output
Should leave it as it is

# Actual Output
The  code actually looked like this after beautification. Notice that the line break before the comment has been removed. This might be wished in _some_ cases, but I think in most cases, this is not desired, because when you start a comment in a newline, you normally do so by intention. You don't want to move that comment up on the previous line, next to the code.
```
        #search-text {
            width: 43%;
            max-width: 270px; // height: 100%;
            border: none;
            border-radius: 5px;
            padding-left: 0.5rem;
            font-size: 1.1rem;
            color: $main-color;
        }
```

# Steps to Reproduce
Just beautify the code (scss file) provided above. Perhaps it also occurs for other file types, not sure, did not try.

## Environment
OS: Kubuntu
IDE: Visual Studio Code

## Settings

```json
{
    "indent_size": 4,
    "end_with_newline": true,
    "wrap_line_length": 120,
    "preserve_newlines": true,
    "max_preserve_newlines": 3
}

```

**Comment by bitwiseman** [comment]
Fixed in 1.8.0
