### ISSUE TITLE
Restyle website

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#1444]
Update jsbeautifier.org to modern website styling, example http://jshint.com/ .

**Comment by mhnaeem** [comment]
@bitwiseman Here's an opinionated redesigned version of the site. It is not as pretty or clean as the jshint website but this is a quick overhaul which can be improved over time. It is also responsive enough that we can use the site from mobile. I have added some pics below to show the differences.

**Old Site Desktop:**
<img width="1792" alt="Screenshot 2022-04-11 at 11 52 55 PM" src="https://user-images.githubusercontent.com/33136628/162866519-ab1ae3f4-d176-42c5-bf95-5aa2db8b370c.png">


**New Site Desktop:**
<img width="1789" alt="Screenshot 2022-04-11 at 11 46 42 PM" src="https://user-images.githubusercontent.com/33136628/162866288-24cd3a33-8b32-4be0-8dca-db6ef8392be2.png">
 
**Old Mobile Site:**
<img width="605" alt="Screenshot 2022-04-11 at 11 53 57 PM" src="https://user-images.githubusercontent.com/33136628/162866619-d2ee987e-f1b5-466b-9d4b-b5c4dd2e5a51.png">

**New Mobile Site:**
<img width="572" alt="Screenshot 2022-04-11 at 11 47 31 PM" src="https://user-images.githubusercontent.com/33136628/162866681-8410072a-8f64-4b70-a32b-5559377ef423.png">
<img width="572" alt="Screenshot 2022-04-11 at 11 47 39 PM" src="https://user-images.githubusercontent.com/33136628/162866716-1c3e8bdd-c35c-4915-b24c-8bbd18e4ee37.png">
