### ISSUE TITLE
how can I disabled auto newlines

### ISSUE THREAD

**Issue by year520** [beautify-web/js-beautify#1453]
# Description
how can I disabled auto newlines for es6
# Input
import {ClaimHandlingAction,ClaimHandlingStore} from 'ClaimCommon';

# Expected Output **do nothing**
import {ClaimHandlingAction,ClaimHandlingStore} from 'ClaimCommon';

# Actual Output
import {
    ClaimHandlingAction,
    ClaimHandlingStore
} from 'ClaimCommon';

**Comment by bitwiseman** [comment]
Setting: `"brace_style": "collapse,preserve-inline"`
