### ISSUE TITLE
Preserve-inline for Arrays (like it is for Objects)

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1457]
# Description

The `brace_style: collapse,preserve-inline` setting lets you have inline object no matter how deep:

```js
const obj = { a: { b: { c: { d: { e: 1 } } } } }
```

I want to have the same for nested arrays:

```js
const arr = [ [ [ [ [1] ] ] ] ]
```

# Input
With this new feature, when I give like this input: 
```js
const arr = [ [ [ [ [1] ] ] ] ]
```

# Expected Output
I'd like to see this output: **(unchanged)**
```js
const arr = [ [ [ [ [1] ] ] ] ]
```

# Actual Output
Currently I see this output: 
```js
const arr = [
  [
    [
      [
        [1]
      ]
    ]
  ]
]
```
## Environment
OS: Win10

**Comment by laggingreflex** [comment]
Dupe #1424

**Comment by jacobsdc** [comment]
This perfectly expresses what I'm trying to do too.
