### ISSUE TITLE
hbs tags are stripped when there is a comment below or inline

### ISSUE THREAD

**Issue by astronomersiva** [beautify-web/js-beautify#1461]
# Description
In HBS files, if there is a comment inline or below an HBS tag, the tag is stripped off.

# Case 1

### Input
The code looked like this before beautification:

```
{{hello "world"}} {{!-- this is comment --}}
```

### Expected Output
The code should have looked like this after beautification:

```
{{hello "world"}} {{!-- this is comment --}}

```

### Actual Output
The  code actually looked like this after beautification:
```
{{!-- this is comment --}}
```

# Case 2

### Input
The code looked like this before beautification:

```
{{hello "world"}}
{{!-- this is comment --}}
{{hello "again"}}
```

### Expected Output
The code should have looked like this after beautification:

```
{{hello "world"}}
{{!-- this is comment --}}
{{hello "again"}}
```

### Actual Output
The  code actually looked like this after beautification:
```
{{!-- this is comment --}}
{{hello
  "world2"}}
```

**Comment by bitwiseman** [comment]
Fixed in 1.8.0-rc3.
