### ISSUE TITLE
HTML tags are indented wrongly when attributes are present

### ISSUE THREAD

**Issue by astronomersiva** [beautify-web/js-beautify#1462]
# Input
The code looked like this before beautification:
```
<div class="hello">
<p>hello</p>
</div>
```

# Expected Output
The code should have looked like this after beautification:
```
<div class="hello">
    <p>hello</p>
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div
  class="hello">
  <p>hello</p>
  </div>
```

**Comment by bitwiseman** [comment]
@astronomersiva 
What settings are you using?

**Comment by astronomersiva** [comment]
I'm running this with the CLI as

`js-beautify -r -s=2 --wrap_line_length=2 --type=html fileName`

The same issue is applicable for handlebars as well(with and without the `--indent_handlebars` flag).

```
<div
  class="hello">
  {{world}}
  </div>
```

**Comment by bitwiseman** [comment]
Which version of js-beautify?  This looks to be fixed in the latest RC (`npm install -g js-beautify@next`).

**Comment by astronomersiva** [comment]
@bitwiseman , thanks a ton for the quick response. Yes, this is fixed in the latest release. Thanks for the great work :)
