### ISSUE TITLE
SyntaxError: invalid or unexpected token mismatches

### ISSUE THREAD

**Issue by jau88** [beautify-web/js-beautify#1463]
# Description
> No detection of  invalid or unexpected token mismatches. Need to check against mismatches like a  simple quotes ( " ) vs non-standard quotation marks ( “ ).

# Input
The code looked like this before beautification:
```
<“This looks like a string”>
```

# Expected Output
The code should have looked like this after beautification, note the quotation marks:
```
<"This is actually a string">
```

# Actual Output
The  code actually looked like this after beautification:
```
<“This looks like a string”>
```

# Steps to Reproduce

## Environment
OS: iOS Safari

**Comment by bitwiseman** [comment]
The beautifier only changes whitespace at this time.  Fixing errors such a quotation marks is not in scope at this time - though I agree they can be a real pain.
