### ISSUE TITLE
Uppercase in the tag becomes lowercase after formating

### ISSUE THREAD

**Issue by 404errors** [beautify-web/js-beautify#1467]
After I format XHTML source code, all uppercase in the tag name become lowercase. I'm pretty sure this is a new issue because I used before with no issue.
Before
![before](https://user-images.githubusercontent.com/15071709/43556211-d78f072a-9628-11e8-9a0b-8ff557324927.PNG)
After
![after](https://user-images.githubusercontent.com/15071709/43556220-e31f537e-9628-11e8-8777-b191cabf4ed0.PNG)

**Comment by bitwiseman** [comment]
Fixed in 1.8.0-rc4.  
Released today.  If this is not fixed please provide code sample in text not image form.

**Comment by 404errors** [comment]
It worked. Thank you very much
