### ISSUE TITLE
HBS attributes should not be collapsed to the same line, including first attribute

### ISSUE THREAD

**Issue by astronomersiva** [beautify-web/js-beautify#1469]
# Description
In HBS files, it is generally a good practice to have attributes on individual lines to avoid horizontal scrolling. `js-beautify` shouldn't collapse already formatted attributes like these into a single line.

# Input
The code looked like this before beautification:
```
{{some-component
    attr1=attr1
    attr2=attr2
    attr3=attr3
    attr4=attr4
    attr5=attr5
    attr6=attr6
    attr7=attr7
    attr8=attr8
    attr9=attr9
    attr10=attr10}}
```

# Expected Output
The code should have looked like this after beautification(no changes):
```
{{some-component
    attr1=attr1
    attr2=attr2
    attr3=attr3
    attr4=attr4
    attr5=attr5
    attr6=attr6
    attr7=attr7
    attr8=attr8
    attr9=attr9
    attr10=attr10}}
```

# Actual Output
The  code actually looked like this after beautification:
`{{some-component attr1=attr1 attr2=attr2 attr3=attr3 attr4=attr4 attr5=attr5 attr6=attr6 attr7=attr7 attr8=attr8 attr9=attr9 attr10=attr10}}`

# Steps to Reproduce

## Environment
OS: macOS
js-beautify: 1.8.0-rc4

## Settings
Example:
`js-beautify --preserve-newlines -r -s=2 --type=html --indent_handlebars fileName`

**Comment by bitwiseman** [comment]
@astronomersiva  in the upcoming rc5, I'm treating treating the text inside the handlebars as literals strings.  So, you will get part way to this behavior.  But indenting won't work. :|

**Comment by astronomersiva** [comment]
@bitwiseman, thanks for this!

I will try and take a stab at making indentation work.
