### ISSUE TITLE
Weird Formatting in VSCode

### ISSUE THREAD

**Issue by TianxinTse** [beautify-web/js-beautify#1475]
## Problem Description
Here is an example:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
```
If the last child element has no closing tag, like `<meta>`, formatting the document above will produce:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"></head>
```
---
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>document</title></head>
```
If the last child element does have a closing tag, like `<title>`, formatting the document above will produce:
```
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>document</title>
</head>
```

## Env
VSCode Version: 1.25.1
OS Version: Windows 10 Version 1803
Installed Related Extensions: Beautify

## Steps to Reproduce:
Open any html files.
Use the shortcut to format the document.
Does this issue occur when all extensions are disabled?: Yes

**Comment by bitwiseman** [comment]
Please try this on http://jsbeautifier.org/ which is running the latest rc4.

**Comment by HookyQR** [comment]
@bitwiseman I ran beautify over this in VS Code, both with the beautify file and beautify selection (with various segments selected) and can't reproduce the described behaviour. Could be a user settings issue. Feel free to move this to https://github.com/HookyQR/VSCodeBeautify

(Still requires further info - VS Code user settings, `rc` file settings etc.)

**Comment by TianxinTse** [comment]
@bitwiseman @HookyQR  I've found one user setting causing this problem.

```
// Whether existing line breaks before elements should be preserved. Only works before elements, not inside tags or for text.
    "html.format.preserveNewLines": true,
```

When the value is true, it seems ok. When the value is set to be false, the formatting result will have the weird style that I described above.

**Comment by TianxinTse** [comment]
@bitwiseman I met the same issue both on Windows 10 and the latest OS X High Sierra.

**Comment by RiFi2k** [comment]
So if you happen to have the `meta` value being added to the content_formatted option it will more or less stop formatting inside the header, until it hits something else. If it doesn't you could have strange results depending on your other settings mixed in.

I don't think this is actually a bug.

Also I have had much better results with the default settings coming from vscode on the new rc releases rather than 1.7.5

**Comment by bitwiseman** [comment]
@RiFi2k 
Thank you!  Your description let me figure out one possible reason for this happening.  
The HTML beautifier needs to evaluate whether something is a `void_element` *before* considering whether it can be `content_unformatted`.  

# Input
The code looked like this before beautification:
```
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"></head>
```

# Current Output
The  code actually looked like this after beautification:
```
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"></head>
```

# Expected Output
The code should have looked like this after beautification:
```
/*Adjust the code to look how you prefer the output to be.*/
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
```

## Environment
Browser User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

Language Selected:
HTML

## Settings
Example:
```json
{
  "indent_size": "2",
  "indent_char": " ",
  "preserve_newlines": false,
  "content_unformatted": [
    "meta"
  ]
}
```
