### ISSUE TITLE
Duplicating HTML Code Nested In PHP

### ISSUE THREAD

**Issue by RiFi2k** [beautify-web/js-beautify#1483]
So I use this library in a vscode extension which formats HTML code inside PHP files. I found this just now when going to publish a new version.
This is going from 1.8.0-rc4 > 1.8.0-rc5 so it has to be something in there because I tested the same situation in both versions with no other changes.

Node.js version

# Input
```
<?php
/**
 * Comment
 */

?>
<div class="">

</div>
```

# Output
```
<?php
/**
 * Comment
 */

?>
<div
<?php
/**
 * Comment
 */

?>
<div
<?php
/**
 * Comment
 */

?>
<div
<?php
/**
 * Comment
 */

?>
<div
<?php
/**
 * Comment
 */

?>
<div

</div>
```

If you lose the class attribute completely off the div tag then it's completely fine, but adding that attribute in that situation causes the duplication.

These are the exact settings I was currently testing at the time.
```
indent_with_tabs:true
indent_size:4
indent_char:" "
end_with_newline:true
extra_liners:Array[3]
0:"head"
1:"body"
2:"/html"
indent_handlebars:true
indent_inner_html:true
max_preserve_newlines:null
preserve_newlines:true
wrap_line_length:0
wrap_attributes:"auto"
content_unformatted:Array[25]
0:"area"
1:"base"
2:"br"
3:"col"
4:"embed"
5:"hr"
6:"img"
7:"input"
8:"keygen"
9:"link"
10:"menuitem"
11:"meta"
12:"param"
13:"source"
14:"track"
15:"wbr"
16:"!doctype"
17:"?xml"
18:"?php"
19:"?="
20:"basefont"
21:"isindex"
22:"pre"
23:"code"
24:"textarea"
```

**Comment by RiFi2k** [comment]
Thanks for looking, not saying you should reopen this or anything, but it's been working fine in configs since 1.7.5 or before, and just on this last rc it breaks so might be worth checking into why.
https://github.com/junstyle/vscode-php-cs-fixer/blob/master/beautifyHtml.js

**Comment by bitwiseman** [comment]
No, thank you for reporting the issue.  It was important and I implemented a fix and released rc6 including a fix for this. Please report any issues, especially regressions you see in the future.  😄

**Comment by RiFi2k** [comment]
On a side note now I can lose a lot of bloat in that array lol
