### ISSUE TITLE
still probem #1439 / #1337

### ISSUE THREAD

**Issue by Mlocik97-issues** [beautify-web/js-beautify#1491]
#1439 (https://github.com/Microsoft/vscode/issues/53546)  #1337
In body it work now correctli bod in head not, it's always formating:

```
<head>
    <script src="one.js"></script> <!-- one -->
    <script src="two.js"></script> <!-- two-->
</head>
```

as

```
<head>
    <script src="one.js"></script>

    <!-- one -->
    <script src="two.js"></script>

    <!-- two-->
</head>
```

1.8.0-rc2 & 1.8.0-rc4

**Comment by bitwiseman** [comment]
@Mlocik97-issues  
Take a look on http://jsbeautifier.org/  1.8.0-rc9

```
<body>
  <script src="one.js">
  </script> <!-- one -->
  <script src="two.js">
  </script> <!-- two-->
</body>
```

Still not quite right, but better. 

Can you include your settings here?

**Comment by bitwiseman** [comment]
Should be fully fixed in rc10. http://jsbeautifier.org/

**Comment by Mlocik97-issues** [comment]
I have default settings as it was installed with vscode, maybe how it has vscode is there: https://github.com/Microsoft/vscode-html-languageservice/tree/master/src

**Comment by Mlocik97-issues** [comment]
```
{
"indent_inner_html": "false",
      "indent_size": "2",
      "indent_char": " ",
      "wrap_line_length": "78",
      "brace_style": "expand",
      "preserve_newlines": "true",
      "max_preserve_newlines": "5",
      "indent_handlebars": "false",
      "extra_liners": "['/html']"
}
```
