### ISSUE TITLE
Weird indentation when using switch-case

### ISSUE THREAD

**Issue by mathiasbynens** [beautify-web/js-beautify#15]
```
switch (v) { case 1: break; case 2: break; case 3: break; default: break; }
```

…becomes…

```
switch (v) {
case 1:
    break;
case 2:
    break;
case 3:
    break;
default:
    break;
}
```

Maybe this is intentional, but I would expect the `case` to be indented by 1 level (based on the settings).

**Comment by robertleeplummerjr** [comment]
This indentation issue is different with the same code on windows vs OSX.  Case in point is https://github.com/gpujs/gpu.js, when I run `yarn make` it beautifies the `./src` folder, using this script: https://github.com/gpujs/gpu.js/blob/012cfff566691a8fa360e0af650a45c616ceff4a/gulpfile.js#L85
