### ISSUE TITLE
Bugs with HTML and XML

### ISSUE THREAD

**Issue by Infocatcher** [beautify-web/js-beautify#150]
Before:
```html
<div>
test
<a href="/">test</a>
</div>
```
After, with default settings:
```html
<div>test
<a href="/">test</a>

</div>
```
Unwanted empty line after "&lt;/a&gt;".

XML example, before:
```xml
<test>
test
<link>test</link>
</test>
```
After, with
```javascript
unformatted = ['link'];
```
```xml
<test>test<link>test</link>
</test>
```
Why we get different behavior?
And wrongly removed space before "&lt;link&gt;".

**Comment by bitwiseman** [comment]
The original problem here is fixed. I'm closing this.
