### ISSUE TITLE
indent_inner_html not working in v1.8.0

### ISSUE THREAD

**Issue by gabrielmaldi** [beautify-web/js-beautify#1514]
# Description
`indent_inner_html: true` seems to be ignored in v1.8.0

# Input
The code looked like this before beautification:
```html
<!DOCTYPE html>
<html>
<head>
<title>Title</title>
</head>
<body>
Body
</body>
</html>
```

# Expected Output
The code should have looked like this after beautification:
```html
<!DOCTYPE html>
<html>

    <head>
        <title>Title</title>
    </head>

    <body>
        Body
    </body>

</html>
```

# Actual Output
The  code actually looked like this after beautification:
```html
<!DOCTYPE html>
<html>

<head>
    <title>Title</title>
</head>

<body>
    Body
</body>

</html>
```

## Environment
https://beautifier.io/

## Settings
Example:
```json
{
    "indent_inner_html": true
}
```

**Comment by bitwiseman** [comment]
Right, this setting got lost in 1.8.0.   I see why, it was not well documented and was implemented in a very strange way.
