### ISSUE TITLE
Missing Bower Assets

### ISSUE THREAD

**Issue by deckar01** [beautify-web/js-beautify#1521]
# Description

When upgrading from 1.7.5 to 1.8.1, the asset path provided in the bower config no longer exists.

# Steps to Reproduce

1. Run `bower install js-beautify`
2. Include `bower_components/js-beautify//js/lib/beautify.js` in an HTML document

## Environment

OS: Ubuntu 18.04 (64 bit)

## Notes

There don't seem to be any bundled javascript assets in the bower package.

**Comment by bitwiseman** [comment]
Are bower packages created from github?

**Comment by deckar01** [comment]
Bower automatically pulls the git tags from the hosted git server that the package was registered with.

https://bower.io/docs/creating-packages/#register

**Comment by bitwiseman** [comment]
@deckar01 Thanks for the detailed info. 
I've created a v1.8.2 tag that points to the gh-pages branch which includes the built files. Your immediate problem should be fixed. 


The right fix for this is probably to use a `release` branch and do tags (and checked in generated files) on that branch.  (As advised here: https://blog.kentcdodds.com/why-i-don-t-commit-generated-files-to-master-a4d76382564)

**Comment by deckar01** [comment]
Thanks for working on this. Maintaining bower support is a nice option also. 😄

**Comment by bitwiseman** [comment]
@deckar01 I don't know about maintain it in the long run, but not breaking it in the short-term is worth doing. And we're not ready to go to v2 yet so that's how it goes.

**Comment by deckar01** [comment]
I had a discussion about hesitation to release major versions in another project yesterday.

> I am personally not a fan of building up breaking changes in a major version milestone. I think this pattern is an artifact of commercial software development with scheduled release windows. Without a hard release schedule, there is no mechanism for punting the backlog to the next major version.
> 
> Semver + upgrade guides should provide the assurance developers need to handle major releases dropping any time an improvement is backwards incompatible.

https://github.com/marshmallow-code/marshmallow/issues/928#issuecomment-417072457

**Comment by bitwiseman** [comment]
@deckar01  That is an interesting point. We've been avoiding 2.0 for some time, but maybe we don't need to.
