### ISSUE TITLE
Space added into url() after SCSS beautified

### ISSUE THREAD

**Issue by iczman** [beautify-web/js-beautify#1522]
# Description
`@import url(//...)` when beautified inserts an extra space after the open paren `@import url( //...)` thus generating invalid scss.

# Input
The code looked like this before beautification:
```scss
@import url(//example.com/style.css);
```

# Expected Output
The code should have looked like this after beautification:
```scss
// No change
@import url(//example.com/style.css);
```

# Actual Output
The  code actually looked like this after beautification:
```scss
// Extra space added
//          ↓
@import url( //example.com/style.css);
```

# Steps to Reproduce

Paste the above code into http://jsbeautifier.org/ and beautify
## Environment
OS: macOS

## Settings
Example:
```json
{
  "indent_size": "2",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": true,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false
}
```

**Comment by bitwiseman** [comment]
`//` is a comment in SCSS. 
http://sass-lang.com/documentation/file.SCSS_FOR_SASS_USERS.html#Comments
The space is added in  front of a comment. 

I think you need to put quotes around that to make it work.

**Comment by iczman** [comment]
Ah you're right, sorry for the false alarm.
