### ISSUE TITLE
Support new js proposals: optional-chaining & pipeline-operator

### ISSUE THREAD

**Issue by sfger** [beautify-web/js-beautify#1530]
# Description
> NOTE:
> * Check the list of open issues before filing a new issue.
> * Please update the expect output section to match how you would prefer the code to look.

# Input
The code looked like this before beautification:
```
'test' |> console.log;
let a = {};
a?.b?.c?.d;
```

# Current Output
The  code actually looked like this after beautification:
```
'test' | > console.log;
let a = {};
a ? .b ? .c ? .d;
```

# Expected Output
The code should have looked like this after beautification:
```
/*Adjust the code to look how you prefer the output to be.*/
'test' |> console.log;
let a = {};
a?.b?.c?.d;
```

## Environment
Browser User Agent:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

Language Selected:
JavaScript

## Settings
Example:
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false
}
```

**Comment by theblang** [comment]
Looks like [optional-chaining](https://github.com/tc39/proposal-optional-chaining) has made it to stage 2!

**Comment by bitwiseman** [comment]
@theblang 
Thanks!  If you have time to submit a PR with tests that would be great!

**Comment by theblang** [comment]
@sfger @bitwiseman I'm thinking that this issue should change to become "optional-chaining & nullish-coalescing". Both [optional-chaining](https://github.com/tc39/proposal-optional-chaining) and [nullish-coalescing](https://github.com/tc39/proposal-nullish-coalescing) are now at stage 3! But [pipeline-operator](https://github.com/tc39/proposal-pipeline-operator) is still at stage 1.

**Comment by bitwiseman** [comment]
@theblang Yes, each item should be filed as separate issue that can be tracked to completion.
