### ISSUE TITLE
unindent_chained_methods broken

### ISSUE THREAD

**Issue by gaby64** [beautify-web/js-beautify#1533]
Latest release breaks unindent_chained_methods

if I have the time, I will update this issue to follow the guidelines

**Comment by bitwiseman** [comment]
Breaks how.  Creating a bug using https:/beautifier.io takes less than 5 minutes. 
Set your beautifier, add `"unindent_chained_methods": true` to the JSON box, paste in your input, click beautify, and then click the button below the input to submit a bug.

**Comment by gaby64** [comment]
Input & Expected:
```
angular.module('test').controller('testCtrl', function($scope) {
	$scope.tnew;
	$scope.toggle_tnew = function() {
		$scope.mode = 0;
		if(!$scope.tnew) {
			$scope.tnew = {};
		} else $scope.tnew = null;
	}
	$scope.fn = function() {
		return null;
	}
});
```

Output:
```
angular.module('test').controller('testCtrl', function($scope) {
$scope.tnew;
$scope.toggle_tnew = function() {
$scope.mode = 0;
if (!$scope.tnew) {
	$scope.tnew = {};
} else $scope.tnew = null;
}
$scope.fn = function() {
return null;
}
});
```
