### ISSUE TITLE
Multiple newlines added between empty textarea and "unformatted" inline elements 

### ISSUE THREAD

**Issue by AmandaFoster** [beautify-web/js-beautify#1534]
# Description
If an inline tag is included in the `unformatted` settings, newlines are added between empty tags. `textarea` elements are affected by this regardless of presence in the `unformatted` array. The newlines double each time as well.

As a work-around, if there is text, comments, or no space between the tags, this does not happen.

# Input
The code looked like this before beautification:
```
<textarea></textarea>
<textarea>
</textarea>

<strong></strong>
<strong>
</strong>

<span></span>
<span>
</span>
```

# Expected Output
The code should have looked like this after beautification:
```
<textarea></textarea>
<textarea>
</textarea>

<strong></strong>
<strong>
</strong>

<span></span>
<span>
</span>
```

# Actual Output
The  code actually looked like this after beautification:
Example without `unformatted` section in settings:  
```
<textarea></textarea>
<textarea>

</textarea>

<strong></strong>
<strong>
</strong>

<span></span>
<span>
</span>
```

Example with `unformatted` section in settings:  
```
<textarea></textarea>
<textarea>

</textarea>

<strong></strong>
<strong>

</strong>

<span></span>
<span>

</span>
```

# Steps to Reproduce
Tested on JS Beautify site

## Environment
OS: windows

## Settings
Example without `unformatted`:  
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false
}
```

Example with `unformatted`:  
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "unformatted": [
    "strong",
    "textarea",
    "span"
  ]
}
```

**Comment by bitwiseman** [comment]
@AmandaFoster  
What about if the `inline` tag is not included in the `unformatted` list?  

`textarea` tags are included in the `content_unformatted` list.  So, the interaction seems to be with `unformatted` and either of the other two lists. 

This is certainly a bug and should be fixed, but could you explain more about the scenario in which this is useful or expected?  

Implementation note: 
One solution would be to only let elements be in one of these three lists - either by silently removing the other lists internally, logging a warning when this happens, or by throwing an exception and simply refusing to beautify when these settings conflict.  The first or second are preferable options.

**Comment by bitwiseman** [comment]
@AmandaFoster Thanks, I went ahead and fixed this bug without doing filtering.  An element can be in all three lists without unexpected side effect now.  

Note: in the default settings, all elements that were `unformatted` in 1.7.5 have moved to `inline` or `content_unformatted` in 1.8.0 - `unformatted` was used to mitigate the lack of proper `inline` behavior.  I would strongly suggest making your `unformatted` list empty and see how that looks. 

Thanks again for reporting this issue!

**Comment by AmandaFoster** [comment]
Will do. Thanks for the quick turn around.
