### ISSUE TITLE
base64 string is broken with v1.8.4

### ISSUE THREAD

**Issue by rivancic** [beautify-web/js-beautify#1535]
# Description
I wrote build script with gulp. One of the steps was to prettify the scss code. I used **gulp-jsbeautifier@2.1.2**
which has a dependency on js-beautify.
When the build process runs with the js-beautify@1.7.5 sass processor does not throw any issues in next step. But with the update of the dependency to js-beautify@1.8.4 the sass procesor step is broken. I was not using any settings for js-beautify lib. But per default previous version was working. Is it neccessary to provide now additional settings?

Error message is as following:
```
[10:39:48] Starting 'sass'...
Error in plugin 'sass'
Message:
    assets/scss/сomponents/_sorting.scss
Error: Invalid CSS after "...round: url(data": expected expression (e.g. 1px, bold), was ":image/gif;"
        on line 16 of assets/scss/сomponents/_sorting.scss
        from line 19 of assets/scss/style.scss
>>   background: url(data:image/gif;

   ------------------^
[10:39:51] Finished 'sass' after 3.3 s
```
I compared the output of both versions for the specific _sorting.scss file

# Input

```
background: url(data:image/gif;base64,R0lGODlhCwALAJEAAAAAAP///xUVFf///yH5BAEAAAMALAAAAAALAAsAAAIPnI+py+0/hJzz0IruwjsVADs=);
```

# Expected Output

Output of **js-beautify@1.7.5** :+1: 

```
background: url(data:image/gif;base64,R0lGODlhCwALAJEAAAAAAP///xUVFf///yH5BAEAAAMALAAAAAALAAsAAAIPnI+py+0/hJzz0IruwjsVADs=);
```

# Actual Output

Output of **js-beautify@1.8.4**

```
 background: url(data:image/gif;
  base64, R0lGODlhCwALAJEAAAAAAP ///xUVFf///yH5BAEAAAMALAAAAAALAAsAAAIPnI+py+0/hJzz0IruwjsVADs=);
```

Now the sass processor is broken because of the spaces in the base64 string representation

# Steps to Reproduce

## Environment
OS: Linux

## Settings

I was using default settings.

**Comment by bitwiseman** [comment]
https://css-tricks.com/data-uris/

**Comment by rivancic** [comment]
Thanks @bitwiseman for the fixing the issue in such a short time. Respect!
I upgraded version to 1.8.6 and I can confirm now the formatting is correct. :+1:
