### ISSUE TITLE
please support single line format like this

### ISSUE THREAD

**Issue by ayin86** [beautify-web/js-beautify#1555]
please support single line format like this
![image](https://user-images.githubusercontent.com/25238537/45935691-55ed6180-bfe0-11e8-843d-18a3da49d153.png)

**Comment by bitwiseman** [comment]
@ayin86 Please use the issue template. Provide text not screenshots. 
https://github.com/beautify-web/js-beautify/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by bitwiseman** [comment]
@ayin86  has not responded. Closing.
