### ISSUE TITLE
Preserve inline braces breaked for dynamic properties

### ISSUE THREAD

**Issue by Verdier** [beautify-web/js-beautify#1561]
# Input
The code looked like this before beautification:
```js
const a = { [b]: 1 }
```

# Expected Output
The code should have looked like this after beautification:
```js
const a = { [b]: 1 }
```

# Actual Output
The  code actually looked like this after beautification:
```js
const a = {
    [b]: 1 }
```

## Settings
Example:
```json
{
    "brace_style": "preserve-inline"
}
```

**Comment by bitwiseman** [comment]
Dynamic properties are not supported yet, which is blocked on javascript parsing. (see #1200).  
When #1200 is implemented it will support this behavior.
