### ISSUE TITLE
Format HTML code adds different line breaks every time, confuses Diff

### ISSUE THREAD

**Issue by smlombardi** [beautify-web/js-beautify#1578]
Whenever I save an HTML file, the code inside a block tag such as p is broken depending on my window width. So a block of code that I've deliberately run together results in multiple lines and has "holes" for no reason.

Worse still, when looking at a Diff these are of course show as a change except that no real changes have been made, other than these breaks I never asked for in the first place.

Am I missing a setting or something? How to prevent this?

<img width="2206" alt="46969366-d5240180-d083-11e8-9908-0397c0ddc3ec" src="https://user-images.githubusercontent.com/835148/47366737-4d09b180-d6ac-11e8-882f-bb837d5074b0.png">

VS Code version: Code - Insiders 1.29.0-insider (6287407, 2018-10-15T05:11:18.840Z)
OS version: Darwin x64 17.7.0

**Comment by bitwiseman** [comment]
@smlombardi You can turn off line wrapping by setting `wrap_line_length` to 0.

**Comment by EnterRavement** [comment]
@bitwiseman  I have the issue. The thing is I personally would like to have automatic wrap when my text exceeds the number, it's just the way it is formatted, what I and probably @smlombardi dont like.  For me it is not only wrapping plain text when it exceeds the limit, but in a for me not forseeable pattern

**Comment by smlombardi** [comment]
> @smlombardi You can turn off line wrapping by setting `wrap_line_length` to 0.

Where does this go, in VSCode?  It's not a prefs key.

**Comment by smlombardi** [comment]
This seems to do what I wanted: ` "html.format.wrapLineLength": 0,`
