### ISSUE TITLE
'less' mixins parameter formatting problem

### ISSUE THREAD

**Issue by chym123** [beautify-web/js-beautify#1582]
# Input
```
.btn {
    .generate-animation(@mykeyframes, 1.4s, .5s, 1, ease-out);
}
```

# Expected Output
```
.btn {
    .generate-animation(@mykeyframes, 1.4s, .5s, 1, ease-out);
}
```

# Actual Output
```
.btn {
    .generate-animation(@mykeyframes,
    1.4s,
    .5s,
    1,
    ease-out);      
}
 
```
## Environment
OS: Windows 10

## Settings
Default settings

**Comment by bitwiseman** [comment]
Same kind of problem as #1018.  Not sure if it is the same issue.

**Comment by chym123** [comment]
Maybe still a little different but the actual output is similar. Is there a solution?
