### ISSUE TITLE
destructuring assignment with a default at first key is wrong indentation

### ISSUE THREAD

**Issue by llwslc** [beautify-web/js-beautify#1586]
# Description
> Destructuring assignment with a default at first key is wrong indentation
>
> NOTE: 
> * Only at first key

# Input
The code looked like this before beautification:
```
let {
  foo = 2,
  bar,
  baz,
} = qux;
```

# Expected Output
The code should have looked like this after beautification:
```
let {
  foo = 2,
  bar,
  baz,
} = qux;
```

# Actual Output
The  code actually looked like this after beautification:
```
let {
  foo = 2,
    bar,
    baz,
} = qux;
```

## Settings
Default

**Comment by bitwiseman** [comment]
See #1128.
