### ISSUE TITLE
_get_full_indent undefined

### ISSUE THREAD

**Issue by adityacoder007** [beautify-web/js-beautify#1590]
Please rename _get_full_indent to get_full_indent; else code is throwing undefined _get_full_indent.

**Comment by bitwiseman** [comment]
@adityacoder007 Please describe how to reproduce the error you are seeing.

**Comment by bitwiseman** [comment]
Ah, I see.  https://github.com/beautify-web/js-beautify/blob/2f8e4f050200b85f3c3b9fb5a292823b52c618ac/js/src/html/beautifier.js#L452
The case where `_beautifier` is not defined is not covered by tests.
