### ISSUE TITLE
 Additional modes on wrap-attributes

### ISSUE THREAD

**Issue by oktamapangestu** [beautify-web/js-beautify#1596]
# Description
> I want a small amount of additional ability, this is related to the style guide that our Team uses. The problem is in wrap-attributes.
> You can see like the code example below.

> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue.

# Input
With this new feature, when I give like this input: 
```
<img
  src="https://vuejs.org/images/logo.png"
  alt="Vue Logo"
>
```

# Expected Output
I'd like to see this output:
```
<img
  src="https://vuejs.org/images/logo.png"
  alt="Vue Logo">
```

## Environment
OS:

**Comment by bitwiseman** [comment]
Given that input, use the setting `wrap_attributes: preserve`, and it will produce the output you want.

Also See #1404. let's make sure this is covered by that proposal.
