### ISSUE TITLE
Use of global MODE before declaration caused uglify problem

### ISSUE THREAD

**Issue by djehring** [beautify-web/js-beautify#1604]
The global variable MODE is used in the code before it is declared. When this package is passed through js-uglify it breaks as these lines:

if (frame.multiline_frame ||
          frame.mode === MODE.ForInitializer ||
          frame.mode === MODE.Conditional) {
          return;
        }

are not parsed to use the uglified constants MODE_ForInitializer and Mode_Conditional.

Moving the declaration of mode before its use fixes this problem.

**Comment by bitwiseman** [comment]
@djehring  Can you submit a PR?
