### ISSUE TITLE
HTML type attribute breaks JavaScript beautification?

### ISSUE THREAD

**Issue by jonkri** [beautify-web/js-beautify#1606]
# Description

The HTML type attribute seems to break JavaScript beautification.

# Input
The code looked like this before beautification (note the double spaces surrounding the `+` operator):
```
<script>
    console.log(1  +  1)
</script>

<input type="submit">
```

# Expected Output
The code should have looked like this after beautification (only single spaces surrounding the `+` operator):
```
<script>
    console.log(1 + 1)
</script>

<input type="submit">
```

# Actual Output
The  code actually looked like this after beautification (identical to the input):
```
<script>
    console.log(1  +  1)
</script>

<input type="submit">
```

# Steps to Reproduce

```
$ printf "<script>\n\
>     console.log(1  +  1)\n\
> </script>\n\
> \n\
> <input type=\"submit\">\n" | html-beautify
<script>
    console.log(1  +  1)
</script>

<input type="submit">
```

Changing the `type` attribute produces the desired result:

```
$ printf "<script>\n\
    console.log(1  +  1)\n\
</script>\n\
\n\
<input type2=\"submit\">\n" | html-beautify
<script>
    console.log(1 + 1)
</script>

<input type2="submit">
```

## Environment
OS: Arch Linux
js-beautify version: 1.8.9

## Settings
```json
{}
```

**Comment by bitwiseman** [comment]
Ugh. 
https://github.com/beautify-web/js-beautify/blob/master/js/src/html/beautifier.js#L144 is wrong.
