### ISSUE TITLE
i want use java api interger to android app

### ISSUE THREAD

**Issue by qssq** [beautify-web/js-beautify#1607]
# Description
> This is the default template for feature requests. 
>
> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue.

# Input
With this new feature, when I give like this input: 
```
<INSERT CODE HERE>
```

# Expected Output
I'd like to see this output:
```
<INSERT CODE HERE>
```

## Environment
OS:

**Comment by bitwiseman** [comment]
I have no idea what you're asking for.  Please come chat on the gitter.im channel.
