### ISSUE TITLE
CLI on Windows doesn't accept -f - for stdin?

### ISSUE THREAD

**Issue by malcolmr** [beautify-web/js-beautify#1609]
Over at https://github.com/google/vim-codefmt/issues/111, we've had a report that our js-beautify integration doesn't work on Windows.

In this case, we're invoking `js-beautify -f - --type js` and expecting to be able to use it as a filter from stdin to stdout, but it looks like the user is getting an error message of the form 'Unable to open path "/Users/.../node_modules/npm/-"'.

This sounds like it might be the same problem as #390, but perhaps only for Windows?

**Comment by bitwiseman** [comment]
@lsff  @malcolmr 
What version of js-beautify do you have installed?

**Comment by bitwiseman** [comment]
Hm, we have Windows in our CI system and the tests around stdin cover a lot of cases :
https://github.com/beautify-web/js-beautify/blob/master/js/test/shell-test.sh#L120

But that specific one is not in there.

**Comment by bitwiseman** [comment]
@jvargas  Thanks for that info that will help with testing and fixing.

**Comment by bitwiseman** [comment]
@jvargas @malcolmr 
Please test this fix by installing 1.8.10-beta2.

**Comment by malcolmr** [comment]
I don't actually use js-beautify. @lsff may be able to help verify the fix as they were the original reporter of  google/vim-codefmt#111.
