### ISSUE TITLE
Add setting to keep all HTML element attributes unformatted

### ISSUE THREAD

**Issue by romanzipp** [beautify-web/js-beautify#1615]
# Description

I'd like to request a new option which prevents reformatting of element attribute line breaks. I am aware that there is a `unformatted` option, but it's time-consuming and weird to add every possible element tag, especially with Vue.js and Components.

When setting the `wrap_line_length` configuration option, the element attributes get splitted over lines but the fact that attributes also appear next to each other makes it really hard to read:

```html
<player ref="player" :video="video"
        :allowFullscreen="false" :allowCinema="false"
        :allowGlobalPlayer="false" :config="{ autostart: true, repeat: true }"
        @player:ready="playerReady = true" />
```

Not setting the `wrap_line_length` option results in single-line formatting.

```html
<player ref="player" :video="video" :allowFullscreen="false" :allowCinema="false" :allowGlobalPlayer="false" :config="{ autostart: true, repeat: true }" @player:ready="playerReady = true" />
```

# Input

```html
<player  ref="player"
         :video="video"
         :allowFullscreen="false"
         :allowCinema="false"
         :allowGlobalPlayer="false"
         :config="{ autostart: true, repeat: true }"
         @player:ready="playerReady = true" />
```

# Expected Output

No formatting work done here.

```html
<player  ref="player"
         :video="video"
         :allowFullscreen="false"
         :allowCinema="false"
         :allowGlobalPlayer="false"
         :config="{ autostart: true, repeat: true }"
         @player:ready="playerReady = true" />
```

**Comment by bitwiseman** [comment]
@romanzipp 
You found the `preserve` setting, right?

**Comment by romanzipp** [comment]
Exactly :D
I've found the package through an editor plugin and got confused. The plugin documentation seemes outdated.

```json
{
    "wrap_attributes": "preserve"
}
```

works perfectly.
