### ISSUE TITLE
javascript hyphen spaceout before and after

### ISSUE THREAD

**Issue by differentMonster** [beautify-web/js-beautify#1629]
i am install js-beautify on spacemacs and set it auto fomatted when save , and turn out the every hyphen having space before and after.

my-components
my-object
my-var

all to

my - components
my - object
my - var 

how do i fix it ? do anyone face this problem before ?

.jsbeautifyrc

{
    "indent_size": 2,
    "indent_char": " ",
    "indent_level": 0,
    "end-with-newline": true,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "css": {
        "selector_separator_newline": false
    }
}

**Comment by bitwiseman** [comment]
Can you provide any actual sample of your code? 
Also, have you tried your code on https://beautifier.io using the JavaScript beautify?

**Comment by differentMonster** [comment]
> Can you provide any actual sample of your code?
> Also, have you tried your code on https://beautifier.io using the JavaScript beautify?

1.You mean normal code or the .jsbeautifyrc ?
2.Yes beautifier show the same too , does it mean my js package or something need to change ?

[https://imgur.com/cNr8NKY](url) check here , so is not beaut js problem ?

**Comment by bitwiseman** [comment]
Oh, right. Dashes are not valid in identifiers in JavaScript.
