### ISSUE TITLE
Anyway to add csutom spaces/lines in HTML?

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [beautify-web/js-beautify#1631]
I had this open here https://github.com/victorporof/Sublime-HTMLPrettify/issues/665

I'm trying to figure out how to add some custom space/line after some divs but can't find any info. 

For example: 

> <body>
    <nav class="navigation">
        <ul class="navigation-menu">
            <li class="menu-item"><a href="#">Home</a></li>
            <li class="menu-item"><a href="#">About</a></li>
            <li class="menu-item"><a href="#">Blog</a></li>
            <li class="menu-item"><a href="#">Support</a></li>
            <li class="menu-item"><a href="#">Contact</a></li>
        </ul>
    </nav>
</body>

After that nav, here I want to add some lines then a new div but on save it just moves up my elements. Can I add some custom space or lines with the **"format_on_save": true,**

If there are settings for this then could you point me out to them?

**Comment by bitwiseman** [comment]
What do you want the output to look like when you're done?

**Comment by Abd-Ur-Rehman** [comment]
@bitwiseman Sorry for the less info, I would like this to be formatted as output: 
```
<nav class="navigation">

    <ul class="navigation-menu">
        <li class="menu-item"><a href="#">Home</a></li>
        <li class="menu-item"><a href="#">About</a></li>
        <li class="menu-item"><a href="#">Blog</a></li>
        <li class="menu-item"><a href="#">Support</a></li>
        <li class="menu-item"><a href="#">Contact</a></li>
    </ul>

</nav>
```
Then after the input if I would like to add more empty lines for another section then it just move them up. Trying to figure out how to have more custom spaces, eg: 👇 

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>

    <nav class="navigation">
        <ul class="navigation-menu">
            <li class="menu-item"><a href="#">Home</a></li>
            <li class="menu-item"><a href="#">About</a></li>
            <li class="menu-item"><a href="#">Blog</a></li>
            <li class="menu-item"><a href="#">Support</a></li>
            <li class="menu-item"><a href="#">Contact</a></li>
        </ul>
    </nav>
    
    <section main="main">
        
        <article>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>    
        </article>

    </section>

    <footer>
        <div class="main-footer">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>

        <div class="bottom-bar">
            Copyrights
        </div>
    </footer>
    
</body>

</html>

```

I can add comments to separate the section but sometime need to add spaces and upon save it just remove them, like this: 
````
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <nav class="navigation">
        <ul class="navigation-menu">
            <li class="menu-item"><a href="#">Home</a></li>
            <li class="menu-item"><a href="#">About</a></li>
            <li class="menu-item"><a href="#">Blog</a></li>
            <li class="menu-item"><a href="#">Support</a></li>
            <li class="menu-item"><a href="#">Contact</a></li>
        </ul>
    </nav>
    <section main="main">
        <article>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
        </article>
    </section>
    <footer>
        <div class="main-footer">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
        <div class="bottom-bar">
            Copyrights
        </div>
    </footer>
</body>

</html>

**Comment by bitwiseman** [comment]
@Abd-Ur-Rehman 

Several possible settings: 
1. `"preserve_newlines": true`  - this should make it so the blank-lines you add are not removed.
2. `"extra_liners": ['head', 'body', '/html']` - This adds a blank line before any specified element.  It isn't ideal, but it can get you closer.   For example, `"extra_liners": ["head", "body", "/html", "/body", "nav", "section", "footer"]` will get the following output: 

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>

    <nav class="navigation">
        <ul class="navigation-menu">
            <li class="menu-item"><a href="#">Home</a></li>
            <li class="menu-item"><a href="#">About</a></li>
            <li class="menu-item"><a href="#">Blog</a></li>
            <li class="menu-item"><a href="#">Support</a></li>
            <li class="menu-item"><a href="#">Contact</a></li>
        </ul>
    </nav>

    <section main="main">
        <article>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
        </article>
    </section>

    <footer>
        <div class="main-footer">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
        <div class="bottom-bar">
            Copyrights
        </div>
    </footer>

</body>

</html>
```

**Comment by Abd-Ur-Rehman** [comment]
Thanks for the support, yeah the 2's example is working fine.  But the 1 still removes extra spaces. I have added them in HTML settings:

https://gist.github.com/Abd-Ur-Rehman/d65803d5c203bdf5c0c3c129e080f52a#file-jsbeautifyrc-L65
https://gist.github.com/Abd-Ur-Rehman/d65803d5c203bdf5c0c3c129e080f52a#file-jsbeautifyrc-L67 

1. Was that supposed to be in the HTML?

**Comment by bitwiseman** [comment]
@Abd-Ur-Rehman 
Glad #2 works.  What you showed should work for #1.  Can you try this on https://beautifier.io ?  I suspect there is some other part of your IDE that is removing the newlines.

**Comment by Abd-Ur-Rehman** [comment]
Hey, @bitwiseman thanks here it works but here I'm seeing that it has `  "max_preserve_newlines": "3",
` I have added that to my settings and it works fine, doesn't remove any lines. Thanks again! 😊

**Comment by Abd-Ur-Rehman** [comment]
Closing the issue as it's resolved with those settings. Thanks 👍

**Comment by Abd-Ur-Rehman** [comment]
Sorry, @bitwiseman I'm trying to figure out how to add space between selectors in CSS I have my the input as below: 

```
.the-checkbox:checked+p {
    background: red;
}
```
I want output like this: 

```
.the-checkbox:checked + p {
    background: green;
}
```

It's removing the spaces how can I have them?

Thanks

**Comment by bitwiseman** [comment]
@Abd-Ur-Rehman
Please look at the CSS issues for one that matches this or open a new issue and we can track this that way (it is a separate issue from this one).   As to where you can find more information, the readme should be up-to-date but it might need updates.

**Comment by Abd-Ur-Rehman** [comment]
@bitwiseman Not quite sure if this is related. https://github.com/beautify-web/js-beautify/issues/1489

**Comment by bitwiseman** [comment]
@Abd-Ur-Rehman I think this is the one: https://github.com/beautify-web/js-beautify/issues/676

**Comment by Abd-Ur-Rehman** [comment]
@bitwiseman Yeah, that's happening with the descendant selector as well, I just had tested with the adjacent selector. Will be following that issue for a fix. Thanks
