### ISSUE TITLE
Script becomes empty after beautification

### ISSUE THREAD

**Issue by razafinarivohanania** [beautify-web/js-beautify#1633]
# Description
Hello, i've tested the JavaScript code below on https://beautifier.io/ but when i beautify it, all code is removed.

# Input
The code looked like this before beautification:
```
var _0x0=[];
```

# Current Output
There is nothing, just an empty result
```

```

# Expected Output
The code should have looked like this after beautification:
```
var _0x0 = [];
```

## Environment
Browser User Agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36

Language Selected: JavaScript

## Settings
Example:
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false
}
```

**Comment by bitwiseman** [comment]
Same issue as  #1350.  Work-around on the web page is to uncheck "Detect packers and obfuscators?"

**Comment by razafinarivohanania** [comment]
@bitwiseman Thanks, it runs as expected when unchecking "Detect packers and obfuscators".
