### ISSUE TITLE
使用最新版本编译美化问题，thymeleaf语法无法识别

### ISSUE THREAD

**Issue by XIAOGUIGUI** [beautify-web/js-beautify#1636]
编译前的写法
![1551451174098](https://user-images.githubusercontent.com/8243283/53645196-4fd86c80-3c73-11e9-949d-d9cb15dda5c6.jpg)
编译后换行
![wechatimg3](https://user-images.githubusercontent.com/8243283/53645206-55ce4d80-3c73-11e9-8696-6a01f3595027.jpeg)

**Comment by bitwiseman** [comment]
@XIAOGUIGUI 
Please provide your input, expected output, and actual output as text.

**Comment by XIAOGUIGUI** [comment]
input
![7282b98e-7dcb-46ef-be19-7f05cfe11fe8](https://user-images.githubusercontent.com/8243283/53716672-9fe04a80-3e90-11e9-94be-b6821c3e53f3.png)
output
![29038256-9d5c-4e0d-ac45-45fbac60773e](https://user-images.githubusercontent.com/8243283/53716680-a4a4fe80-3e90-11e9-8f34-dd0a2ff66b8a.png)
actual output
![f885e5cf-5792-4f9f-aa6d-cfd64cc25336](https://user-images.githubusercontent.com/8243283/53716728-cef6bc00-3e90-11e9-863a-dbf72047302f.png)

**Comment by bitwiseman** [comment]
@XIAOGUIGUI 
As text please. Images are of no help.
