### ISSUE TITLE
paragraph messed up hmtl5 with random spaces, breaks, and indents

### ISSUE THREAD

**Issue by bebotette** [beautify-web/js-beautify#1643]
# Description
> This is the default template for bug reports
>
> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue. 

# Input
The code looked like this before beautification:
```
<p><em>Ex aliquip <a href="http://www.google.com" target="_blank">commodo cupidatat</a> laboris ut nulla	exercitation labore laboris ullamco eiusmod cupidatat nostrud. Ex fugiat sed deserunt in dolore eiusmod pariatur aliquip in non proident deserunt minim velit ut. Sit culpa laborum proident voluptate ex deserunt cillum pariatur elit sint labore anim.</em></p>
```

# Expected Output
The code should have looked like this after beautification:
```
<p><em>Ex aliquip <a href="http://www.google.com" target="_blank">commodo cupidatat</a> laboris ut nulla	exercitation labore laboris ullamco eiusmod cupidatat nostrud. Ex fugiat sed deserunt in dolore eiusmod pariatur aliquip in non proident deserunt minim velit ut. Sit culpa laborum proident voluptate ex deserunt cillum pariatur elit sint labore anim.</em></p>
```

# Actual Output
The  code actually looked like this after beautification:
```
<p><em>Ex aliquip <a href="http://www.google.com" target="_blank">commodo cupidatat</a> laboris ut nulla
						exercitation labore laboris ullamco eiusmod cupidatat nostrud. Ex fugiat sed deserunt in dolore
						eiusmod pariatur aliquip in non proident deserunt minim velit ut. Sit culpa laborum proident
						voluptate ex deserunt cillum pariatur elit sint labore anim.</em></p>
```

# Steps to Reproduce

## Environment
OS: Windows 10 x 64 1809

## Settings
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by bebotette** [comment]
see in action:
[http://recordit.co/lskf3RORW3](url)

**Comment by bitwiseman** [comment]
Have you tried this on https://beautifier.io ?  What version of the beautifier are you using?  There was a recent fix.

**Comment by bebotette** [comment]
Thanks for the response. I'm using the built-in beautifier inside VS Code. Docs tell me that VS Code uses this js-beautify so I had to ask help from you (and there's nothing VSCode guys can do). I'm using the latest VS Code, and I don't know how to check its built-in js-beautify version. Can you please help?

**Comment by bitwiseman** [comment]
Latest VS Code tells me what I need to know.  

The video shows different input from the text in your description. 

In both cases, the wrapping must be occurring because you have wrap line length set.
  
In your video the wrapping results in some odd formatting because the beautifier wraps the long lines, but it also preserves existing newlines.  The beautifier doesn't have a "flow content" wrap setting yet.  

In the text currently in the description, the indenting seems extreme and I can't reproduce it locally.

Can you edit the description to included surrounding content - at least all the parent tags back to `body`? The indenting might make more sense in context.

**Comment by bebotette** [comment]
@bitwiseman Thanks for shedding a new line to my issue. Your response really helped me looked at it from a different perspective.

I finally realized what was wrong and why my `<p>` tag turned out looking ugly after formatting.

So in the video I sent a link above, I have the local word wrap of VS Code active. In other words, two word wraps did their job, respecting new existing line breaks I have. So if the local word wrap is smaller than the current 120 wrap line length during formatting, it breaks the line visually. When I stretch the window, there I can actually see how beautiful the formatting did its job.

Now, these are my current settings:
`{
    "editor.formatOnSave": true,
    "html.format.preserveNewLines": false,
    "html.format.wrapLineLength": 90,
    "editor.wordWrap": "on"
}`

And I make sure my local viewport is wider than the wraplinelength.
Now I don't have any more issues.

Thank you very much!
