### ISSUE TITLE
wrong indent for unclosed <? - need to support disabling templating

### ISSUE THREAD

**Issue by junstyle** [beautify-web/js-beautify#1647]
# Description
> wrong indent

# Input
The code looked like this before beautification:
```
class Class {
    init1() {
        let code = "<?php $a='1'";
    }

    init2() {
      let code = "<?php $a='1';?>";
    }

    init3() {
            let code = "<?php $a='1'";
    }
  
 init4() {
            let code = "<php $a='1'";
    }
}
```

# Expected Output
The code should have looked like this after beautification:
```
class Class {
  init1() {
    let code = "<?php $a='1'";
  }

  init2() {
    let code = "<?php $a='1';?>";
  }

  init3() {
    let code = "<?php $a='1'";
  }
  
  init4() {
    let code = "<php $a='1'";
  }
}
```

# Actual Output
The  code actually looked like this after beautification:
```
class Class {
    init1() {
        let code = "<?php $a='1'";
  }

  init2() {
    let code = "<?php $a='1';?>";
    }

    init3() {
            let code = "<?php $a='1'";
  }
  
  init4() {
    let code = "<php $a='1'";
  }
}
```

# Steps to Reproduce

## Environment
OS:
window10

## Settings
Example:
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false
}
```

**Comment by bitwiseman** [comment]
@junstyle of course.
Improved support for templating, but I didn't add a way to disable it via options.

https://github.com/beautify-web/js-beautify/blob/master/js/src/javascript/tokenizer.js#L111-L113

Adding this to v1.9.1 - coming soon.

**Comment by bitwiseman** [comment]
In 1.9.0 we improved the processing of templating languages such as php and turned them on by default.  Unfortunately, that causes issues for some users who were no using templating (See https://github.com/beautify-web/js-beautify/issues/1647 for details).
 
So, there is a new setting added in 1.10.0: `templating`.  
```
values: (auto,django,erb,handlebars,php) [default: "auto"] auto = none in JavaScript, all in html
```
Even though this is html, the area inside the script is treated as Javascript and so by default does not handle php.  To fix this, set `"templating": "php"` (in your `.jsbeautifyrc` file).
