### ISSUE TITLE
User setting for indent_size is ignored

### ISSUE THREAD

**Issue by L5eoneill** [beautify-web/js-beautify#1655]
# Description
SublimeText and JS-Beautify settings for indent size are being ignored when Prettify is run on HTML and JS

# Input
The code looked like this before beautification:
```
<div class="content-wrapper">
<div class="faq-label">Q.</div>
<div class="faq-question">
<a class="qlink" id="question123" href="javascript: void(0)">What is a question?</a>
</div>
<div id="said123" class="faq-response">
<br class="clear">
<div class="faq-label">A.</div>
...
```

# Expected Output
The code should have looked like this after beautification:
```
<div class="content-wrapper">
  <div class="faq-label">Q.</div>
  <div class="faq-question">
    <a class="qlink" id="question123" href="javascript: void(0)">What is a question?</a>
  </div>
  <div id="said123" class="faq-response">
    <br class="clear">
    <div class="faq-label">A.</div>    ...
```

# Actual Output
The  code actually looked like this after beautification:
```
<div class="content-wrapper">
    <div class="faq-label">Q.</div>
    <div class="faq-question">
        <a class="qlink" id="question123" href="javascript: void(0)">What is a question?</a>
    </div>
    <div id="said123" class="faq-response">
        <br class="clear">
        <div class="faq-label">A.</div>        ...
```

# Steps to Reproduce
Sublime Text 3 on Windows 7 with settings for Indent Using Spaces and Tab Width of 2. Ran Prettify Code tool on above HTML text and instead of getting output with 2-space indents, I consistently get output with 4-space indents. Same happens with JS. Since it ignored Sublimes indentation settings, I added User Settings: Packages\User\ .jsbeautifyrc, shown below.

## Environment
OS: Windows

## Settings
```json
{
  "indent_size": 2,
  "indent_char": " ",
}

```

**Comment by eggofevil** [comment]
Looks like default 4 spaces of indent_size for css overriding indent_size wich was set for all files, in my case this construction works:
`{
  css: {
    'indent_size': 2,
    'preserve_newlines': false,
    'newline_between_rules': false
  }
}`
