### ISSUE TITLE
Option to keep empty lines between tags in HTML

### ISSUE THREAD

**Issue by alexreg** [beautify-web/js-beautify#1666]
Could we get an option to keep empty (blank) lines between tags on HTML? At the moment they're removed/stripped.

**Comment by bitwiseman** [comment]
How about `"preserve_newlines": true`?

**Comment by alexreg** [comment]
Doesn't work.

**Comment by bitwiseman** [comment]
Example?   Are trying this on https://beautifier.io ?

**Comment by alexreg** [comment]
No, locally, with this `.jsbeautifyrc` file:

```json
{
	"brace_style": "collapse,preserve-inline",
	"end_with_newline": true,
	"indent_with_tabs": true,
	"preserve_newlines": true,
	"wrap_line_length": 0,
	"html": {
		"indent_inner_html": true
	}
}
```

You should see this issue with any HTML file with empty lines.

**Comment by bitwiseman** [comment]
@alexreg  
What version are you using?

**Comment by alexreg** [comment]
1.8.9. I know that's not quite the most recent, but it's pretty up-to-date, right? Sorry, I should have said earlier though.

**Comment by alexreg** [comment]
Actually, I just ran `npm upgrade` and it's 1.9.1 now, but same issue.

**Comment by bitwiseman** [comment]
Please try on https://beautifier.io . If it works there it means there is a settings issue in your local environment.

**Comment by alexreg** [comment]
@bitwiseman My apologies, you're quite right; it turns out another part of my gulp pipeline was incorrectly removing newlines when it shouldn't!
