### ISSUE TITLE
HTML: wrap-attributes preserve does not preserve tabs

### ISSUE THREAD

**Issue by richardtallent** [beautify-web/js-beautify#1678]
# Input
The code looked like this before beautification:
```HTML
<vue-stars
	v-model="demo.value"
	:active-color="demo.activeColor"
	:inactive-color="demo.inactiveColor"
	:shadow-color="demo.shadowColor"
	:hover-color="demo.hoverColor"
	:max="demo.max"
	:readonly="demo.readonly"
	:char="demo.char"
	:inactive-char="demo.inactiveChar"
	:class="demo.class"
	name="multiDemo" />
```

# Expected Output
The code should have looked like this after beautification:
```HTML
<vue-stars
	v-model="demo.value"
	:active-color="demo.activeColor"
	:inactive-color="demo.inactiveColor"
	:shadow-color="demo.shadowColor"
	:hover-color="demo.hoverColor"
	:max="demo.max"
	:readonly="demo.readonly"
	:char="demo.char"
	:inactive-char="demo.inactiveChar"
	:class="demo.class"
	name="multiDemo" />
```

# Actual Output
The  code actually looked like this after beautification:
```HTML
<vue-stars
 v-model="demo.value"
 :active-color="demo.activeColor"
 :inactive-color="demo.inactiveColor"
 :shadow-color="demo.shadowColor"
 :hover-color="demo.hoverColor"
 :max="demo.max"
 :readonly="demo.readonly"
 :char="demo.char"
 :inactive-char="demo.inactiveChar"
 :class="demo.class"
 name="multiDemo" />
```

# Steps to Reproduce
Tab a set of attributes under its tag. Format. Note how the tabs leading up to the tag's starting position are preserved, but the tab(s) actually indenting the attributes under their tag are **not preserved**, they are replaced with a single space.

Auto and force also use spaces to indent attributes, ignoring the "indent_with_tabs" option (making them unusable for me), but one would think that "preserve" would, well, *preserve* whatever whitespace is chosen. I understand why the more alignment-driven options must use space, but these other options should use the specified whitespace setting.

## Environment
OS: OS X, VS Code, using js-beautify-html as my HTML formatter for the Vetur plugin.

## Settings
Example:
```json
{
      "wrap_line_length": 160,
      "indent_with_tabs": true,
      "wrap_attributes": "preserve"
}
```

**Comment by bitwiseman** [comment]
This works on https://beautifier.io/.  Your plugin is likely using an older version.  Please check.

**Comment by richardtallent** [comment]
OMG. Vetur is still using 1.7.5! *sigh*

Guess I'll raise an issue there. Thanks!
