### ISSUE TITLE
Wrong indentation when the last line in a case is a right brace

### ISSUE THREAD

**Issue by fmkang** [beautify-web/js-beautify#1683]
# Description
The indentation is wrong if the last line of code is a right brace in a case code block.

However, if you put another statement (something other than a comment) after the right brace, it becomes correct.

# Input
The code looked like this before beautification:
```
switch (a) {
    case 'foo':
    case 'bar':
        if (foo == bar) {
            console.log(a);
        } else {
            console.log(a);
        }
    case 'baz':
        console.log(a);
}
```

# Expected Output
The code should have kept the same after beautification:
```
switch (a) {
    case 'foo':
    case 'bar':
        if (foo == bar) {
            console.log(a);
        } else {
            console.log(a);
        }
    case 'baz':
        console.log(a);
}
```

# Actual Output
The  code actually looked like this after beautification:
```
switch (a) {
    case 'foo':
    case 'bar':
        if (foo == bar) {
            console.log(a);
        } else {
            console.log(a);
        }
        case 'baz':
            console.log(a);
}
```
The last case is mistakenly indented.

If you add one line after the brace, it will keep the same:
```
switch (a) {
    case 'foo':
    case 'bar':
        if (foo == bar) {
            console.log(a);
        } else {
            console.log(a);
        }
        console.log(a);
    case 'baz':
        console.log(a);
}
```

## Environment
OS: macOS 10.14.5

## Settings
As default:
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by marianayap** [comment]
@bitwiseman Hello! Can I give this issue a try?

**Comment by bitwiseman** [comment]
@marianayap Please do!

**Comment by marianayap** [comment]
@bitwiseman Hello! I won't be able to continue with the issue. It's open for anyone that wants to contribute. Thank you!

**Comment by pr0grammm** [comment]
Hello, I have been given a  task to contribute to an open source repo and I am interested in this project! Could I please be assigned this issue?
