### ISSUE TITLE
One Question

### ISSUE THREAD

**Issue by thefued** [beautify-web/js-beautify#1684]
input - 
```
<p> TEXT <strong> FULLLLLLLLLLLLLLSSSTROOONG </strong> other text </p>
```

Output - 
```
<p>
      TEXT
<strong>
                 FULLLLLLLLLLLLLLLLLLSSSSTROOOONG
</strong>
      other text
</p>
```

This format is very suitable for translating texts, etc.
Is it possible to do this?

**Comment by bitwiseman** [comment]
What part of it are you asking about?  That specific formatting is very odd.  You might be able to do  something similar, but not exactly that.

**Comment by thefued** [comment]
right, not quite, it will be enough for me:
text not on line with tag

**Comment by thefued** [comment]
<p> Text </p>  ->
<p>
       Text
</p>

**Comment by thefued** [comment]
`<p>text</p> .    ->
<p>
        text
</p>`

**Comment by bitwiseman** [comment]
PIease edit your examples to use triple-backtick notation.

**Comment by thefued** [comment]
\<p>TEXT\</p>  
->
\<p>
        TEXT
\</p>
I need this result. How to achieve this? I did not understand from the sentence above (
