### ISSUE TITLE
PHP open/close tags get spaces inserted when inside <script> blocks

### ISSUE THREAD

**Issue by bmewburn** [beautify-web/js-beautify#1685]
# Description
I'm using jsbeautify on mixed PHP/CSS/JS/HTML. PHP open/close tags inside script blocks get spaces inserted between the characters. I don't expect the PHP to be formatted itself, but is it possible for the tags to remain intact? It makes it easy to then find and replace with the original PHP content after formatting.

# Input
The code looked like this before beautification:
```
<script>
var foo = <?php ?>;
var bar = <?= ?>;
</script>
```

# Expected Output
The code should have looked like this after beautification:
```
<script>
    var foo = <?php ?>;
    var bar = <?= ?>;
</script>
```

# Actual Output
The  code actually looked like this after beautification:
```
<script>
    var foo = < ? php ? > ;
    var bar = < ? = ? > ;
</script>
```

# Steps to Reproduce
```
var format = require('js-beautify');
var fs = require('fs');
var src = fs.readFileSync('./test.php').toString();
fs.writeFileSync('./formatted.php', format.html(src));
```

## Environment
OS: `Linux xps 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux`

## Settings
default settings

**Comment by bitwiseman** [comment]
See #1647 .  If you have a suggestion as to how to improve the readme to make this more discoverable, I would appreciate a PR.

**Comment by bmewburn** [comment]
Thanks @bitwiseman I see it now in the changelog and readme.
