### ISSUE TITLE
HTML beautifier breaks when encountering {#

### ISSUE THREAD

**Issue by Tgoh** [beautify-web/js-beautify#1692]
The HTML beautifier appears to stop functioning after encountering the sequence {#.
Have tested using that as a string, as well as in an attribute. The beautifier stops working after any occurrence of that string anywhere in the input.

# Input
The code looked like this before beautification:
```
<div><div>{#Test}</div></div>
```

# Expected Output
The code should have looked like this after beautification:
```
<div>
    <div>{#Test}</div>
</div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div>
    <div>{#Test}</div></div>
```

# Steps to Reproduce
Run specified text through beautifier.

## Environment
OS: WIndows 10, NodeJS
Version: 1.10.1

## Settings
Example:
Have tested with default settings as well as:
```json
{
    indent_with_tabs: false,
    indent_size: 4,
    unformatted: [],
    wrap_line_length: 0
}
```

If you need any more information let me know and I can provide a more detailed sample.

**Comment by Jaans** [comment]
We are having the same issue with this thought it was browser issue.

**Comment by bitwiseman** [comment]
Is that `{#Test}` a template? Handlebars? Or do you mean it as normal text?

**Comment by Tgoh** [comment]
Literally normal text. We feed that exact string into the beautifier.

**Comment by bitwiseman** [comment]
Ah, use the setting `"templating": "none"`.

**Comment by bitwiseman** [comment]
@Tgoh 
Did that work for you?

**Comment by Tgoh** [comment]
Hey sorry I thought I'd already replied. Yeah the templating none did work for me, issue is resolved.
