### ISSUE TITLE
Please update CodeMirror Addon

### ISSUE THREAD

**Issue by tranzitwww** [beautify-web/js-beautify#1695]
# Description
Trying to do a CRTL+A and CRTL+C for a code larger than 1055 characters may results in having a clipboard with just one character "-" (minus).
It always fill the clipboard with "-" when trying to copy a larger text code, and this is frustrating :)

I've opened this bug to another project and they had updated the codemirror add-on and now is working.
https://github.com/greasemonkey/greasemonkey/issues/2894
https://github.com/openstyles/stylus/issues/225

# Steps to Reproduce
Go to https://beautifier.io/
Select Beautify CSS
Put the content form http://danielmontague.com/css/main.min.css
Click Beautify Code
Copy the Beautified code (CRTL+A and CRTL+C)
Paste somewhere
The result will be "-". Just one character was getting into the clipboard during copy process

## Environment
OS:
Win7 64Bit
Firefox 68.0.1

**Comment by bitwiseman** [comment]
Updated and improved to work with CSS and html highlighting.
