### ISSUE TITLE
Search (ctrl+f) works only in view field in CodeMirror

### ISSUE THREAD

**Issue by oleedd** [beautify-web/js-beautify#1696]
No such problem in textarea. But CodeMirror is default.
Possible to fix?

**Comment by bitwiseman** [comment]
@oleedd 
This would require adding the search addon for CodeMirror.  
https://codemirror.net/doc/manual.html#addons
Not too hard to fix, just needs someone with time to do it.

**Comment by oleedd** [comment]
It would be very nice)

**Comment by oleedd** [comment]
It is probably a javascript search.
Possible to make the standard browser search work as it works in the textarea?

**Comment by oleedd** [comment]
It is probably a javascript search in the addon.
CodeMirror is very strange. It rewrites strings according to the view field and deletes lower/higher strings from the html. The search does't work because all strings don't exist in the html at the same time. There seems to be some limit for the number of strings.
Moreover, such behavior requires certain computing power, which don't justify the goal - CPU loads up to 50% (i5) during scrolling.
Possible to fix this rewriting and remove these useless calculations to make the standard browser search work as it works in the textarea?

**Comment by oleedd** [comment]
It is probably a javascript search in the addon.
CodeMirror is very strange. It rewrites strings according to the view field and deletes lower/higher strings from the html. The search does't work because all strings don't exist in the html at the same time. There seems to be some limit for the number of strings.
Moreover, such behavior requires certain computing power, what doesn't justify the goal - CPU loads up to 60% (i5) during scrolling.
Possible to fix this rewriting and remove these useless calculations to make the standard browser search work as it works in the textarea?
