### ISSUE TITLE
[HTML]: Add option to indent HTML tag text in a newline

### ISSUE THREAD

**Issue by ntnyq** [beautify-web/js-beautify#1703]
# Description

I've read the __js-beautify-html__ options and issues with label `language: html`.

# Input
With this new feature, when I give like this input: 
```
<p>Lorem ipsum.<p>
<span>Lorem ipsum.<span>
<p>Lorem ipsum.<span>Lorem ipsum.</span>Lorem ipsum.</p>
```

# Expected Output
I'd like to see this output:
```
<p>
    Lorem ipsum.
</p>
<span>
    Lorem ipsum.
</span>
<p>
    Lorem ipsum.
    <span>
        Lorem ipsum.
    </span>
    Lorem ipsum.
</p>
```

## Environment
OS: MacOS High Sierra & Mojave

**Comment by bitwiseman** [comment]
@ntnyq 
Thanks for the report.

These two inputs produce different formatting due to `span` being an inline tag, so that will never be supported.  
```
<span>Lorem ipsum.<span>
<span>
    Lorem ipsum.
</span>
```

However the other part is reasonable and is tracked by #980 (was missing the html label, added now).
