### ISSUE TITLE
"@" symbol is converted to "<blade"  in `blade.php` files.

### ISSUE THREAD

**Issue by iwasherefirst2** [beautify-web/js-beautify#1725]
# Input
The code looked like this before beautification:
```
<script type="text/javascript">
     document.write( "@" );
</script>
```

# Expected Output
The code should have looked like this after beautification:
```
<script type="text/javascript">
     document.write( "@" );
</script>
```

# Actual Output
The  code actually looked like this after beautification:
```
<script type="text/javascript">
    document.write("<blade " / > );
</script>
```

# Steps to Reproduce
- Use ATOM editor
- create file with above content
- save as `test.blade.php` 
- run beautify through `atom-beautify:beautify-language-blade`

## Environment
OS: Ubuntu 18.04
Using Beautify in Atom Editor

## Settings
I did not specify any settings anywhere
```

**Comment by bitwiseman** [comment]
@iwasherefirst2 

Did you try this on https://beautifier.io ? 

I can think of no code in this library that would do what you have described.  It is likely that this is cause by some other part of Atom and/or that plugin.

**Comment by iwasherefirst2** [comment]
@bitwiseman it seems that it was not related to the `language-blade` package. I can reproduce the issue even with all other packages beeing disabled. One has to call the command  `atom-beautify:beautify-language-blade` from console ( I adjusted the reproduce-steps from original post). 

It seems that calling `Beautify` through the menu does not call `atom-beautify:beautify-language-blade` by default, but it did when I enabled the `language-blade` package. That why I thought the package is causing it.

**Comment by bitwiseman** [comment]
If this isn't reproducible on  https://beautifier.io it is unlikely to be caused by this library.  You'll need to talk to the author of that plugin.  Sorry.

**Comment by iwasherefirst2** [comment]
@bitwiseman the error appears even if all other plugins are disabled. But I just noticed that there is another repo for the atom package of beautify: https://github.com/Glavin001/atom-beautify

I will create an issue on atom-beautify repo
