### ISSUE TITLE
JSON keys enclosed in double quotes

### ISSUE THREAD

**Issue by gsscoder** [beautify-web/js-beautify#1729]
I don't know if this is possible, but I'd like to know if there's an option to force JSON keys into double quotes.

From this:
`[ key1: "valueA", key2: "valueB", key3: "valueC" ]`
to this:
`[ "key1": "valueA", "key2": "valueB", "key3": "valueC"]`

I need it using Pyhon version from code.

Thank you.

**EDIT:**
For the moment I've solved using `regex` (see https://gist.github.com/gsscoder/e212d1630bc4e7f036c63411b1262116). But I'm interested if `js-beautify` can do this.

**Comment by bitwiseman** [comment]
The beautifier only changes whitespace formatting not text.

**Comment by gsscoder** [comment]
Roger.
Have a nice day
