### ISSUE TITLE
Broken private fields in classes (JS)

### ISSUE THREAD

**Issue by MikeDombo** [beautify-web/js-beautify#1734]
# Description
Private fields in JS classes use `#` as part of the identifier name. When beautifying the initial declaration, this library puts it on the wrong line.

# Input
The code looked like this before beautification:
```
class X {
    #__private = null;
}
```

# Expected Output
The code should have looked like this after beautification:
```
class X {
    #__private = null;
}
```

# Actual Output
The  code actually looked like this after beautification:
```
class X {
    #
    __private = null;
}
```

# Steps to Reproduce

## Environment
OS: Windows
Language: Python

## Settings
Example:
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse,preserve-inline",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0
}
```

**Comment by appleinautumn** [comment]
So what's the solution for this?

**Comment by MikeDombo** [comment]
PR #1735 fixed it and it is released.
