### ISSUE TITLE
PHP Application Integration

### ISSUE THREAD

**Issue by menjilx** [beautify-web/js-beautify#1747]
Hi, is there an option to incorporate this on a PHP application?

thank you

**Comment by bitwiseman** [comment]
@menjilx  I don't know what you mean exactly. What are you trying to achieve?

**Comment by menjilx** [comment]
> @menjilx I don't know what you mean exactly. What are you trying to achieve?

I want to use this library/package to "beautify" a javascript source code from my PHP program that gets the page content. Cause the JS codes on some sites are encoded. 

Thank you

**Comment by bitwiseman** [comment]
You if your php can run javascript via node that should do it. I don't have any specific pointers.
