### ISSUE TITLE
fails on simple-looking json

### ISSUE THREAD

**Issue by divinity76** [beautify-web/js-beautify#1753]
Edit:
I **can** reproduce it on Firefox 72.0.1 from the Ubuntu Linux 18.04 repo

I can **not** reproduce it on Firefox 72.0.2 from the Ubuntu Linux 18.04 repo

I can **not** reproduce it on the older ESR Firefox 68.4.2esr

also i can **not** reproduce it on Chrome (version is 79.0.3945.130  but doubt that's relevant)

for some reason it fails on this simple-looking json:
```json
[{"Category":"Other","Comment":null,"DataChangedAt":"2018-05-09T68","Id":"4PAFO92","Tags":"","Url":"https:\/\/"},{"Category":"Other","Comment":null,"DataChangedAt":"2018-058","Id":"QBFOAV","Tags":"","Url":"https:\/\/cdV.jpg"},{"Category":"Other","Comment":null,"DataChangedAt":"2018.68","Id":"4PABTMOUI3QBFO0N","Tags":"","Url":"https:\/\/cd3QBFO0N.jpg"},{"Category":"Other","Comment":null,"DataChangedAt":"2018-05-09T15:43:06","Id":"6555","Tags":"","Url":"https:\/\/cdES.jpg"},{"Category":"Other","Comment":null,"DataChangedAt":"2013:06","Id":"666","Tags":"","Url":"https:\/\/cdn.easyFLOQ.jpg"},{"Category":"Other","Comment":null,"DataChangedAt":"2018-05-09T15:43:06","Id":"44","Tags":"","Url":"https:\/\/cdnD.jpg"}]
```

the output is just that 1 line.. 
![image](https://user-images.githubusercontent.com/1874996/73281526-67f09d00-41f0-11ea-89f0-01a997e397de.png)

i expected something like:
```json
[
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2018-05-09T68",
        "Id": "4PAFO92",
        "Tags": "",
        "Url": "https://"
    },
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2018-058",
        "Id": "QBFOAV",
        "Tags": "",
        "Url": "https://cdV.jpg"
    },
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2018.68",
        "Id": "4PABTMOUI3QBFO0N",
        "Tags": "",
        "Url": "https://cd3QBFO0N.jpg"
    },
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2018-05-09T15:43:06",
        "Id": "6555",
        "Tags": "",
        "Url": "https://cdES.jpg"
    },
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2013:06",
        "Id": "666",
        "Tags": "",
        "Url": "https://cdn.easyFLOQ.jpg"
    },
    {
        "Category": "Other",
        "Comment": null,
        "DataChangedAt": "2018-05-09T15:43:06",
        "Id": "44",
        "Tags": "",
        "Url": "https://cdnD.jpg"
    }
]
```
which looks much prettier imo (it's the same data but prettified via PHP's `JSON_PRETTY_PRINT` )

it's possible that it's just my expectations that are wrong, idk

i don't think i changed the formatting options, i just used the default ones, but for completes: 
```
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": true,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by bitwiseman** [comment]
There's setting that preserves single line statement, but that isn't turn on...  I'm not able to reproduce the problem.  Do you see anything in the browser's console log?

**Comment by divinity76** [comment]
hmm, there is nothing in the browser console log, *but*

I can reproduce it on Firefox 72.0.1 from the Ubuntu Linux 18.04 repo

I can *not* reproduce it on the older ESR Firefox 68.4.2esr

also i can *not* reproduce it on Chrome (version is 79.0.3945.130  but doubt that's relevant)

**Comment by bitwiseman** [comment]
Well, it means it is a browser and version specific bug.

**Comment by divinity76** [comment]
.. i can NOT reproduce it on Firefox 72.0.2 - which is awfully close the version where i can reproduce it, 72.0.1...

**Comment by bitwiseman** [comment]
Wow, that is very version specific.

**Comment by divinity76** [comment]
since it cannot be reproduced on any up-to-date version of Firefox (not even the slowest release-cycle ESR version), and it cannot be reproduced on other browsers, 

Im guessing it's not even worth looking into, and should be closed?

**Comment by bitwiseman** [comment]
Agreed. Thanks for tracking it down.
