### ISSUE TITLE
Incorrect indentation of Handlebars inline partials

### ISSUE THREAD

**Issue by andycnguyen** [beautify-web/js-beautify#1756]
# Input
The code looked like this before beautification:
```
{{#*inline "MyInlinePartial"}}
{{MyIdentifier}}
{{/inline}}
```

# Expected Output
The code should have looked like this after beautification:
```
{{#*inline "MyInlinePartial"}}
    {{MyIdentifier}}
{{/inline}}
```

# Actual Output
The  code actually looked like this after beautification:
```
    {{#*inline "MyInlinePartial"}}
        {{MyIdentifier}}
        {{/inline}}
```

# Steps to Reproduce

## Settings
Example:
```json
{
    "indent_handlebars": true
}
```

**Comment by bitwiseman** [comment]
Inline Partials: https://handlebarsjs.com/guide/partials.html#inline-partials

This pattern recognizer is looking for `{{#` or `{{^` which is fine...

https://github.com/beautify-web/js-beautify/blob/ae3e9e6b1c47487c72f92951333b2944dd5160b0/js/src/html/beautifier.js#L608-L609

 but this this line thinks the name of the tag is `*inline` when it is actually `inline`.  
https://github.com/beautify-web/js-beautify/blob/ae3e9e6b1c47487c72f92951333b2944dd5160b0/js/src/html/beautifier.js#L618

Should someone have time to fix this, they'll need to add a check for `*` and then add tests.
