### ISSUE TITLE
Partial HTML formatted invalid

### ISSUE THREAD

**Issue by rolandkakonyi** [beautify-web/js-beautify#1764]
# Description
We tried to use js-beautify to re-format partial HTML that is pre-indented.
It fails to remove indentation fo most of the lines but one without tags, this makes the formatted result broken.

## Input
The code looked like this before beautification:
```
 <body>
  <h1>My favorite things</h1>
  <h2>Raindrops on roses</h2>
  <h3>Whiskers on kittens</h3>
  Bright copper kettles
 </body>


```

## Current Output
The  code actually looked like this after beautification:
```
 <body>
   <h1>My favorite things</h1>
   <h2>Raindrops on roses</h2>
   <h3>Whiskers on kittens</h3>
  Bright copper kettles
  </body>
```

## Expected Output
The code should have looked like this after beautification:
```
<body>
 <h1>My favorite things</h1>
 <h2>Raindrops on roses</h2>
 <h3>Whiskers on kittens</h3>
 Bright copper kettles
</body>
```

# Environment

## Browser User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

Language Selected:
Beautify HTML

## Settings
```json
{
  "indent_size": 1,
  "indent_char": " ",
  "max_preserve_newlines": "1",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": 41,
  "indent_inner_html": true,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false,
  "extra_liners": ""
}
```

**Comment by bitwiseman** [comment]
Odd, I don't see that behavior locally.
