### ISSUE TITLE
Formatting stops after occurence of {#

### ISSUE THREAD

**Issue by jensweigele** [beautify-web/js-beautify#1767]
# Description
When formatting the (pseudo) HTML code below, the formatting stops after the "img"-tag.
If I remove the "{#" code (or replace it with "{{#"), everything works as expected.
This syntax is for sure not "standard conform" - but it's used in JsReport for some special functions and it would be nice to get the formatter running even with those templates.
 

## Input
The code looked like this before beautification:
```
<header class="header">
    <img src="{#asset test.svg @encoding=dataURI}" />
<h1 class="title report-title">{{ __report.name }}</h1>
</header>
```

## Current Output
The  code actually looked like this after beautification:
```
<header class="header">
    <img src="{#asset test.svg @encoding=dataURI}" />
<h1 class="title report-title">{{ __report.name }}</h1>
</header>
```

## Expected Output
The code should have looked like this after beautification:
```
<header class="header">
    <img src="{#asset test.svg @encoding=dataURI}" />
    <h1 class="title report-title">{{ __report.name }}</h1>
</header>
```

# Environment

## Browser User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

Language Selected:
Beautify HTML

## Settings
```json
{
  "indent_size": "4",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by bitwiseman** [comment]
See #1692.
