### ISSUE TITLE
Please bump mkdirp to fix mkdirp@0.5.1 vulnerability

### ISSUE THREAD

**Issue by e2tha-e** [beautify-web/js-beautify#1768]
__Vulnerability:__ https://app.snyk.io/test/npm/js-beautify/1.10.3
Also affects older js-beautify versions that depend on mkdirp@0.5.1

Thanks!

**Comment by e2tha-e** [comment]
2 prs can fix this:
https://github.com/beautify-web/js-beautify/pull/1750
https://github.com/beautify-web/js-beautify/pull/1769

**Comment by shahar-h** [comment]
`mkdirp` 0.5.3 was released with an upgrade to `minimist`:
https://github.com/isaacs/node-mkdirp/issues/7

**Comment by e2tha-e** [comment]
Excellent! js-beautify will now depend on mkdirp@0.5.3, which is remedied of the vulnerability. Nonetheless, it might be worth bumping mkdirp to the latest major version, since mkdirp@0.5.3 is a deprecated version.

Otherwise, the mkdirp vulnerability is no longer an issue. I'll leave it to the js-beautify maintainers to decide whether to proceed further and whether to close this issue.
