### ISSUE TITLE
Node version requires at least 10

### ISSUE THREAD

**Issue by JuXie-QiBao** [beautify-web/js-beautify#1783]
# Description
The mkdirp of 1.0.4 is installed in JS beauty of 1.1.0, because the mkdirp of 1.0.4 requires that the node environment be at least 10, resulting in the node environment used by JS beauty of at least 10.Is this normal?

# Input
The code looked like this before beautification:
```
the mkdirp of 1.0.4:
"engines": {
    "node": ">=10"
  },
```

**Comment by bitwiseman** [comment]
I was unaware of that.  Our CI system include node8 and up : 
https://dev.azure.com/beautifier-io/js-beautify/_build/results?buildId=340&view=results

We could not retain the older version of mkdirp due to vulnerabilities.

**Comment by Rem486** [comment]
I also encountered this problem. Our CI system use node8, got this error:

`error mkdirp@1.0.4: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.x"`

Then,build failure.

**Comment by bitwiseman** [comment]
@Rem486 @JuXie-QiBao 
Please try changing the `npm config` setting `engines-strict` to `false`. 
https://docs.npmjs.com/misc/config#engine-strict

Or try manually setting `node-version` to `0.10.0`
https://docs.npmjs.com/misc/config#node-version

Note Node 8 LTS expired on 2020-01-01 but mkdirp should still work on Node 8. 
https://github.com/isaacs/node-mkdirp#platform-support

**Comment by bitwiseman** [comment]
You can also lock your js-beautify version to `1.10.x`. 

I'm sorry, but we cannot downgrade the version of `mkdirp`.

**Comment by Rem486** [comment]
@bitwiseman 
Thanks for your advice! I temporarily locked `js-beautify` version to `1.10.3` , `mkdirp` to `0.5.5` to avoid this issue. 
Consider upgrading `node` version of our CI system later.

**Comment by janlazo** [comment]
Can the `mkdirp` version be loosed to support 0.5.2+ which has the fix, https://github.com/isaacs/node-mkdirp/commit/c5b97d17d45a22bcf4c815645cbb989dab57ddd8?
