### ISSUE TITLE
Children of p are not indented properly in 1.11.0

### ISSUE THREAD

**Issue by HitkoDev** [beautify-web/js-beautify#1784]
# Description
Children of `p` are not indented properly in `1.11.0`.

# Input
The code looked like this before beautification:
```
<p>
    <ul>
        <li>sadas</li>
    </ul>
</p>
```

# Expected Output
The code should have looked like this after beautification:
```
<p>
    <ul>
        <li>sadas</li>
    </ul>
</p>
```

or

```
<p></p>
<ul>
    <li>sadas</li>
</ul>
<p></p>
```

# Actual Output
The  code actually looked like this after beautification:
```
<p>
<ul>
    <li>sadas</li>
</ul>
</p>
```

# Steps to Reproduce
1. Beautify code.

## Environment
OS: Win, Linux

## Settings
Defaults

**Comment by HitkoDev** [comment]
I believe https://github.com/beautify-web/js-beautify/commit/35ed0cd2180a036234760ae6cf319c56c4d4b688 is tem main culprit here.

**Comment by bitwiseman** [comment]
@HitkoDev 
In fact, for html, the output in 1.11 is correct.

Interesting fact:  `ol` and `ul` elements are not legally allowed inside `p` elements.  
[This SO answer](https://stackoverflow.com/a/5681796/1637252) has a good summary of it.


Try putting the text below into the html validator at  https://validator.w3.org/nu/#textarea : 
```
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
<body>
<p>
<ul>
    <li>sadas</li>
</ul>
</p>
```
You will get an error message for the closing `p` tag.  

It could be argued that the beautifier should be more permissive.  The user has provided a closing tag, the beautifier should detect that and use it.   However doing that is not easy within the current design of  the html beautifier.  We had a choice between supporting correct formatting of `p` elements with valid content (including optional closing tag for that `p` element) or we can support correct formatting for invalid content.   

Possible ways to address your scenario: 
1. Add a flag to disable the optional closing tags - Simple to implement, but is still another flag with added testing complexity.  If someone has time to do that work, PRs are welcome.
2. Improve the html parsing to respect provided closing tags over option closing tags - This avoids the flag but is a potential bug farm.
3. Create a xml beautifier and have the html beautifier extend it - this would be useful in general but also a lot of work.

**Comment by HitkoDev** [comment]
Perhaps you're right, however up until version `1.11.0` all elements were properly nested, so this is a major breaking change and should be labelled as such in the first place. Instead it's not even mentioned in the changelog, and it's been introduced in a minor version, which is against semantic versioning.

**Comment by bitwiseman** [comment]
@HitkoDev 
I understand that you're upset at this fix.  It produced an unexpected change to your formatting.

I'm sorry, but up until 1.11.0 the elements were not properly nested, they were incorrectly nested in a way that appeared reasonable.  Now they are correctly nested in a way that is surprising until you dig into it.

This fix was noted in the change log.  The change log doesn't highlight your scenario, but that is not really surprising given that it's not valid html.

Understand, if there were any scenario in which this syntax were valid, I'd be in complete agreement with you. I have just spent several hours looking for any scenario in which the input you provided is valid html, but I can't find one.  I was thinking this might be valid in xhtml, but even there it is not: http://xstandard.com/en/articles/xhtml-reference/p/#p-contains .  In xhtml, the `ul` still cannot be a child of the `p` so the result is the same as in html.   (The only scenario I can find is if you are writing plain xml).

The project does follow semantic versioning to the extent that is reasonable in this area.

We use major version to indicate API compatibility.  This project has never made API incompatible changes. There are a number of options that have been retained for backward compatibility.  

The question then is what is the definition of "backward compatible" when it comes to formatting output?  If we say any change to output is not backward compatible" then every change will be a new major version.  That would actually less informative for the consumers of this library - they would not know whether a release is API compatible or not. 

We use minor versions to indicate significant formatting fixes or added features. 
We use patch versions to indicate small bug fixes formatting fixes or added options that cannot cause any side effects.

We do not make spurious changes the output, but output for a given input *MAY* change for minor or patch versions.  For changes that *fix formatting errors* (making the output more accurate), we turn those on by default and may or may not provide the ability to turn them off. We only do this only when the formatting was strictly incorrect.  All other changes should be added as formatting *options*, which must be off by default such that the default formatting of valid input doesn't change whenever a feature is added.  

Best effort is made to handle invalid inputs in a reasonable way as well, but that is not a priority.

**Comment by bitwiseman** [comment]
As an added point, not having an option to revert to the old formatting is not just a theoretical point either.  The difference can be seen in the rendered html. If you look at [this jsfiddle](https://jsfiddle.net/qk9atb2u/1/), you can see that CSS that applies to the `p` element contents does not apply to the `ul` even though from the text you might think the `ul` was "inside" the `p` element. 
```
// css
p {
  background: green;
}

// html
<p>
Hello
</p>
<p>
<span>
Hello again
</span>
</p>
<p>
<ul>
<li>Hello again</li>
</ul>
</p>
```

By indenting the `ul` element, the beautifier has been indicating that the `ul` is a child of the `p` element, which it absolutely is not.

**Comment by HitkoDev** [comment]
Thanks for your example; however, there's an important difference between your jsfiddle and js-beautify behaviour: if you inspect the resulting (rendered) html you get

```html
<p></p>
<ul> 
    <li>Hello all!</li>
</ul>
<p></p>
```

So although I completely agree regarding `<ul>` being on the same level as `<p>`, I still believe as long as an open tag comes before a close tag of another element, it should be indented accordingly. 

---

It makes me wonder, though, should a formatter even care about semantics?

**Comment by bitwiseman** [comment]
Could you point out the part of this difference you mentioned above that you feel is the key difference and what it means? I'm not sure I understood. 

> I still believe as long as an open tag comes before a close tag of another element, it should be indented accordingly.

> It makes me wonder, though, should a formatter even care about semantics?

The beautifier has to care about semantics in order to correctly indent valid html.  There have been multiple requests to fix this formatting bug and others related to [optional closing tags](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags).  The easy example is list items.  This is what lists would look like if the formatter ignored semantics:

```html
<ul>
    <li>Item 1
        <li>Item 2
            <li>Item 3
                <li>Item 4
</ul>
```

I get what you're saying. You'd like the formatter to use the input as indicator of your intention and format accordingly regardless of whether it matches the language semantics.   There are plenty of cases where the beautifier does exactly this - it doesn't fully parse the html and it doesn't check all the semantics. 

```html
<span>
    <div>
        Hello again
    </div>
</span>
```
The beautifier keeps this formatting even though the `div` is *not* inside the `span`.  This is a bug, but one that no one has requested it be fixed. The difference is that the `p` element has defined correct behavior that people have requested be fixed. And it has taken years to get to finally fix even that.

Let me give an extreme example. If the user pass the input below would you want the beautifier to keep this formatting? 

```html
<ul>
    <li>Item 1
        <li>Item 2
            <li>Item 3
                <li>Item 4
                </li>
            </li>
        </li>
    </li>
</ul>
```
