### ISSUE TITLE
beautify inserts spaces before and after braces in javascript object definitions

### ISSUE THREAD

**Issue by kshartman** [beautify-web/js-beautify#1797]
# Description
Perhaps I am missing some settings but it is not obvious to me how to suppress the insertion of spaces before and after braces in js object definitions, i.e. {$and: [{foo: bar}, {baz: quux}]} becomes { $and: [{  foo: bar }, { baz: quux }] }.  

I looked through the code and I see space_in_paren and space_in_empty_paren but they do not control spacing in braces. With my settings, it bloats complex queries and structures with spaces which makes it unusable in files that contain such elements unless I mark the sections with
`/* beautify preserve:start */ and /* beautify preserve:end */`

Thanks for your time. 

# Input

            return Events.find({$and: [{$or: [{community: group.slug}, {communities: group.slug}]}, {date: {$gte: new Date()}}]},
                               {sort: {date: 1}});

# Expected Output

            return Events.find({$and: [{$or: [{community: group.slug}, {communities: group.slug}]}, {date: {$gte: new Date()}}]},
                               {sort: {date: 1}});

# Actual Output

            return Events.find({ $and: [{ $or: [{ community: group.slug }, { communities: group.slug }] }, { date: { $gte: new Date() } }] }, { sort: { date: 1 } });

# Steps to Reproduce

run it through js-beautify for node via shell. I actually do this under emacs 26.3 but running it directly in bash yields the same result.

## Environment
OS:
ubuntu 18.04
node 10.20.1
js-beautify 1.11.0 

## Settings
    "js": {
        "indent_size": 4,
        "indent_char": " ",
        "indent_level": 0,
        "indent_with_tabs": false,
        "preserve_newlines": true,
        "max_preserve_newlines": 10,
        "jslint_happy": false,
        "space_after_anon_function": false,
        "space_after_named_function": false,
        "space_in_paren": false,
        "space_in_empty_paren": false,
        "brace_style": "end-expand,preserve-inline",
        "keep_array_indentation": false,        
        "keep_function_indentation": false,
        "space_before_conditional": true,
        "break_chained_methods": false,
        "eval_code": false,
        "unescape_strings": false,
        "wrap_line_length": 0
    }

**Comment by bitwiseman** [comment]
Are "js object definitions" part of some specification?

**Comment by kshartman** [comment]
When I say "js object definitions", what I mean is a set of key-value pairs enclosed in braces.

For example:
{z: {x: y}}

What beautify currently does with my settings 

{z: {x: y}} -> { z: { x: y } }

In other words, it seems to insert spaces after every open brace and before every close brace in such constructs.  Yes, it is a syntactically valid result, but it consumes significantly more horizontal space than before and in my opinion, is less readable.  It does not treat parens or square brackets this way with my current settings. 

Is there a way to control this?  As it is, I have to run awk after js-beautify to fix what it did.

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/issues/1204
