### ISSUE TITLE
SCSS module system @use problem

### ISSUE THREAD

**Issue by mrahhal** [beautify-web/js-beautify#1798]
# Description

When using the [SCSS module system](https://sass-lang.com/blog/the-module-system-is-launched), you can configure namespacing using something like:

```
@use 'variables' as *;
```

Which is the equivalent of the following without the module system:

```
@import 'variables';
```

# Input
The code looked like this before beautification:
```
@use 'variables' as *;
```

# Expected Output
The code should have looked like this after beautification:
```
@use 'variables' as *;
```

Should stay the same.

# Actual Output
The  code actually looked like this after beautification:
```
@use 'variables'as *;
```

The space between the module name and "as" gets erased. 

## Environment
OS: Windows

## Settings

```json
{
  "end_with_newline": true,
  "max_preserve_newlines": 2,
  "preserve_newlines": true,
  "css": {
    "indent_size": 2,
    "newline_between_rules": true,
    "selector_separator_newline": true,
    "space_around_combinator": true
  },
  "html": {
    "indent_size": 2,
    "unformatted": [],
    "wrap_attributes": "force-aligned"
  }
}

```

**Comment by mhnaeem** [comment]
Possibly fixed by #2018

**Comment by bitwiseman** [comment]
@mhnaeem  
Submit a PR with tests showing it is if fixed.

**Comment by mhnaeem** [comment]
@bitwiseman Done!
