### ISSUE TITLE
add Copy to Clipboard or Select all key

### ISSUE THREAD

**Issue by StenAskerBergman** [beautify-web/js-beautify#1805]
# Description

Add a copy to clip board button 

https://www.freeformatter.com/html-formatter.html#ad-output 

like these people did, if they can you can 2

and yes this is a issue

**Comment by bitwiseman** [comment]
@StenAskerBergman 
Thanks for filing this issue.  

This pages has instructions on how to add this functionality: https://www.w3schools.com/howto/howto_js_copy_clipboard.asp

PRs welcome.

**Comment by mayankshouche** [comment]
Hey there @bitwiseman
Can I take this issue?

**Comment by mayankshouche** [comment]
If any maintainers could provide some feedback on that PR, it would be much appreciated (esp. button placement and UI changes).
