### ISSUE TITLE
What option makes boolean attributes written as `attr` instead of `attr=""` ?

### ISSUE THREAD

**Issue by cata-code** [beautify-web/js-beautify#1821]
My `hidden` attribute shows up as `hidden=""` instead of `hidden`. What option do I need to correctly output boolean attributes?
I tried `wrap_attributes` and doesn't do what I need.

**Comment by cata-code** [comment]
For now I'm using this code

```js
fixHtml (html) {
  return html.replace(/(hidden|checked|selected|disabled|readonly|required|multiple|controls|autoplay|loop|muted|default|reversed)=".*?"/g, '$1')
}
```

**Comment by bitwiseman** [comment]
@cata-code  This library only changes whitespace.  If something is changing `hidden` to `hidden=""` it is not this library.  Sorry.
