### ISSUE TITLE
Numbers should be allowed to contain underscores

### ISSUE THREAD

**Issue by gcxfd** [beautify-web/js-beautify#1836]
how to remove the space add before underline ? 

`const _list = 0b1111_0110;`
-> 

`const _list = 0b1111 _0110`;

break my code

**Comment by bitwiseman** [comment]
@gcxfd 
`0b` indicates a binary number, which cannot contain underscores.  What are you trying to achieve with that code?

**Comment by gcxfd** [comment]
![image](https://user-images.githubusercontent.com/69608605/91837048-36f0b300-ec7e-11ea-9852-7a321fa5502c.png)
see the screen shot , it can contains `_`

**Comment by gcxfd** [comment]
0xFFFF_1234 is ok too

**Comment by bitwiseman** [comment]
Ah, I see. Relatively new feature - numeric separator. 
https://github.com/tc39/proposal-numeric-separator

Someone just needs to add `_` as a valid numeral inside numbers along with a few tests.  Would be a good first issue.

**Comment by mrmonroe** [comment]
I'll be glad to take this.
