### ISSUE TITLE
DO NOT FILE THIS ISSUE AT https://github.com/beautify-web/js-beautify?

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1839]
Why does the issue template say "DO NOT FILE THIS ISSUE AT https://github.com/beautify-web/js-beautify"? I don't understand..

![image](https://user-images.githubusercontent.com/2523987/93692640-52c7d600-fb13-11ea-861f-74d58cc04c61.png)

**Comment by bitwiseman** [comment]
Usage questions should not be filed as issues. That is what the gitter channel is for.
https://github.com/beautify-web/js-beautify/blob/master/.github/ISSUE_TEMPLATE/question-about-usage.md

**Comment by bitwiseman** [comment]
Ah, there was a merge of changes back from beautifier.io
