### ISSUE TITLE
{# Breaks html auto format

### ISSUE THREAD

**Issue by timcluyts** [beautify-web/js-beautify#1847]
Issue Type: Bug

Typing {# causes the html auto format to stop

Steps to Reproduce:

Type some html containing {#
Auto Format
Example:
```html
      <html>
        <div>
     <p>   Sample Text    </p>
  </div>    <div>
      <p>   Typing {# breaks vscode </p>

       <p>     
             This part is not formatted
             </p>
         </div>
</html>
```

Expected:
```html
<html>
<div>
    <p> Sample Text </p>
</div>
<div>
    <p> Typing {# breaks vscode </p>

    <p>
        This part is not formatted
    </p>
</div>
</html>
```

Actual:

```html
<html>
<div>
    <p> Sample Text </p>
</div>
<div>
    <p> Typing {# breaks vscode </p>

       <p>     
             This part is not formatted
             </p>
         </div>
</html>
```

This is relevant for any Thymeleaf templates, which make extensive use of '{#' syntax, as seen [here](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#strings)

**Comment by DubiousDoggo** [comment]
relevant downstream issue for vscode: https://github.com/microsoft/vscode/issues/84606

**Comment by bitwiseman** [comment]
Disable templating. 
#1647
