### ISSUE TITLE
Maybe add a setting?

### ISSUE THREAD

**Issue by Omay-Codes** [beautify-web/js-beautify#1853]
# Description
I want there to be something where you can remove some new lines, such as the ones below.

## Input
The code looked like this before beautification:
```
document.getElementById("menu").style.display = "none";
```

## Current Output
The  code actually looked like this after beautification:
```
document.getElementById("menu")
	.style.display = "none";
```

## Expected Output
The code should have looked like this after beautification:
```
document.getElementById("menu").style.display = "none";
```

# Environment

## Browser User Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

Language Selected:
Beautify JavaScript

## Settings
```json
{
  "indent_size": "1",
  "indent_char": "\t",
  "max_preserve_newlines": "-1",
  "preserve_newlines": false,
  "keep_array_indentation": false,
  "break_chained_methods": true,
  "indent_scripts": "normal",
  "brace_style": "end-expand,preserve-inline",
  "space_before_conditional": false,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": true,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by bitwiseman** [comment]
Try setting `break_chained_methods` to `false`.  Reopen if that does not work.
