### ISSUE TITLE
React Fragment Short Syntax <></> issue

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#1854]
# Description

[React Fragment Short Syntax][1] gets messed up.

The beautified code results in compile errors. 

# Input
```
class Columns extends React.Component {
  render() {
    return (
      <>        
        <td>Hello</td>
        <td>World</td>
      </>    
    );
  }
}
```

# Expected Output

Shouldn't change:

```
class Columns extends React.Component {
  render() {
    return (
      <>        
        <td>Hello</td>
        <td>World</td>
      </>    
    );
  }
}
```

# Actual Output
The  code actually looked like this after beautification:
```
class Columns extends React.Component {
    render() {
        return (
            <>        
        <td>Hello</td> <
            td > World < /td> <
            />    
        );
    }
}
```

# Steps to Reproduce

Copy paste the [the sample code from docs][1] on https://beautifier.io/

## Environment

Tried on https://beautifier.io/

## Settings

Default on https://beautifier.io/ (with jsx)

[1]: https://reactjs.org/docs/fragments.html#short-syntax

**Comment by bitwiseman** [comment]
Need to update the `xml` tokenizer to capture an empty tag. 

https://github.com/beautify-web/js-beautify/blob/97caa308491e1379b226c514f677fa4f278e15d4/js/src/javascript/tokenizer.js#L129

**Comment by JuanFML** [comment]
Hello! I was looking into this issue, could I work on it?
