### ISSUE TITLE
Option 'max_preserve_newlines' not working on beautify_css.js CSS Beautifier

### ISSUE THREAD

**Issue by BibekOli** [beautify-web/js-beautify#1863]
# Description
> This is the default template for bug reports
> The option 'max_preserve_newline' is not working with CSS Beautifier. When the option 'preserve_newlines': true and 'max_preserve_newlines': 2, it is keeping all the newlines instead of 2 only.
> NOTE: 
> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 
> * Check the list of open issues before filing a new issue. 

# Input
The code looked like this before beautification:
```
p {





color: blue;
}
```

# Expected Output
The code should have looked like this after beautification:
```
p {

color: blue;
}
```

# Actual Output
The  code actually looked like this after beautification:
```
p {





color: blue;
}
```

# Steps to Reproduce
Use these options:
{
    'preserve_newlines': true,
    'max_preserve_newlines': 2,
}
It will keep all newlines instead of 2 only.

## Environment
OS: Chrome Browser

## Settings
Example:
```json
{
    'preserve_newlines': true,
    'max_preserve_newlines': 2,
}
```

**Comment by bitwiseman** [comment]
Thanks for reporting!
Would you be up for submitting a PR?

**Comment by JuanFML** [comment]
Hello! I saw this issue and I would like to work on it.
