### ISSUE TITLE
html formatter doesn't support handlebars partial blocks (`#>`)

### ISSUE THREAD

**Issue by Goobles** [beautify-web/js-beautify#1869]
# Description

The handlebars support in the HTML beautifier is incomplete and doesn't account for partial blocks.
(as documented here: https://handlebarsjs.com/guide/partials.html#partial-blocks)

# Input
The code looked like this before beautification:
```
{{#>row}}
    {{#>column}}
        <span>content</span>
    {{/column}}
{{/row}}
```

# Expected Output
The code should have looked like this after beautification:
```
{{#>row}}
    {{#>column}}
        <span>content</span>
    {{/column}}
{{/row}}
```

# Actual Output
The  code actually looked like this after beautification:
```
{{#>row}}
    {{#>column}}
        <span>content</span>
        {{/column}}
        {{/row}}
```

# Steps to Reproduce

## Environment
OS: Windows 10 Pro
VSCode version: 1.52.0

## Settings

```json
{
  "html.format.indentHandlebars": true,
  "html.format.enable": true,
}
```

**Comment by bitwiseman** [comment]
Does this reproduce on https://beautifier.io ? 
This code looks like it handles partials: https://github.com/beautify-web/js-beautify/blob/5bfad82226f98a5f6543fbde96e479e6763fd3cd/js/src/html/beautifier.js#L613-L616 .

**Comment by Goobles** [comment]
Ah it does reproduce, there's a slight nuance, depending on if there's a space between the `>` and the partial name

Without the space:
```
{{#>row}}
  {{#>column}}
    <span>content</span>
    {{/column}}
    {{/row}}
```

With the space it works:
```
{{#> row}}
  {{#> column}}
    <span>content</span>
  {{/column}}
{{/row}}
```

**Comment by Goobles** [comment]
That being said, both with and without spaces show the same wrong behavior in VSCode

Since I read [here](https://github.com/microsoft/vscode/issues/56346#issuecomment-413576989) that vsc uses beautify underneath I posted my issue here. Both with the vscode builtin HTML formatter and using the Beautify extension.

**Comment by bitwiseman** [comment]
@Goobles  
It is likely that the version inside vscode is out of date, so it is probably missing some fixes.  

The space fixing the issue comes from here:
https://github.com/beautify-web/js-beautify/blob/5bfad82226f98a5f6543fbde96e479e6763fd3cd/js/src/html/tokenizer.js#L71

The earlier code segment expects there to be two separate tokens for the start of the block the `{{#>` and the word following.  So, we need some combination of fixes between the two.

**Comment by a-vento** [comment]
I can work on this issue and will update you with any changes!
