### ISSUE TITLE
Cannot force inline elements to format when its removed from unformatted 

### ISSUE THREAD

**Issue by surjithctly** [beautify-web/js-beautify#1885]
# Description

I saw an option called `unformatted ` which will not be formatted. That is cool, but when I remove an item from it, It does not format. I think its just skips the format, but not checking the current line and formats if necessary. See the example below. 

# Input
The code looked like this before beautification:
```
<div><label>title</label><input type="text"><div>
```

# Expected Output
The code should have looked like this after beautification:
```
<div>
    <label>title</label>
    <input type="text">
<div>
```

# Actual Output
The  code actually looked like this after beautification:
```
<div>
<label>title</title><input type="text">
<div>
```

# Steps to Reproduce

## Environment
OS: Node.js, Windows

## Settings

```json
{
  unformatted: ["code", "pre", "em", "strong", "span"],
}
```

**Comment by bitwiseman** [comment]
What settings were you using?

**Comment by surjithctly** [comment]
@bitwiseman I’m using default setting along with the unformatted argument as I shared above.

**Comment by bitwiseman** [comment]
@surjithctly 
I don't see any of the elements from your example in the setting you shared. 

You expected the output to take `<label>label title><input type="text">` and split them to separate lines? 

Also the html you provided is not valid:
```html
<label>label title><input type="text">
<!--              ^ -->
```

**Comment by surjithctly** [comment]
Never mind the code example, it was a typo error. fixed it now. but the actual issue stays.

I want to split those in multiple lines as shown in the expected section.

From what I understand from the docs is when you remove inline items from unformatted it should format as block items thus single line.

Make sense?

**Comment by bitwiseman** [comment]
The docs are incorrect.  `inline` elements are a separate thing .   You can create a list of `inline` elements that doesn't include specific items or even make `inline: []`.  The default list is [here](https://github.com/beautify-web/js-beautify/blob/3862ce30e891e8be48faadcb6923cfaeb35dd1ba/js/src/html/options.js#L53-L62).

However, I strongly suggest you NOT do so. Inline elements are "inline" for a reason - `<label>title</label><input type="text">` will produce different displayed output from `<label>title</label>\n    <input type="text">`.

**Comment by surjithctly** [comment]
Great. using this `beautify(markup, { inline: [] });` outputs what I expected. 

So consider this issue is solved.
