### ISSUE TITLE
GHSL-2020-344: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [beautify-web/js-beautify#1889]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-344) in your project (beautify-web/js-beautify). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-344 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by bitwiseman** [comment]
@anticomputer 
Perhaps your team could integrate with the existing security tab that is already present in the UI.  You email was sent to my junk folder.  Found it now.  The email doesn't specify the regular expression that is the problem, just gives related examples.

**Comment by anticomputer** [comment]
> @anticomputer
> Perhaps your team could integrate with the existing security tab that is already present in the UI. You email was sent to my junk folder. Found it now. The email doesn't specify the regular expression that is the problem, just gives related examples.
> 
> I have no time to work on this for at least then next month, I'm not sure what else I can do about this.

@bitwiseman I think the issue is low-impact in the context of beautify-js. I will send you additional detail in email re: the finding and connect you to the original reporter if required.

Agreed re: ui integration, we're hoping to fit more seamlessly into the existing advisory features of GitHub in the future.

In the interim we recommend you specify a [security policy](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) for your project, which can be a simple 1 liner that specifies how and where you prefer to receive security reports.
