### ISSUE TITLE
IE11 compatibility failure v>1.13.5

### ISSUE THREAD

**Issue by itutto** [beautify-web/js-beautify#1918]
# Description
### Breaking change in the latest patch releases
With the latest patch update if the library is imported, IE11 will throw an error.
v.13.5 still works as expected

# Steps to Reproduce
Import the latest release in your project and open in IE11. IE11 will throw a syntax error on a anonymous function call. 
 _(node modules are typically not babel transpiled)_

## Environment
OS: Windows, IE 11

**Comment by bitwiseman** [comment]
Ah, there was an update to Webpack.  
https://stackoverflow.com/questions/64478671/after-build-via-webpack-5-app-stoped-working-on-internet-explorer-ie11/64494479
