### ISSUE TITLE
Beautifier breaks adds space in underscore seperated number

### ISSUE THREAD

**Issue by Centipede5** [beautify-web/js-beautify#1933]
# Description

when you use the "_" character to break up numbers in JavaScript, the Beautifier breaks adds a space before the _ which causes an error if you try to run it

# Input
The code looked like this before beautification:
```
var x = 100_000
```

# Expected Output
The code should have looked like this after beautification:
```
var x = 100_000
```

# Actual Output
The  code actually looked like this after beautification:
```
var x = 100 _000
```

# Steps to Reproduce

use any broken-up number in the beautifier 

## Environment
OS: Windows (any?)

**Comment by bitwiseman** [comment]
See #1836 and the related PR #1844.  If you have time to finish it that would be a huge help.
