### ISSUE TITLE
js-beautify inserts space in hexadecimal bigint literals

### ISSUE THREAD

**Issue by rigille** [beautify-web/js-beautify#1934]
# Description
The input is parsed as a BigInt, the output is parsed as a Number and an identifier.

# Input
The code looked like this before beautification:

```
0xFFn
```

# Expected Output
The code should have looked like this after beautification:
```
0xFFn
```

# Actual Output
The  code actually looked like this after beautification:
```
0xFF n
```

# Steps to Reproduce
```
$ echo "0xFFn" | js-beautify
```

## Environment
OS: Ubuntu 20.04.2 LTS

## Settings
I'm not sure, but i think it's with the default settings

**Comment by bitwiseman** [comment]
Extend the fix applied in #1844 to include BigInt literals for binary,octal, anc hex. 
@rigille  Would you be willing to submit a PR?

**Comment by rigille** [comment]
sure 🙂
