### ISSUE TITLE
Do not remove whitespace after number

### ISSUE THREAD

**Issue by RaoHai** [beautify-web/js-beautify#1950]
# Description
Whitespace after number have been removed, which will case an `Uncaught SyntaxError: Invalid or unexpected token` error.

# Input
The code looked like this before beautification:
```
1000000000000000100 .toFixed(0)!=="1000000000000000128")
```

# Expected Output
The code should have looked like this after beautification:
```
1000000000000000100 .toFixed(0) !== "1000000000000000128")
```

# Actual Output
The  code actually looked like this after beautification:
```
1000000000000000100.toFixed(0) !== "1000000000000000128")
```

# Steps to Reproduce

## Environment
OS:

**Comment by 1bsilver** [comment]
Hi, I am a beginner.
I would like to work on this issue.
Can you guide me?

**Comment by bitwiseman** [comment]
@1bsilver 
Start by following the instructions in the CONTRIBUTING.md file to get your environment set up.  If you get stuck, we can discuss further on gitter.im .

**Comment by adist98** [comment]
Is this issue up for grabs? Interested in working on it.

**Comment by sahilmore-git** [comment]
Where can I find this code for debugging ??

**Comment by AbhishekSrivas114319** [comment]
Hello, I just went through the folder structure and contributing.MD file. Can you suggest to me where the beautification code is handled for this case, is it in root/js/src/javascript/beautifier.js .
I would like to solve the issue. If you can guide me a bit.

**Comment by Larreth** [comment]
Agree with @bitwiseman

**Comment by bharathks005** [comment]
Hi Team, I'm a full stack web developer, I want to contribute these project. First, I will start debug after the number whitespace remove  issue. I want to know is there any standard format for creating new branch for bug fix?

**Comment by bhaveshvasnani** [comment]
@bitwiseman I do not see much progress on this so far. Also, the PR #1956 has no updates. Could you please let me know if this issue is up for grabs if the previous owner doesn't have plans to work on it? Thanks!

**Comment by bitwiseman** [comment]
@bhaveshvasnani 
Go ahead and work on it. It can't hurt.

**Comment by bhaveshvasnani** [comment]
Thanks!! I'll work on this and also agree that the fix should be in handle_dot() itself.

**Comment by bhaveshvasnani** [comment]
@bitwiseman could you please provide me access to push the fix for review? Thanks!!
