### ISSUE TITLE
feature request: cmd+enter hotkey for mac users

### ISSUE THREAD

**Issue by jimmywarting** [beautify-web/js-beautify#1985]
# Description
On your website you have a little hot key for ctrl+enter to beautify the code 
but for us mac user we hardly use the ctrl for anything...

we use cmd interested. 🙃 

## Environment
OS: Mac

**Comment by bitwiseman** [comment]
PR welcome.

**Comment by mhnaeem** [comment]
@bitwiseman If this issue is not taken I can implement it

**Comment by jimmywarting** [comment]
@mhnaeem i haven't started working on such a PR. so i say go for it! 🙂

**Comment by jimmywarting** [comment]
Gosh, i revisit jsbutifier from times to times to debug others code, it felt so natural to just simply press cmd + enter right away without even reading anything, i feel just right at home. and the dark mode is just suprem! 

Want to thank you @bitwiseman, @mhnaeem and @adityakush24 for the new and improved UI ❤️
