### ISSUE TITLE
SVG doesn't get line wrapped

### ISSUE THREAD

**Issue by floreapaun** [beautify-web/js-beautify#1986]
# Description
Line wrapping does not work for HTML containing SVGs. 

# Input
The code looked like this before beautification:
```
<clipPath id="GlassClip">
   <path d="M380.857,346.164c-1.247,4.651-4.668,8.421-9.196,10.06c-9.332,3.377-26.2,7.817-42.301,3.5
       s-28.485-16.599-34.877-24.192c-3.101-3.684-4.177-8.66-2.93-13.311l7.453-27.798c0.756-2.82,3.181-4.868,6.088-5.13
      c6.755-0.61,20.546-0.608,41.785,5.087s33.181,12.591,38.725,16.498c2.387,1.682,3.461,4.668,2.705,7.488L380.857,346.164z" />
</clipPath>
```

# Actual Output
```
<clipPath id="GlassClip">
  <path
    d="M380.857,346.164c-1.247,4.651-4.668,8.421-9.196,10.06c-9.332,3.377-26.2,7.817-42.301,3.5
       s-28.485-16.599-34.877-24.192c-3.101-3.684-4.177-8.66-2.93-13.311l7.453-27.798c0.756-2.82,3.181-4.868,6.088-5.13
      c6.755-0.61,20.546-0.608,41.785,5.087s33.181,12.591,38.725,16.498c2.387,1.682,3.461,4.668,2.705,7.488L380.857,346.164z" />
```
</clipPath>

## Settings
```json
{
  "indent_size": "2",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "normal",
  "brace_style": "collapse",
  "space_before_conditional": true,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "40",
  "indent_inner_html": false,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by bitwiseman** [comment]
What is the expected output you'd like to see?

**Comment by Meesujit** [comment]
Ok no problem, I'll look for the solution, if there any help that I need, reach out to you.

**Comment by Meesujit** [comment]
everything looks fine, I put svg in beautifier, and it give the proper output as expected. maybe @floreapaun have some issue in his system. maybe it could be something else. `<clipPath id="GlassClip">
    <path d="M380.857,346.164c-1.247,4.651-4.668,8.421-9.196,10.06c-9.332,3.377-26.2,7.817-42.301,3.5
       s-28.485-16.599-34.877-24.192c-3.101-3.684-4.177-8.66-2.93-13.311l7.453-27.798c0.756-2.82,3.181-4.868,6.088-5.13
      c6.755-0.61,20.546-0.608,41.785,5.087s33.181,12.591,38.725,16.498c2.387,1.682,3.461,4.668,2.705,7.488L380.857,346.164z" />
</clipPath>` here is the output which was as expected as in input. https://beautifier.io/ put the svg in beautifier select the html option then everything works.

**Comment by bitwiseman** [comment]
It doesn't look like the original filer of this issue clarified their intent.  Closing.
