### ISSUE TITLE
Fails to recognize Handlebars block with whitespace control, e.g. {{~#if true ~}}

### ISSUE THREAD

**Issue by andersk** [beautify-web/js-beautify#1988]
# Description

Handlebars supports [whitespace control](https://handlebarsjs.com/guide/expressions.html#whitespace-control) by putting `~` on one or both sides of any double-brace-enclosed statement. But js-beautify fails to recognize a statement with whitespace control, resulting in incorrect indentation.

# Input
The code looked like this before beautification:
```handlebars
{{#if true}}<div><div>
{{~#if true ~}}<p>true</p>{{/if}}
</div></div>{{/if}}
```

# Expected Output
The code should have looked like this after beautification:
```handlebars
{{#if true}}
    <div>
        <div>
            {{~#if true ~}}
                <p>true</p>
            {{/if}}
        </div>
    </div>
{{/if}}
```

# Actual Output
The  code actually looked like this after beautification:
```handlebars
{{#if true}}
    <div>
        <div>
            {{~#if true ~}}
            <p>true</p>
{{/if}}
</div>
</div>{{/if}}
```

# Steps to Reproduce
`html-beautify -H test.hbs`

## Environment
OS: Linux

## Settings
None

**Comment by zalsaedy** [comment]
Hello! I saw this issue and would like to work on it. Are there any steps I need to take before doing so, besides what was stated in CONTRIBUTING.md?
