### ISSUE TITLE
HTML formatter breaks layout by introducing newlines

### ISSUE THREAD

**Issue by lgarron** [beautify-web/js-beautify#1989]
Moved here from https://github.com/microsoft/vscode/issues/144042

# Description

The HTML formatter breaks the layout of the page.

# Input
The code looked like this before beautification:
```html
<span>
  <span>
    <span>1:02</span
    ><time-dot>.</time-dot
    ><time-decimals>27</time-decimals>
  </span>
</span>
```

# Expected Output
The code should have looked like this after beautification:
```html
<!-- no change? -->
<span>
  <span>
    <span>1:02</span
    ><time-dot>.</time-dot
    ><time-decimals>27</time-decimals>
  </span>
</span>
```

# Actual Output
The  code actually looked like this after beautification:

```html
<span>
  <span>
    <span>1:02</span>
    <time-dot>.</time-dot>
    <time-decimals>27</time-decimals>
  </span>
</span>
```

This introduces newlines (and spaces) before and after the `<time-dot>` element, which adds visual space between the elements on the page that was not there before:

<img width="241" alt="Screen Shot 2022-02-27 at 14 40 15" src="https://user-images.githubusercontent.com/248078/155902938-63ae11ca-0ae9-45b9-9f37-815d27bd4797.png">

# Steps to Reproduce

Paste into https://beautifier.io/ or format in VSCode.

## Environment

OS: N/A

## Settings

Default?

**Comment by lgarron** [comment]
FYI: The bug template says:

> * Do not include screenshots! This library is a text processor, we need text inputs and outputs for debugging and fixing issues. 

I assume this means "do not submit screenshots without submitting associated text examples", not "screenshots are forbidden, even if they illustrate the text examples". Apologies if that's not the case.

**Comment by bitwiseman** [comment]
@lgarron 

I don't understand the problem with the actual output. 
Why is the expected output better/correct?  
Why do you consider this to be breaking layout? Functionally, I think those two result in the same thing being displayed by the browser.

**Comment by lgarron** [comment]
> It appears that you want `<time-dot>` and `<time-decimals>` to be treated as "inline" elements.

Correct, that is how they are treated by default.

> Question: `<time-dot>` and `<time-decimals>` are not valid html elements. Where are you getting them?

Any tag with a hyphen is a valid [custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) name. They can be defined in JS, but they can also be used in the DOM (and styled) before being defined.

Would it be feasible to conservatively treat every hyphenated tag as inline?

**Comment by lgarron** [comment]
*poke*

This is still really frustrating. It completely breaks the layout of some pages in VSCode out of the box, which requires a moment of "what happened?" followed by turning off HTML formatting completely (therefore missing out on the benefits). 🥺

**Comment by EktaEngineer** [comment]
@lgarron can you  assign this issue to me

**Comment by lgarron** [comment]
> @lgarron can you assign this issue to me

That would be up to @bitwiseman.

In any case, I would still be glad to see this addressed.

**Comment by lgarron** [comment]
This might be a potential solution: https://github.com/beautify-web/js-beautify/commit/4885d5d9d4f0d1af485d8a13653a62d94cb6f959

```diff
commit 4885d5d9d4f0d1af485d8a13653a62d94cb6f959
Author: Lucas Garron <code@garron.net>
Date:   Wed Sep 21 11:06:57 2022 -0700

    Treat all custom elements as inline elements.
    
    Addresses https://github.com/beautify-web/js-beautify/issues/1989

diff --git a/js/src/html/beautifier.js b/js/src/html/beautifier.js
index 942d8318..87c84ad0 100644
--- a/js/src/html/beautifier.js
+++ b/js/src/html/beautifier.js
@@ -658,7 +658,10 @@ Beautifier.prototype._get_tag_open_token = function(raw_token) { //function to g
 
   parser_token.is_unformatted = !parser_token.tag_complete && in_array(parser_token.tag_check, this._options.unformatted);
   parser_token.is_content_unformatted = !parser_token.is_empty_element && in_array(parser_token.tag_check, this._options.content_unformatted);
-  parser_token.is_inline_element = in_array(parser_token.tag_name, this._options.inline) || parser_token.tag_start_char === '{';
+  parser_token.is_inline_element =
+			in_array(parser_token.tag_name, this._options.inline) ||
+			parser_token.tag_name.includes("-") ||
+			parser_token.tag_start_char === "{";
 
   return parser_token;
 };
```

**Comment by EktaEngineer** [comment]
@bitwiseman can you assign this issue to me
