### ISSUE TITLE
[Bug] Logical assignments in JS are incorrectly beautified 

### ISSUE THREAD

**Issue by mhnaeem** [beautify-web/js-beautify#1991]
# Description
The tool incorrectly beautifies logical AND, OR and NULL assignments.

# Links:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment

# Input
The code looked like this before beautification:
```
x&&=y
x||=y
x??=y
```

# Expected Output
The code should have looked like this after beautification:
```
x &&= y
x ||= y
x ??= y
```

# Actual Output
The  code actually looked like this after beautification:
```
x && = y
x || = y
x ?? = y
```

# Steps to Reproduce

1. Opened https://beautifier.io/
2. Entered the input text
3. Clicked "Beautify Code" button

I am new to the repo but would be happy to work on this issue

**Comment by mhnaeem** [comment]
@bitwiseman What is the process for closing issues in the project? I noticed that we released some issues but they weren't closed like this one. In addition, what is the update process for the website (https://beautifier.io/) I noticed that this issue still doesn't work on the site.

**Comment by bitwiseman** [comment]
@mhnaeem 
Thanks for calling attention to this.  It looks like github pages publishing action is failing in beautifier/beautifier.io project: https://github.com/beautifier/beautifier.io/actions/runs/2059622873

I'll take a look at it some time this week.
