### ISSUE TITLE
Formatting of form element

### ISSUE THREAD

**Issue by mk202020212022** [beautify-web/js-beautify#1998]
# Description

The `<form>` HTML element doesn't format correctly.
## Input
The code looked like this before beautification:
```
<form method="get"><label>Name:<input name="submitted-name" autocomplete="name"></label><button>Save</button></form>
```

## Current Output
The  code actually looked like this after beautification:
```
<form method="get"><label>Name:<input name="submitted-name" autocomplete="name"></label><button>Save</button></form>
```

## Expected Output
The code should have looked like this after beautification:
```
<form method="get">
  <label>Name: <input name="submitted-name" autocomplete="name">
  </label>
  <button>Save</button>
</form>
```

# Environment

## Browser User Agent:

Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36

Language Selected:
Beautify HTML

## Settings
```json
{
  "indent_size": "2",
  "indent_char": " ",
  "max_preserve_newlines": "5",
  "preserve_newlines": true,
  "keep_array_indentation": false,
  "break_chained_methods": false,
  "indent_scripts": "keep",
  "brace_style": "collapse",
  "space_before_conditional": false,
  "unescape_strings": false,
  "jslint_happy": false,
  "end_with_newline": false,
  "wrap_line_length": "0",
  "indent_inner_html": true,
  "comma_first": false,
  "e4x": false,
  "indent_empty_lines": false
}
```

**Comment by a-vento** [comment]
Hi! I would like to work on this issue. Are there any steps I need to take before doing so, besides what was stated in CONTRIBUTING.md?

**Comment by bitwiseman** [comment]
Note that these two html snippets produce different rendered output in the browser: 
## A
```
<form method="get"><label>Name:<input name="submitted-name" autocomplete="name"></label><button>Save</button></form>
```

## B
```
<form method="get">
  <label>Name: <input name="submitted-name" autocomplete="name">
  </label>
  <button>Save</button>
</form>
```

Approximating the difference in text form it looks like this:
```
A:
Name:[         ][Save]

B:
Name: [         ] [Save]
```

On this small scale those spaces don't seem like a big deal, but for real world scenarios they could result in radically different formatting. 


The current policy of this project is that if the rendered html looks different after the beautifier runs, that is a bug.  It seems like something that most designers and engineers do not want their code formatter to do.  Am I missing something?

**Comment by mk202020212022** [comment]
Therefore, a possible answer would be to preprocess html with a regular expression, e.g. `s/\>\s*\</\>\n\</g`, and after run beautify. It would be nice if documentation had a notice about whitespaces.

**Comment by bitwiseman** [comment]
> It would be nice if documentation had a notice about whitespaces.
I don't know what you mean. 

To be absolutely clear, this HTML: 

```
<form method="get"><label>Name:</label> <input name="submitted-name" autocomplete="name"> <button>Save</button> </form>
```

is **functionally** the same as this HTML: 

```
<form method="get">
  <label>Name:</label>
  <input name="submitted-name" autocomplete="name">
  <button>Save</button>
</form>
```

but both of the above are **functionally different** from this HTML: 

```
<form method="get"> <label>Name:</label><input name="submitted-name" autocomplete="name"><button>Save</button> </form>
```

> So you suggest that the second output is the correct solution.

I am not saying that any of these are correct.  That is a separate discussion.  What I'm saying is that the output you want the beautifier to produce is **functionally different** from the the input you have provided. That is a fact that you can verify using your browser or by reading the HTML spec.

It is the policy of this project that a "code beautifier" should **never** change the functional behavior of the code. If it does, that is a bug.  

> Therefore, a possible answer would be to preprocess html with a regular expression, e.g. `s/\>\s*\</\>\n\</g`, and after run beautify. It would be nice if documentation had a notice about whitespaces.

The HTML spec provides documentation about whitespace behavior between various elements. You are welcome to fork this project and do whatever regular expression processing you like. I'm trying to warn you that if you do, you will end up changing the functionality of your web pages in ways may not be clear to you right now.  Perhaps that is fine with you but that is out of scope for this project.  Sorry.
