### ISSUE TITLE
Version 1.14.2 from PYPI has worse 'import' lines

### ISSUE THREAD

**Issue by Alexey-T** [beautify-web/js-beautify#2014]
I used version 1.0.0 which had simple imports:
```
import ...
import ....
```

Now I got version 1.4.2 from PYPI and see it has changed imports like this:
```
_main = __import__("cssbeautifier", globals(), locals(), ["_main"])._main
```
This now does not work if I put the module to CudaText plugin:
```
Traceback (most recent call last):
......
  File "/home/user/.config/cudatext/py/cuda_fmt_css_format/cssbeautifier/__init__.py", line 30, in default_options
    _main = __import__("cssbeautifier", globals(), locals(), ["_main"])._main
ModuleNotFoundError: No module named 'cssbeautifier'
ERROR: Exception in CudaText for format: ModuleNotFoundError: No module named 'cssbeautifier'
```

Maybe you can change 'import' lines to usual ones? like this
```
from . import .....
from . import ...
```

Plugin code -- https://github.com/CudaText-addons/cuda_fmt_css_format

**Comment by bitwiseman** [comment]
I assume you mean `v1.14.2`.  `v1.4.2` is a long time ago. 

Sorry for the inconvenience. PR #1830 (which fixed #1830) is where the change to the complex `import` statements was introduced.  It seemed to be required, but I'm not a Python expert.  If there is a better way to do this, I'm happy to look at PRs. 

You're trying to use this inside https://github.com/CudaText-addons/cuda_fmt_css_format ?  
Are you doing `pip install cssbeautifier` and then using the installed package?  
Or are you trying to do something else, like copying the code into that directory?

**Comment by Alexey-T** [comment]
I am trying to copy module folder to plugin directory. "complex imports" don't work there.

**Comment by Alexey-T** [comment]
I am suggesting to try it on your end: change imports to __relative__ imports.
```
from .nnnn import mmmmm
from . import nnn
```
this way is will work.

**Comment by bitwiseman** [comment]
@Alexey-T 
Note: `cssbeautifier` depends on `jsbeautifier`, so you might need to copy the contents of the `python` directory. That might fix the problem you're seeing. 

This is change that will benefit you by simplifying updating your local copy of the project.  As I said, you're welcome to try fixing this and I'll be happy to look a PR. I'm sorry I can't do more, but I personally don't time to work this problem.
