### ISSUE TITLE
Autosave in VS Code scss breaks tailwindjs parsing

### ISSUE THREAD

**Issue by DibyodyutiMondal** [beautify-web/js-beautify#2049]
# Description
I use tailwind inside of vs code. Recently, every time I save scss files, it inserts spaces after every comma and a space after the first colon it encounters, which breaks tailwindcss. I had opened an issue in the VS Code repo ([#147548](https://github.com/microsoft/vscode/issues/147548)), and they asked me to report this to beautify instead.

# Input
The code looked like this before beautification:
```
 @apply grid gap-6 mt-6 
    grid-cols-[repeat(1,minmax(12rem,1fr))] 
    sm:grid-cols-[repeat(2,minmax(12rem,1fr))] 
    lg:grid-cols-[repeat(3,minmax(12rem,1fr))];
```

# Expected Output
The code should have looked like this after beautification:
```
@apply grid gap-6 mt-6 grid-cols-[repeat(1,minmax(12rem,1fr))] sm:grid-cols-[repeat(2,minmax(12rem,1fr))] lg:grid-cols-[repeat(3,minmax(12rem,1fr))];
```

# Actual Output
The  code actually looked like this after beautification:
```
                                                                    v space inserted after first colon                                v space inserted after all commas
@apply grid gap-6 mt-6 grid-cols-[repeat(1, minmax(12rem, 1fr))] sm: grid-cols-[repeat(2, minmax(12rem, 1fr))] lg:grid-cols-[repeat(3, minmax(12rem, 1fr))];
```

# Steps to Reproduce
Create an scss file

## Environment
OS: Ubuntu 20.04 (Windows Subsystem for Linux)

## Settings
I am not aware of the setting VS Code uses by default.

**Comment by bitwiseman** [comment]
#2012

**Comment by focussing** [comment]
Is there already a fix for this? I use volar in vue project and every 'format document' I have to do a lot of repair work....

**Comment by bitwiseman** [comment]
No, this is a duplicate of #2012
