### ISSUE TITLE
Build output

### ISSUE THREAD

**Issue by Dessader** [beautify-web/js-beautify#2055]
# Description
Perhaps my problem is not quite typical and I have gone to the wrong section. I have no problem with the formatting of the code, but I have a problem with the placement of the code after processing.

In my packages.json there is the following script:

```json
"scripts": {
    "format:html": "js-beautify --type html --file ./build/*.html --output ./build/*.html --config .jsbeautifyrc"
},
```

The problem is the following, when there are several html pages in the build directory, everything works fine, but if there is only one page, the ```--unindent_chained_methods``` file is created in the root of the project, which contains the final output, and there are no changes in the build directory.

See example: [repo](https://github.com/Dessader/js-beautify-issue)

## Environment
OS: macOS Monterey 12.3.1
Node: 16.14.0

## Settings
```json
{
  "indent_size": 2,
  "inline": [],
  "indent-inner-html": true
}
```

**Comment by Kir-Antipov** [comment]
The issue does not seem to be reproducible on Windows.
