### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jimmywarting** [beautify-web/js-beautify#2057]
<p align="center">
  <img src="https://media2.giphy.com/media/irOE2ho4vMdEqsCdly/giphy.gif?cid=790b7611867349783b897bf39b1c51f1fce70e12a0358dfb&rid=giphy.gif&ct=g">
</p>

**Comment by bitwiseman** [comment]
PRs welcome.

**Comment by ilancohen** [comment]
The idea is to implement a "dark mode" version of the website in /web, changing with the user's OS settings?
If so, I can give it a shot.

**Comment by jimmywarting** [comment]
yes, go ahead 👍

**Comment by ilancohen** [comment]
@jimmywarting can I add a lightweight CSS library like [Bulma](https://bulma.io/) while I'm at it, to make the page look better?

**Comment by bitwiseman** [comment]
@ilancohen 
That would be a bigger change. We've tried to maintain backward compatibility as far as possible.  I support the idea of making the website look better but will balance that against backwards compatibility concerns. 

Please make a new issue for what you want to do and we can discuss it there.

**Comment by sidtohan** [comment]
Can I work on this feature?

**Comment by bitwiseman** [comment]
I think there's already a PR... Take a look and comment on it.

**Comment by GAURAV1-ui** [comment]
Can @ilancohen I solve this issue?

**Comment by ilancohen** [comment]
Be my guest.
