### ISSUE TITLE
Erroneous output with upcoming Records syntax

### ISSUE THREAD

**Issue by nchevobbe** [beautify-web/js-beautify#2062]
# Description

Records are a new primitives in Javascript, and they are currently being implemented in Firefox (See https://bugzilla.mozilla.org/show_bug.cgi?id=1658309, https://bugzilla.mozilla.org/show_bug.cgi?id=1774360 and https://github.com/tc39/proposal-record-tuple)

Records are instantiated like objects, but with a hash before the curly bracket, e.g. `#{ hello: "world" }`

# Input
The code looked like this before beautification:
```js
#{ hello: "world" }
```

# Expected Output
The code should have looked like this after beautification:
```js
#{ 
  hello: "world"
}
```

# Actual Output
The  code actually looked like this after beautification:
```js
# { 
  hello: "world"
}
```

Notice the space between `#` and `{`.
If the output would be evaluated, it would result in a `SyntaxError`

# Steps to Reproduce

## Environment
OS: OSX

## Settings

Default settings, I ran `echo "#{hello: 'world'}" | npx js-beautify`

---

Let me know if I can be of any help

**Comment by cwthedev** [comment]
Just submitted a pull request for this (i apologize for editing the PR template)

**Comment by antoniusanggito** [comment]
Hello, is this issue still open for contribution?

**Comment by bitwiseman** [comment]
@antoniusanggito 
Please help with the existing PR.

**Comment by antoniusanggito** [comment]
I'm creating a new pull request continuing from the previous PR by @cwthedev because I have no permission to push into his actual branch. You can close his previous PR, I'm sure to finish my PR in several days. ^^
