### ISSUE TITLE
New Layout JSON max width limit to 75-80%?

### ISSUE THREAD

**Issue by ArndBrugman** [beautify-web/js-beautify#2069]
# Description
I am a big fan and often use this beautifier online and see the new layout which is a great improvement. I would like to opt for a small modification for the layout and that is to maximize the left full JSON pane to max around 75%to80% so in all cases the interface on the right remains visible.

Thanks for your time and effort.

## Environment
OS: Chrome, Windows 11x64

**Comment by bitwiseman** [comment]
PR welcome. You might limit it, but also keep full width on mobile. Please include pictures in your PR.

**Comment by mhnaeem** [comment]
Possibly related to #2071
