### ISSUE TITLE
new layout breaks everything on long lines

### ISSUE THREAD

**Issue by Owyn** [beautify-web/js-beautify#2071]
How author imagined it would be:
![image](https://user-images.githubusercontent.com/1309656/175617669-7ee1eb94-2a6c-4bef-b00b-c3a97cdd35db.png)

How it actually is when used:
![image](https://user-images.githubusercontent.com/1309656/175617725-09467f22-7c3f-4232-959f-1f5eeee3668e.png)

**Comment by bitwiseman** [comment]
Strange. I actually see the top image. What browser are you running?

**Comment by Owyn** [comment]
Firefox stable (101)

Have you tried inputting a long string?

**Comment by SimaDovakin** [comment]
What about  temporary adding `min-width` to block with code?

**Comment by SimaDovakin** [comment]
It's can be a temporary solution.

**Comment by bitwiseman** [comment]
PRs welcome.

**Comment by PineappleRind** [comment]
So this happens for any string that's longer than the input area

**Comment by plotpoi** [comment]
It will be reproduced in chrome. It's hard to press the button.
