### ISSUE TITLE
How to get the new cursor position after beautify

### ISSUE THREAD

**Issue by wanls4583** [beautify-web/js-beautify#2075]
I am now developing an editor. I want to know how to record the position of the cursor so that I can get the new cursor position after beautify.

**Comment by bitwiseman** [comment]
The beautifier doesn't have this functionality.  Adding this information would require some pretty deep changes, but feel free to file an issue (or even a PR if you want to do the work).

**Comment by sabbaticaldev** [comment]
hey @wanls4583 did you figure out a solution? I'm starting to work on it, would be great to know about what you find.
