### ISSUE TITLE
JSON Array formatting issue

### ISSUE THREAD

**Issue by petermarks12** [beautify-web/js-beautify#2082]
I have tried almost all possible settings to get desired output but unfortunately failed at it.  I will be very thankful if someone can point me in right direction. I am getting same output as my input.

JSON
```
{
	"Movies": ["item1", "item2", "item3"]
}
```

Expected Output
```
{
  "Movies": [
    "item1",
    "item2",
    "item3"
  ]
}
```

**Comment by santhos-13** [comment]
you just need to format the file
