### ISSUE TITLE
Globs no longer work on Windows in 1.14.5

### ISSUE THREAD

**Issue by HitkoDev** [beautify-web/js-beautify#2093]
# Description
Glob 8, introduced in `1.14.5`, now treats backslashes (`\`) in input as escape characters (https://github.com/isaacs/node-glob/blob/main/changelog.md#80). Nopt on Windows expands paths passed as arguments to contain backslashes, so they no longer get matched by glob.

**Comment by HitkoDev** [comment]
@bitwiseman https://github.com/beautify-web/js-beautify/commit/e7c9dcb7f67b7494d29d8a62b17c362516f9c3cd

**Comment by bitwiseman** [comment]
@HitkoDev 
A PR to fix this would be great. This made it in because the Windows CI builds were failing for other reasons.

**Comment by bitwiseman** [comment]
@HitkoDev 
Thanks!  Releasing the new version now.
