### ISSUE TITLE
[Question] Function signature formatting

### ISSUE THREAD

**Issue by hyunsooda** [beautify-web/js-beautify#2119]
Given text,
```
function
foo
()
{
}
```
outputs is as follows
```
function 
foo () {}
```

Desired output is:
```
function foo() {}
```

I iterated all the currently supported options but the desired option seems not provided yet. Is there a consideration for function signature formatting? 

Thanks.

**Comment by bitwiseman** [comment]
For the above input the output I get is 
```
function 
foo() {}
```

There is a `space-after-named-function` option which is off by default. Please try you input on https://beautifier.io and see what happens.
