### ISSUE TITLE
How can I customize css formatting rules in html file (<style> tag)?

### ISSUE THREAD

**Issue by vincentzchao** [beautify-web/js-beautify#2123]
As the title
How can I customize css formatting rules in html file (<style> tag)?

```html
  <style>
    body {
      max-width: 800px;
      margin: 0 auto;
    }

    p,
    li,
    dd,
    dt,
    address {
      line-height: 1.5;
    }
  </style>
```

**Comment by bitwiseman** [comment]
See "Setting inheritance and Language-specific overrides" in the README.md.

**Comment by vincentzchao** [comment]
Thanks

**Comment by vincentzchao** [comment]
> See "Setting inheritance and Language-specific overrides" in the README.md.

Thanks
