### ISSUE TITLE
Wrong indent

### ISSUE THREAD

**Issue by WNinja** [beautify-web/js-beautify#2124]
# Description
when using function "each" in block

# Input
The code looked like this before beautification:
```
#Parent {
	each(range(10),{
	});

	#Others {
		
	}
}
```

# Expected Output
The code should have looked like this after beautification:
```
#Parent {
	each(range(10),{
	});

	#Others {
		
	}
}
```

# Actual Output
The  code actually looked like this after beautification:
```
#Parent {
	each(range(10),{
	});

#Others {
	
}
}
```

# Steps to Reproduce

## Environment
OS:

## Settings
all default

**Comment by bitwiseman** [comment]
@WNinja What language is this?  CSS? SCSS?

**Comment by bitwiseman** [comment]
No response.  Closing.
