### ISSUE TITLE
add wrong space in attribute when formating html

### ISSUE THREAD

**Issue by kunhualqk** [beautify-web/js-beautify#2126]
# Input
The code looked like this before beautification:
```
<a to="'/playground/video-manage?contentPlanId='"/>
```

# Expected Output
The code should have looked like this after beautification:
```
<a to="'/playground/video-manage?contentPlanId='"/>
```

# Actual Output
The  code actually looked like this after beautification:
```
<a to="' /playground/video-manage?contentPlanId='"/>
```

# Steps to Reproduce

## Environment
OS:All

## Settings
with any Setting

**Comment by amanakhtar78** [comment]
Hay there, I am new to open source, can you please mentor me and assign me some new basic issue which I can solve and give back to this open source community.

**Comment by xNOVA2** [comment]
Hello can you assign me this task? And elaborate more and provide SS

**Comment by bitwiseman** [comment]
It looks like this doesn't repro in the current version.

**Comment by xNOVA2** [comment]
yeah its closed, I just saw the tag my bad

**Comment by bitwiseman** [comment]
@xNOVA2 No problem, please look at one of the other "good first issue` items.
