### ISSUE TITLE
Ability to Back to old UI, new is slower

### ISSUE THREAD

**Issue by Kevoting** [beautify-web/js-beautify#2129]
The old UI worked better, I usually use big javascript files, so I copied and pasted and it didn't freeze like this new UI (it's several months old), I don't know if it's because it processes the syntax and the colors, but it takes about a minute to paste the code ( page totally frozes) in the code input.
The old UI just worked better!

You can reproduce the lag by pasting a long minified javascript file

**Comment by bitwiseman** [comment]
You can disable the rich editor.

**Comment by mhnaeem** [comment]
@Kevoting Try this link out https://beautifier.io/?without-codemirror it works better for me when pasting large pieces of code.
