### ISSUE TITLE
[Website] Dark mode doesn't work on the “without-codemirror” page

### ISSUE THREAD

**Issue by przemo20** [beautify-web/js-beautify#2133]
As the title says — if you visit https://beautifier.io/?without-codemirror (or go to the main page and click on the “Use a simple textarea for code input?” link), the “Enable Dark Mode” toggle doesn't do anything – the page is still in the “light” mode.

Sorry if that's not the right place to report this kind of issue.

**Comment by shindodkar** [comment]
I made PR on this project. please let me knew it does work correctly or not. #2138
