### ISSUE TITLE
2 same file, different result

### ISSUE THREAD

**Issue by wjx0912** [beautify-web/js-beautify#2136]
hello, i have 2 big  jasvascript file (more then 130k lines), and they have only a little difference. 
after i format with default param:
js-beautify  1.js > 1_out.js
js-beautify  2.js > 2_out.js

the result screenshot (it's should same source, but in beyond compare, it's different because style problem )
![s](https://user-images.githubusercontent.com/5556482/221728122-66c46cd0-f22b-4dbe-bce6-487accd0f483.png)

**Comment by bitwiseman** [comment]
Ah, 1.js has no newlines in it, 2.js does have newlines.  By default, the beautifier tries to preserve newlines that are present in the input file.  

If you want the files to look the same you'll want to set `"preserve_newlines": false`.
