### ISSUE TITLE
Optional chaining operator with array broken

### ISSUE THREAD

**Issue by ymittal** [beautify-web/js-beautify#2139]
# Description
It looks like the optional chaining operator with arrays is broken. I'm using [HTML-CSS-JS Prettify](https://packagecontrol.io/packages/HTML-CSS-JS%20Prettify) on Sublime.

# Input
The code looked like this before beautification:
```
const walletNode = document.getElementsByClassName('fEEsaa')?.[0];
```

# Expected Output
The code should have looked like this after beautification:
```
const walletNode = document.getElementsByClassName('fEEsaa')?.[0];
```

# Actual Output
The  code actually looked like this after beautification:
```
const walletNode = document.getElementsByClassName('fEEsaa') ? . [0];
```

## Environment
OS: macOS 13.2

## Settings
All defaults except with `"indent_size": 2`

**Comment by bitwiseman** [comment]
Doesn't reproduce on https://beautifier.io/ . That plugin for sublime is using an outdated version of this library.
