### ISSUE TITLE
Re-enable python generated tests

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#2152]
(edited) 
Thanks @havardAasen for #2156 fixing the python js tests.  I've re-enabled them in #2158 .  CSS tests remain broken. 

Due to missing `__init__.py` files the generated test for the python css  beautifier have not been running for some time.

Add the following `__init__.py` file:

* `python/cssbeautifier/tests/generated/__init__.py`

Once the needed `__init__.py` file is added I get test failures.  Need to fix the failures as well.

**Comment by Ashhar-24** [comment]
Hey @bitwiseman , I would love to work on this issue.
Can you please guide me what code should I add into `__init__.py` file.

Need you cooperation as I'm a beginner to Open Source contributions. :)
Thanks

**Comment by bitwiseman** [comment]
That was fixed.  Sorry. Try another PR!
