### ISSUE TITLE
Update editorconfig package

### ISSUE THREAD

**Issue by k725** [beautify-web/js-beautify#2160]
The editorconfig package that js-beautify depends [^1] on is too old and contains a vulnerable package (semver). [^2][^3]
I hope you will consider updating the editorconfig package.

At least the latest version of the editorconfig package [^4] does not contain the vulnerable semver package.

[^1]: https://github.com/beautify-web/js-beautify/blob/main/package.json#L53
[^2]: https://security.snyk.io/package/npm/semver
[^3]: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
[^4]: https://github.com/editorconfig/editorconfig-core-js/blob/main/package.json#L46

**Comment by bitwiseman** [comment]
#2161 Fixes.

**Comment by curtispd** [comment]
Could we get a release for this please so that we can resolve the underlying vulnerability?

**Comment by curtispd** [comment]
@bitwiseman would it be possible to create a release with this change ?  We have strict compliance timelines to remediate CVEs in our apps and this would really help us out

**Comment by bitwiseman** [comment]
@curtispd  I'll get to it in the next few days.
