### ISSUE TITLE
Java port

### ISSUE THREAD

**Issue by karlvr** [beautify-web/js-beautify#2162]
# Description

I have created a Java port of this library. Currently only the `.js` formatter, but my intention is to do the `.css` and `.html` as well. My approach was to do a line-by-line port as much as possible, so in theory it will be easy to keep it up to date with changes to the official version. Currently I've kept most of the function and variable naming in the JavaScript style as well, to facilitate comparisons, but maybe that can change to be a little more Java-friendly!

I've also ported the generated tests, with a Java-specific template, and all of the tests are passing.

Are you interested in integrating a Java version into this repository, like the Python version is?

I haven't published any Maven packages yet. I've currently set the `groupId` as `io.beautifier`, with the thought that maybe it would become an official version! I'll change that if you're not keen to officialise it.

https://github.com/karlvr/js-beautify-java

**Comment by bitwiseman** [comment]
@karlvr 
Nicely done! 

I'm not sure that adding another port to this project is a good idea.  The requirement to port changes to two implementation languages already scares away a lot of contributors.  Adding another implementation would add even more overhead.  What do you see as the advantage of integrating this?  Are you interested in continuing to contribute to the project?

**Comment by karlvr** [comment]
@bitwiseman I'm happy to maintain it separately... I use it in my app, Charles, so I have an ongoing interest in maintaining it, with luck!

It would be great if people who wanted such a thing found it. Does the team have any interest in having it under the beautify-web organisation and using the `io.beautifier` namespace? It's a bit more legitimate than on my personal Github.

**Comment by bitwiseman** [comment]
> It would be great if people who wanted such a thing found it. Does the team have any interest in having it under the `beautify-web` organisation and using the `io.beautifier` namespace? It's a bit more legitimate than on my personal Github.

Hm, that seems reasonable.  I think I'd want to use the `beautifier` org rather than the `beautify-web` org.

**Comment by karlvr** [comment]
@bitwiseman that sounds great. I am hopeful tha maintaining parity won't be too tricky... as it's mostly a line-by-line port I'm _hoping_ that applying changes commit by commit won't be too hard. But we'll see!

**Comment by karlvr** [comment]
@bitwiseman I'm keen to tie this up and to publish a maven package... starting with the GitHub repository, can I transfer it to the beautifier org?

**Comment by bitwiseman** [comment]
@karlvr 
I've invited you the the `beautifier` org as a member.  See if you can transfer ownership of your repo to the org. If not, I'll upgrade you permissions.

**Comment by karlvr** [comment]
@bitwiseman thank you, I have successfully transferred it. Now I'll get to work on a Maven release. Could you please give me access to the settings on that repo so I can add secrets for the GitHub actions?

**Comment by bitwiseman** [comment]
@karlvr  I've set you as admin for that repo. I'm going to close this now and we can continue in issue in that repo. Yay!

**Comment by karlvr** [comment]
@bitwiseman picking this up again, I have just synchronised the Java code with the latest changes here. A 20 minute job, so I'm pretty chuffed.

I am working now on publishing this to Maven so it's easier for others to use. In order to use the io.beautifier group ID there is a verification step. Please see https://issues.sonatype.org/browse/OSSRH-95619 to see if you're happy / the organisation is happy to do this for this repository. If not, or if that's a pain, then I don't think it will be a big deal to change the groupId to `io.github.beautifier` as per the feedback on that ticket.

**Comment by bitwiseman** [comment]
I'll look at it next week. Thanks for doing this!

**Comment by karlvr** [comment]
@bitwiseman thank _you_

**Comment by bitwiseman** [comment]
@karlvr 
I see what I need to do to approve this.  Please add `bitwiseman` to the `Usernames(s)` field on https://issues.sonatype.org/browse/OSSRH-95619 .  Then I'll update the DNS record.  

Thanks!

**Comment by bitwiseman** [comment]
@karlvr  Any update?

**Comment by karlvr** [comment]
@bitwiseman I've finally gotten back to this, https://issues.sonatype.org/browse/OSSRH-96699

**Comment by karlvr** [comment]
@bitwiseman when you have a moment, please…

> Add a DNS TXT record to your domain with the text: [OSSRH-96699](https://issues.sonatype.org/browse/OSSRH-96699)

**Comment by bitwiseman** [comment]
@karlvr Updated.

**Comment by karlvr** [comment]
@bitwiseman thank you, and it looks like it's been completed at OSSRH too... next step, actually publish :-)

**Comment by karlvr** [comment]
@bitwiseman one and a half short months later, I've published the first release at version 1.14.11 to sync with js-beautify. Thanks for your help. 

https://repo1.maven.org/maven2/io/beautifier/js-beautify/1.14.11/
