### ISSUE TITLE
editorconfig ^0.15.3 vulnerability

### ISSUE THREAD

**Issue by Andyloz** [beautify-web/js-beautify#2163]
That package at that version depends on a [vulnerable version of semver](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)

I've seen that in master is fixed. There, we have at `package.json` `"editorconfig": "^1.0.3"`, so no vulnerability. But from `npm i` i get the package with tag `1.14.8` which at `package.json` has `"editorconfig": "^0.15.3"` which has that vulnerability.

**Comment by bitwiseman** [comment]
The fix isn't released yet.  See #2161.
