### ISSUE TITLE
【BUG】js-beautify's dependency editorconfig no longer supports node versions lower than 16

### ISSUE THREAD

**Issue by fuzi1996** [beautify-web/js-beautify#2168]
# Description

Since the 1.0.3 version of editorconfig no longer supports node versions below 16

So, it is recommended not to use `^1.0.3` if it is not necessary

If it's necessary,please use `1.0.2` version

commit: https://github.com/beautify-web/js-beautify/commit/019aeb9c0b650952cd088aec7cdfcc3eb3e5d884#r122176064

# Detailed reasons

The 1.0.3 version of editorconfig import the 11.0.0 version of the commander, which no longer supports nodes with version numbers lower than 16

commit: https://github.com/editorconfig/editorconfig-core-js/commit/1a08949d9ae61a9be22f2fba1ef3087b51a133f9#r122176791

**Comment by bitwiseman** [comment]
Sorry, versions of Node below version 16 were EOL several months ago.   Even Node 16 is no longer supported and will only be getting security updates for about another 7 weeks. 

This project does it's best to support older versions of node and browsers, but makes no guarantees. 

If you want to maintain a less secure version of this library, you are welcome to fork and maintain it on your own.

**Comment by fuzi1996** [comment]
Thanks. The problem has been resolved https://github.com/editorconfig/editorconfig-core-js/pull/125
