### ISSUE TITLE
Unsafe js-beautify library because of inflight memory leak vulnerability

### ISSUE THREAD

**Issue by rm0123** [beautify-web/js-beautify#2170]
# Description

Hi, I use js-beautify 1.14.9 that uses Glob version  [^v8.1.0](https://github.com/isaacs/node-glob/releases/tag/v8.1.0) which rely on inflight 1.0.6. This one has a vulnerability raised regarding memory leaks. Using an alternative to glob like fast-glob, it could be work fine without memory leak issue. Is a patched version is plan  to remediate this vulnerability ?

Thanks & Regards.

# Package.json using unsecure glob module
```
 "dependencies": {
    "config-chain": "^1.1.13",
    "editorconfig": "^1.0.3",
    "glob": "^8.1.0",
    "nopt": "^6.0.0"
  },
```

**Comment by bitwiseman** [comment]
See https://github.com/isaacs/node-glob/issues/540#issuecomment-1635396937 .  `inflight` is a dev dependency since v8.

**Comment by rm0123** [comment]
Hello, 

The comment was updated, please see https://github.com/isaacs/node-glob/issues/540#issuecomment-1664310745  The glob version [^v8.1.0](https://github.com/isaacs/node-glob/releases/tag/v8.1.0) is unsafe which makes js-beautify unsafe. He explained that the patched version not using inflight is v9 and v10. 

Thanks

**Comment by bitwiseman** [comment]
Closed by https://github.com/beautify-web/js-beautify/pull/2182
