### ISSUE TITLE
css space around binary operator

### ISSUE THREAD

**Issue by legend-sabbir** [beautify-web/js-beautify#2186]
# Description

# Input
With this new feature, when I give like this input: 
```
body>h1 {}
```

# Expected Output
I'd like to see this output:
```
body > h1 {}
```

## Environment
OS:

**Comment by rbiswasTw** [comment]
@legend-sabbir  - which ENV is having this issue. I have tested this in Javascript, and it works fine. 

`body>h1 {}`

returns 

`body > h1 {}`

**Comment by paidPlugins** [comment]
i was talking about css/scss/less
