### ISSUE TITLE
Memory leak vulnerability because of inflight version

### ISSUE THREAD

**Issue by rm0123** [beautify-web/js-beautify#2193]
Hello,
I use js-beautify 1.14.9 that uses Glob version [^v8.1.0](https://github.com/isaacs/node-glob/releases/tag/v8.1.0) which rely on inflight 1.0.6. This one has a vulnerability raised regarding memory leaks. please see https://github.com/isaacs/node-glob/issues/540#issuecomment-1664310745 The glob version [^v8.1.0](https://github.com/isaacs/node-glob/releases/tag/v8.1.0) is unsafe which makes js-beautify unsafe. He explained that the corrected versions that don't use inflight are v9 and v10. Is a patched version is plan  for js-beautify 1.14.9 to remediate this vulnerability ?

` "dependencies": {
    "config-chain": "^1.1.13",
    "editorconfig": "^1.0.3",
    "glob": "^8.1.0",
    "nopt": "^6.0.0"
  },
`
Thanks

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/pull/2182
