### ISSUE TITLE
Editor not working https://beautifier.io/

### ISSUE THREAD

**Issue by OsamaFarooqi** [beautify-web/js-beautify#2201]
I tried to add the text in the editor for Beautify but it seems the text is disabled. Is anyone else facing the same issue?

**Comment by jatin-2708** [comment]
Its working dude!

**Comment by m0riya42** [comment]
no, he is right. there is problem with Code Mirror files:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/theme/darcula.min.css' with computed SHA-256 integrity 'Fxr+aGftuFXhaJIvakiUpy6kXsjrZxCEJ0p15lO+xnU='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.js' with computed SHA-256 integrity '0KuQ1XThHXVhDa6jdITxdeTYDzaWV/lPuBYwPVycGrM='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/xml/xml.min.js' with computed SHA-256 integrity 'k5VUTWMtSLTiSEeTkgvL5JmW/CvqJpnMMCctFFYDhNk='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/javascript/javascript.min.js' with computed SHA-256 integrity '+8VGSstY4NpdOKrpqikOA7VL/2kFtpAZLogBVyi2oG4='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/css/css.min.js' with computed SHA-256 integrity 'gQQR5ZHMZP6hok3/cft321eIa7RumZlbgHEV8LWtLpo='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/htmlmixed/htmlmixed.min.js' with computed SHA-256 integrity 'ogj2tQCFQi/aCdn6B5tKnqYPFJigkQ0A6cs+1juMt5Y='. The resource has been blocked.
search.js:18 Uncaught ReferenceError: CodeMirror is not defined
    at search.js:18:9
    at search.js:19:3
(anonymous) @ search.js:18
(anonymous) @ search.js:19
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/search/searchcursor.min.js' with computed SHA-256 integrity 'h1dBxYRDp0lGIwSxpwtZg/5xwQ7Ar+pnmLubIUW4pg0='. The resource has been blocked.
beautifier.io/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/dialog/dialog.min.js' with computed SHA-256 integrity '+RMZ8Ss5fH2P0i2mWXYBJ8PObZMfTBf2dbyHKhaY6bU='. The resource has been blocked.`

**Comment by bitwiseman** [comment]
It looks like the integrity sha-256 changed for https://cdnjs.com/libraries/codemirror/5.48.4 changed.  
There's also considerably newer versions of codemirror 5.x available: https://cdnjs.com/libraries/codemirror/5.65.15  
Would one of you be willing to submit a PR with the updated script tags.  It basically is just a matter of copying them (using the convenient appropriate "copy script tag" button) from on of the pages above.

**Comment by m0riya42** [comment]
Do you mean to update this part:

```
<!-- Codemirror from https://cdnjs.com/libraries/codemirror -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.css" integrity="sha256-vZ3SaLOjnKO/gGvcUWegySoDU6ff33CS5i9ot8J9Czk=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/theme/darcula.min.css" integrity="sha256-ZzdkdGSdYSUv4R77x7A5G7EeFDLMhAiCybNBNxNoxos=" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/codemirror.min.js" integrity="sha256-dPTL2a+npIonoK5i0Tyes0txCMUWZBf8cfKRfACRotc=" crossorigin="anonymous"></script>

  <!-- Codemirror Modes -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/xml/xml.min.js" integrity="sha256-cphnEddX56MtGJsi1PoCPLds+dlnDj1QQkAlCWeJYDo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/javascript/javascript.min.js" integrity="sha256-7AjEsHnW7cpq2raC/uxnGCP2G4zIKmCdz7OAv6LN00o=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/css/css.min.js" integrity="sha256-mjhvNBMExwa2AtP0mBlK9NkzJ7sgRSyZdgw9sPhhtb0=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/mode/htmlmixed/htmlmixed.min.js" integrity="sha256-qfS6ZUe6JhPU75/Sc1ftiWzC2N9IxGEjlRwpKB78Ico=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/search/search.js" integrity="sha256-iUnNlgkrU5Jj8oKl2zBBCTmESI2xpXwZrTX+arxSEKc=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/search/searchcursor.min.js" integrity="sha256-y7nxCQ9bT6p4fEq9ylGxWfMQBpL6ingXkav6Nr1AcZ8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/dialog/dialog.min.js" integrity="sha256-G+QhvxjUNi5P5cyQqjROwriSUy2lZtCFUQh+8W1o6I0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.48.4/addon/dialog/dialog.css" integrity="sha256-XfaQ13HxIRg0hWLdKpAGBDOuLt7M0JCKvKpEgLHj5Gg=" crossorigin="anonymous">
```

to new version? 

there is more versions, to which one?

![image](https://github.com/beautify-web/js-beautify/assets/44200760/fd6fc18f-82fc-48a0-bf0c-56e0c435c2fa)

**Comment by bitwiseman** [comment]
We need to stick with 5.x for now.  6.x has broader breaking changes.   If you want to do that upgrade as well, feel free.  But I would suggest just upgrading 5.x and then looking at what needs to be done for 6.x.
