### ISSUE TITLE
Thanks, issue add Discussions tab?

### ISSUE THREAD

**Issue by ldijkman** [beautify-web/js-beautify#2204]
Thanks

playing with your code
trying to make an editor

https://ldijkman.github.io/Ace_Seventh_Heaven/Hell.html
![2023-10-17-045228_1920x1080_scrot](https://github.com/beautify-web/js-beautify/assets/45427770/afff8258-9ce1-49dd-a360-a197ef87819b)

**Comment by ldijkman** [comment]
trying to get 
an options menu
;ike 

https://ldijkman.github.io/Ace_Seventh_Heaven/Hell.html

![2023-10-21-081647_1920x1080_scrot](https://github.com/beautify-web/js-beautify/assets/45427770/83ac7289-be53-48cc-9bce-47a59854412c)

**Comment by bitwiseman** [comment]
Added discussions.
