### ISSUE TITLE
SRI hash outdated

### ISSUE THREAD

**Issue by likendev** [beautify-web/js-beautify#2208]
# Description
SRI hash is outdated

# Actual Output
![image](https://github.com/beautify-web/js-beautify/assets/15458805/0c6f8440-1b88-44d6-ba01-6e45077eead4)

# Steps to Reproduce
Visit to [https://beautifier.io/](https://beautifier.io/)
Open developer console (F12) and notice the problem

## Environment
OS: Windows
Browser: Edge

**Comment by bitwiseman** [comment]
Duplicate of #2201
