### ISSUE TITLE
Move html-beautify and css-beautify to separate repository 

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#257]
Another issue from the discussion in #193.  Since html and css is beautification is in js only and much less mature and with different command line options, it might be better to split them off in to a separate project.  This is different from #176, which suggested splitting out python version of js beautification.

**Comment by adius** [comment]
This should definitely happen!

**Comment by wtgtybhertgeghgtwtg** [comment]
I can create packages for `html-beautify` and `css-beautify` and transfer ownership, if that would help.

**Comment by bitwiseman** [comment]
We've gone in a different direction.
