### ISSUE TITLE
Alternative Newline Characters

### ISSUE THREAD

**Issue by manngo** [beautify-web/js-beautify#260]
Secondly, it appears that when jsBeautifier adds new line, it is always with the '\n' character. Is it possible to allow for the windows style '\r\n' newline? I thought I had found where the new line is created, but it seems to break the indentation. Here is what I tried:

//	Somewhere around line 170:
	opt.eol = options.eol ? options.eol : '\n';	//	a new option

//	Somewhere around line 370, change to:
	if (force_newline || !just_added_newline()) {
		output.push(opt.eol);			//	was output.push("\n");
	}

… but I find that if opt.eol is anything other than '\n' all of the tabs get through away.

Thanks,

Mark

**Comment by sethflowers** [comment]
+1 - unable to incorporate this into our teams workflow due to forcing `\n` as newline character.

**Comment by gabrielmaldi** [comment]
Would it be possible to release a version with this change before `v1.6.0`? I realize it may well be a breaking change, but I fear it will be too long until `v1.6.0` is released (there are a lot of open issues) and we need this so that `grunt-jsbeautifier` can target it.
Thanks!

**Comment by bitwiseman** [comment]
Sure, I can do that.

**Comment by corgrath** [comment]
+1 on @gabrielmaldi 's suggestion

It would be fantastic if the eol option could come in before 1.6.0, as it is the only bug that currently breaks our code and prevents us from using grunt-jsbeautifier/jsbeautify :-)

**Comment by mahboob-awan** [comment]
@corgrath +1

**Comment by gabrielmaldi** [comment]
I've tried this new feature and it works fine :+1: However, I think I found a bug which I reported in #781.
