### ISSUE TITLE
Add an option to strip empty lines

### ISSUE THREAD

**Issue by keeganstreet** [beautify-web/js-beautify#307]
It would be useful if JS Beautify had an option to strip empty lines.

Includes, partials and other serverside code can create blank lines in the HTML. The HTML would be more beautiful without these blank lines.

This used to be the behaviour in version 1.3.1 but I think it was changed for https://github.com/einars/js-beautify/issues/285.

**Input:**

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Demo</title>
</head>
<body>
    <p>P1</p>

    <p>P2</p>

</body>
</html>
```

_(Note: the line after P1 should contain some spaces and tabs but GitHub Flavored Markdown is removing them. This line should still be removed by JS Beautify.)_

**Configuration:**

`js-beautify input.html -o output.html --remove-empty-lines`

**Expected output:**

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Demo</title>
</head>
<body>
    <p>P1</p>
    <p>P2</p>
</body>
</html>
```

**Actual output:**

``` html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Demo</title>
</head>

<body>
    <p>P1</p>

    <p>P2</p>

</body>

</html>


```

**Comment by taigh** [comment]
Hi, can you add same option for css?

**Comment by Migacz85** [comment]
Please add the same functionality to css :-)

**Comment by bitwiseman** [comment]
@Migacz85 Have you tried this? I think it is already there.  You'll also need to set `"newline-between-rules": false`. Please open a new issue for css if this doesn't work.

**Comment by filip-savic-bm** [comment]
setting `extra_liners: [],` made me not have the newlines anywhere in my HTML formatting

**Comment by filip-savic-bm** [comment]
docs (https://www.npmjs.com/package/js-beautify#css--html):
>  -E, --extra_liners                 List of tags (defaults to [head,body,/html] that should have an extra newline before them.

so, setting `extra_liners: [],` made me not have any extra newlines :))

**Comment by filip-savic-bm** [comment]
docs (https://www.npmjs.com/package/js-beautify#css--html):
>  -E, --extra_liners                 List of tags (defaults to [head,body,/html] that should have an extra newline before them.
 
so, setting `extra_liners: [],` made me not have any extra newlines :))
