### ISSUE TITLE
Handling of newlines around if/else/if statements

### ISSUE THREAD

**Issue by dcwatson84** [beautify-web/js-beautify#311]
The handling of an if/else/if block is ambiguous depending on input

With the code on a single line - ie -
if(...){...}else{...}if(...){...}

It will be formatted as such
if (...) {
...
} else {
...
} if (...) {
...
}

Note: No newline between the closure of the else and the second if.
However if there is already a newline after the else{} - ie -
if (...) {...} else {...}
if (...) {...}

Then that newline will be preserved *even* if preserve newlines is set to false.  So the output is - 
if (...) {
...
} else {
...
} 
if (...) {
...
}

Note: The newline after the else{...}
I dont think this is the expected behavior?  With preserve_newlines set to false, the code should always produce the same output (in terms of line breaks), correct?

**Comment by trusktr** [comment]
How do we make
```js
if(x){a();}else{b();}
```
result in
```js
if (x) {
    a();
}
else {
    b();
}
```
where `else` is on a new line after the `}`?

**Comment by trusktr** [comment]
Aha, it seems to be "End braces on own line". Does that correspond to the `end-expand` brace-style setting?

**Comment by trusktr** [comment]
Confirmed, I just the encountered the bug of this issue, with a `if` section not being on it's own line.

**Comment by bitwiseman** [comment]
So... Bug here or not?

**Comment by trusktr** [comment]
@bitwiseman I'd say it's a bug.

**Comment by trusktr** [comment]
I don't think
```js
// actual 
if (x) {
    a();
} else {
    b();
} if (y) {
    c();
}
```

should happen. I've never seen anyone code like that intentionally.

**Comment by bitwiseman** [comment]
Okay, I've tried the above and I'm not getting a repro.  In all the cases I tried, the `if` popped to the next line.  Could you open a new issue with the specific input/expected/actual and settings?  It is likely your is not the same as this one (regression test in place to cover this one).

**Comment by trusktr** [comment]
I've just tried reproducing, and apparently it doesn't happen all the time. If I encounter it again I'll let you know, but it definitely does happen sometimes.
