### ISSUE TITLE
Option to preserve or inline "short objects" on a single line

### ISSUE THREAD

**Issue by mrchief** [beautify-web/js-beautify#315]
Typically the JS Beautifier expands all JS object declarations into multiple lines, each line having a key value pair. However, this is overly verbose for many situations (e.g. short objects which could easily fit on a single line).

Additional details found here: https://github.com/einars/js-beautify/pull/55

**Comment by dmitriiabramov** [comment]
Is there any progress on this one? 
It will make my test fixtures 5 times smaller :)

**Comment by eTorAken** [comment]
+1 I wish it could be available!

**Comment by cloudbring** [comment]
+1 - Need this so we can beautify on save everywhere

**Comment by gfaceless** [comment]
+1

**Comment by tielur** [comment]
:+1:

**Comment by geronime** [comment]
+1 - also not using with pre-save because of this

**Comment by vkz** [comment]
:+1: 

Also, Escodegen does this correctly, it's code might be the source of inspiration:
```js
var esprima = require("esprima"),
    esgen = require("escodegen").generate;

console.log(esgen(esprima.parse("var a = {code: 'code'}")));
console.log(esgen(esprima.parse("var a = {code: 'code', more: 'code'}")));
```

**Comment by donasaur** [comment]
@bitwiseman 
This problem may not be solvable for an arbitrary amount of nesting (e.g., really large amount of nesting) since the language corresponding to this nesting is nonregular but perhaps you can assume a limit for practical purposes (e.g., at most level-10 nesting)

**Comment by ttsirkia** [comment]
+1 for this request.

It is a way too verbose to split for example this

```javascript
view.on('post', {action: 'removeTask'}, function(next) {
```

to multiple lines.

**Comment by schoening** [comment]
+1

It's been almost two years now. Is there any new ETA?

**Comment by openjck** [comment]
:+1:

**Comment by zwarag** [comment]
We need this!!

**Comment by rolandnsharp** [comment]
:+1:

**Comment by alexbyk** [comment]
:+1:

**Comment by Tsarpf** [comment]
:+1:

**Comment by logstown** [comment]
+1

**Comment by aves84** [comment]
While this feature not implemented, I use regex in my own run script [somewhere about here](https://github.com/beautify-web/js-beautify/blob/master/js/lib/cli.js#L309) like `pretty = pretty.replace(/{([^{}]*?)}/g, function(s, p) { return (s.length < 100 && !/;/.test(p)) ? s.replace(/\n\s*/g, ' ') : s })` 
May be it will useful somebody.

**Comment by schoening** [comment]
@aves84 can't get it to work.. But you made me take a look at the source code instead of just waiting around now so thank you very much :D

**Comment by aves84** [comment]
@schoening perhaps I'm confusing wrote, the line should be added after "beautify", not instead of.  Now I tried to change this particular script:
```javascript
var pretty = beautify[fileType](code, config);
if (fileType == 'js') pretty = pretty.replace(/{([^{}]*?)}/g, function(s, p) {
            return (s.length < 100 && !/;/.test(p)) ? s.replace(/\n\s*/g, ' ') : s
        });
```
 And it works properly.

**Comment by schoening** [comment]
@aves84, nah that I did understand, it made sense. I am on Linux Mint and I am browsing this folder / changing this file: 
/home/hello/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/scripts/node_modules/js-beautify/js/lib/cli.js

Changing this function:

```javascript
function makePretty( code, config, outfile, callback ) {
  try {
    var fileType = getOutputType( outfile, config.type );
    var pretty = beautify[ fileType ]( code, config );
    if ( fileType == 'js' ) pretty = pretty.replace( /{([^{}]*?)}/g, function ( s, p ) {
      return ( s.length < 100 && !/;/.test( p ) ) ? s.replace( /\n\s*/g, ' ' ) : s
    } );

    callback( null, pretty, outfile, config );
  } catch ( ex ) {
    callback( ex );
  }

}
```

And then when I try something like this:

```javascript
var foo = {
  bar: "Hello world!"
};
```
Sorry for all the questioning mate.

**Comment by aves84** [comment]
@schoening most likely the extension don't uses cli.js and replaces it with its own file with `require('js-beautify')`. In Brackets I made changes to ~/.config/Brackets/extensions/user/hirse.beautify/main.js
It could be in Sublime extension written not in javascript, so you can try edit https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L369 for example.

**Comment by mokkabonna** [comment]
I think sublime uses the python version.

**Comment by bitwiseman** [comment]
@mokkabonna - it depends.  Some sublime plugins wrap node.js calls, other use python directly.

**Comment by MetaMemoryT** [comment]
:+1: plusoneplusone

**Comment by FrankFang** [comment]
+1.  Is there an such option for now?

**Comment by Jacq** [comment]
:+1: looking forward to it, thanks.

**Comment by dani-h** [comment]
:+1:

**Comment by aves84** [comment]
@dani-h Well, this method is far from ideal, it relies on the semicolon in the definition of short objects and code blocks: if there are no semicolons and the number of characters is less than 100, the line breaks are removed. It even will cause errors in code that uses javascript's automatic semicolon insertion.

**Comment by zepedrorocha** [comment]
:+1:

**Comment by FrankFang** [comment]
:+1:    Looking forward to that.

**Comment by kaia9** [comment]
+1 ... i'd love to see this make it in soon.

it's the only reason that we're not able to use this plugin at this point.

**Comment by mgmcdermott** [comment]
+1

**Comment by pkerschbaum** [comment]
+1

**Comment by AdriVanHoudt** [comment]
+1 on this, blocks me from using this. Even an option to just disable this would help!

**Comment by auser** [comment]
+1 +1 +1

**Comment by cwhenderson20** [comment]
+1

**Comment by daniel-pedersen** [comment]
+1

**Comment by glennr** [comment]
+1 and a thanks for all your hard work on this!

**Comment by Ceyaje** [comment]
+1 Right now, beautifying literally doubles my code into a horrible ugly mess because of this issue. It's quite a crippling bug in some circumstances. Especially since I use js-beautify as a psedo-linter (If indents aren't right, I missed a bracket somewhere.) My muscle memory turns my beautiful unit-tests into a 10 minute task of fixing all my object literals.

**Comment by seavan** [comment]
`js-beautify -pX <filename> | perl -0777 -i -pe 's/\{\s*([^{}]{30,180}?)\s*\}/\{ $1 \}/mg'`

this line of code will fold back the unfolded things between 30 to 180 characters length without embedded blocks. probably it can be useful for some people.

**Comment by catataw** [comment]
+1 and a thanks for all your hard work on this!

**Comment by verjik** [comment]
+1. Three lines instead of one is too much.

**Comment by vekat** [comment]
I hope this can be done. :+1:

It is the only behavior of js-beautify that makes me displeased. :sweat_smile:

**Comment by bitwiseman** [comment]
@vekat - As you can see, you're not alone. :smile:

**Comment by select** [comment]
+1

**Comment by nels-o** [comment]
I'll add that this would make the beautifier work more reliably for documents like bottle templates where the {{thing}}, or {{! thing}} syntax is badly affected by line breaks.

**Comment by bitwiseman** [comment]
@nels-o - totally different thing, sorry.  Template braces like `{{` and `}}` are parsed completely differently than javascript braces.  Besides which, when inlining objects they would look like `{ a:{ b:{} } } }`

**Comment by nels-o** [comment]
Is it? If they're in script tags those seem to be formatted. For example this: 

![image](https://cloud.githubusercontent.com/assets/2745310/12524631/3b7430a0-c113-11e5-9016-804cd64ee42f.png)

becomes this after running the prettifier.

![image](https://cloud.githubusercontent.com/assets/2745310/12524617/2d52a5ec-c113-11e5-83e6-59690e1a2081.png)

**Comment by bitwiseman** [comment]
Perhaps what I should have said is, _if_ they were to be handled they _would_ be handled completely separately. :smile:  Still, sorry.

**Comment by C-Weinstein** [comment]
+1. Any idea of an ETA? This is making me very sad :(

**Comment by sarneeh** [comment]
+1. Would love that feature too! Unfortunately I don't have time actually to help somehow :(

**Comment by naelkhann** [comment]
+1, we're all still patiently waiting. This will be an awesome addition

**Comment by bitwiseman** [comment]
The change I made doesn't really understand "short" objects - it just tries to preserve the objects that the input provides that have no newlines in them.  Once line-wrapping occurs, the object flips to "collapse" formatting.   So, this is still an imperfect solution, but an improvement.

**Comment by ttsirkia** [comment]
If this works as I understood, I think this is already a huge improvement to the current situation. In most cases, this is sufficient.

**Comment by taosx** [comment]
+1

**Comment by NerdPad** [comment]
+1 hope this is done soon

**Comment by bitwiseman** [comment]
@NerdPad  - it *is* done.

**Comment by C-Weinstein** [comment]
Can we use it with Brackets? o_O

**Comment by lnewman-book** [comment]
@C-Weinstein - Could you be more specific?  Have you searched this issues in the project for Brackets?

**Comment by bitwiseman** [comment]
@C-Weinstein - Perhaps you could open a new issue with example of input and desired output?

**Comment by alepez** [comment]
For people like me coming here looking for a way to make it work: **it works** and can be enabled with the options in .jsbeautifyrc

       "brace_style": "collapse-preserve-inline"

**Comment by Ceyaje** [comment]
Unfortunately, that didn't work :( But thanks for trying.

**Comment by bitwiseman** [comment]
@Ceyaje  - How didn't work?  Where didn't it work?  What were your inputs and outputs?

**Comment by Ceyaje** [comment]
Input was 

    var q = { x: "a", b: "c" }

It "beautifies" to 

    var q = {
        x: "a",
        b: "c"
    }

**Comment by aves84** [comment]
@Ceyaje you need set option "brace-style" to "collapse-preserve-inline"

**Comment by bitwiseman** [comment]
@aves84 - thanks!  Continuing discussion in #995.

**Comment by Ceyaje** [comment]
@aves84 I did that. I was saying it was still happening, so I opened #995 but I'm using Brackets and wasn't aware that it was different code

**Comment by Kutsan** [comment]
What about expand-preserve-inline?

**Comment by bitwiseman** [comment]
@Kutsan - Please open a new issue.

**Comment by sandangel** [comment]
I could not find expand-preserve-inline option with html file. I write javascript in html file too. Am I the only one?

**Comment by jonscottclark** [comment]
Place "preserve-inline" after the setting you want to use (collapse, expand, etc.)

**"brace_style": "collapse,preserve-inline"**

**Comment by djoaquing** [comment]
https://i.gyazo.com/2831254cc47d08c879c7d36a7f1a30d0.png

The above happens, however my brace style is collapse-preserve-inline. I read the full thread, I don't believe I'm doing anything incorrectly. Already restarted Atom, just in case, nothing.

**Comment by grandslammer** [comment]
Any update on this? collapse-preserve-inline still expands the arrow function onto multiple lines.

**Comment by bitwiseman** [comment]
@grandslammer - Please take a look at open issues that include the word "arrow".  If you don't see an issue that covers what you're talking about, please open a new issue.

**Comment by ainthek** [comment]
I'm sorry: Original topis is "Option to preserve or inline "short objects" on a single line #315?
this discussion has drifted many way, can PLEASE ANYONE point the correct settings for latest version of js-beautify to achieve requested formatting ? Thanx

**Comment by timhuff** [comment]
@ainthek it's `"brace_style": "collapse,preserve-inline"`

**Comment by rajeshwarpatlolla** [comment]
How about the settings in vs code latest version to fix this issue?

**Comment by souravsaraf** [comment]
In vs code 1.20.1 , i cannot get the style "brace_style": "expand,preserve-inline", to work. 

Input : 

<pre>const
	{
		dialog
	} = require("electron").remote;</pre>

Output (After selecting this area and clicking F1 ---> Beautify Selection) : NO CHANGE :(

Expected Output : `const {dialog} = require("electron").remote;`

P.S  ----> the distorted input was obtained after Beautifying the whole file. Nobody writes code in that distorted way :P

**Comment by vipingoel** [comment]
For vscode, adding below in user settings worked for me:
    "beautify.config": { "brace_style": "collapse,preserve-inline" }

Thank you for the support guys.

**Comment by sulkhanp** [comment]
From what I've noticed this only works for js but not json files. Is there a way to enable this setting for json too?

**Comment by bitwiseman** [comment]
@sulkhanp - Please file an issue describing the behavior.

**Comment by sulkhanp** [comment]
@bitwiseman #1424

**Comment by iplus26** [comment]
@vipingoel 's solution works!
Why is this option only works in vscode user preference, not in my `.jsbeautifyrc` file?

**Comment by SiJinmin** [comment]
"brace_style": "expand,preserve-inline" doesn't work. 

expect behavior:
```
  let $w = $(window),  w = $w.width(),  h = $w.height();
  constructor()
  {
    this.setupData(); this.setupMenus(); this.setupUser(); this.setupUI();
  }
```
current behavior:
```
    let $w = $(window),
      w = $w.width(),
      h = $w.height();

  constructor()
  {
    this.setupData();
    this.setupMenus();
    this.setupUser();
    this.setupUI();
  }
```

**Comment by ttsirkia** [comment]
@SiJinmin these are not short objects and therefore not related to this issue.

**Comment by Mizumaki** [comment]
@vipingoel It works. I'm really happy. Thanks!!!
