### ISSUE TITLE
newline removal seems not to work properly (in sublime text 3 on xp pro sp3)

### ISSUE THREAD

**Issue by dominiklenne** [beautify-web/js-beautify#348]
## Action

Edit code like this

```
    <header>
     <h1>


      <ul>

        <li class="menuactive menuparent">
          <a >
            <span>Anita Koppe</span>
          </a>


        </li>
      </ul>
    </h1>
  </header>
```

Set 

```
    "max_preserve_newlines": 0,
    "preserve_newlines": false,
```

in .jsbeautifyrc in the sections "html" and "js".
Run htmlprettify on html-file.
## Expected Result

```
  <header>
    <h1>
      <ul>
        <li class="menuactive menuparent">
          <a >
            <span>Anita Koppe</span>
          </a>
        </li>
      </ul>
    </h1>
  </header>
```
## Actual Result

No change at all.

**Comment by dominiklenne** [comment]
Hi,

sorry for waiting so long,
i just updated the /js directory in the sublime 3 / html-prettify plugin directory to be sure to have the current version, and found out, that the behaviour changed a little, but is still broken.
The output is the same as the input with one difference: the "</header>" at the end has jumped one line up and appears behind the "</h1>".

all the best

Dominik

**Comment by MacKLess** [comment]
As of 1.8.0-rc6 this is resolved. 

@dominiklenne feel free to review this at (http://jsbeautifier.org/)
