### ISSUE TITLE
Add option to prefix commas on json objects (feature request)

### ISSUE THREAD

**Issue by asdf23** [beautify-web/js-beautify#350]
I would really like an option to prefix arrays with a comma/space. For example:
Input file:
<pre>
function foo() {
  return [
    {
      one: 'x',
      two: [
        {
          id: 'a',
          name: 'apple'
        },
        {
          id: 'b',
          name: 'banana'
        }
      ]
    }
  ];
}
</pre>
Would create the following output file (only commas and spaces were changed, I am not addressing the brackets):
<pre>
function foo() {
  return [
    {
       one: 'x'
      ,two: [
         {
           id: 'a'
          ,name: 'apple'
        }
        ,{
           id: 'b'
          ,name: 'banana'
        }
      ]
    }
  ];
}
</pre>

**Comment by bitwiseman** [comment]
Please take a look at branch `feature/comma-first` - https://github.com/beautify-web/js-beautify/commit/e5bfcf34b6089752e0a474e86ff533b46ac1677a

Tell me if this is a sufficient first step towards what you want that I should add it to the next release.
