### ISSUE TITLE
Lonely closing tags

### ISSUE THREAD

**Issue by chrisbateman** [beautify-web/js-beautify#362]
I'm not sure if this is doable, but it might be nice if elements that are all on one line - except for a closing tag - could be consolidated to one line.

(And maybe even vice-versa with the opening tag)

Example:

``` html
<p>My paragraph text.
        </p>
```

Result:

``` html
<p>My paragraph text.
</p>
```

Desired:

``` html
<p>My paragraph text.</p>
```

**Comment by bitwiseman** [comment]
Not sure, but that one is on my list, so thanks for linking.
