### ISSUE TITLE
Unexpected output in Python 3.3

### ISSUE THREAD

**Issue by dcharles** [beautify-web/js-beautify#377]
A few weeks ago, I downloaded the ZIP of js-beautify from GitHub and set it up in Python 3.3.3 on Windows 7 Enterprise. When I try running it on some HTML, it doesn't seem to work. For example, I want to break up this line:

```
<body><table cellspacing='0' cellpadding='0'><tr><td>
```

When I type that into jsbeautifier.org, I get this, which is what I would expect:

```
<body>
    <table cellspacing='0' cellpadding='0'>
        <tr>
            <td>
```

Here's the code that I type in Python:

``` python
import jsbeautifier

opts = jsbeautifier.default_options()
opts.type = 'html'

x = "<body><table cellspacing='0' cellpadding='0'><tr><td>"

y = jsbeautifier.beautify(x, opts)
```

And here's the result:

```
< body > < table cellspacing = '0'
cellpadding = '0' > < tr > < td >
```

~~Running the Beautifier on Javascript also gives unexpected results, so~~ I suspect that I may simply be doing something wrong, but I can't figure out what, from the documentation. If this is a bug, I'd be glad to try to help; or if I'm simply doing something wrong, any help would be appreciated.

By the way, I previously emailed Liam Newman about this issue, and he recommended that I post it here.

**Comment by Kladdkaka** [comment]
this is still the case? :/

**Comment by bitwiseman** [comment]
@Kladdkaka No one has take the time to implement the HTML beautifier in Python.
