### ISSUE TITLE
Newline inserted after ES6 module import/export

### ISSUE THREAD

**Issue by redking** [beautify-web/js-beautify#382]
Hey,

I'm running jsbeautifier on a collection of Ember.JS ES6 modules and I've noticed a small issue with export statements.

Suppose I have a module that exports as below

```javascript
export default DS.FixtureAdapter.extend();
```

jsbeautifier will add a newline after export

```javascript
export
default DS.FixtureAdapter.extend();
```

It's a minor problem that is only an issue for us as we enforce a jsbeautifier run before a commit is accepted. So, if a developer removes the newline, the file in question will be included in the commit even though it may have nothing to do with the changes being commited.

**Comment by pgilad** [comment]
:+1:
Any fix in sight?

**Comment by bitwiseman** [comment]
In my copious free time...

**Comment by simplyianm** [comment]
:+1:

**Comment by dred9e** [comment]
+1

**Comment by Aluxian** [comment]
+1

**Comment by bitwiseman** [comment]
The original issue was fixed in 1.5.2. 

@dred9e, @Aluxian, @simplyianm, @pgilad, @webbushka, @fpauser, @Volox, @naomifeehanmoran, @darlanalves, @thaume - 

I'd like your help. 

Please provide examples of input, actual output, and desired output so that I can work my way through this issue.   Also indicate whether the actual output is only not desirable or if it causes syntax errors.  Syntax errors will get priority. I have one so far from @thaume - 
```
//input
import { mod1, mod2 } from 'filePath';

// actual output - non-breaking 
import { 
  mod1, 
  mod2 
} from 'filePath';

// desired output (unchanged)
import { mod1, mod2 } from 'filePath';
```

NOTES: 
* Please look at each other's comments and try not to repeat classes of formatting with slight differences.  Best effort is fine.  :smile: 
* Brace positioning is going to be a key problem.  We currently have one setting for positioning all types of braces - collapse, expand, 
* Since the original issue has been fixed, I may end up closing this issue and open new ones for various inputs you provide.

**Comment by darlanalves** [comment]
@bitwiseman The sample above is exactly what I'd expect too. I've been playing with ES6 lately on Atom editor, where I don't have auto-format on save, only because the imports are messed up.

Expected:
```
import { Bar } from 'lib/Bar';

class Foo {
	constructor() {
		this.bar = new Bar();
	}
}

export { Foo }
```

How it is now:

```
import {
    Bar
}
from 'lib/Bar';

class Foo {
    constructor() {
        this.bar = new Bar();
    }
}

export {
    Foo
}
```

**Comment by loopmode** [comment]
It breaks when working with react/jsx, but I guess that is a separate issue altogether:

    return <div {...props}></div>;

becomes

    return <div {...props
        } > < /div>;

**Comment by bitwiseman** [comment]
Did you set `e4x = true`?

**Comment by loopmode** [comment]
Yes I did, and I can see on regular jsx without literals that it is being respected. However, having a literal like {...props} in the outermost tag breaks the formatting immediatly. If the literal is inside a nested element, it works slightly better but still breaks on the closing tag. I can post more examples if this is the right place/issue.

**Comment by bitwiseman** [comment]
Please open a new issue.

**Comment by rofrischmann** [comment]
I also encountered a problem with props, but with different behavoir. It always changes the order my attributes are applied.

**Input/Expected**
```javascript
<Element {...props} style={styles.element} className={classes.element}>...</Element>
```

**Output**
```javascript
<Element style={styles.element} className={classes.element}  {...props}>...</Element>
```

Problem is that `{...props}` might contain `style` or `className` => overwrites those.

**Comment by bitwiseman** [comment]
@loopmode - Please open a new issue with example you have above.

**Comment by nickpoorman** [comment]
+1

**Comment by ggentzke** [comment]
:+1: This also affects destructuring objects.
```javascript
var { type, size } = someObject;
```
is converted to
```javascript
var {
        type, size
    } = someObject;
```

**Comment by dijs** [comment]
:+1:  imports and jsx formatting are broken for me also when using atom

**Comment by michaelchum** [comment]
+1

**Comment by divmgl** [comment]
+1

**Comment by MattSPalmer** [comment]
+1

**Comment by mitermayer** [comment]
+1

**Comment by andrew-w-ross** [comment]
+1

**Comment by ckknight** [comment]
With js-beautify 1.5.10, I'm getting the following:

Input:
```js
import { x, y, z } from './other';
```

Output:
```js
import {
	x, y, z
}
from './other';
```

I definitely don't want the newline after the ending brace.

**Comment by HaNdTriX** [comment]
+1

**Comment by jraede** [comment]
Any plans for supporting this?

**Comment by simplyianm** [comment]
Is this still not fixed?

**Comment by bitwiseman** [comment]
It is still open.  Pull requests welcome.

**Comment by sahlouls** [comment]
+1

**Comment by piaolingxue** [comment]
+1

**Comment by TylerYang** [comment]
+1

**Comment by wthinkit** [comment]
+1

**Comment by superzadeh** [comment]
+1

**Comment by bitwiseman** [comment]
For anyone interested, the remaining issue is with `import {x, y} from './other'`.  This seems to be a sub-case of destructured objects.   See #511.

**Comment by tomitrescak** [comment]
I still get the behaviour for imports, but all tickets are closed. How can I preserve a single line in imports after beautification in Atom? Thanks!

**Comment by tomitrescak** [comment]
Got it, all that was needed was to add following config in .jslintrc

```
{
  "preserve_newlines": true,
  "max_preserve_newlines": 2
}
```

**Comment by the-simian** [comment]
I am still experiencing this issue with `import`. I am using `1.6.3`
```js
import { mod1, mod2 } from 'filePath';
```
becomes
```js
import { 
  mod1, 
  mod2 
} from 'filePath';
```

for those of you that it works correctly, can you post your .rc file json with the correct properties pointed out? I have no idea why it isn't working at all.

**Comment by eloquence** [comment]
@the-simian The correct option is `"brace_style": "collapse-preserve-inline"`, in the "Brace style" section if you go through the Atom preferences. The "preserve_newlines" option is for preservation of newlines across the whole file. You definitely want that one to be true, though. :)

**Comment by the-simian** [comment]
@eloquence thanks for the update, I'll try that out as soon as I can

**Comment by naoyeye** [comment]
@loopmode I got a similar problem with `collapse-preserve-inline`

```json
"brace_style": "collapse-preserve-inline",
```

Input:

```js
const _state = { ...state }
```

Output:

```js
const _state = {...state }
```

**Comment by Coburn37** [comment]
While `collapse-preserve-inline` works, there's no way to get the same behavior with `end-expand` or `expand`. Is there any way that we could get a `end-expand-preserve-inline` and similar for other options or perhaps maybe even a `preserve-inline-braces` option with true or false?

**Comment by bitwiseman** [comment]
@Coburn37 - Please file a new issue and/or see #1052 to see if that describes what you want.

**Comment by bj97301** [comment]
+1.  I am not a fan of collapse,preserve-inline.  I would like to add a rule specifically for imports...
