### ISSUE TITLE
NPM js-beautify: different treatment of "-" in command line

### ISSUE THREAD

**Issue by einars** [beautify-web/js-beautify#390]
Is it possible that "-" as a parameter is being treated differently in the situation if the script is run from the git checkout, or from npm install?

js-beautify@1.4.2 installed via npm:
% js-beautify -
Unable to open path "/home/e/-"

git checkout, v1.4.2:
% ./js/bin/js-beautify.js -
[waiting for stdin]

**Comment by cdosborn** [comment]
From npm, the command does not seem to handle stdin.

    $ js-beautify - "var x = 3"
    Unable to open path "my/home/path/blah-"
    Run `js-beautify -h` for help.

    $ npm -v js-beautify
    1.4.3

    $ npm version
    { http_parser: '1.0',
      node: '0.10.26',
      v8: '3.14.5.9',
      ares: '1.9.0-DEV',
      uv: '0.10.25',
      zlib: '1.2.3',
      modules: '11',
      openssl: '1.0.1e',
      npm: '1.4.3' }

**Comment by bitwiseman** [comment]
@cdosborn - Thanks!  
Here's a work around for the moment:
```
$ js-beautify -f - <<< "var x = 3"
var x = 3
```
There's a pull request already in for improving this area, so maybe this will get into the next release.

**Comment by cdosborn** [comment]
Thanks, looking forward.

**Comment by bitwiseman** [comment]
This looks to be fixed for the next version.
