### ISSUE TITLE
Format of .jsbeatifyrc

### ISSUE THREAD

**Issue by mokkabonna** [beautify-web/js-beautify#391]
This tool only supports .jsbeautifyrc files with the js options on the first level of the JSON file.

That was fine until this project got formatting for html/css as well.

Other projects

https://github.com/vitormil/sublime-text-2-preferences/tree/master/HTML-CSS-JS%20Prettify#using-your-own-jsbeautifyrc-options

and 

https://github.com/vkadam/grunt-jsbeautifier#default-options-from-js-beautify-can-be-used

Uses one level to first separate html/css/js

Would be great if this structure could be used for this project as well. If doing `js-beautify style.css --type css` that results in in jsbeautify reading the config file and using what is the js settings for indent etc, not the css settings.

**Comment by bitwiseman** [comment]
This has been address by having config file with settings per language and inheritance.
