### ISSUE TITLE
line wrapping breaks in weird places

### ISSUE THREAD

**Issue by jdavisclark** [beautify-web/js-beautify#438]
per @jackocnr via https://github.com/jdc0589/JsFormat/issues/103:

---

It breaks after negation e.g.

```
if ( .... lots of conditions here ... && !someVar) {
```

becomes

```
if ( .... lots of conditions here ... && !
    someVar) {
```

and also before property names e.g.

```
if ( .... lots of conditions here ... && someVar.someProperty) {
```

becomes

```
if ( .... lots of conditions here ... && someVar
    .someProperty) {
```

Both make the code way less readable. Perhaps it should only break on spaces? Or between logical operators e.g. `&&` or `||`?

**Comment by Claymm** [comment]
Can we have `if (! something) {`?
