### ISSUE TITLE
Preserve attributes line break in HTML

### ISSUE THREAD

**Issue by kentliau** [beautify-web/js-beautify#455]
like this

```html
  <div id="anId"
       name="aName"
       class="aClass"
       onclick="alert('hello')"
       ondblclick="alert('hello')">asdf</div>

  <input type="text"
         name="aName"
         class="aClass"
         id="anId">
```

**Comment by dam0** [comment]
+1

**Comment by prathiraj** [comment]
+1

**Comment by gigablox** [comment]
+1

**Comment by bitwiseman** [comment]
Good to know folks.  Anyone want to take a swing at it?

**Comment by solmstead25** [comment]
+1

**Comment by frasator** [comment]
+1

**Comment by websirnik** [comment]
+1

**Comment by jfletcher-nuxeo** [comment]
+1

**Comment by bitwiseman** [comment]
@jfletcher-nuxeo, @websirnik , @frasator , @kentliau , 
I believe this is fixed in 1.6.0.  Please take a look at the wrap_attributes settings.

**Comment by jfletcher-nuxeo** [comment]
So `wrap_attributes=auto` doesn't seem to do anything.  What's the expected behavior? The code doesn't seem to do anything with that setting.

`wrap_attributes=force` does not completely address OP's issue.  With this convention the indentation should be based on the position of the first attribute, not based on a fixed width. Maybe I'll make this a new issue.

**Comment by saritasa** [comment]
agreed with @jfletcher-nuxeo , better to position by first attribute

**Comment by Deklin** [comment]
+1

**Comment by phamhongphuc** [comment]
+1

**Comment by fabioel** [comment]
+1

**Comment by jorgeramirez** [comment]
does anyone get this to work?

**Comment by bitwiseman** [comment]
@jorgeramirez - See #1015.  Does `wrap_attributes = "force-aligned"` work for you?

**Comment by Vortilion** [comment]
Any news on this issue? its quite annoying!

**Comment by bitwiseman** [comment]
@Vortilion 
This issue is closed fixed.  What's your question?  Please join us on Gitter if you want to chat.

**Comment by Vortilion** [comment]
Where can I do this? As far as I can see it here it’s not fixed? This option does nothing for me... it always formats the html attributes as one liner...ö
