### ISSUE TITLE
HTML normalization

### ISSUE THREAD

**Issue by mightyiam** [beautify-web/js-beautify#456]
I'm using `html_beautify` within a testing framework, [like this](https://github.com/mightyiam/wymeditor/blob/53dd15f233cf8cbdda1df39512c1a7e2756ad3bf/src/test/unit/utils.js#L47).

It is already very useful for this purpose because its beautified output is far more easy for me to visually inspect than something like `<ol><li>0<ul><li>0.0<ul><li>0.0.0</li><li>0.0.1</li></ul></li></ul></li></ol>`.

During the tests the HTML begins as a string and then gets turned into browser DOM and manipulated and then back into a string and then beautified and then compared with another beautified string that serves as the expected HTML.

So the beautification also serves as a normalization. And it works pretty well, in most cases.

But it is missing some features:
- Consistent and foreseeable sorting of attributes (perhaps in a widely used ordering rule set like ASCII?).
- Perhaps tag close standard conversion switch (`<br />` vs. `<br>`).

I couldn't think of more but there probably are more.

So each of these could be a separate switch and there could be one, `dom_testing`, switch, that would turn those on.

**Comment by bitwiseman** [comment]
This issue is old and out of scope.  Should the project ever change to support non-whitespace beautification, we can revisit.
