### ISSUE TITLE
Double curly braces does not beautify

### ISSUE THREAD

**Issue by agarwlGaurav** [beautify-web/js-beautify#460]
I am trying to use Bracket with Meteor.js, the code on double curly braces does not respect line breaks and indentation (see image)

![](https://cloud.githubusercontent.com/assets/1813116/2882659/3c4dbca0-d491-11e3-93f9-11e8a0b6391a.png)

**Comment by bitwiseman** [comment]
Please provide text for input, expected output, actual output.

**Comment by terryupton** [comment]
+1 for Twig
