### ISSUE TITLE
Array formatting inconsistencies

### ISSUE THREAD

**Issue by acls** [beautify-web/js-beautify#463]
If I have an array with object literals in this format:

``` javascript
var v = [
  {
    id: 1,
  }, {
    id: 2,
  },
];
```

When formatted it looks like this:

``` javascript
var v = [{
  id: 1,
}, {
  id: 2,
}, ];
```

But if the first item is anything but an object literal, the formatted output will match the input:

``` javascript
var v = [
  0, {
    id: 1,
  }, {
    id: 2,
  },
];
```

The two differences between the two formats are:
- The open and close brackets of the array are on different lines than the array items.
- The array items are indented one level more than the array brackets.

Changing one item in the array shouldn't change the formatting of the entire array. Which means one format should be chosen, right? So I would suggest the latter format should be chosen for these two reason:
- The code is easier to read and follow because of the extra indentation. (which people will probably argue against)
- Sublime Text can properly code fold it. With the former format sublime only collapses the first object instead of the entire array. (which people can't argue against:-)

**Comment by kdelmonte** [comment]
@bitwiseman and @acls , was this ever resolved?

**Comment by acls** [comment]
@kdelmonte It looks like it may be resolved. On http://jsbeautifier.org/ I was able to get the example to work with these config changes:
- Changed indentation select to: Indent with 2 spaces (only because the example uses 2 spaces)
- Changed braces select to: Attempt to keep braces where they are
- Checked: Keep array indentation?
