### ISSUE TITLE
Unnecessary spaces in PHP code

### ISSUE THREAD

**Issue by mrpavlikov** [beautify-web/js-beautify#490]
I have some html file with php insertions:

```html
<h1 class="content-page-header"><?=$view['name']; ?></h1>
```

After beautifying I use to have this:

```html
<h1 class="content-page-header">
    <?=$view[ 'name']; ?>
</h1>
```

See that space right after `[`. 

Also code like this: 
```html
<?= $view['content'][0]['descr']; ?>
```

becomes:

```html
<?=$ view[ 'content'][0][ 'descr']; ?>
```

and ofc breaks syntax.

I seem to be unable to find the way to solve this. Is there any?

**Comment by dboune** [comment]
I believe the best option for this case, and other similar tickets here, is to allow beautify-html to leave the contents of `<?= ... ?>` and `<?php ... ?>` tags unformatted. I'm sure there may be other tags that could benefit from the same treatment.  So far I have not found any existing setting sufficient to remedy this or other similar issues.

Should someone come along with a PR to handle PHP, wonderful, but until then the ability to ignore it would be extremely useful.

**Comment by bitwiseman** [comment]
Agreed.

**Comment by dboune** [comment]
:clap: Thank you!

**Comment by sufius** [comment]
Hello, unfortunately this bug still exists ((

the following code is formatted correctly:

```
<script>
  $(document).layoutEdClient({
    'roomName': '<?php echo $sf_params->get("pmbRoomName"); ?>'
  });
</script>
```
and this is formatted correctly too:

```
<script>
  $(document).layoutEdClient({
    'roomName': "<?php echo $sf_params->get('pmbRoomName'); ?>"
  });
</script>
```

Buuuuut this not:

```
<script>
    $(document).layoutEdClient({
        'roomName': '<?php echo $sf_params->get('pmbRoomName'); ?>'
    });
</script>
```

it will be formatted to this:

```
<script>
  $(document).layoutEdClient({
    'roomName': '<?php echo $sf_params->get('  <--- Line break!!! Why?
    pmbRoomName '); ?>'  <--- Space!!! Why?
  });
</script>
```

The problem lies in the php-single quotes inside of the js-single quotes.

Do you have any idea how to solve this problem? The quotes inside of the php tag should be ignored.

**Comment by esetnik** [comment]
This is still happening for unclosed single quotes.

Example:
```php
<a href='' onclick='doIt("<?php echo str_replace("'", "\\ ", $var); ?>  "); '>
                            Test
                        </a>
                
<?php include_once $_SERVER['DOCUMENT_ROOT'] . "/shared/helpModal.php";  ?>
```

Output:
```
<a href='' onclick='doIt("<?php echo str_replace("' ", "\\ ", $var); ?>  "); '>
                            Test
                        </a>
                
<?php include_once $_SERVER['DOCUMENT_ROOT '] . "/shared/helpModal.php";  ?>
```

Note that `$_SERVER['DOCUMENT_ROOT ']` will be broken after formatting.

**Comment by bitwiseman** [comment]
@esetnik 
Wow, that is bad.  Please open a new issue.
