### ISSUE TITLE
Preserve new line at end of file

### ISSUE THREAD

**Issue by hezjing** [beautify-web/js-beautify#492]
Hi,

The js-beautify will remove the last new line before inside the HTML script tag. For example the new line in the following HTML script, 

```
<head>
  <script>
    mocha.setup('bdd');

  </script>
</head>
```

will be removed after js-beautify reformatted the file,

```
<head>
  <script>
    mocha.setup('bdd');
  </script>
</head>
```

However, the problem is ESLint will complaint that a newline required at end of file but not found (eol-last).

May I know if we can configure js-beautify not to remove the last newline?

**Comment by Jiaaa1014** [comment]
it helps if remove the extension `Beautify`  that's confused and bothering when using ESLint

**Comment by tkalfigo** [comment]
For those wondering how to enable this on the command line, it is provided by the `-n` flag.

**Comment by jonkri** [comment]
I may be missing something obvious here, but is there a way to have `-n` add a newline at the end of the file, but at the same time __not__ add newline at the end of `script` or `style` elements, like so:

```html
<script>
    console.log()

</script>
<style>
    body {
        color: blue;
    }

</style>
```

I would like the resulting markup to be...

```html
<script>
    console.log()
</script>
<style>
    body {
        color: blue;
    }
</style>
```

... with a newline after `</style>.

Thanks!

**Comment by bitwiseman** [comment]
@jonkri 
[Settings overrides](https://github.com/beautify-web/js-beautify#setting-inheritance-and-language-specific-overrides) should work for this.  Set the html (or root) setting to `true` and set the value for `js` and `css` children to `false`.    It would look something like this. 

```json
{
  "end_with_newline": true,        
  "html": {
    "js": {
      "end_with_newline": false        
    }
    "css": {
      "end_with_newline": false        
    }
  }
}

**Comment by jonkri** [comment]
@bitwiseman: Brilliant! Thanks a lot! :slightly_smiling_face:

**Comment by nelson6e65** [comment]
> 
> 
> @jonkri
> [Settings overrides](https://github.com/beautify-web/js-beautify#setting-inheritance-and-language-specific-overrides) should work for this. Set the html (or root) setting to `true` and set the value for `js` and `css` children to `false`. It would look something like this.
> 
> ```json
> {
>   "end_with_newline": true,        
>   "html": {
>     "js": {
>       "end_with_newline": false        
>     },
>     "css": {
>       "end_with_newline": false        
>     }
>   }
> }
> ```

It triggers this "autofix".

```cson
"atom-beautify":
    d:
      with_newline: true
```

But my scss file still not ending with new line.

I had to disable "Beautify on save" 😞

**Comment by bitwiseman** [comment]
@nelson6e65 
This is not atom-beautify, sorry.  You'll need to address the issue in that project.

**Comment by lechner** [comment]
Hi, `-n` does not work for JS files with the version in Debian _bullseye_. Trailing newlines disappear, which `git` then flags as an error.

I don't think that's a formatting question. Thanks!
