### ISSUE TITLE
HTML Beautify: do not format YAML front matter

### ISSUE THREAD

**Issue by chaenu** [beautify-web/js-beautify#510]
Static site generators like [Assemble](http://assemble.io/) or [Middleman](http://middlemanapp.com/) or Jekyll are supporting YAML front matter at the top of a template. When running html beautify on these templates, the front matter gets messed up. 

So this yaml front matter:

```

---
title: Test
is-test: true

---
```

converts to:

```
--- title: Test is-test: true ---
```

I would suggest to ignore everything "wrapped" between three dashes or to add an extra option.

Further information: http://assemble.io/docs/YAML.html or http://middlemanapp.com/basics/frontmatter/

**Comment by Serhioromano** [comment]
I do believe that beautifier should have a parameter like `preservenewlines` . If it already have it then preserve new lines in the text. It is not only issue of front matter. For example let's say there is HTML code and some people work in VS Code and other in MidnightCommander right on the server. that is why all text is formatted like this.

```html
<p>
    This is multiple
    line text, that is
    easy to read in 
   MC
</p>
```

This works right when HTML is rendered and also visible in MC. But if someone format it with beautifier this is gone.

So preserve new lines in the text would awesome.
