### ISSUE TITLE
sass/less: variable formatting, value set to rgb()

### ISSUE THREAD

**Issue by gnrlbzik** [beautify-web/js-beautify#512]
This does not generate parsing bug, but rather weird formatting.

This has been issue in sass code formatting, but i assume this might be formatted same way in less code as well.

following is reformatted:
```
$success:rgb(150, 206, 86);
$info:rgb(50, 170, 225);
$warning:rgb(246, 152, 17);
$error:rgb(207, 54,8);
```

into:
```
$success:rgb(150,
206,
86);
 $info:rgb(50,
170,
225);
 $warning:rgb(246,
152,
17);
 $error:rgb(207,
54,
8);
```

**Comment by bitwiseman** [comment]
I believe this is fixed. If you can verify and comment, I will reopen.

**Comment by gnrlbzik** [comment]
Thank you @bitwiseman . Will do, setting up new project soon.
