### ISSUE TITLE
How add newline after <br>?

### ISSUE THREAD

**Issue by bernex** [beautify-web/js-beautify#513]
I want to do like:

```
Text<br/>a<br><br>b
```

to

```
Text<br/>
a<br>
<br>
b
```

But do not understand...
thanks!

**Comment by NemoStein** [comment]
I'm having the exact same issue.
This ticket is years old, so I'll assume that was forgotten (poor boy).

Can we have this feature implemented?

**Comment by MartyGentillon** [comment]
It looks like this can be added after line 921 and line 930.  We will have to also add a new configuration option.
