### ISSUE TITLE
Kendo Template scripts get messed up!

### ISSUE THREAD

**Issue by lamuertepeluda** [beautify-web/js-beautify#516]
Hi,

I'm trying to beautify some code which uses [kendo templates](http://docs.telerik.com/kendo-ui/getting-started/framework/templates/overview) in HTML.  
They are a kind of script tag which mixes html and javascript. The beautifier inserts spaces between the angular braces of some html element inside the tags. What can I do? Is this a bug/unsupported feature or a bad setting?

Example:
```html
    <script type="text/x-kendo-template" id="LVI_User_Template">
        <a>
            <h2 data-bind="value: username">#: username #</h2>
            <img src="#: imgurl #" />
        </a>
        <a data-role="detailbutton" data-icon="compose"></a>
    </script>
```
becomes
```html
        <script type="text/x-kendo-template" id="LVI_User_Template">
        < a >
            < h2 data - bind = "value: username" > #: username# < /h2>
            <img src="#: imgurl #" / >
            < /a>
        <a data-role="detailbutton" data-icon="compose"></a >
        </script>
```

which causes my app not to display correctly.

Any solution is welcome! Thanks in advance

**Comment by bitwiseman** [comment]
Fixed with #494.
