### ISSUE TITLE
html-beautify's max_preserve_newlines preserves one new line too much

### ISSUE THREAD

**Issue by raphinesse** [beautify-web/js-beautify#517]
`"max_preserve_newlines": 2` will preserve 2 consecutive blank lines (ergo 3 newlines) when beautifying HTML. With JS this behaves like the name would suggest.

Personally I would have preferred `max_preserve_blank_lines`, but that's just my two cents.

Using the JS-Version of js-beautify.

**Comment by raphinesse** [comment]
Has this been fixed in 1.7.6?

**Comment by bitwiseman** [comment]
Will be.
