### ISSUE TITLE
Can't get "unformatted" to work

### ISSUE THREAD

**Issue by SubZane** [beautify-web/js-beautify#518]
In my config file for the beautifier I want to add the li element so that the beautifier won't beautify it. But it doesn't seem to work as my <li>...</li> rows still gets formatted into two rows. Am I doing something wrong?

input:
```
<nav class="sidenav hidden-xs hidden-sm">
<ul>
<li><a href="#">Lorem ipsum</a></li>
<li><a href="#">Lorem ipsum</a></li>
</ul>
</nav>
```

Output:
```
<nav class="sidenav hidden-xs hidden-sm">
  <ul>
    <li><a href="#">Lorem ipsum</a>
    </li>
    <li><a href="#">Lorem ipsum</a>
    </li>
  </ul>
</nav>
```

Expected output
```
<nav class="sidenav hidden-xs hidden-sm">
  <ul>
    <li><a href="#">Lorem ipsum</a></li>
    <li><a href="#">Lorem ipsum</a></li>
  </ul>
</nav>
```

**Comment by adrien-be** [comment]
Why closed?

**Comment by SubZane** [comment]
I think it's closed because it now works as intended. I've tested again and added "li" to unformatted and it works! :)
