### ISSUE TITLE
HTML beautifier inserts extra newline into <li>s ending with <code>

### ISSUE THREAD

**Issue by domenic** [beautify-web/js-beautify#524]
Trying to use this for some ES spec stuff... Running

```html
<ol><li>a</li><li>b<code>c</code></li></ol>
```

through the HTML beautifier gives

```html
<ol>
  <li>a</li>
  <li>b<code>c</code>
  </li>
</ol>
```

but I would expect

```html
<ol>
  <li>a</li>
  <li>b<code>c</code></li>
</ol>
```

**Comment by domenic** [comment]
This now works with `<code>`, but for some reason is not working for elements I mark as `unformatted` myself.

**Comment by bitwiseman** [comment]
Please open a new issue with examples.
