### ISSUE TITLE
Less: Sorts the a-pseudo elements in wrong order

### ISSUE THREAD

**Issue by SubZane** [beautify-web/js-beautify#533]
This gets sorted
```
a.btn-blue-outline {
  &:link,
  &:visited {
    background-color: transparent;
    border: solid 2px @ab_blue;
    color: @ab_blue;
  }
  &:active {
    background-color: @ab_blue;
    color: #fff;
  }
  &:hover {
    background-color: @ab_blue;
    color: #fff;
  }
}
```
Like this:
```
a.btn-blue-outline {
  &:active {
    background-color: @ab_blue;
    color: #fff;
  }
  &:hover {
    background-color: @ab_blue;
    color: #fff;
  }
  &:link,
  &:visited {
    background-color: transparent;
    border: solid 2px @ab_blue;
    color: @ab_blue;
  }

}
```
There are some notes on the order of these pseudo classes:

"Note that the A:hover must be placed after the A:link and A:visited rules, since otherwise the cascading rules will hide the 'color' property of the A:hover rule. Similarly, because A:active is placed after A:hover, the active color (lime) will apply when the user both activates and hovers over the A element."

**Comment by bitwiseman** [comment]
@SubZane - The beautifier does not do sorting. How did you get this output?

**Comment by SubZane** [comment]
This was 2 years ago, I cannot even remember posting this. Sorry :)

**Comment by bitwiseman** [comment]
Okay. 😄
