### ISSUE TITLE
Need option to ignore brace style

### ISSUE THREAD

**Issue by c32hedge** [beautify-web/js-beautify#538]
"Where to stick your stupid braces" is a common hot button for many teams so having to choose between collapse, expand, and end-expand will force us to either fight that battle or choose a different tool. Can we get an "ignore" option for -b | --brace-style, or else a separate --keep-brace-style option?

**Comment by markortiz** [comment]
Can we really implement `"ignore"` all braces? I mean ignore opening and closing braces but still fix any whitespaces in between braces?
Currently I'm coding reactjs using babel es6 and some decorations. I used more functional programming and most of it I wanted to remain in the same line. 

When I use `"brace_style": "none"` the first brace will remain on the same line while the closing brace will be on the next line. 

I hope to see this feature on [https://github.com/victorporof/Sublime-HTMLPrettify](https://github.com/victorporof/Sublime-HTMLPrettify
)

**Comment by bitwiseman** [comment]
If you see a problem, please file a new issue and reference this one.
Also, provide config settings, input, actual output, desired output.
