### ISSUE TITLE
Use inline-elements package for unformatted HTML tags

### ISSUE THREAD

**Issue by domenic** [beautify-web/js-beautify#539]
I wanted to add a HTML element to the list of ones that are unformatted. I thought I'd have to copy the entire list from js-beautify's source and then add mine at the end. HOWEVER, I fortuitously discovered https://www.npmjs.org/package/inline-elements which contains them as a package. Awesome!

I think js-beautify should use that package :)

**Comment by bitwiseman** [comment]
Inline elements have been added.  This list is not so difficult to maintain internally.
