### ISSUE TITLE
Integrating editor config

### ISSUE THREAD

**Issue by ilanbiala** [beautify-web/js-beautify#551]
What do you guys think about taking into account editorconfig files when beautifying. I'm not sure how many people use this in a package/plugin/build proccess way, but when JSBeautify is used to beautify a file, some settings that editorconfig sets up are disregarded and overriden like trailing newlines. Do you guys think it would be a good idea to allow people to pass in a .editorconfig file programmatically and for the CLI look for one in the cwd and take these settings into account to avoid that code being duplicated everywhere else?

**Comment by dcharbonnier** [comment]
editorconfig support would be very very nice

**Comment by bitwiseman** [comment]
Please help!  Submit a pull request!

**Comment by justrossthings** [comment]
this is would be really useful to contribute to open source projects. Make it pls! ლ ( ◕  ᗜ  ◕ ) ლ

**Comment by mitermayer** [comment]
Has anyone create a PR for this? I am happy to create one if no-body has done it yet.

**Comment by ethanluoyc** [comment]
I am starting to implement the editorconfig functionality. Anybody who wants to review my code?

**Comment by ethanluoyc** [comment]
I have implemented the feature. Please feel free to try it out and comment on it.
