### ISSUE TITLE
yield statements are being beautified to their own newlines since 1.5.2

### ISSUE THREAD

**Issue by jemartti** [beautify-web/js-beautify#560]
Version @1.5.2 included 820d267 to resolve #458. However, this fix introduced some unintended behaviour for beautifying code that includes `yield` statements; specifically, it's forcing every `yield` statement to start on a new line.

For example:
```
result = yield pgClient.query_(queryString);
```
is being beautified to:
```
result = 
    yield pgClient.query_(queryString);
```
when it should be remaining unchanged.

Since we're building a koa app, we're stuck with pinning to version @1.5.1 as this is causing some widespread annoyances in our codebase.

**Comment by magicdawn** [comment]
+1

@jdc0589 when can this `yield` fixed in  JsFormat

**Comment by drewhamlett** [comment]
Any news on this?

**Comment by bitwiseman** [comment]
I've been busy with the job that pays me...

**Comment by drewhamlett** [comment]
Haha.  I got you man.  I'll get you a pull request.

**Comment by divergant** [comment]
I want to see an Extension for Brackets 
like this photo
http://oi59.tinypic.com/30tri94.jpg
when I select tag the points between open and closed tag colored with red 
also I have closing and opening mark in the left
just like Notepad++

**Comment by MetaMemoryT** [comment]
:+1:

**Comment by magicdawn** [comment]
Any Update ...

I tried to remove `yield` form line_starters, it just workes for this case. Don't know whether this will bring other side effects.

https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L1429

test.js
```js
function test * (arg1) {
  var text = yield getText();
}
```
![2015-03-04_22-06-11](https://cloud.githubusercontent.com/assets/4067115/6485032/abb293b8-c2bb-11e4-938a-a1b892141317.png)

should I get PR for this small modification ?

**Comment by magicdawn** [comment]
手滑 function * test 写成了 function test *

![2015-03-04_22-15-22](https://cloud.githubusercontent.com/assets/4067115/6485133/5d0000b0-c2bc-11e4-88be-5779e9c42622.png)

**Comment by jemartti** [comment]
@magicdawn: #458 explains why `yield` is placed in `line_starters`.

We can't keep going back and forth on these two bugs; a proper solution is needed.

**Comment by bitwiseman** [comment]
@jemartti - we're not going back and forth.  `yield` is a keyword but it could probably just be moved to reserved words.

**Comment by jemartti** [comment]
@bitwiseman: I know, I'm the one that opened this issue and pointed out that it's a follow–on bug from #458 :). My comment was referring to @magicdawn's suggestion not being sufficient, as it would result in reopening the previous bug.

**Comment by bitwiseman** [comment]
Ah.  :smile: Got it.
