### ISSUE TITLE
Generates faulty :not formatting

### ISSUE THREAD

**Issue by rebelliard** [beautify-web/js-beautify#561]
The beautifier adds some spaces between `not` directives that break the styles:

`.form-group:not(:last-child)` becomes `.form-group: not(: last-child)`

**Comment by noducks** [comment]
Just ran into this myself using 'Less' 

+1 for a fix.

**Comment by noducks** [comment]
Just ran into this too. +1 for a fix.

**Comment by bitwiseman** [comment]
@rebelliard, @noducks, This appears to be fixed. 

On http://jsbeautifier.org/ this remains unchanged:
```html
<style>
    .form-group:not(:last-child)
</style>
```
Can you verify?

**Comment by bitwiseman** [comment]
Maybe #557 is the root issue?

**Comment by bitwiseman** [comment]
Maybe #557 the actually issue?

**Comment by noducks** [comment]
Yes. It is fixed now. Thanks.

**Comment by bitwiseman** [comment]
Thanks!
