### ISSUE TITLE
Diacritics in utf-8 encoded files parsed incorrectly using the command-line

### ISSUE THREAD

**Issue by ampersand55** [beautify-web/js-beautify#581]
```
js-beautify -x -o ./out.js in.js
```

in.js:

``` javascript
var åäö;
```

out.js:

``` javascript


var å ä ö;
```

(there is an added empty line in the beginning of out.js). 

Using python 2.7.8 on windows 7.

**Comment by bitwiseman** [comment]
Can you try it with the current master branch python?

**Comment by bitwiseman** [comment]
@ampersand55 - Ping?
