### ISSUE TITLE
No option to "Indent with tabs" for HTML files

### ISSUE THREAD

**Issue by whatsnewsaes** [beautify-web/js-beautify#587]
Indent_with_tabs: true ---- this option is only available under the "JS" section.

I tried copying this rule to the HTML section. Did not work

**Comment by rlindner81** [comment]
I was looking for this today and it is indeed missing. 

The available options for both HTML and CSS are fewer than for JS, as stated in
https://github.com/beautify-web/js-beautify/blob/master/README.md

In my opinion, it would make a lot of sense to at least add the tabs option.
