### ISSUE TITLE
Support for Custom web-components 

### ISSUE THREAD

**Issue by mhartington** [beautify-web/js-beautify#590]
Originally posted here.
https://github.com/maksimr/vim-jsbeautify/issues/70

With custom web components and angular directives, js-beautify doesn't properly format them.

I found this repo which has the regex for web components in vim, which would help vim.beautify, but it relies on this repo under the hood. 

Any plans on custom web components support?

**Comment by mhartington** [comment]
Alright, so apologies first. 
The mistake came from me :disappointed: 

So jsBeautify does work with custom elements, but you got make sure you're calling the right functions....

Originally I was just calling `jsBeautify()` on everything. So html was getting processed thought the javascript beautifier. Little did I know that there was multiple functions per file type 

```
" JSBeautify
  autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for html
  autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
  autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
```
All in all, once you specify what function to call, (html, js, or css) everything works fine. 
So no issue on your part! 
Sorry to be a bother

**Comment by bitwiseman** [comment]
No problem!  Enjoy!
