### ISSUE TITLE
Space does not let save using "&:"

### ISSUE THREAD

**Issue by netlarico** [beautify-web/js-beautify#594]
I can't save the File when is like that:

<pre>
.div {
  &: after {}
}
</pre>

or:

<pre>
.sample {
  &: hover {
    color: red
  }
}</pre>

Should Be:
<pre>
.div {
  &:after {}
}
</pre>

<pre>
.sample {
  &:hover {
    color: red
  }
}</pre>

A space is created and does not let save the document.  (just usign &:)

**Comment by bitwiseman** [comment]
I think we have this as a bug report already, but I'll double check

**Comment by bitwiseman** [comment]
This does not repro for me.  I've tested on the website ( ) and this remains unchanged:
```
<style>
    .div {
        &:after {}
    }
</style>
```

I'm going to move this to 1.6.0 for further review, but I'm pretty sure it is fixed and working correctly in 1.5.4.
