### ISSUE TITLE
Difference between brace styles? (collapse vs end-expand)

### ISSUE THREAD

**Issue by CaitlinWeb** [beautify-web/js-beautify#596]
Sorry if this has been answered before or is explained somewhere, but I couldn't find it.

First let me start with an example. In my code I have a lot of objects that hold settings for functions. With the option `brace_style: collapse`, I would expect:

``` javascript
function someFunc(settings) {
  return settings.set;
}
someFunc( { set: 'string' } );
```

But maybe if it's large enough (like 3 or more properties? maybe that could be a setting?):

``` javascript
someFunc( {
  set: 'string', 
  set2: 'string2',
  set3: 'string3'
} );
```

Except that it instead does this:

``` javascript
someFunc( { 
  set: 'string' 
} );
```

When there are a lot of these objects being used, it can be quite hard to read. I'd like "collapse" to mean that smaller curly-braced code (statements, objects, anonymous functions, etc) would all stay on one line.

I also don't see a difference between "collapse" and "end-expand". As far as I can tell, they do the same thing.

**Comment by Crystal-RainSlide** [comment]
Searching `js-beautify brace-style explain` on Google will lead to this issue. Those who really want to learn this without reading the code can get what they want.
