### ISSUE TITLE
only print the file names of changed files

### ISSUE THREAD

**Issue by coderhaoxin** [beautify-web/js-beautify#597]
for now, when I run `js-beautify` from cli, it will print all the file names passed to `js-beautify`, but some are not changed.

So, it's better to print the names of `changed files only`.

**Comment by bitwiseman** [comment]
Could you give an example of the command-line you call and the output?

**Comment by coderhaoxin** [comment]
Forgive my pool English :cry: 

When I run the cli with `-r` flag, it will display all the files passed to the cli. Such as I have some files

```
a.js
b.js
c.js
```

Always show

```
beautified a.js
beautified b.js
beautified c.js
```

But, not all the files are changed, some files have been beautified.
Only display the changed files, such as (If only b.js is changed)

```
beautified b.js
```

**Comment by bitwiseman** [comment]
Ah, ok.

**Comment by bitwiseman** [comment]
Updated and added tests.  @coderhaoxin - please take a look and tell me if the behavior is still what you'd expect.
