### ISSUE TITLE
Keep trailing spaces on comments

### ISSUE THREAD

**Issue by sitegui** [beautify-web/js-beautify#598]
Hello,

I've noticed that trailing spaces on comments are stripped in some cases. Some examples that keep them:
```
// A line comment  
var a = 2
```
```
/*
A multiline with no star  
*/
var a = 2
```

But this one does not:
```
/*
* A multiline with star  
*/
var a = 2
```
(Tested on web)

For my use case, this is bad because js-docs comments are processed as Markdown, and two trailing spaces is the markdown way to print a new line in the final rendering.

This seems like a bug, since some formats do keep the trailing space, but I would like some confirmation on that.

Happy Holidays,
Gui

**Comment by bitwiseman** [comment]
Interesting.  Shouldn't be hard to fix.

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L1157
If we change that `trim` to `ltrim`, I think that would do it.
