### ISSUE TITLE
Inducing errors on Android XML files

### ISSUE THREAD

**Issue by rbaprado** [beautify-web/js-beautify#601]
<item name="android:cacheColorHint">@android:color/transparent</item>
Turns into:

    <item name="android:cacheColorHint">@android: color/transparent</item>

Side-question: is there a way to preserve newlines in XML files?

**Comment by bitwiseman** [comment]
You realize we don't support xml beautification, right?

**Comment by rbaprado** [comment]
In fact, I doo :-P

Initially I raised an issue to a Atom plugin (Atom Beautify) with a example
XML (it could not handle Android XML files) but the people there told me to
raise this issue to js-beautify.

Please refer to this discussion:
https://github.com/Glavin001/atom-beautify/issues/158

Sorry for any noise I may have created.

Em Thu Jan 29 2015 at 16:56:12, Liam Newman <notifications@github.com>
escreveu:

**Comment by bitwiseman** [comment]
No probelm .  I've changed this issue to reflect that you're asking for support for xml beautification.   I'm sorry to say I don't see it happening any time soon.

**Comment by bitwiseman** [comment]
Hmm... looking at this a bit more, it looks like it could be a bug...  But I can't repro it on http://jsbeautifier.org/ .   Could you give me a little more detail about the inputs and outputs?

**Comment by rbaprado** [comment]
I do not have the same code base I used at that time anymore, but I
remember the problems were visible when you had a ":" inside the contents
of a tag, like my initial example:

<item name="android:cacheColorHint">@android:color/transparent</item>

<item name="android:cacheColorHint">@android: color/transparent</item>


Em qui, 12 de mar de 2015 às 20:57, Liam Newman <notifications@github.com>
escreveu:

**Comment by bitwiseman** [comment]
Maybe it only happened with a particular setting turned on?

**Comment by rbaprado** [comment]
The only option I remember changing was to suppress warnings for
unsupported languages

Em sex, 13 de mar de 2015 às 14:42, Liam Newman <notifications@github.com>
escreveu:

**Comment by bitwiseman** [comment]
Tried this in atom-beautify as well. Doesn't repro, sorry.
