### ISSUE TITLE
<input disabled> is more beautiful than <input disabled="">

### ISSUE THREAD

**Issue by domenic** [beautify-web/js-beautify#604]
I am using a library that outputs `<input disabled="">`. It would be pretty cool if I passed this through the HTML beautifier and it came out as `<input disabled>`. Right now I am doing a custom post-processing pass.

(This of course applies to all attributes, not just `disabled`. In general the DOM generated is always the same.)

**Comment by bitwiseman** [comment]
The beautifier is whitespace-only reformatter, it does not rework the code.  Sorry.
