### ISSUE TITLE
Space before function arguments (space-after-function)

### ISSUE THREAD

**Issue by adius** [beautify-web/js-beautify#608]
There should be flag to force a space before the function arguments like this:

``` js
function foo (bar, baz) {
    // …
}
```

maybe: `{"space_before_arguments": true}`

**Comment by bitwiseman** [comment]
There's a `--space-after-anon-function`.  Probably call this `--space-after-function`.

**Comment by bcomnes** [comment]
:+1:

**Comment by doque** [comment]
Yes, please.

**Comment by yeahoffline** [comment]
so?

**Comment by bitwiseman** [comment]
It's an enhancement. I'm fixing higher priority issues.  Pull requests are welcome.

**Comment by atrioom** [comment]
Can somebody please point me in a direction on how to hack this into `/js/lib/js-beautify.js` myself? In line 681 I found the statement handling anon_functions. I couldn't get anything going by fiddling with different kinds of statements, e.g.: `if (current_token.text === '(' && last_last_word === 'function') ...

**Comment by jsejcksn** [comment]
@bitwiseman I think calling it `--space-after-named-function` would be the most clear, yes? Like @atrioom, I'm interested to work on this. Where do I start?

**Comment by jsejcksn** [comment]
@atrioom I don't really know what I'm looking at, but maybe [here](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L745)'s a good place to look?

**Comment by bitwiseman** [comment]
@jsejcksn - Name sounds fine. 
And you're in the right area, but you'll want to separate `else if` with `last_type === 'TK_WORD'`.

**Comment by laggingreflex** [comment]
Please also consider async functions

    const a = async () {...}
    async function b () {...}

**Comment by lironess** [comment]
`--space-after-named-function` is a good name

**Comment by zekida** [comment]
+1
i do really hope this gets some more attention as 'javascript standard style' is getting more popular.

**Comment by tahaerden** [comment]
@zekida And it should, it's "standard"! 😄

**Comment by jaysaurus** [comment]
Not to sound mean, but given this is a specification of js *standard* it's kind of surprising it hasn't been a higher priority. I imagine most of us lint with standard these days, heck, most Vue frameworks have it by default.

**Comment by bitwiseman** [comment]
@jaysaurus 
The existence of this project (and its ever growing list of requests for different formatting options) is one more living proof that formatting wars are alive and well in the land of JavaScript.  Your "standard" is an other developer's "never-doing-it-that-way".
