### ISSUE TITLE
Translations / More languages

### ISSUE THREAD

**Issue by herrherrmann** [beautify-web/js-beautify#614]
There are several [pull requests](https://github.com/drewhamlett/brackets-beautify/pulls) for new translations (currently Italian, Spanish, Japanese and German) of your cool plugin - I think those are safe to accept.

Let us translators know if there's anything we're missing.
Thanks and keep up the good work!

**Comment by bitwiseman** [comment]
We're not really involved in the reporting of errors, which is what those commits seem to be focused on.  What kind of feedback would you like?

**Comment by herrherrmann** [comment]
Please excuse me, I actually wanted to post this issue in a [different repository](https://github.com/drewhamlett/brackets-beautify).
