### ISSUE TITLE
Extra space after pseudo-elements within :not()

### ISSUE THREAD

**Issue by jessefisher** [beautify-web/js-beautify#618]
Beautifying this code:
`&:not(:last-child) {}`
Results in this:
`&:not(: last-child) {}`

The extra space causes an error, which tries to identify the line above as an invalid property error.

Thanks for the great extension!

**Comment by bitwiseman** [comment]
Is this the same as #557?

**Comment by jessefisher** [comment]
If the patch for [#557](https://github.com/beautify-web/js-beautify/issues/557) fixes the space between all colon and pseudo-elements then yes. In this instance the extra space has only occured on `:last-child` when inside `:not()`.

**Comment by bitwiseman** [comment]
Um... is there a patch for #557 that I don't know about?

**Comment by jessefisher** [comment]
No, sorry I meant you might be able to fix it with the same solution.

**Comment by bitwiseman** [comment]
Okay, good to have another example.

**Comment by bitwiseman** [comment]
This appears to be fixed.  On http://jsbeautifier.org/ this remains unchanged:
```html
<style>
    &:not(:last-child) {}
</style>
```
Can anyone verify?

**Comment by bitwiseman** [comment]
@jessefisher, This appears to be fixed.  On http://jsbeautifier.org/ this remains unchanged:
```html
<style>
    &:not(:last-child) {}
</style>
```
Can you verify?

**Comment by corgrath** [comment]
This is still broken.

This code:

```
  <style>
      div {
          &:not(:first-of-type) {
              background: red;
          }
      }
  </style>
```

Results in:

```
  <style>
      div {
          &:not(: first-of-type) {
              background: red;
          }
      }
  </style>
```

**Comment by brianfryer** [comment]
I am also experiencing this issue.

**Comment by maelfrize** [comment]
Same here

**Comment by alan-cole** [comment]
Same.

I find if compiling the following:

```
[type="checkbox"]:not(:checked) {
  background-color: transparent;
}

@mixin hello {
  [type="checkbox"]:not(:checked) {
    background-color: transparent;
  }
}
```

The output is:

```
[type="checkbox"]:not(:checked) {
  background-color: transparent;
}

@mixin hello {
  [type="checkbox"]:not(: checked) {
    background-color: transparent;
  }
}
```

Notice the first `:not(:checked)` outside the braces works, the second one inside the @mixin{} braces doesn't work.

**Comment by hmaesta** [comment]
I am facing this bug using [brackets-beautify](https://github.com/Hirse/brackets-beautify/issues/19).

**Comment by jessefisher** [comment]
Sorry for the delay @bitwiseman I was also having this issue using brackets-beautify, but I don't remember how I ended up posting the issue here instead.

The code below works fine in brackets-beautify now, but on http://jsbeautifier.org/ the code inside div{} still has the issue with the extra space on both lines as @alan-cole has said.

```html
<style>   
    [type="checkbox"]:not(:checked) {
        background-color: transparent;
    }
    div {
        &:not(:last-child) {}
        [type="checkbox"]:not(:checked) {
            background-color: transparent;
        }
    }
</style>
```
