### ISSUE TITLE
using html-beautify on handlebars template deletes unclosed tag if on second line

### ISSUE THREAD

**Issue by ezpuzz** [beautify-web/js-beautify#623]
when running master version of html-beautify on the following

```

{{page-title}}
```

The output is empty.  It should preserve the tag.

The tag is output fine when on the first line though...

**Comment by ezpuzz** [comment]
it is also deleted if more than one line of whitespace occurs before  the tag

**Comment by bitwiseman** [comment]
Bug obviously. Thanks!
