### ISSUE TITLE
Add semicolons after statements

### ISSUE THREAD

**Issue by pauldraper** [beautify-web/js-beautify#626]
JS's funny semicolon insertion can cause non-obvious bugs.

```javascript
function foo() {
    return
    1
}
```

returns `undefined`.

For this reason, it's considered best practice to explicitly end statements with a semicolon.

It would be nice if js-beautify did this.

In this case, it would format it as

```javascript
function foo() {
    return;
    1;
}
```

(FYI, uglifyjs -b does exactly this.)

**Comment by bitwiseman** [comment]
Out of scope, sorry.  

The beautifier is designed to be purely a code reformatter, it modifies only white space and does no folding or modifying of the code itself.

**Comment by pauldraper** [comment]
I might disagree with those semantics, with whitespace categorically being "not code" and everything else being "code".

The presence and type of whitespace can alter the behavior of program as much as a semicolon. (e.g. placing a newline in `return 1` is highly significant. just as placing a semicolon.)

But I'll concede that it is different than what js-beautify does now.

**Comment by slorenzot** [comment]
The semicolin is not necesary on current JS versions, but is a good practice for back compatibility, it would be a good setting for being include
