### ISSUE TITLE
Publish v1.5.5

### ISSUE THREAD

**Issue by MetaMemoryT** [beautify-web/js-beautify#629]
the recent merge https://github.com/beautify-web/js-beautify/pull/625

adds new functionality, could we get a version bump and npm release for using the new features?

**Comment by bitwiseman** [comment]
There's a few more things I'd like to get in before doing a version bump.  I'll review them again and get something out for this week.

**Comment by joseluisq** [comment]
@bitwiseman bro this sounds great ! :+1:
