### ISSUE TITLE
Support for ES7 async

### ISSUE THREAD

**Issue by Xiot** [beautify-web/js-beautify#630]
I have enabled the ES7 style async / await using babeljs and I've noticed that js-beautify doesn't like it too much.

the line
```
async function(){
}
```

gets 'beautified' into
```
async
function() {
}
```

which breaks compilation.
I haven't looked through the source yet, but is that a way to keep the `async` on the same line?

**Comment by bitwiseman** [comment]
wow, ES7?  PR welcome, but ... ES6 isn't even final yet is it?

**Comment by Xiot** [comment]
ES6 is almost finalized and I like to stay ahead. Also promises are so much
nicer with async / await. I should be able to take a look at it this
weekend.
Since I haven't looked through the code yet you have any pointers on where
to start?

**Comment by bitwiseman** [comment]
Look at this commit: 
https://github.com/beautify-web/js-beautify/commit/b5426a8558ac07bdacc91b437141f4fe0d27b5cb

NOTE: `testjsbeautifier.py` and `beautify-javascript-tests.js` are generated from `test/data/javascript.js`. Add tests to the data file and the code will be generated for both python and js implementations.
