### ISSUE TITLE
Comment causes extra indentation

### ISSUE THREAD

**Issue by gagern** [beautify-web/js-beautify#632]
Using 1.5.4 with default parameters, the following code

```
function foo() { var x; }
function bar() { var y; } // end bar
function baz() { var z; }
```

beautifies to

```
function foo() {
    var x;
}

function bar() {
        var y;
    } // end bar
function baz() {
    var z;
}
```

So apparently the comment after the function is confusing js-beautify, causing extra indentation for the function body, and also causing the lack of an empty line between functions.

**Comment by bitwiseman** [comment]
See #583.
I've copied your example.
