### ISSUE TITLE
Added space before and after dash breaks css

### ISSUE THREAD

**Issue by Wendihihi** [beautify-web/js-beautify#637]
This
<code>body { line-height: 1; font-family: Georgia, serif; }</code>

will turn into this
<pre><code>body {
    line - height: 1;
    font - family: Georgia, serif;
}
</code></pre>

and therefore breaks the css. The outcome should be

<pre><code>body {
    line-height: 1;
    font-family: Georgia, serif;
}
</code></pre>

**Comment by bitwiseman** [comment]
Wow.

**Comment by Wendihihi** [comment]
Yes, I guess the javascript beautifier. I can't figure out where the css beautifier option is. I assumed that it was built in since it was included in the code.

How can I beautify the css?

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify#css--html

**Comment by Wendihihi** [comment]
Thanks. 

Reminder to myself: the css has to be wrapped in <style> for it to format well.
