### ISSUE TITLE
Improve support for xml parts of jsx (React) => spaces, spread attributes and nested objects break the process

### ISSUE THREAD

**Issue by fabien-h** [beautify-web/js-beautify#646]
When working on a `.jsx` file, we have both javascript and xml in the same file. So when I try to beautify the js, it sometimes break all the xml. Would it be a way to ignore parts of the code ? Or to beautify xml as xml and js as js ?

By the way, why are they not considered as e4x XML literals ? It works for most cases, but not always.

For instance, this code works :

	let a = React.createClass( {
		render() {
			return (
				<p className='b'>
					<span>c</span>
				</p>
			);
		}
	} );

But if you add a space around the `=`, like that : `<p className = 'b'>`, it transforms it a very strange way :

	let a = React.createClass( {
		render() {
			return ( < p className = 'b' >
				<span>c</span> < /p>
			);
		}
	} );

And it breaks the syntax highlighter and the transpiler (babel).

The spread attribute `{...this.something}` is not supported => http://facebook.github.io/react/docs/jsx-spread.html#spread-attributes

	let CheckLink = React.createClass({
		render() {
			return <a {...this.props}>{'√ '}{this.props.children}</a>;
		}
	});

Is transformed into :

	let CheckLink = React.createClass( {
		render() {
			return <a {...this.props
			} > {
				'√ '
			} {
				this.props.children
			} < /a>;
		}
	} );

The nested objects are not supported

	let CheckLink = React.createClass({
		render() {
			return <a style={{display: 'block'}}>{'√ '}{this.props.children}</a>;
		}
	});

It transformed into :

	let CheckLink = React.createClass( {
		render() {
			return <a style = {
				{
					display: 'block'
				}
			} > {
				'√ '
			} {
				this.props.children
			} < /a>;
		}
	} );

They both should keep their initial form

**Comment by fabien-h** [comment]
(oh, there is something to enable it in the configuration file :x )

**Comment by bitwiseman** [comment]
As you say works in many cases, but not all. Feel free to file specific bugs as you see them.

**Comment by fabien-h** [comment]
For instance, this code works :

	let a = React.createClass( {
		render() {
			return (
				<p className='b'>
					<span>c</span>
				</p>
			);
		}
	} );

But if you add a space around the `=`, like that : `<p className = 'b'>`, it tranfsforms it a very strange way :

	let a = React.createClass( {
		render() {
			return ( < p className = 'b' >
				<span>c</span> < /p>
			);
		}
	} );

And it breaks the syntax highlighter and the transpiler (babel).

**Comment by bitwiseman** [comment]
Please file this a s new issue.  That looks like something easily solvable.

**Comment by fabien-h** [comment]
Ok, I reopened the issue and changed the title and description a little bit.

**Comment by bitwiseman** [comment]
Cool, that works.

**Comment by fabien-h** [comment]
Quick an clean fix ! Thanks a lot :)
