### ISSUE TITLE
ES6 concise method not propely indented

### ISSUE THREAD

**Issue by fabien-h** [beautify-web/js-beautify#647]
In an object literal, classic methods are correctly indented : 

	let o2 = {
		a: function () {
			return 1;
		},
		b: function () {
			return 2;
		},
		c: function () {
			return 3;
		}
	};

Concise methods does not work that well : 

	let o = {
		a() {
				return 1;
			},
			b() {
				return 2;
			},
			c() {
				return 3;
			}
	};

After the first method, there's one additional indent. Not a major issue, but it makes objects look weird.

**Comment by bitwiseman** [comment]
ES6 is only partially supported and lower priority.  PRs welcome.

**Comment by pgilad** [comment]
:+1:

**Comment by bitwiseman** [comment]
Implementation notes: we currently recognize ObjectLiterals based on `{`, `name`, then `:`.  If we modify that for locations where we expect to find a value (assignment). This will be more imprecise than usual, but would still address this.

http://es6-features.org/#MethodProperties

**Comment by mike-post** [comment]
This is actually a big bug for ember developers, not an enhancement. In ember, all code is defined as a module therefore all code is defined as an object literal. I just ran into this an it's making me look around for a beautifier that supports ES6 due to the pain. :/

**Comment by bitwiseman** [comment]
@mike-post,
Yeah, it's really unfortunate, but it also non-trivial.  
PRs welcome and appreciated.

**Comment by Kilowhisky** [comment]
+1 for ember issues. 

Never looked at this project before but maybe i'll take a swing at it.

**Comment by bitwiseman** [comment]
Looks like this might be fixed already in the upcoming release.

**Comment by bitwiseman** [comment]
Yup, this is covered by the fix for #602
