### ISSUE TITLE
Pseudo-classes formatted incorrectly and inconsistently with @page

### ISSUE THREAD

**Issue by dylanmensaert** [beautify-web/js-beautify#661]
Pseudo-classes are being formatted incorrectly and inconsistently with @page:

<code>@page :first</code> -> <code>@page:first</code> -> <code>@page: first</code>

This is a problem since the last format is invalid css.
Is there a temporary fix where I can disable formatting of pseudo-classes?

**Comment by bitwiseman** [comment]
What version are you using?   What command are your running?   What language are your writing? 
Please give an full example.  Not a one-line snippet, but a valid statement that could be handed to the beautifier and the resulting output and the output you'd expect to see.

**Comment by dylanmensaert** [comment]
As I stated in my comment, it's css.

Original issue:
https://github.com/victorporof/Sublime-HTMLPrettify/issues/207

I am using the packages latest version.
Since the package I use is installed as a direct plugin into Sublime, I have limited knowledge of this library and it's uses.
Is there any other kind of information I can provide you with?

**Comment by bitwiseman** [comment]
You're using the html-beautifier, so
```html
<!-- Input, expected not to change-->
<style>
  @page :first {}
</style>

<!-- Output on first run -->
<style>
  @page: first {}
</style>

<!-- Output on second run -->
<style>
  @page:first {}
</style>
```

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

**Comment by rherring** [comment]
I'm having the same issue. What did you do to get it fixed?

**Comment by dylanmensaert** [comment]
@rherring 

If you are using the sublime plugin, you will have to wait until @victorporof releases a version that contains the fix @bitwiseman provided.

Until then, I believe there is no solution for it.
As a workaround, I format all my pseudo classes to `@page :first` every time before saving.

**Comment by bitwiseman** [comment]
I'll release a new version in the next week or so.

**Comment by victorporof** [comment]
@dylanmensaert Let me know as soon as the @bitwiseman's fix reaches stable. I'll update the sublime plugin then.

**Comment by dylanmensaert** [comment]
Thanks a lot guys!
