### ISSUE TITLE
ES6 Module Loading Object Destructuring newlines

### ISSUE THREAD

**Issue by godd9170** [beautify-web/js-beautify#668]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Module_loading

```
var { ProjectStore } = require('../stores');
```
Becomes
```
var {
    ProjectStore
} = require('../stores');
```

**Comment by bitwiseman** [comment]
Thanks!

Poor formatting but not breaking, right? 
Is this really a JSX issue or more a general ES6 issue?

**Comment by godd9170** [comment]
No it certainly still runs just fine, I'd say it is best classed as an ES6 issue yeah.

**Comment by darlanalves** [comment]
#315 Would fix this too I think

**Comment by bitwiseman** [comment]
Partly, but `var {...} = foo;` is also something the beautifier doesn't really understand yet.

**Comment by darlanalves** [comment]
@bitwiseman I've tried to read the code and figure out how to implement #315, but it's way too much for a initial read.

If you point me how it's done maybe I can help :)

**Comment by bitwiseman** [comment]
We treat all braces the basically the same when talking about expand or collapse.
You might try fixing just this scenario.

**Comment by brantwedel** [comment]
I see alot of places where people don't expect a `{ Literal }` is expanded to
```
{
  Literal
}
```

I think any "Objects" that consist of only Literals should not be broken, this would cover beautification of imports, exports, as well as shorthand objects where the Literal name is expanded, I think in all these situations it is expected to have a single line.

Maybe a config for `collapse_literals` to turn this on and off.

```
import { Thing } from "things";

var { ThingOptions } = require('../options')

var name = "a thing name";

// expanded by some specs to: Thing.setOptions({ name: name });
Thing.setOptions({ name });
Thing.setOptions({
  name: name,
  version: ThingOptions.
});

exports { Thing };
```

**Comment by hugoduraes** [comment]
@brantwedel :+1:

**Comment by loopmode** [comment]
I currently use a naive patch as a workaround until a proper implementation. It works fine for me so far.
primitive, pragmatic.

    // in Sublime Text, Preferences -> Browse Packages, find HTML-CSS-JS Prettify/scripts/node_modules/js-beautify/js/lib/beautify.js
    // find the last line of the 'beautify' function, and place the next lines just before 'return sweet_code';
     
    // es7 decorators
    sweet_code = sweet_code.replace(/@\n/g, '@'); 
    sweet_code = sweet_code.replace(/\)@\s/g, ')\n@'); 
    sweet_code = sweet_code.replace(/    @    /g, '    @'); 
    sweet_code = sweet_code.replace(/@\s/g, '\n@'); 
    // destructuring imports
    sweet_code = sweet_code.replace(/(import {\n)(\t|\s*)/g, '\import {'); 
    sweet_code = sweet_code.replace(/\n}\nfrom\s/g, '} from ');

**Comment by bitwiseman** [comment]
@brantwedel - Interesting idea.  

@loopmode - thanks for the workaround.  As you say, primitive and pragmatic.  :smile:

**Comment by iksose** [comment]
@loopmode  Great fix, works in atom

**Comment by spredemann** [comment]
the fix works, thanks

**Comment by bitwiseman** [comment]
This is sub-case of #511 and #382.  Leaving open for reference.
