### ISSUE TITLE
cannot add braces for short statements

### ISSUE THREAD

**Issue by cuixiping** [beautify-web/js-beautify#669]
sample code:

    if (1) alert(1)
    for (;;) alert(1)

expected result is:

    if (1) {
        alert(1);
    }
    for (;;) {
        alert(1);
    }

actually result is:

    if (1) alert(1)
    for (;;) alert(1)

even I checked the option **Braces with control statement**.
No braces and semicolons are added.

I tested on the web site: http://jsbeautifier.org/?without-codemirror

**Comment by bitwiseman** [comment]
Beautifier doesn't add braces or semicolons.  It only reformats whitespace. This is by design.
