### ISSUE TITLE
JSX/JS: Single field objects should not expand

### ISSUE THREAD

**Issue by r-tock** [beautify-web/js-beautify#674]
Reposted: Originally reported [here](https://github.com/maksimr/vim-jsbeautify/issues/84)
Its common in a react app to write a set field method

```javascript
_setFoo: function() { this.setState({foo: "bar"}); },
```

currently the beautifier expands that to and just scrolls.

```javascript 
_setFoo: function() { 
  this.setState({
    foo: "bar"
  }); 
},
```

Would be great to support a a folded version based on a flag option.

**Comment by vkz** [comment]
Hi. Any chance of this feature landing any time soon? Thx!

**Comment by bitwiseman** [comment]
This is another aspect of #315.  It is highly requested feature.
