### ISSUE TITLE
Calls to functions get completely messed up in Sass (*.scss)

### ISSUE THREAD

**Issue by raduluchian** [beautify-web/js-beautify#675]
When I beautify a Sass file and there is a call to a function the code gets messed up really bad and obviously Sass has errors when compiling. For example there is this function:

    @function headings($from:1, $to:6) {
         ...
    }
And then this would be the call for said function:

    #{headings(1,6)} {
        margin: 0;
    }
What the plugin does is it turns it into this:

    # {
    headings(1, 6)
    }
    {
        margin: 0;
    }
Needless to say this makes the plugin completely unusable if you are using functions in your Sass code, which is quite unfortunate as it seems to be pretty handy.

**Comment by jeremytm** [comment]
+1

**Comment by bitwiseman** [comment]
Fixed at the same time as #689.
