### ISSUE TITLE
Can't Nest Conditionals

### ISSUE THREAD

**Issue by loganknecht** [beautify-web/js-beautify#680]
Hi there!

I'm using this wonderful tool via the sublime html prettify plugin.

I'm having an issue with it where it won't nest conditionals and was redirected to posting here.

------------------------------------------------
Original Posting:
------------------------------------------------
https://github.com/victorporof/Sublime-HTMLPrettify/issues/219
------------------------------------------------

Hello!

I'm having an issue with my code where I want to nest conditional logic for better readability, however upon saving it causes the conditionals to be inlined together.

For example this is how I want the code to look

```javascript
if((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) 
   && (!_.isNull(jqXHR.responseJSON.errMessage) && !_.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}
```

But, when I save it formats it to this

```javascript
if((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) && (!_.isNull(jqXHR.responseJSON.errMessage) && _.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}

```

I tried changing multiple settings, however I wasn't able to really configure it such that it would match the desired style.

Is there a setting that would afford me this ability that I'm unaware of?

**Comment by bitwiseman** [comment]
Yes, the beautifier does not quite support what you are trying.

This works:
```js
if ((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) &&
    (!_.isNull(jqXHR.responseJSON.errMessage) && !_.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}
```

This does not work:
```js
if((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) 
   && (!_.isNull(jqXHR.responseJSON.errMessage) && !_.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}
```

**Comment by loganknecht** [comment]
Aw... Ok. I await with bated breathe for #611. Thank you.

**Comment by bitwiseman** [comment]
#735 added option to control this.
