### ISSUE TITLE
Support for ES7 decorators

### ISSUE THREAD

**Issue by Verdier** [beautify-web/js-beautify#685]
ES7 decorators (https://github.com/wycats/javascript-decorators) are now available in Babel, and heavy used by AngularJS 2 and Aurelia (http://aurelia.io).

Would be awesome to support the upcoming standard. If not for now, a way to ignore a portion of code would also be very useful, such as:

```javascript
// start ignore
@Annotation({
 a: 'value'
})
// end ignore
class A {}
```

**Comment by bitwiseman** [comment]
Wow.  Please provide a link to the es7 information.  I doubt I'll have time to deal with this, but we do shoot for non-breaking behavior where possible.   PR welcome.

**Comment by Verdier** [comment]
Here is the official proposition for decorators (https://github.com/wycats/javascript-decorators/blob/master/README.md). The grammar is fully detailed at the end of the article. The feature is actually in stage 1, but there is a big community pressure due to the full adoption by two major web frameworks.

**Comment by netaisllc** [comment]
+1 
@Verdier , yeah this messes up my Aurelia src big time; do you have a workaround?

**Comment by Verdier** [comment]
Yep @netaisllc I use the latest version of typescript-formatter (https://github.com/vvakame/typescript-formatter) which is able to format pure javascript (TypeScript is a superset of javascript). There is a good grunt task on top of it. The latest version supports decorators. But there is a workaround, because: TypeScripte thinks that decorators are not javascript (which is, for now, not totally absurd... ^^), they are badly formatted. A quick and dirty (but functional) solution is to rename the *.js files to *.ts before the formatting task and rename back to *.js just after. This works fine for me.

**Comment by jeffijoe** [comment]
Any updates on this?

**Comment by amacdougall** [comment]
I've submitted https://github.com/beautify-web/js-beautify/pull/765, which should clear this up. It covers at least the following cases, as seen in the automated test:

```javascript
@foo

@foo(bar)

@foo(function(k, v) {
    implementation();
})
```

@jeffijoe @netaisllc @Verdier @bitwiseman
