### ISSUE TITLE
Replace existing file fails using python beautifier

### ISSUE THREAD

**Issue by surfer190** [beautify-web/js-beautify#686]
Trying to pretty print a `Gruntfile.js`:

So based on:

`Usage: jsbeautifier.py [options] <infile>`

I used:

`jsbeautify -o Gruntfile.js Gruntfile.js`

Result:

`[Errno 2] No such file or directory: ''`

**Comment by bitwiseman** [comment]
Try `-r` instead and just the one file name.

**Comment by surfer190** [comment]
I used: `js-beautify -r Gruntfile.js`

returned:

`[Errno 2] No such file or directory: ''`

**Comment by surfer190** [comment]
@bitwiseman I was using the `python` version. Changed to `javascript` version and it worked

**Comment by bitwiseman** [comment]
Thanks!
