### ISSUE TITLE
[python version] SyntaxError: missing while after do-loop body

### ISSUE THREAD

**Issue by nickdesaulniers** [beautify-web/js-beautify#703]
I have a very large JS file (30MB minified, 70MB beautified, from Emscripten).  Using the python version, the resulting JS does not run, and suffers from a syntax error related to do-while loops.  Unfortunately, I'm not able to share the JS, so that's the only hint I can provide.  My debugger points to the statement:
```
} elseif ((n | 0) == 134) {
```
Which I'm sure is not valid JS, `elseif`.

**Comment by bitwiseman** [comment]
Okay, here's what I'll need from you.  
1. Check that the minified output says `else if`.  
1.a If not, then this is not bug in the beautifier. We don't fix bad javascript, sorry. (end)
1b. If so, then there is a case where the beautifier is turning `else if` into `elseif`.  That's bad. Take the do-while that contains this if statement, and ...
2. Put the selected statement a separate file and try beautifying it alone.   Does the issue still occur? 
2a. If no, got back to the original file and find the function or clause containing the do-while, and ... (do step 2 again.) 
2b. If yes, continue to 3. 
3. Beginning at '} else if ((n | 0) == 134) {', remove extraneous siblings at all levels. That is, try removing all other `else` and `else if` clauses, but leave the starting `if`.  Does it still repro? 
3a. If yes, repeat this at each level, until you get the least code that reproduces the issue. 

4. Decide if you are comfortable posting that code in this issue.  The code you post should at this point be  syntactically correct, but not functionally meaningful, thus making it probably safe to post. 

Then I can work on this issue.   
4. If yes,

**Comment by nickdesaulniers** [comment]
> 1. Check that the minified output says else if.
> 1.a If not, then this is not bug in the beautifier. We don't fix bad javascript, sorry. (end)

Check the pre-minified input?

Sorry, I just burned the beautified version (overwrote it with output from Closure), should have kept it around for forensics.

Without a test case, I'll close the issue.  Worth noting in case it pops up again.

**Comment by bitwiseman** [comment]
Wait, you're feeding the minified file into the beautifier, right?  So, look in the minified file for `elseif`.

**Comment by nickdesaulniers** [comment]
> Wait, you're feeding the minified file into the beautifier, right?

Oops, yeah, man I don't do Monday mornings...

**Comment by bitwiseman** [comment]
:smile: It's cool, just get me the info when you get a chance. 
Thanks.

**Comment by bitwiseman** [comment]
Any update?

**Comment by bitwiseman** [comment]
Closing for now.  Will reopen if needed.

**Comment by nickdesaulniers** [comment]
```
➜  Release  cat Mozilla.js.backup | grep 'else if' | wc -l
      25
➜  Release  cat Mozilla.js.backup | grep 'elseif' | wc -l
       0
```

**Comment by bitwiseman** [comment]
Meaning?  Re-open or not?
