### ISSUE TITLE
ES6 generator shortcut notation breaks

### ISSUE THREAD

**Issue by Verdier** [beautify-web/js-beautify#704]
The following: 

``` javascript
let a = {
 *gen() {
  }
}
```

result in:

``` javascript
let a = { * gen() {

    }
};
```

and:

``` javascript
let a = {
    notGen() {

    },
    * gen() {

    }
};
```

result in:

``` javascript
let a = {
    notGen() {

        },
        * gen() {

        }
};
```

**Comment by bitwiseman** [comment]
@Verdier - I'm sorry this will not make it into this release.  
While this is not beautiful, it is also not a syntax error.

**Comment by bitwiseman** [comment]
http://es6-features.org/#MethodProperties
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by bitwiseman** [comment]
#941
