### ISSUE TITLE
CSS3 Negation Selector gets formatted and breaks LESS

### ISSUE THREAD

**Issue by phillip-haydon** [beautify-web/js-beautify#706]
Given:
```css
div:not(.middle) {

}
```

This gets reformatted as:
```css
div: not(.middle) {

}
```

(A space between `:` and `(`)

This causes LESS parsing to fail, when this is valid syntax. 

https://developer.mozilla.org/en/docs/Web/CSS/:not

**Comment by bitwiseman** [comment]
@phillip-haydon ,  I can't repro this using the input given.  

For instance, on http://jsbeautifier.org/
```html
<style>
    div:not(.middle) {}
</style>
```

Is there more to this example?

**Comment by bitwiseman** [comment]
Maybe #557 the actually issue?

**Comment by phillip-haydon** [comment]
I tried it in a HTML file with `<style>` and it works fine. I tried it again in a LESS file and it broke.

**Comment by bitwiseman** [comment]
How did you run on a LESS file?  When you say file, do you mean that was the only thing in the file?
More detail please.  :smile:

**Comment by phillip-haydon** [comment]
I wonder if its the brackets extension that's broken and not beautify itself. And I've been directed to the wrong repo.

```
div.stats {
    padding-bottom: 20px;
    text-align: justify;
    div: not(.clearer) {
        width: 16%;
        display: inline-block;
        h5 {
            display: block;
            font-size: 14px;
            text-transform: uppercase;
            color: #666666;
            font-weight: 600;
            margin: 0 0 10px 0;
        }
        span {
            font-size: 50px;
            font-weight: 100;
            line-height: 35px;
        }
    }
}
```
![beautifyerror](https://cloud.githubusercontent.com/assets/895629/8197765/562c6dae-14cf-11e5-8907-99f9a9fb35cb.gif)

**Comment by phillip-haydon** [comment]
Brackets currently uses v1.5.4 of js-beautify.

**Comment by bitwiseman** [comment]
I've verified this is a duplicate #557.  The fix will be released within the week in v1.5.7.  At that time, you might file an issue with brackets to upgrade.  It will treat CSS (and LESS) _much_ better than 1.5.4.

**Comment by phillip-haydon** [comment]
Ok cool! Thank you very much. <3

**Comment by derwaldgeist** [comment]
Thanks for fixing this. Highly appreciated.
