### ISSUE TITLE
html tag with < format bug 

### ISSUE THREAD

**Issue by zsytssk** [beautify-web/js-beautify#708]
![87abaf80-03b7-11e5-8100-662d37da6258](https://cloud.githubusercontent.com/assets/2304648/8028158/a902bac6-0dd9-11e5-8bde-80880e6ad8a0.jpg)
to be
![8a34c71e-03b7-11e5-8368-1d6be132ec42](https://cloud.githubusercontent.com/assets/2304648/8028159/b12fc59a-0dd9-11e5-9e21-fde702c4c1a4.jpg)

**Comment by bitwiseman** [comment]
Not a bug.  If you want a `<` you need to use `&gt;`.
