### ISSUE TITLE
Can we treat JS objects differently?

### ISSUE THREAD

**Issue by Jangla** [beautify-web/js-beautify#710]
My main bug bear is that the js-beautifier murders objects. 

So this: http://puu.sh/ijCov/e2cd23c628.png
Becomes this: http://puu.sh/ijCpy/082a016cdb.png

Nasty, right?

So is there an option to leave objects like this alone?

As an additional "nice to have", is there a way to maintain the indents between assignments so they all stay in line like this: http://puu.sh/ijCs4/14096a6139.png

**Comment by bitwiseman** [comment]
See #315 and #365, among others. I'd happily accept help on these.
