### ISSUE TITLE
Is \n hard coded into CSS Beautifier logic?

### ISSUE THREAD

**Issue by corgrath** [beautify-web/js-beautify#715]
JSBeautifier released 1.5.6 with an "eol" fix.

I am looking at the CSS Beautifier code (beautifiy-css.js) and it looks like there are a lot of hard coded  "\n".

I am on a Windows system and I am noticing the files are getting changed in git, but without any visible changes, so I am suspecting its a line ending problem between Windows/Linux environments.

Could it be that CSS Beautifier should have its own eol fix as well?

**Comment by bitwiseman** [comment]
Yes, it should.

**Comment by corgrath** [comment]
Awesome work, thanks!
