### ISSUE TITLE
css: selector_separator does nothing

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#716]
Don't know when this happened, but this option is not connected to anything and not covered by any tests.

**Comment by harryyuanfeng** [comment]
has this been fixed?

**Comment by MacKLess** [comment]
@harryyuanfeng you should be able to use "selector_separator_newline" to accomplish this desired functionality.

**Comment by bitwiseman** [comment]
@MacKLess  You are correct this option has been superseded by `selector_separator_newline`.  Closing this.
