### ISSUE TITLE
beautify HTML argument "preserve-newlines"

### ISSUE THREAD

**Issue by LaKing** [beautify-web/js-beautify#717]
``` javascript
var beautify_html = require('js-beautify').html;

  beat = beautify_html(text, {
       indent_size: 4,
       preserve-newlines: true
 });
```

Gives an error at the middle of preserve-newlines.
Is this a documentation mistake? It doesent seem to work with underscores. 

 -p, --preserve-newlines            Preserve existing line-breaks (--no-preserve-newlines disables)

**Comment by bitwiseman** [comment]
It looks like you have `preserve-newlines` instead of `preserve_newlines`.  On the command line it is `preserve-newlines`, in the options it is `preserve_newlines`.

**Comment by corgrath** [comment]
Awesome work, thanks!
