### ISSUE TITLE
LESS mixins gets formatted strangely

### ISSUE THREAD

**Issue by corgrath** [beautify-web/js-beautify#722]
Given code like this:

```
.mq-medium( {
    position: absolute;
    background: red;
});
```

It ends up like this by the CSS Beautifier formatter:

```
.mq-medium( {
    position: absolute;
    background: red;
}
);
```

It still works, but it just looks a bit strange that } and ); ends up on their own rows.

```
```

**Comment by bitwiseman** [comment]
Need to look at bugfix by @corgrath.  See if it works in general.
