### ISSUE TITLE
beautify.js doesn't have indent_level option

### ISSUE THREAD

**Issue by Hirse** [beautify-web/js-beautify#724]
In the [options documentation](https://github.com/beautify-web/js-beautify#options) I found the setting `indent_level` as _Initial indentation level_ for both CLI and underscored option.

However when using it in the js version, the setting seems to be ignored.
When checking the code, it seems like it should be included somewhere [here](https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L282), but it isn't.

**Comment by bitwiseman** [comment]
Another good report, thanks!
Until this is fixed, you can do workaround this by adding the text of the indent you want to the beginning of the file(s).

For example, before:
```
    // Top of file
    if (test) 
a();
b();
```
After:
```
    // Top of file
    if (test)
        a();
    b();
```

**Comment by thoger** [comment]
FWIW, this is also applicable to the python CLI.  It also accepts the -l / --indent-level option, but ignores it completely.

**Comment by MacKLess** [comment]
I've just submitted a PR addressing this issue. One aspect (the ability to set the indent level at zero in the html and JavaScript); however, is not functional. I'll be filing an issue for this specific issue.
