### ISSUE TITLE
Website went missing?

### ISSUE THREAD

**Issue by CamiloMM** [beautify-web/js-beautify#726]
I'm not sure you've been notified but the site seems to have gone the way of the dodo:

![site not found github pages - google chrome](https://cloud.githubusercontent.com/assets/2404138/8366260/e162e772-1b69-11e5-8a28-8baa7399825d.png)

I wonder what may have caused it.

**Comment by jt3k** [comment]
I confirm

**Comment by dotcarls** [comment]
Also confirm

**Comment by kenzierocks** [comment]
While this is out, you can use http://beautify-web.github.io/js-beautify/.

**Comment by dotcarls** [comment]
Thanks @kenzierocks !

**Comment by bitwiseman** [comment]
Fixed!  My bad!  Thanks, everyone!

**Comment by kenzierocks** [comment]
Thanks!
