### ISSUE TITLE
Spaces between function name an parenthesis

### ISSUE THREAD

**Issue by johannes-z** [beautify-web/js-beautify#727]
It would be great if there was an option for the standard as defined here:
https://github.com/feross/standard#rules 
**Space after function name** `function name (arg) { ... }`
This already exists for anonymous functions, see: https://github.com/beautify-web/js-beautify/issues/372

**Comment by kirkstrobeck** [comment]
+1

**Comment by bitwiseman** [comment]
Duplicate of #608

**Comment by thurt** [comment]
Depending on your environment, a possible alternative is to use their cli [standard-format](https://github.com/maxogden/standard-format). It looks like it currently has plugins for Ace and Sublime.
