### ISSUE TITLE
Unformatted inline tag should have correct newline?

### ISSUE THREAD

**Issue by bitinn** [beautify-web/js-beautify#731]
Pretty sure this is a known issue, but would like to confirm these 2 behaviors are by-design:

Inline style tags in head:

``` html
<head>
    ...
    <meta name="local:token" content="TRHRWkAf-sOQpO6l7UMqfrf17z3eA6zO_EiA"><script id="css-loader">function loadCSS(href,before,media,callback){"use strict";var ss=window.document.createElement("link");var ref=before||window.document.getElementsByTagName("script")[0];var sheets=window.document.styleSheets;ss.rel="stylesheet";ss.href=href;ss.media="only x";if(callback){ss.onload=callback}ref.parentNode.insertBefore(ss,ref);ss.onloadcssdefined=function(cb){var defined;for(var i=0;i<sheets.length;i++){if(sheets[i].href&&sheets[i].href.indexOf(href)>-1){defined=true}}if(defined){cb()}else{setTimeout(function(){ss.onloadcssdefined(cb)})}};ss.onloadcssdefined(function(){ss.media=media||"all"});return ss}
;var l=document.getElementById("css-loader");loadCSS("https://local.dev/dev/app.css?v1.0.18", l);loadCSS("https://local.dev/fonts/webfont.css?v1.0.18", l);</script>
    <noscript>
        <link rel="stylesheet" href="https://local.dev/dev/app.css?v1.0.18">
    </noscript><script src="https://local.dev/dev/app.js?v1.0.18" async></script></head>
```

Inline span in body:

``` html
                    <li class="item">
                        <a href="/" class="m-button rounded heading">
                            <svg class="m-icon">
                                <use xlink:href="/assets/icons.svg?v1.0.18#upload"></use>
                            </svg><span class="m-text">Login</span></a>
                    </li>
```

My setup is:

``` javascript
            html = beautify(html, {
                preserve_newlines: false
                , unformatted: unformatted
            });
```

where unformatted is taken from `inline-elements` module, as mentioned in https://github.com/beautify-web/js-beautify/issues/539

Question:

Is there any reason we can't format the whitespace before and after those inline tags? I am kinda expecting js-beautify to add newline and indent for `script` and `span` in such cases (admittedly not a big issue, just OCD).

**Comment by bitinn** [comment]
Basically I am not sure how intelligent is `unformatted` options, for nested inline elements I think your decision make perfect sense, for inline element within block element, I am not sure?

But I understand making special case for these sort of things can be a maintenance problem...

**Comment by bitwiseman** [comment]
Could you restate your example as input, actual output, and desired output?  I think I get what you're asking but I'd like to make sure.

**Comment by bitinn** [comment]
Example input are very likely a single line, but I will need to double check (generated by `virtual-dom` and `vdom-to-html` modules, so I don't have direct control on how they format).

Actual output is as shown.

Expected outputs:

```
<head>
    ...
    <meta name="local:token" content="TRHRWkAf-sOQpO6l7UMqfrf17z3eA6zO_EiA">
    <script id="css-loader">function loadCSS(href,before,media,callback){"use strict";var ss=window.document.createElement("link");var ref=before||window.document.getElementsByTagName("script")[0];var sheets=window.document.styleSheets;ss.rel="stylesheet";ss.href=href;ss.media="only x";if(callback){ss.onload=callback}ref.parentNode.insertBefore(ss,ref);ss.onloadcssdefined=function(cb){var defined;for(var i=0;i<sheets.length;i++){if(sheets[i].href&&sheets[i].href.indexOf(href)>-1){defined=true}}if(defined){cb()}else{setTimeout(function(){ss.onloadcssdefined(cb)})}};ss.onloadcssdefined(function(){ss.media=media||"all"});return ss}
;var l=document.getElementById("css-loader");loadCSS("https://local.dev/dev/app.css?v1.0.18", l);loadCSS("https://local.dev/fonts/webfont.css?v1.0.18", l);</script>
    <noscript>
        <link rel="stylesheet" href="https://local.dev/dev/app.css?v1.0.18">
    </noscript>
    <script src="https://local.dev/dev/app.js?v1.0.18" async></script>
</head>
```

```
                    <li class="item">
                        <a href="/" class="m-button rounded heading">
                            <svg class="m-icon">
                                <use xlink:href="/assets/icons.svg?v1.0.18#upload"></use>
                            </svg>
                            <span class="m-text">Login</span>
                        </a>
                    </li>
```

In short I think it might be feasible for `unformatted` to only ignore the content / child element within an inline tag, but not sure how smart it has to be in order to not break things.

For example, if `a` is by default inline, `svg` is not, and `span` is inline, how should `span` be formatted?

**Comment by Tigt** [comment]
`<svg>` is an inline element by default, like `<img>`. Its internal tags are tricky; all SVG elements are defined as `display: inline`, but sure don't behave like it.

(Strictly speaking, [the allowed values are `none`, `inherit`, and literally anything else](http://www.w3.org/TR/SVG11/painting.html#DisplayProperty). Firefox will only accept `display: inline` to override other rules, since that's the default `display` of all elements, which is then overridden by UA stylesheets for things like `<div>`, etc.)

To make things worse, for HTML5 SVG, the tags `<title>`, `<desc>`, and `<foreignObject>` all auto-switch to the HTML5 namespace, which means tags inside of *them* are allowed to be block-level elements. (`<title>` at least has its content model restricted to phrasing content.) And the HTML inside of *those* is technically supposed to be well-formed, so self-closing elements matter.

**Comment by bitwiseman** [comment]
@tigt , @bitinn 

Could you try this on 1.6.0 and see what results you get?

**Comment by bitinn** [comment]
@bitwiseman sure, a bit busy lately, will get back to you :)

**Comment by bitwiseman** [comment]
@bitinn Please try this on http://jsbeautifier.org/  v1.8.0-rc4.

**Comment by MacKLess** [comment]
This bug was filed from a time before we had the inline setting. No longer a viable issue.
