### ISSUE TITLE
feature request for 'wrap_attributes_size'

### ISSUE THREAD

**Issue by lili21** [beautify-web/js-beautify#746]
I prefer this
<img width="416" alt="2015-07-24 12 07 22" src="https://cloud.githubusercontent.com/assets/4456380/8867484/621f03ca-31fc-11e5-845f-f6fd5257cdb1.png">

to

<img width="476" alt="2015-07-24 12 12 11" src="https://cloud.githubusercontent.com/assets/4456380/8867508/e2adfd52-31fc-11e5-91f7-8d659b02b496.png">

For each tag, `wrap_attributes_size` equals to first attribute indent.

**Comment by pwambach** [comment]
+1, yes that would make angular development a lot better!

**Comment by kennethkoontz** [comment]
+1

**Comment by bitwiseman** [comment]
Please provide as description using markdown and text with backticks for formatting.  Images are not useful.

**Comment by jfletcher-nuxeo** [comment]
+1

As requested, example of current behavior:

```html
<nuxeo-resource id="oauth2directory"
    path="/oauth2directory/salesforce"></nuxeo-resource>
```
First attribute is on the same line as the element. Subsequent attributes are indented using a fixed amount.

Desired behavior:

```html
<nuxeo-resource id="oauth2directory"
                path="/oauth2directory/salesforce"></nuxeo-resource>
```

First attribute is on the same line as the element. Subsequent attributes have the same indentation as the first attribute.

**Comment by bitwiseman** [comment]
There are now several `aligned` options that do exactly this.
