### ISSUE TITLE
Beautify unbeautified js-code

### ISSUE THREAD

**Issue by Andrej730** [beautify-web/js-beautify#748]
Hello. Perhaps, its not an issue at all, its just suggestion.
You know, there's a lot js-code unbeautifiers that converts usual code in unreadable piece of junk with hexnumbers instead of normal variable names. And a thing that they use very often is collecting all strings from code in one array and then replacing all those strings with links to elements of this array.
Here's one example - http://pastebin.com/JcvJrdCE
Beautifying this code with "Unescape printable chars encoded as \xNN or \uNNNN" option works realy good but code still hard to read. All strings are collected in _0xae17 and then used as elements of array. F.e. this part of code could be more readble:

```javascript
chrome[_0xae17[17]][_0xae17[16]]({
    method: _0xae17[4],
    key: _0xae17[5]
}
```
Like this:

```javascript
chrome["runtime"]["sendMessage"]({
    method: "ConfigGet",
    key: "valuta"
}
```

Will be nice to have such option in beautifier. Also would be nice to replace those gibberish variables (like _0xec46x3) with just usual letters.
And sorry, i dont realy now how hard will be implementing this in current code and maybe i want too much )
Thank you for your attention.

**Comment by bitwiseman** [comment]
Sorry, this is out-of-scope for this project.  Beautifier is a whitespace-only formatter of code, it does not rewrite/modify the code itself.
