### ISSUE TITLE
space-after-anon-function not applied to object properties

### ISSUE THREAD

**Issue by JulianLaval** [beautify-web/js-beautify#761]
I've noticed an inconsistency in the "space-after-anon-function" option, although am unsure whether it is a feature or a bug.

In particular, toggling the option doesn't seem to beautify anonymous functions that are specified as object parameters, e.g.

```
// Original
var objectName = {
  functionName: function(){ ... }
}

// Expected behaviour
var objectName = {
  functionName: function () { ... }
}

// Actual behaviour
var objectName = {
  functionName: function() { ... }
}
```

The fact that the brace is beautified makes me think that this was simply an oversight rather than intentional; if so, what are your thoughts on supporting this?

**Comment by bitwiseman** [comment]
@JulianLaval - This appears to be fixed in 1.6.0.  I need to add regression test for it.

**Comment by JulianLaval** [comment]
Great!

**Comment by bitwiseman** [comment]
I'm going to keep it open until I have the test added.

**Comment by JulianLaval** [comment]
:+1:
