### ISSUE TITLE
function argument with var

### ISSUE THREAD

**Issue by mtangoo** [beautify-web/js-beautify#762]
The beautifier formats fine with function `function fn(x, y)` but with `function fn(var x, var y)` add a new line per argument that is
```js
function fn(var x,
     var y)
```
I want all to behave as `function fn( x,  y)`
Is there an option for that?

**Comment by bitwiseman** [comment]
Is `var` valid in that location?  I've never seen that done.

**Comment by mtangoo** [comment]
Can you explain what you mean? 
I don't understand your comment

**Comment by bitwiseman** [comment]
I think this is valid javascript: 
```js
function fn(x, y)
```

I think this is not valid javascript:
```js
function fn(var x, var y)
```
Please point to documentation for this syntax.

Even if it is valid javascript why would you use it?

**Comment by mtangoo** [comment]
Mhh, I found it on one of my JS in project (not written by me). I since deleted the Project files as they caused me troubles. Since am not JS maverick, I thought may be its something advanced.

I will close this issue and If I happen to remember it, I will update it.
Sorry!
