### ISSUE TITLE
Disable space between the right parenthesis ) and the left curly brace {

### ISSUE THREAD

**Issue by ReinoutvanKempen** [beautify-web/js-beautify#767]
I'd like to disable the placing of a space char between the right parenthesis ) and the left curly brace { in my JavaScript functions. Is there a way I can configure the preferences or do something else to get the desired behavior?

function example(){

}

function(){

}

I now use 'replace with' in Sublime Text 3 to fix it after usage but I'd like something automatic. And then I could also set it to be used on save.

**Comment by bitwiseman** [comment]
Not currently supported.
