### ISSUE TITLE
Added Space on CSS Selector

### ISSUE THREAD

**Issue by jgriffen** [beautify-web/js-beautify#770]
When beautifying an SCSS file I have, the plugin always adds a space in this selector:

```
&:not(: first-child)
```

I remove the space, save the file again, and it adds the space again. Tying this with an SCSS compiler in Brackets, the compiler fails because of the space.

If you need any more information, I'll be happy to provide it.

Thanks.
~ Griff

**Comment by PalmerAL** [comment]
The following selector also shows this issue:

```
	.nav-item:not(:first-child)
```

**Comment by bitwiseman** [comment]
This does not repro in the current version.

**Comment by ahmedam55** [comment]
.blog-menu {
        position: static;
        margin: 45px 0 30px;
        width: 100%;
        display: table;
        li {
            padding: 0;
            width: 50%;
            display: block;
            float: left;
            &:last-child:not(:first-child) {
                padding: $mobile-text-block-padding;
            }
        }
    }
