### ISSUE TITLE
Why added space between < and >?

### ISSUE THREAD

**Issue by re4lfl0w** [beautify-web/js-beautify#771]
I compared libraries.

https://gist.github.com/re4lfl0w/4ee671d210902362ffff

Thanks.

jsbeautifier will fix space problems then I will choose jsbeautifier.

**Comment by prettydiff** [comment]
It looks like the HTML is being parsed as JavaScript.  From reading the documentation it appears the default language setting is for the language JavaScript.  You can change to HTML beautification by requiring the library with the property `.html`.  Look at the readme.md file in this repo for the section CSS & HTML.

**Comment by re4lfl0w** [comment]
@prettydiff I don't understand. Could you put me some example?

I think 

> var beautify_html = require('js-beautify').html;

but I don't know how affect the code in python?

**Comment by prettydiff** [comment]
I am not a Python guy, so I cannot help with that.  Try this to make it work in JavaScript

    var options = {}, //this is where you can populate the JS Beautify options
        beautify_html = require('js-beautify').html;
    beautify_html(code, options);
