### ISSUE TITLE
Newline is inserted after comment with comma_first

### ISSUE THREAD

**Issue by masterwok** [beautify-web/js-beautify#775]
When using "comma_first" lines leading with a comma after a line containing a comment insert a newline. This is causing newlines to be inserted on every save.

**Before Format:**

    changeCollection.add({
        name: 'Jonathan' // New line inserted after this line on every save
        , age: 25
    });

**After First Save**

    changeCollection.add({
        name: 'Jonathan' // New line inserted after this line on every save
            
        , age: 25
    });

**After Second Save:**

    changeCollection.add({
        name: 'Jonathan' // New line inserted after this line on every save

        
        , age: 25
    });

**Comment by wellcaffeinated** [comment]
+1 I also found this. It's rather annoying.
