### ISSUE TITLE
.class:not(:first or last)

### ISSUE THREAD

**Issue by AlexandreOrlowski** [beautify-web/js-beautify#786]
.class:not(:first-of-type) {}
.class:not(:last-of-type) {}
.class:not(:first-child) {}
.class:not(:last-child) {}

Beautify

.class:not(: first-of-type) {}
.class:not(: last-of-type) {}
.class:not(: first-child) {}
.class:not(: last-child) {}

**Comment by maelfrize** [comment]
+1
I noticed the same bug.
