### ISSUE TITLE
end_with_newline not work

### ISSUE THREAD

**Issue by cybermerlin** [beautify-web/js-beautify#796]
i use
{
    "indent_char": "\t",
    "eol": "\n",
    "indent_level": 0,
    "indent_with_tabs": true,
    "keep_array_indentation": true,
    "keep_function_indentation": true,
    "space_before_conditional": true,
    "brace_style": "end-expand",
    "end_with_newline": true
}

its working if use with parameter -n on execute in console

**Comment by bitwiseman** [comment]
Please provide the command line you're running?  Can you give an example of the code you're running this against as well?
