### ISSUE TITLE
Beautifier breaks ES6 nested template strings

### ISSUE THREAD

**Issue by GuilhermeReda** [beautify-web/js-beautify#797]
Hi, I have a file with the following code.
```javascript
`SELECT
  nextval('${this.options.schema ? `${this.options.schema}.` : ''}"${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

When I format the file, that line becomes
```javascript
`SELECT
  nextval('${this.options.schema ? `
  $ {
    this.options.schema
  }.
  ` : ''}"${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

it is putting a space between $ and {, and that breaks my code.

**Comment by iNovozhilov** [comment]
+1
I have similar problems.
Before:
```js
      return `${err.name}${err.message?`: ${err.message}`:''}\n${stackLines}`;
```

After:
```js
      return `${err.name}${err.message?`: $ {
         err.message
      }
      `:''}\n${stackLines}`;
```

**Comment by bitwiseman** [comment]
Please point to documentation of `${` syntax.

**Comment by GuilhermeReda** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

**Comment by bitwiseman** [comment]
@GuilhermeReda 
Your original example is not valid javascript.  The `${` notation must occur inside backtick pairs.
```javascript
// Note the "`" after the first "?" 
`SELECT
  nextval('${this.options.schema ? `${this.options.schema}.` : ''}"${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

I can't tell exactly what you want to do, but this is closer:
```javascript
`SELECT
  nextval('${this.options.schema ? this.options.schema + '.' : ''} "${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

**Comment by bitwiseman** [comment]
@iNovozhilov 
I think you also need to review your code:
```js
return `${err.name}${err.message ? err.message : ''}\n${stackLines}`;
```

**Comment by iNovozhilov** [comment]
No, @bitwiseman, my code is correct.
I used a nested string template:
 ``` `: ${err.message}` ```
in template
``` `${err.name}${err.message?...<mySubTemplate>...:''}\n${stackLines}` ```.

The ES6 specification is not prohibited to use nested templates describing them in a block of `${...}`

**Comment by iNovozhilov** [comment]
Here is a simple example of correct template:
```js
var a = '1';
var b = `a is ${ `${ a }` }`;
console.log(b);
```
output:
```
a is 1
```

**Comment by GuilhermeReda** [comment]
Take a look at https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/

"The code in a template substitution can be any JavaScript expression, so function calls, arithmetic, and so on are allowed. (If you really want to, you can even nest a template string inside another template string, which I call template inception.)"

**Comment by bitwiseman** [comment]
Every time I think I've seen it all.  Okay, I see what would be needed.  Recursive Template string parsing.     Considering this breaks the code in this case, I'll prioritize it.  In the meanwhile, you'll need to use an annotation to disable beautification of that section.

**Comment by aleung** [comment]
Can I ask how to "use an annotation to disable beautification of that section"? I can't find the answer from readme.

**Comment by bitwiseman** [comment]
Sorry, I meant "directives":
https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only

**Comment by MidnightWonderer** [comment]
I have another problem related to template string.
If js-beautify encounter some code like this.
```javascript
let testTable = function() {
	return `CREATE TABLE IF NOT EXISTS some_table (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
label VARCHAR(64) NOT NULL
PRIMARY KEY (id)
) ENGINE=Aria DEFAULT CHARSET ascii;`;
};
```
It will add extra linebreak between return and the template which make the function return undefined.

**Comment by bitwiseman** [comment]
@MidnightWonderer -
"I have another problem" - that is indeed another problem.  Please open a separate issue for it.  :smile: 
In that new issue, please include the input, expected output (as you've done), and the actual output.

**Comment by iNovozhilov** [comment]
:+1: good job
