### ISSUE TITLE
HTML Beautifier hangs on vnexpress.net

### ISSUE THREAD

**Issue by BruceBerry** [beautify-web/js-beautify#798]
I was studying the behavior of http://vnexpress.net and piped JS and HTML content through js-beautify... beautifying the main HTML never terminates. I am using the node module, but you can reproduce the bug even using the CLI:

    wget "http://vnexpress.net"
    html-beautify index.html

**Comment by bitwiseman** [comment]
This looks to be fixed in 1.6.0.
