### ISSUE TITLE
Improper indentation {{else}} in combination with {{#unless}}

### ISSUE THREAD

**Issue by louwers** [beautify-web/js-beautify#800]
Proper indentation with `{{#if ...}`:
![screen shot 2015-10-18 at 21 32 46](https://github-cloud.s3.amazonaws.com/assets/649392/10566184/fdccf7a6-75df-11e5-906c-7674946a9ed1.png)

Improper indentation with `{{#unless ...}}`:
![screen shot 2015-10-18 at 21 33 51](https://github-cloud.s3.amazonaws.com/assets/649392/10566182/f75f4b26-75df-11e5-96da-009a15fd4f75.png)

**Comment by bitwiseman** [comment]
Need repro steps.  Also, pasting in images is not useful for debugging.  Please provide the text in, use markdown to make it format as code.

**Comment by louwers** [comment]
Gotcha.
With `{{#if ...}}`, `{{else}}` is indented properly (that is, not indented).
```js
{{if something}
    <p>This</p>
{{else}}
    <p>That</p>
{{/if}}
```
With `{{#unless ...}}`, `{{else}}` is NOT indented properly (that is, it is indented).
```js
{{if something}
    <p>This</p>
{{else}}
    <p>That</p>
{{/if}}
```

```js
{{unless something}
    <p>This</p>
{{else}}
    <p>That</p>
{{/unless}}
```

**Comment by bitwiseman** [comment]
Great thanks!  That's much clearer.

**Comment by louwers** [comment]
Yes indeed. :+1: 
Thanks for taking a look at it.

**Comment by bitwiseman** [comment]
Related: #785
