### ISSUE TITLE
Newlines after spacebars/handlebars templates not preserved

### ISSUE THREAD

**Issue by louwers** [beautify-web/js-beautify#801]
Newlines after spacebars/handlebars templates are not preserved.

For example:
```handlebars
{{> pageContentsMenuItem name="Hoofdpagina" path="/"}}
{{> pageContentsMenuItem name="Over het project" path="/over-het-project"}}
```
becomes:
```handlebars
{{> pageContentsMenuItem name="Hoofdpagina" path="/"}} {{> pageContentsMenuItem name="Over het project" path="/over-het-project"}}
```

**Comment by bitwiseman** [comment]
Need repro steps. How are you getting this output?

**Comment by louwers** [comment]
I am using [this](https://github.com/victorporof/Sublime-HTMLPrettify/tree/master/scripts/node_modules/js-beautify) plugin for Sublime Text, it uses js-beautify v1.5.10 and [according to the dev](https://github.com/beautify-web/js-beautify/issues/800#issuecomment-156243887), it is a problem with js-beautify.

**Comment by louwers** [comment]
Try it on http://jsbeautifier.org/:
```js
<a>test</a> 

{{> test}}
{{> test}}
{{> test}}

<a>Test</a>
```
becomes:

```js
<a>test</a> {{> test}} {{> test}} {{> test}}

<a>Test</a>
```

**Comment by lnmunhoz** [comment]
Anyone is working on this?

**Comment by louwers** [comment]
This is a duplicate I found out just now https://github.com/beautify-web/js-beautify/issues/660

**Comment by bax-** [comment]
+1

**Comment by TimvdEijnden** [comment]
In my case 

```
{{#each items as |item|}}
   {{item-view item=item}}
{{/each}}
```

becomes
```{{#each items as |item|}} {{item-view item=item}} {{/each}}```

Is this on the roadmap?

**Comment by louwers** [comment]
See #801 @TimvdEijnden
