### ISSUE TITLE
Implicit Return Function on New Line not Preserved

### ISSUE THREAD

**Issue by timothyeburke** [beautify-web/js-beautify#806]
Original Code:
```js
angular.module('bugcheck.filters').filter('zeroToDash',
    () => (i) => i === 0 ? '-' : i
)
```
I have `"preserve_newlines": true,` in my config file, but I get this output:
```js
angular.module('bugcheck.filters').filter('zeroToDash', () => (i) => i === 0 ? '-' : i)
```
Is there a different config flag I should be using to preserve the line break there?

**Comment by bitwiseman** [comment]
```js
// remains unchanged
angular.module('bugcheck.filters').filter('zeroToDash',
    a
)

// has same problem as reported above
angular.module('bugcheck.filters').filter('zeroToDash',
    (a)
)
```

I'm going to say this is a bug, but the fix may be tricky.  I'll see what i can do in the next milestone. 

What is the syntax your using at `() => (i) =>`?  Can you point me to docs on it?

**Comment by timothyeburke** [comment]
@bitwiseman https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

It's an es6 arrow function using implicit return that's returning an es6 arrow function using implicit return.

Using [babel](http://bit.ly/1l4p7jF), it would look like this in es5:
```
angular.module('bugcheck.filters').filter('zeroToDash', function () {
    return function (i) {
        return i === 0 ? '-' : i;
    };
});
```

**Comment by bitwiseman** [comment]
Okay, the issue is that we don't preserve new lines after comma and before `(`.  Easy to do, but the tricky part will be not breaking other scenarios.  But I'll definitely look at it.

**Comment by timothyeburke** [comment]
I threw this together - it works in my scenario and doesn't break the other tests.
https://github.com/beautify-web/js-beautify/pull/808

**Comment by bitwiseman** [comment]
Well, that's pretty cool.  Thanks!
