### ISSUE TITLE
space_before_conditional doesn't work in python

### ISSUE THREAD

**Issue by derfsubterfuge** [beautify-web/js-beautify#807]
Howdy,

I have my a.js file and .jsbeautifyrc file in the same directory.  My .jsbeautifyrc file looks like:
{"wrap_line_length": 130, "space_before_conditional":false, "indent_size": 4}.

All of my rules are being adhered to except for the "space_before_conditional" rule.

Am I doing something incorrectly?

Right now I'm running the format through Sublime 3 using the JsFormat plugin.  My JsFormat settings file is: {"jsbeautifyrc_files": true}.

Thanks,
Nicholas Castorina

**Comment by bitwiseman** [comment]
Could you provide an example of input, actual output, and expected output?

**Comment by derfsubterfuge** [comment]
Input: http://jsfiddle.net/vpv3u4uh/
Actual Output: http://jsfiddle.net/xyykLjLs/
Expected Output: http://jsfiddle.net/0ck11cm5/

The difference between expected and actual is space in "...for (..." and the space in "...if (...".

**Comment by bitwiseman** [comment]
It looks like this setting is missing from the python implementation, for a while now. :cry:

**Comment by MacKLess** [comment]
This appears to be fixed as of v1.8.6.
