### ISSUE TITLE
ES6 Object Shortand Indenting Weirdly Sometimes

### ISSUE THREAD

**Issue by timothyeburke** [beautify-web/js-beautify#810]
```
// original
function badFormatting() {
    return {
        a,
        b: c,
        d: e,
        f: g,
        h,
        i,
        j:k
    }
}

function goodFormatting() {
    return {
        a: b,
        c,
        d: e,
        f: g,
        h,
        i,
        j:k
    }
}


// output
function badFormatting() {
    return {
        a,
        b: c,
            d: e,
            f: g,
            h,
            i,
            j: k
    }
}

function goodFormatting() {
    return {
        a: b,
        c,
        d: e,
        f: g,
        h,
        i,
        j: k
    }
}
```

In ES6, the object shorthand is getting weirdly indented when preserving new line, but only in the case that the object's first token is the shorthand syntax. This syntax is documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

If you feel this is a legit bug, I'll be glad to look into fixing it.

**Comment by bitwiseman** [comment]
It is a legit bug.
Probably related to https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L741 .
It's the `:` in the first field that we look for. Before ES6 that was a reasonable assumption.
