### ISSUE TITLE
How do I beautify in place using the Python module?

### ISSUE THREAD

**Issue by stodge** [beautify-web/js-beautify#811]
How do I beautify in place using the Python module? I have:

        opts = jsbeautifier.default_options()
        opts.indent_size = 4
        opts.replace = True
        res = jsbeautifier.beautify(fn, opts)

But it doesn't actually do anything. Thanks

**Comment by bitwiseman** [comment]
If you're importing and running beautifier, and if `fn` is a file name, then you probably want to use `beautify_file()` instead of `beautify()`.

**Comment by stodge** [comment]
Ok thanks, how did I miss that! :)
