### ISSUE TITLE
Increment/Decrement Operator on object property extra indent on subsequent line

### ISSUE THREAD

**Issue by timothyeburke** [beautify-web/js-beautify#814]
When not using line terminators, increment and decrement operators on an object property are causing the subsequent line to have an extra level of indentation. Legit bug?

```
// Input
obj.num++
foo()
bar()

obj.num--
foo()
bar()

// Output
obj.num++
    foo()
bar()

obj.num--
    foo()
bar()
```

**Comment by bitwiseman** [comment]
Support for newline as start of new statement is still a bug farm for the beautifier.  Stuff like this.

**Comment by bitwiseman** [comment]
Similar to #1095
