### ISSUE TITLE
PHP processing should take precednce over javascript syntax 

### ISSUE THREAD

**Issue by Wendihihi** [beautify-web/js-beautify#817]
In the example below jsbeautify adds a space in the ending <? which breaks the code.

```
var docTitle = '<?php
echo str_replace("'", "\'", the_title('', '', false)); ?> ';
```

**Comment by bitwiseman** [comment]
To my knowledge single-quoted strings do not support newlines inside them.  What you wrote is not valid javascript, so no surprising that the beautifier gets confused.  

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String for alternatives.

**Comment by Wendihihi** [comment]
With new line, you mean that echo starts at a new line?

**Comment by Wendihihi** [comment]
I tried the line break at several places and I think you are right. The javascript is not valid the way I wrote it. 

Thanks

**Comment by bitwiseman** [comment]
No problem.

**Comment by bitwiseman** [comment]
You got me thinking about it... Each of the following works:
```js
var docTitle = '<?php \
echo str_replace("\'", "\'", the_title(\'\', \'\', false)); ?> ';
var docTitle2 = '<?php \
echo str_replace("\'", "\\\'", the_title(\'\', \'\', false)); ?> ';
var docTitle3 = `<?php
echo str_replace("'", "\\'", the_title('', '', false)); ?> `;
```
Just not sure of what you meant.

**Comment by Wendihihi** [comment]
I don't know if it is correct javascript, but this one works.

var docTitle = '<?php echo str_replace("'", "\'", the_title('', '', false)); ?> ';

Would that be an option as well? I don't need to use a next line.

**Comment by bitwiseman** [comment]
Hm... That "works" but it is not valid javascript.  

Chrome gives this response:
```js
var docTitle = '<?php echo str_replace("'", "\'", the_title('', '', false)); ?> ';
VM1041:2 Uncaught SyntaxError: Unexpected string(…)
InjectedScript._evaluateOn @ VM1039:875
InjectedScript._evaluateAndWrap @ VM1039:808
InjectedScript.evaluate @ VM1039:664
```

You might have a point though.  PHP replacing the text inside the outer single-quotes might make it fine at runtime.  Do you think PHP handling should probably take precedence over javascript syntax?

**Comment by Wendihihi** [comment]
PHP is executed before any Javascripts. But you are right about the error. Maybe I should use one of your examples.

**Comment by bitwiseman** [comment]
Or avoid the new line in the middle, like you said.

**Comment by prettydiff** [comment]
Yeah, the PHP code would be processed before the JavaScript, so the JavaScript would never see the line break inside the PHP code.  The PHP tag should be processed as a single unit so as to avoid a JS parse error.  I just checked and I have the same error in my application.
