### ISSUE TITLE
De-obfuscator does not support JavascriptObfuscator

### ISSUE THREAD

**Issue by Someguy123** [beautify-web/js-beautify#823]
Scripts obfuscated using the website https://www.javascriptobfuscator.com aren't fully supported by JSBeautifier.

At the best, it can decode the strings inside the `_0x???` variable, but doesn't correct the actual variables to useful output.

**Comment by bitwiseman** [comment]
Please provide example input and expected output.

**Comment by bitwiseman** [comment]
@Someguy123 - ping?

**Comment by Someguy123** [comment]
Example Input:

    var _0x7dde=["\x53\x61\x79\x48\x65\x6C\x6C\x6F","\x47\x65\x74\x43\x6F\x75\x6E\x74","\x4D\x65\x73\x73\x61\x67\x65\x20\x3A\x20","\x59\x6F\x75\x20\x61\x72\x65\x20\x77\x65\x6C\x63\x6F\x6D\x65\x2E"];function NewObject(_0x302ax2){var _0x302ax3=0;this[_0x7dde[0]]=function(_0x302ax4){_0x302ax3++;alert(_0x302ax2+_0x302ax4);};this[_0x7dde[1]]=function(){return _0x302ax3};}var obj= new NewObject(_0x7dde[2]);obj.SayHello(_0x7dde[3]);

Current output:

```
var _0x7dde = ["SayHello", "GetCount", "Message : ", "You are welcome."];

function NewObject(_0x302ax2) {
    var _0x302ax3 = 0;
    this[_0x7dde[0]] = function (_0x302ax4) {
        _0x302ax3++;
        alert(_0x302ax2 + _0x302ax4);
    };
    this[_0x7dde[1]] = function () {
        return _0x302ax3
    };
}
var obj = new NewObject(_0x7dde[2]);
obj.SayHello(_0x7dde[3]);
```

Expected output:

```
function NewObject(_0x302ax2) {
    var _0x302ax3 = 0;
    this['SayHello'] = function (_0x302ax4) {
        _0x302ax3++;
        alert(_0x302ax2 + _0x302ax4);
    };
    this['GetCount'] = function () {
        return _0x302ax3
    };
}
var obj = new NewObject("Message : ");
obj.SayHello("You are welcome.");
```
Thus extracting the names from `_0x7dde` (I think it's random each time...) allowing the code to be read much easier.

**Comment by Someguy123** [comment]
Could detect it using something like `_0x([0-9]|[a-f]){4}` as Regex, then checking if the variable is an array.

**Comment by bitwiseman** [comment]
This is by design.   I went to that website and tried their example at
https://www.javascriptobfuscator.com/Javascript-Obfuscator.aspx.  

```js 
// original code
function NewObject(prefix)
{
    var count=0;
    this.SayHello=function(msg)
    {
          count++;
          alert(prefix+msg);
    }
    this.GetCount=function()
    {
          return count;
    }
}
var obj=new NewObject("Message : ");
obj.SayHello("You are welcome.");

// obfuscated code
var _0xb3de=["\x53\x61\x79\x48\x65\x6C\x6C\x6F","\x47\x65\x74\x43\x6F\x75\x6E\x74","\x4D\x65\x73\x73\x61\x67\x65\x20\x3A\x20","\x59\x6F\x75\x20\x61\x72\x65\x20\x77\x65\x6C\x63\x6F\x6D\x65\x2E"];function NewObject(_0xb12dx2){var _0xb12dx3=0;this[_0xb3de[0]]=function(_0xb12dx4){_0xb12dx3++;alert(_0xb12dx2+_0xb12dx4);};this[_0xb3de[1]]=function(){return _0xb12dx3};}var obj= new NewObject(_0xb3de[2]);obj.SayHello(_0xb3de[3]);

// Output from beautification with "unescape" option turned on
var _0xb3de = ["SayHello", "GetCount", "Message : ", "You are welcome."];

function NewObject(_0xb12dx2) {
    var _0xb12dx3 = 0;
    this[_0xb3de[0]] = function(_0xb12dx4) { _0xb12dx3++;
        alert(_0xb12dx2 + _0xb12dx4); };
    this[_0xb3de[1]] = function() {
        return _0xb12dx3 }; }
var obj = new NewObject(_0xb3de[2]);
obj.SayHello(_0xb3de[3]);
```

This exactly how the beautifier is supposed to behave.  It has formatted the code and unescaped the strings. 

What you are requesting would require at least adding another de-obfuscator/unpacker.  In the more general case, it would require full parsing and manipulation of the javascript syntax tree.  Neither of these is in scope for this project at this time.
