### ISSUE TITLE
exponentiation operator

### ISSUE THREAD

**Issue by yukulele** [beautify-web/js-beautify#825]
Don't works with future exponentiation operator `**` (es7)

this
```js
var square=x ** 2;
```

is converted to this
```js
var square = x * * 2;
```

**Comment by yukulele** [comment]
sorry but I realize their is also an assignment operator `**=`

example:
```
var a = 4;
a **= 3;
console.log(a); //64
```

**Comment by bitwiseman** [comment]
Please file a new issue. :smile:

**Comment by yukulele** [comment]
https://github.com/beautify-web/js-beautify/issues/864
