### ISSUE TITLE
HTML after PHP is indented

### ISSUE THREAD

**Issue by Hirse** [beautify-web/js-beautify#826]
Any PHP block causes all following tags to be indented by one level.

This came up as https://github.com/brackets-beautify/brackets-beautify/issues/178 in Brackets Beautify, and has also been mentioned here https://github.com/beautify-web/js-beautify/issues/714#issuecomment-123072020.

Input:
```php
<?php ?>
<!DOCTYPE html>
<html>
<head></head>

<body></body>
</html>
```
Output:
```php
<?php ?>
    <!DOCTYPE html>
    <html>

    <head></head>

    <body></body>

    </html>
```
Desired Output:
```php
<?php ?>
<!DOCTYPE html>
<html>

    <head></head>

    <body></body>

</html>
```

**Comment by cyberbeat** [comment]
It would be nice, if this would also work for php "short-open-tags", for example
<? include("include.php"); ?>

**Comment by Hirse** [comment]
@bitwiseman would it be as easy as just adding `?` and `?=` to the list of `single_tokens` to support php short tags (`<? ?>`) and short echo tags (`<?= ?>`)?
