### ISSUE TITLE
Can't beautify SCSS correctly

### ISSUE THREAD

**Issue by brunofin** [beautify-web/js-beautify#827]
Hey guys, I'm having some trouble to beautify some SCSS files.

I'm using the [Gulp][1] plugin [gulp-jsbeautifier][2], which is a js-beautify wrapper for Gulp, to automatically format a project's source-code after a file's content changes.

The plugin is able to format the JavaScript source-code perfectly the way I want, and it's beautiful!

But when I try to extend this functionality to format the SCSS, it changes everything to a single-line file.

This is a SCSS **input *example***:

    dg-login {
    	
    	height: 470px;
    	width: 440px;
    	border-radius: 15px;
    	background-color: #001d40;
    	background-image: radial-gradient(#28bae2, #001d40);
    	display: block;
    	
    	& > div:not(#compatibleBrowsers) {
    		padding: 48px;
    		img {
    			&#dglogo {
    				margin: {
    					top: 20px;
    					bottom: 20px;
    				}
    			}
    			width: 130px;
    		}
    		
    		input {
    			height: 40px;
    		}
    	}
    
    	#compatibleBrowsers { 
    		position : absolute;
    		right: 70px;
    		bottom: 30px;
    	}
    }

And that's the "formatted" **output**:

    dg-login { height: 470px; width: 440px; border-radius: 15px; background-color: #001d40; background-image: radial-gradient(#28bae2, #001d40); display: block; & > div:not(#compatibleBrowsers) { padding: 48px; img { &#dglogo { margin: { top: 20px; bottom: 20px; } } width: 130px; } input { height: 40px; } } #compatibleBrowsers { position : absolute; right: 70px; bottom: 30px; } }

Unfortunately, I don't want to minimize the SCSS source-code, they do get minimized but on a later step of the build, not of the source-code maintenance.

This is my **.jsbeautifyrc** file:

    {
      "html": {
        "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"],
        "brace_style": "collapse",
        "end_with_newline": true,
        "indent_char": " ",
        "indent_handlebars": false,
        "indent_inner_html": true,
        "indent_scripts": "keep",
        "indent_size": 2,
        "max_preserve_newlines": 0,
        "preserve_newlines": true,
        "unformatted": ["a", "span", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"],
        "wrap_line_length": 0
      },
      "css": {
        "allowed_file_extensions": ["css", "scss", "sass", "less"],
        "end_with_newline": true,
        "indent_char": " ",
        "indent_size": 2,
        "selector_separator": " ",
        "selector_separator_newline": false
      },
        "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],
        "brace_style": "collapse",
        "break_chained_methods": false,
        "e4x": false,
        "end_with_newline": true,
        "indent_char": " ",
        "indent_level": 0,
        "indent_size": 2,
        "indent_with_tabs": false,
        "jslint_happy": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "max_preserve_newlines": 0,
        "preserve_newlines": true,
        "space_after_anon_function": false,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false,
        "wrap_line_length": 0
      }
    }

And finally, the watch defined in the **gulpfile.js**:

    gulp.watch([
         'app/' + project.jsSrcFolder + '/**/*.js',
         'app/' + project.scssSrcFolder + '/**/*.scss'
       ], function(event) {
        if (event.type === 'changed') {
          gulp.src(event.path)
            .pipe(prettify({config: '.jsbeautifyrc', mode: 'VERIFY_AND_WRITE'}))
            .pipe(gulp.dest(event.path.substring(0, event.path.lastIndexOf('/'))));
        }
      });

What it looks like for me is that the `"css"` rules defined on `.jsbeautifyrc` are not being applied to the `SCSS` files, but maybe there can be a misconfiguration from my part. Any help?

  [1]: http://gulpjs.com/http://gulpjs.com/
  [2]: https://www.npmjs.com/package/gulp-jsbeautifier

**Comment by bitwiseman** [comment]
It seems likely that the gulp plugin isn't recognizing scss files as css-ish.  
If you look at https://github.com/tarunc/gulp-jsbeautifier/blob/master/index.js#L155, it looks like the filetypes configuration is not being set the way you think. Please review and try again.

**Comment by brunofin** [comment]
@bitwiseman Thanks for the hint! I managed to make it format SCSS correctly. I needed to replace in my `.jsbeautifyrc` the property `allowed_file_extensions` for `fileTypes`:

```javascript
"css": {
    "fileTypes": [".scss", ".sass", ".less"],
    // rules
}
``` 

Now it works as I need.
