### ISSUE TITLE
Can't deal with XHTML5

### ISSUE THREAD

**Issue by garretwilson** [beautify-web/js-beautify#828]
I'm using XHTML5, which for most practical purposes means HTML5 using the XML syntax---which again is pretty much HTML5 syntax except that it's stricter.

http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml

I have a nice little XHTML5 document, starting with this:

    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE html>
    <html lang="en-us" xmlns="http://www.w3.org/1999/xhtml">

Unfortunately atom-beautify (which uses js-beautify) thinks that the XML declaration is a tag or something, and indents the entire document except for the first line!

    <?xml version="1.0" encoding="utf-8"?>
        <!DOCTYPE html>
        <html lang="en-us" xmlns="http://www.w3.org/1999/xhtml">
        ....

Please recognize the XML declaration in XHTML documents, and don't cause the entire documented because of this. Thanks.

**Comment by garretwilson** [comment]
@bitwiseman , sincere thanks for accepting my bug report and scheduling it to be fixed. It is a refreshing change from other bug reports for other tools, where they have no idea what XHTML is and just say "we don't support XML".

Any idea when 1.6.0 is scheduled to be released? Until then I may have to learn how to write Atom plugins just to write a workaround for the atom-beautify plugin.

Thanks again.

**Comment by bitwiseman** [comment]
Looks like this might be related or partly addressed by #683.  
Release date for 1.6.0 is when I get together enough changes to warrant it.  Probably sometime in January.

**Comment by bitwiseman** [comment]
Fixed!

**Comment by garretwilson** [comment]
I just wanted to say thanks. I had stopped using XML declarations for a while to work around this problem, but a few months ago I realized this was working and brought them back. It helps a lot and I appreciate it.
