### ISSUE TITLE
Alternate formatting for wrapping attributes

### ISSUE THREAD

**Issue by timkelty** [beautify-web/js-beautify#832]
Currently, `js-beautify` does this

```
<input type="hidden"
  name="theName"
  value="">
```

I'm looking for a set of options that achieves this:

```
<input
  type="hidden"
  name="theName"
  value=""
>
```

**Comment by timkelty** [comment]
I suppose this could be 2 settings:

* `wrap_attributes: 'all'` ?
* `close_tag_with_wrapped_attributes_on_new_line: true`

**Comment by bitwiseman** [comment]
`close_tag_with_wrapped_attributes_on_new_line` would be a new setting, right?

**Comment by timkelty** [comment]
Or something to that effect, yes.

The 'wrap_attributes

**Comment by timkelty** [comment]
Or maybe even a new `wrap_attributes_threshold` setting.

**Comment by bitwiseman** [comment]
That would be a different enhancement. :smile: One thing at time.

**Comment by bitwiseman** [comment]
This exists now.  It is call `force-expand-multiline`.
