### ISSUE TITLE
single attribute breaks jsx beautification

### ISSUE THREAD

**Issue by zenyr** [beautify-web/js-beautify#834]
Thanks for your hard work.  Apart from infamous one-lining `{foo:'bar'}` issue (wink wink), I'm having some different issue here. Possibly duplicate issue, but don't know the specific keyword to search here, so I'm submitting one. 

## Problem
single attribute breaks jsx beautification. If I either put out `someAttr` or replace to `someAttr={true}` from the repro case below, it works as expected. 

Edit: Also it seems like only happening at the out-most jsx tag. 

Environment:  atom-beautify, jsbeautifier.org

### Input
```jsx
export default class TestCase extends React.Component {
  render() {
    return ( <div className={this.props.className} someAttr>
      <div>Smth</div>
    </div> );
  }
}
```
### Expected
```
(Untouched from Input)
```
### Output
```jsx
export default class TestCase extends React.Component {
    render() {
      return ( < div className = {
          this.props.className
        }
        someAttr >
        <div>Smth</div> < /div> );
      }
    }
```

**Comment by bitwiseman** [comment]
Yeah, I didn't know ```<div someAttr>val</div>``` is a valid attribute.  I thought attributes needed at least ```someAttr=''```

**Comment by zenyr** [comment]
Pretty sure this is a jsx thing. <CamelCaseTagName
such={{double:'curlybraces'}} {...with.props.spread} /> is definitely NOT a
valid XML ;D

2015년 12월 23일 (수) 오전 3:28, Liam Newman <notifications@github.com>님이 작성:

**Comment by phuna** [comment]
I got same problem today with JSX. I'm using Atom editor with atom-beautify package. I need to change beautifier for `.js` file to Pretty Diff.

**Comment by luckyyang** [comment]
I still got the error, is this bug fixed?

**Comment by c-gargi** [comment]
Input :  ```<MenuItem
          data-id={org.value}
          onClick={self.changeMenuState} 
/>```


Out put : ```< MenuItem data - id = {
					org.value
				}
				onClick = {
					self.changeMenuState
				}
/>```

The space between `data - id` causing parsing error. Please help me with that.

**Comment by bitwiseman** [comment]
@c-gargi Did you turn on `e4x`?

**Comment by c-gargi** [comment]
Yes I did @bitwiseman

**Comment by bitwiseman** [comment]
@c-gargi  When I use `e4x` enabled on http://jsbeautifier.org/ the input remains unchanged.   Disabled, gets the output you saw.  Seems likely there's a settings or versioning issue in your environment.
