### ISSUE TITLE
Vertical alignment of the assignment operator (=) in a list of variable assignments

### ISSUE THREAD

**Issue by kevinkleine** [beautify-web/js-beautify#835]
Hi there! 

Super handy package, it's helping me out a lot, so thanks!

Just wondering, is there a way to align the equal signs (and / or other parts of statements) when assigning to a list of variables?

    var a                = 1,
        someVar          = 'fa',
        myObj.height     = 56.4;

or even

    var a                = 1
    ,   someVar          = 'fa'
    ,   myObj.height     = 56.4
    ;

instead of

    var a = 1,
    someVar = 'fa',
    myObj.height = 56.6;
?

**Comment by bitwiseman** [comment]
No, sorry.  See #603 .
