### ISSUE TITLE
<col> elements within a <colgroup> are getting indented incorrectly

### ISSUE THREAD

**Issue by vaadin-marcus** [beautify-web/js-beautify#836]
Col elements within a `<colgroup>` get indented incorrectly.

Input:
`<colgroup><col><col><col></colgroup>`

Expected:
```
<colgroup>
  <col>
  <col>
  <col>
</colgroup>
```

Actual:
```
<colgroup>
  <col>
    <col>
      <col>
</colgroup>

**Comment by bitwiseman** [comment]
Same thing happens with `<li>` elements right now as well.

**Comment by bitwiseman** [comment]
Here's the list of all the optional tags.  A real solution will require understanding all these.  In the short term, it probably makes sense to just pick the most used ones, like `li` and `col`.
