### ISSUE TITLE
Beautifying bracket-less if/elses

### ISSUE THREAD

**Issue by i1ben** [beautify-web/js-beautify#838]
I am using jsbeautify to beautify a large number of documents (in a proxy) and found a tiny bug. The following code triggers the issue:
```
function(url, callback) {
    var script = document.createElement("script")
    if (true) script.onreadystatechange = function() {
        /* dummy */
    }
    else script.onload = callback;
}
```

This will be re-written to:
```
function(url, callback) {
    var script = document.createElement("script")
    if (true) script.onreadystatechange = function() {
        /* dummy */
    } else script.onload = callback;
}
```

which in turn is a syntax error. There must either be a line break after the } or a semi-colon.

**Comment by bitwiseman** [comment]
Thanks for the clear description. 
Wow, that is ... quite an edge case.  :smile: 
I'll see what what I can do.
