### ISSUE TITLE
Feature request: add support for inline PHP

### ISSUE THREAD

**Issue by thdoan** [beautify-web/js-beautify#839]
Currently, this is not able to properly format code that contains inline PHP, e.g.:

```
  if (isTrue) {
    myVar = '<?php echo $this->__('Case 1') ?>';
  } else {
    myVar = '<?php echo $this->__('Case 2') ?>';
  }
```

It would be nice if you could add support for inline PHP.

**Comment by bitwiseman** [comment]
That's the input?  Is that also the expected output?

**Comment by thdoan** [comment]
@bitwiseman js-beautify appears to trip up only when both the JavaScript string and inline PHP string use the same type of quote (single vs. double), e.g.:

**Input:**
```js
if (true) { str = '<?php echo $this->__('Some text 1') ?>'; }
```
**Output:**
```js
if (true) {
  str = '<?php echo $this->__('
  Some text 1 ') ?>';
}
```

js-beautify adds a newline at the first nested PHP quote character. However, if JS and PHP strings use different quotes, then it's fine, e.g.:

**Input:**
```js
if (true) { str = '<?php echo $this->__("Some text 1") ?>'; }
```
**Output:**
```js
if (true) {
  str = '<?php echo $this->__("Some text 1") ?>';
}
```

**Comment by thdoan** [comment]
My python-fu is not strong, but would it be possible to do something like this (high level)?

1. Extract the inline PHP code (using regexp pattern `/<\?php\s.+?\?>/`) and place it in a temp variable.
2. Replace the inline PHP code with some placeholder text that won't cause the nested quote confusion, e.g.: `if (true) { str = '##inline_php_1##'; }`. The incremented number at the end should be added in case there are multiple inline PHP embeds, e.g.: `if (true) { str = '##inline_php_1## blah blah blah ##inline_php_2##'; }`.
3. Do the beautification.
4. Finally, replace the placeholder text with the inline PHP code that was saved in the temp variable.

You can apply this to pretty much any language that can have inline server code, e.g.:

**ColdFusion:**
```js
if (true) { str = '#request.event.getArg('paramName')#'; }
```

**JSP:**
```js
if (true) { str = '<%= request.getParameter('paramName') %>'; }
```

**Ruby:**
```js
if (true) { str = '<%= @date.strftime('%A, %d %B %Y') %>'; }
```

We'd just need to create a regex pattern for each language, which people can contribute to :-).

**Comment by bitwiseman** [comment]
Yes, as you have recognized this is general problem with templating languages vs pure javascript.  The beautifier has been tweaked and hacked any number of times to make it not behave badly when dealing with templating of various kinds.  The case you describe isn't so bad, but it can get ugly really fast: What happens to the indenting when some uses a more complex php that traverses lines? 

What really need is to switch to a more configurable model where you can specify additional beautifiers and the order in which they run.  Each beautifier would tokenize the parts of the code it understands and pass the rest on to the next one in the list.  In the long run that is the only way I see this being viable. 

Of course, that change would introduce additional complexity and make testing that much harder.

**Comment by thdoan** [comment]
@bitwiseman The work-around isn't perfect, as you stated, but at least it won't break the PHP parser or result in malformed JavaScript. The worst case scenario is that some JavaScript will remain un-beautified.

Since I am using only the Python module, I will try to implement a fix there.

**Comment by bitwiseman** [comment]
We for the fix to be accepted you're going to have to implement it in both javascript and python.  If you're more comfortable writing javascript, you might as well do that and then port to python.

**Comment by thdoan** [comment]
OK, thanks for the heads up. I'm currently using the 'jsbeautifier' Python module from inside Notepad++  using the Python Script plugin to format my text selection. Since I needed a quick fix, I implemented the steps I outlined above in my Python Script plugin script instead of the module itself, which is too complicated for me and would take too long. For those who are curious, here is my fix that is implemented in the Python Script plugin:

```python
sSelectedText = editor.getSelText()
if sSelectedText:
  import jsbeautifier
  import re
  # Extract inline PHP code and replace with placeholder
  matches = re.findall(r'<\?php\s.+?\?>', sSelectedText, re.DOTALL)
  for i, val in enumerate(matches):
    sSelectedText = re.sub(re.escape(val), '@@' + str(i) + '@@', sSelectedText)
  # Beautify selection
  options = jsbeautifier.default_options()
  options.indent_size = 2
  sSelectedText = jsbeautifier.beautify(sSelectedText, options)
  # Replace placeholder with inline PHP code
  for i, val in enumerate(matches):
    sSelectedText = re.sub('@@' + str(i) + '@@', matches[i], sSelectedText)
  # Output to Notepad++
  editor.replaceSel(sSelectedText)
```

Now js-beautify is working, well, beautifully. Here are some sample test cases...

**Input:**
```
if(true){str='1: <?php echo $this->__('Some text 1') ?>\n2: <?php echo $this->__('Some text 2') ?>';}
```

**Output:**
```
if (true) {
  str = '1: <?php echo $this->__('Some text 1') ?>\n2: <?php echo $this->__('Some text 2') ?>';
}
```

**Input:**
```
if (true) { str = 
'1: <?php echo $this->__('Some text 1') ?>\n' +
'2: <?php echo $this->__('Some text 2') ?>' }
```

**Output:**
```
if (true) {
  str =
    '1: <?php echo $this->__('Some text 1') ?>\n' +
    '2: <?php echo $this->__('Some text 2') ?>'
}
```

**Input:**
```
if(true){ str = '<?php
                 if (true) {
                   echo 'Something true';
                 } else {
                   echo 'Something false';
                 }
                 ?>'; }
```

**Output:**
```
if (true) {
  str = '<?php
                 if (true) {
                   echo 'Something true';
                 } else {
                   echo 'Something false';
                 }
                 ?>';
}
```

**Comment by bitwiseman** [comment]
Ah, now I see what you meant. :smile: Well, I can't use this but thank you for posting it so others can.
