### ISSUE TITLE
Bug in less format

### ISSUE THREAD

**Issue by lelinhtinh** [beautify-web/js-beautify#842]
I'm using package HTML-CSS-JS Prettify in Sublime Text 3.
## Bug Extend

Before:

``` less
strong {
    &:extend(a:hover);
}
```

After:

``` less
strong {
    &:extend(a: hover);
}
```

**Comment by bitwiseman** [comment]
Please file a separate issue for the mixins.

**Comment by pmanu93** [comment]
I'm having the same issue.. -.-'

**Comment by bitwiseman** [comment]
@pmanu93 
We could use help fixing this issue.
