### ISSUE TITLE
Issue with beautification of JavaScript in an inline XML-like template

### ISSUE THREAD

**Issue by keul** [beautify-web/js-beautify#843]
The issue born from discussion at https://github.com/Glavin001/atom-beautify/issues/755.

It seems that there are issues when beautify JavaScript code inline a XML file (the JavaScript is used inside an application server template file).

See the original ticket for code examples.

**Comment by bitwiseman** [comment]
Thanks for the heads up, I've commented there.

**Comment by keul** [comment]
As discussed at https://github.com/Glavin001/atom-beautify/issues/755 the issue disappeared and I can't give context to reproduce it anymore.
