### ISSUE TITLE
Keep inline objects option

### ISSUE THREAD

**Issue by vekat** [beautify-web/js-beautify#847]
Hello, it would be great if we could have more control over plain object formatting.

Right now, any object, even the ones with only one parameter gets expanded. For example:
```javascript
var object = { id: 10 };
```
Ends up transformed into:
```javascript
var object = {
  id: 10
};
```
I personally don't think expanding every object is a good thing, not every object is going to be complex, specially plain javascript objects, so this formatting rule often becomes a minor annoyance that adds more lines to your source code.

Additionally (but maybe out of the scope of this feature request), this causes problems with a few javascript features of ES6 ( #511, #382 ), making the code seem ugly.

The internet is full of examples where plain objects are used inline, like this snippet from Node's [about page](https://nodejs.org/en/about/):
```javascript
http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('Hello World\n');
}).[...]
```
I think most of these issues could be solved if we had ways to tell jsbeautifier what to do about small plain objects ( maybe `{name:'hello'}` -> `{ name: 'hello' }`) instead of using the same behavior of function blocks.

**Comment by bitwiseman** [comment]
You are not alone in wanting this.  See #315.  
I just updated that issue's title to include the word "inline".  
Thanks for this well written feature request.  :smile:
