### ISSUE TITLE
Object attribute assigned fat arrow function with implicit return of a ternary causes next line to indent

### ISSUE THREAD

**Issue by underscorebrody** [beautify-web/js-beautify#854]
For example:

Original:
```javascript
test(() => {
    var a = {}

    a.what = () => true ? 1 : 2

    a.thing = () => {
        // some code
    }
})
```
Becomes this:
```javascript
test(() => {
    var a = {}

    a.what = () => true ? 1 : 2

        a.thing = () => {
        // some code
    }
})
```

Notes:
* This can be worked around by putting the ternary in parentheses
* It does not occur if the fat arrow function is being assigned to a the value of a var, only if it's assigned to the attribute of an object
* Only occurs inside a function being passed as an argument to another function
* Only occurs if there is a line between the function with the ternary and the next function

**Comment by bitwiseman** [comment]
Again, are you sure?  I don't see this when I run with the new setting against that input. :smile:

**Comment by bitwiseman** [comment]
In just a minute, I'll have the new code up on the website and you should be able to double check issues you find.

**Comment by underscorebrody** [comment]
This one i'm pretty sure about! I saw this issue but not the other one i mentioned. I will re-test once the code is live though to verify.

**Comment by underscorebrody** [comment]
Okay I've done some additonal testing, it seems this only occurs if the code is inside a function being passed as an argument to another function, i've updated the description with additional notes and specifications for reproduction. I was able to reproduce it in a blank file with the above code in it.

**Comment by bitwiseman** [comment]
Excellent! Thanks!

**Comment by bitwiseman** [comment]
So, both of these work, but the one you provided breaks. Should be easy enough to track down. Thanks again.

```js
test(() => {
    var a = {}

    a.what = () => true ? 1 : 2;

    a.thing = () => {
        // some code
    }
})

test(() => {
    var a = {}

    a.what = () => true ? 1 : 2
    a.thing = () => {
        a()
    }
})
```

**Comment by underscorebrody** [comment]
Interesting, this one also works FYI:

```javascript
test(() => {
    var a = {}

    a.what = () => (true ? 1 : 2)

    a.thing = () => {
        // some code
    }
})
```

**Comment by bitwiseman** [comment]
Yeah, that makes sense.  The `=>` has an implied expression after it.  The `()` makes the expression explicit.  The `;` case is the same way, it make the end-of-statement explicit. The beautifier has a hard time with implicit cases - it often doesn't have enough information to figure out what is going on.

**Comment by underscorebrody** [comment]
Thanks, @bitwiseman !!
