### ISSUE TITLE
Space added to "from++" due to ES6 keyword in v1.6.0

### ISSUE THREAD

**Issue by lzilioli** [beautify-web/js-beautify#858]
After the 1.6.0 update, jsbeautifier wants to make the following change to my code. It wants to change `i++` to `i ++`. Is there a way to prevent this?

**Comment by lnewman-book** [comment]
Could you give some example with a bit more context?  I've got tests that cover that, so it seem strange that the behavior would regress.

**Comment by bitwiseman** [comment]
Could you provide an example with more context?  I have tests for `i++` (https://github.com/beautify-web/js-beautify/blob/master/test/data/javascript/tests.js#L1726), so it is isn't as simple as that.

**Comment by lzilioli** [comment]
This is our .jsbeautifyrc, if that helps. We are using grunt-jsbeautifier

```
{
	"js": {
		"jslint_happy": true,
		"indent_with_tabs": true,
		"space_in_paren": true
	}
}
```

Our package.json:

```
$ cat package.json | grep beaut
45:    "grunt-jsbeautifier": "^0.2.8",
58:    "js-beautify": "^1.5.7",
```

npm install output:

```
grunt-jsbeautifier@0.2.10 node_modules/grunt-jsbeautifier
├── semver@5.1.0
├── rc@1.1.6 (ini@1.3.4, strip-json-comments@1.0.4, deep-extend@0.4.1, minimist@1.2.0)
├── underscore.string@3.2.3
└── lodash@4.0.1

js-beautify@1.6.0 node_modules/js-beautify
├── config-chain@1.1.10 (ini@1.3.4, proto-list@1.2.4)
├── nopt@3.0.6 (abbrev@1.0.7)
└── mkdirp@0.5.1 (minimist@0.0.8)
```

example.js

```javascript
function resizeWindow( from, to ) {
	while ( from !== to ) {
		getWidthStub.returns( from );
		$( window ).trigger( 'resize' );

		if ( from < to ) {
			from++;
		} else {
			from--;
		}
	}
}
```

after running `grunt jsbeautifier`:

```javascript
function resizeWindow( from, to ) {
	while ( from !== to ) {
		getWidthStub.returns( from );
		$( window ).trigger( 'resize' );

		if ( from < to ) {
			from ++;
		} else {
			from --;
		}
	}
}
```

Curiously, I do not see the same behavior if example.js contains

```javascript
var i = 0;
i ++;
```

**Comment by lzilioli** [comment]
After further testing, the following reduced example.js also exhibits the same issue:

```javascript
if ( from < to ) {
	from++;
} else {
	from--;
}
```

**Comment by lzilioli** [comment]
After further digging, we have determined that this is happening likely because `from` is a reserved word es6, which it looks like the release aims to support. I think we can resolve this issue on our end by renaming our variable to something else, however this may still be something you want to address in the package, as it seems from, even under the es6 spec is still a valid variable name.

**Comment by bitwiseman** [comment]
Yes, thank you for drilling in on this.  Yes, `from` should only be treated as a keyword inside an import statement.
