### ISSUE TITLE
using newest update

### ISSUE THREAD

**Issue by jayceekay** [beautify-web/js-beautify#862]
i'm trying to use the recently updated `brace_style` (`collapse-preserve-inline`) with a vim jsbeautify plugin (https://github.com/maksimr/vim-jsbeautify) but after updating everything it's not working. found that command line usage points to `cli.js` which is what vim-jsbeautify invokes. is this file being maintained? from a quick glance it doesn't seem so.

**Comment by bitwiseman** [comment]
See #861 and pick up v1.6.2.
