### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by TaylorHuston** [beautify-web/js-beautify#871]
Not so much of an issue as maybe an enhancement request/looking for advice.

But in general, the beautify doesn't do a good job on AngularJS files. Anything after `angular.module('')` doesn't come out well formatted. Brackets and braces specifically don't seem to line up at all.

Any advice?

**Comment by bitwiseman** [comment]
Give me an example.  I think I know what you're talking about, but I'm not sure.
