### ISSUE TITLE
Dojo unsupported script types.

### ISSUE THREAD

**Issue by joselightware** [beautify-web/js-beautify#874]
Dojo Toolkit uses **script type=”dojo/method”** and **script type=”dojo/aspect”** since this is not a default MIME this will cause formatting issues.

dojo/method and dojo/aspect is highly used when working with Dojo Toolkit, as described in

[https://dojotoolkit.org/reference-guide/1.10/dijit/Declaration.html](https://dojotoolkit.org/reference-guide/1.10/dijit/Declaration.html)

**Comment by joselightware** [comment]
It can be easily fixed like so (line 502 of beautify-html.js)
`
tag_complete.search(/\b(text|application|dojo)\/(x-)?(javascript|ecmascript|jscript|livescript|(ld\+)?json|method|aspect)/) > -1))) {`

Ideally js-beautify shouldn't attempt to format unknown types since in worst case scenario the formatting would be omitted while if wrong formatting is applied to an unknown type code will get messed up affecting its functionality.

**Comment by bitwiseman** [comment]
@joselightware - Could you give an example of input, expected output, and actually output?
