### ISSUE TITLE
sourceMappingURL/sourceURL support?

### ISSUE THREAD

**Issue by yan12125** [beautify-web/js-beautify#885]
Here's a minimized JS: http://cdn.theatlantic.com/assets/static/b/theatlantic/js/video_embed.min.4eca65989dc6.js (from http://www.theatlantic.com/video/iframe/417309/)

Its last line is:

```
//# sourceMappingURL=video_embed.min.js.8dce9ae544de.map
```

And http://cdn.theatlantic.com/assets/static/b/theatlantic/js/video_embed.min.js.8dce9ae544de.map available. Can I import this map when invoking js-beautify?

**Comment by bitwiseman** [comment]
What would you expect the beautifier to do with the source map?

**Comment by yan12125** [comment]
Sorry this is not a good example - video_embed.min.4eca65989dc6.js is compressed but variable names are kept. Here another example: variables names in http://code.jquery.com/jquery-2.2.1.min.js are changed. Is it possible that the beautified code has variable names like http://code.jquery.com/jquery-2.2.1.js. For example, in first few tokens of the second line, ```function (a, b)``` is restored as ```function( global, factory)```.

I was studying JS from TheAtlantic, but seems there's no more information to generate a more readable form. You can consider this feature request as invalid.
