### ISSUE TITLE
deobfuscation feature request

### ISSUE THREAD

**Issue by gSpikey** [beautify-web/js-beautify#893]
`var MyVariable = this[("word", "anotherword", 'A') + 'cti' + 've' + 'XObject'];`

Would be nice to output the above as:
`var MyVariable = this['ActiveXObject'];`

This one is more challenging:
`var abc = defg[("dog", "cat", "dog", "cat", "dog", 'ExpandE') + 'n' + 'vironmentStr' + 'ings'](("dog", "cat", "dog", "cat", "dog", '%T') + 'E' + 'M' + ("dog", "cat", "dog", 'P%')) + ("dog", "cat", "dog", "cat", '/Hello') + 'Wo' + 'rld.' + 'exe';`
I think, but it's just a guess, is supposed to be:
`var abc = defg['ExpandEnvironmentStrings']('%TEMP%')+'/HelloWorld.exe';`

Both of the above use the same basic obfuscation trick.

**Comment by bitwiseman** [comment]
Out of scope for this project.
