### ISSUE TITLE
let x of [a, b, c]

### ISSUE THREAD

**Issue by assaflavie** [beautify-web/js-beautify#895]
jsbeautify converts this:

```
for i of [1, 2] {
    console.log(i);
}
```

to this:

```
for i of[1, 2] {
    console.log(i);
}
```

It gets rid of the space between the `of` operator and the array literal. Is this intentional?
If not, could this be caused by not recognising `of` as a keyword or something?

**Comment by bitwiseman** [comment]
Bug, not intentional.

**Comment by bitwiseman** [comment]
@assaflavie  - ping? Is the es6?  es7?

**Comment by assaflavie** [comment]
I believe it happened with es7.

**Comment by ramonsan** [comment]
for...of is a Javascript ES2015 (ES6) feature.

This code works fine with beautifier:

```
for (let element of array) {
  console.log(element);
}
```

But if you pass an array lineral like @assaflavie said:

```
for (let element of [1,2,3]) {
  console.log(element);
}
```

Beautify deletes the space between _of_ and _[_, causing linters throw an error like: 'Expeted space after keyword'.

**Comment by bitwiseman** [comment]
@ramonsan @assaflavie - Could you send a link to the part of the spec that describes it.

**Comment by ramonsan** [comment]
[Here is the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-for-in-and-for-of-statements) of for of, and here is the [MDN entry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).

**Comment by bitwiseman** [comment]
See #875.
