### ISSUE TITLE
Whitespace after ES7 `async` keyword for arrow functions

### ISSUE THREAD

**Issue by geakstr** [beautify-web/js-beautify#896]
Hello. js-beautify format

``` js
const double = async (x) => x * 2;
```

to

``` js
const double = async(x) => x * 2;
```

It continues to work, but seems like bad behavior. 

It formatted correctly

``` js
const double = async function(x) { return x * 2; };
const double = async x => x * 2;
```

**Comment by paullryan** [comment]
Given that async/await just made it into node7 it would be great for this to get merged...

**Comment by bitwiseman** [comment]
@paullryan - if you want to pick up for @afuous left off and work PR #977 to completion that would be greatly appreciated.

**Comment by serge-nikitin** [comment]
Any progress? 

eslint-config-airbnb is not happy with the lack of space :(
