### ISSUE TITLE
Erroneously changes CRLF to LF on Windows in HTML and CSS

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#899]
See #829.  The same feature needs to be added to html and css.

**Comment by JohnLukeBentley** [comment]
A temporary workaround is to install the atom package [line-ending-converter](https://atom.io/packages/line-ending-converter) and set 
`(Experimental) Normalize File EOL's On Save` to `Win (CRLF)`

Thanks for opening this issue @bitwiseman (and thanks to @garretwilson for your lengthy discussions elsewhere that have brought the issue to the fore).
