### ISSUE TITLE
support for conditional compilation

### ISSUE THREAD

**Issue by paulirish** [beautify-web/js-beautify#9]
code inside of 
    /_@cc_on  
    ...
    @_/
Gets totally flattened by the prettifier.

An example: http://sandbox.thewikies.com/createElement/shimproof.js

Think we could handle this case?

**Comment by bitwiseman** [comment]
https://docs.microsoft.com/en-us/scripting/javascript/advanced/conditional-compilation-javascript

**Comment by bitwiseman** [comment]
This is an ancient issue request.  I'm closing if there is a need for a it currently, someone can reopen or open a new issue.
