### ISSUE TITLE
Bug report: Closing 'body' tag isn't formatted correctly

### ISSUE THREAD

**Issue by jeremykohn** [beautify-web/js-beautify#900]
Here's the text I pasted into jsbeautify.com:

```
<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><h1>Hi!</h1></body></html>
```

After beautifying, most of the text is formatted and indented properly, except for the closing body tag.

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
</head>

<body>
    <h1>Hi!</h1></body>

</html>
```

Basically, the `</body>` tag remains at the end of its line instead of moving down to a new line.

This issue also occurs in the Sublime-HTMLPrettify plugin (I earlier posted a bug report at https://github.com/victorporof/Sublime-HTMLPrettify/issues/284).

**Comment by ErisDS** [comment]
Also encountering this issue, which appears to have occurred between 1.5.4 and 1.5.5, in case that helps.
