### ISSUE TITLE
unary operators in multiline statement - before vs after

### ISSUE THREAD

**Issue by laggingreflex** [beautify-web/js-beautify#901]
Currently this is allowed:

    var mystring = "asdfasdf" +
      "asdfasdfasdf" +
      "asdfasdfasdfasdfasdfasd" +
      "hzallo"

but not this: (it gets flattened to one line)

    var mystring = "asdfasdf"
      + "asdfasdfasdf"
      + "asdfasdfasdfasdfasdfasd"
      + "hzallo"

Latter makes more sense to me because adding more lines doesn't require changineg *two* lines, as is the case with the former in which you have to add the operator + to the previous line in order to add the text in the new line.

thoughts?

**Comment by bitwiseman** [comment]
Those are not unary operators... But in anycase, see 'operator_position' option added in #735. You want to try `after-newline`.
