### ISSUE TITLE
Unexpected result with collapse-preserve-inline and nested objects and arrays

### ISSUE THREAD

**Issue by fabien-michel** [beautify-web/js-beautify#904]
- jsbeautifier : 1.6.2 installed with pip on a fresh python 2.7.5 virtualenv
- Command : js-beautify --brace-style=collapse-preserve-inline test.js

**test.js :**

```
A = {
  B: [
    {D:[
        {a: 1, b:2, c:3},
        {a: 1, b:2, c:3},
        {a: 1, b :2, c:3},
        {a: 1, b:2, c: 3},
        {a: 1, b:2, c:3 },
      ]
    },
    { id: 'yo',
    truc: 'bidule'}
  ]
};
```

**Actual result :**

```
A = {
    B: [{
        D: [
            { a: 1, b: 2, c: 3 },
            { a: 1, b: 2, c: 3 },
            { a: 1, b: 2, c: 3 },
            { a: 1, b: 2, c: 3 },
            { a: 1, b: 2, c: 3 },
        ]
    }, {
        id: 'yo',
        truc: 'bidule'
    }]
};
```

*_Expected result : *_

```
A = {
  B: [
    {
      D: [
        { a: 1, b: 2, c: 3 },
        { a: 1, b: 2, c: 3 },
        { a: 1, b: 2, c: 3 },
        { a: 1, b: 2, c: 3 },
        { a: 1, b: 2, c: 3 },
      ]
    },
    {
      id: 'yo',
      truc: 'bidule'
    }
  ]
};
```

The differences are : array opening and closing bracets, new line between non-inline array of objects

The http://jsbeautifier.org/ version give the expected result

**Comment by fabien-michel** [comment]
Keep array indentation is the option to have the expected result

**Comment by bitwiseman** [comment]
Thanks for the excellent bug report.  I'm reopening this to make sure we add this scenario to the tests.

**Comment by fabien-michel** [comment]
After sending issue i've discovered that jsbeautifier.org has "Keep array indentation" checked by default. And adding this option does the expected result. So the corresponding command is : ```js-beautify --brace-style=collapse-preserve-inline --keep-array-indentation test.js```
