### ISSUE TITLE
huge memory leak

### ISSUE THREAD

**Issue by pps83** [beautify-web/js-beautify#909]
It looks like js-beautify is a giant memory hog. It wasn't meant to be used in code by long-running aps?
If I take any minified js file from google and run js-beautify in a loop I get 50-100M plus on each iteration.

**Comment by bitwiseman** [comment]
Are you talking about the python implementation or the javascript one?  Could you provide an example of how you measured this?

**Comment by pps83** [comment]
I'm talking about js version. I tested more with different scripts, looks like some perhaps trigger some weird results. For example, paste into node:
```
var request = require('request'), beautify = require('js-beautify').js_beautify, base_js;
function test_beautify(){
    beautify(base_js);
    setTimeout(test_beautify, 1000);
}
request('https://s.ytimg.com/yts/jsbin/player-en_US-vfl9rzyi6/base.js', function(err, req, body){
    base_js = body;
    test_beautify();
});
```
This will take hundreds of megs of ram in no time. With other scripts I saw less dramatic results where ram seems to stay stable (e.g. with jquery: https://code.jquery.com/jquery-1.12.2.min.js)

**Comment by bitwiseman** [comment]
I can reproduce the issue with the file you sent.  Thanks!
That said, I don't have time to track it down currently. I'll keep it on the list for a future release.

**Comment by pps83** [comment]
Any pointers on how I could track it down myself?

**Comment by bitwiseman** [comment]
You can try turning off the formatting handlers (so only parsing runs) - comment out the line that calls the handlers formatting. Then turn the handlers back on one by one.

**Comment by bitwiseman** [comment]
I took my own advice.  It looks like this leak is in the parser, not the handlers.

**Comment by bitwiseman** [comment]
This seems to fix the issue: https://github.com/beautify-web/js-beautify/tree/feature/memory-leak .  Minor performance degradation, but acceptable.
