### ISSUE TITLE
Option to put HTML attributes on their own lines, aligned

### ISSUE THREAD

**Issue by JVimes** [beautify-web/js-beautify#916]
Suggest an option to put HTML attributes on their own lines, aligned with each other. For example, turn this:
``` html
<button id="start-signout" class="button button-full" ng-click="vm.signout()" click-animation translate>AUTH.SIGN_OUT</button>
```
into this:
``` html
<button id="start-signout"
        class="button button-full"
        ng-click="vm.signout()"
        click-animation
        translate>AUTH.SIGN_OUT</button>
```

This [has been requested](https://github.com/Microsoft/vscode/issues/2204) and up-voted in a dependent product, Visual Studio Code.

**Comment by siulung4073** [comment]
+1

**Comment by bitwiseman** [comment]
Fixed by @Lukinos.  Thanks!

**Comment by hneuer** [comment]
Great work!

Is there an ETA for the 1.6.5 release? I would really like to see the force-align feature get into vscode!

**Comment by zourun** [comment]
vscode 1.23.1  
"html.format.wrapAttributes": "force-aligned",
not works

**Comment by Seebiscuit** [comment]
VSCode 1.23.1
"html.format.wrapAttributes": "force-aligned" 
Not working in Vue SFC templates

**Comment by Cristy94** [comment]
It would be nice if we could bind this "html.format.wrapAttributes" command to a keyboard shorcut.
