### ISSUE TITLE
Cursor position after beautification at start of file in vim.

### ISSUE THREAD

**Issue by atrioom** [beautify-web/js-beautify#925]
I use js-beautify in vim. Vim passes the file content to `js-beautify` and replaces the current buffer with the result of `js-beautify`. So far so good, but that leaves the cursor position at the start of the file after each invocation. I waste a considerable amount of time scrolling back to the part I just been coding on.
I tried workarounds like leveraging vi's jumplist, sadly to no avail, because the jumplist seems to be wiped after the buffer reload.
Is there a preferred/known solution for that workflow issue?

**Comment by bitwiseman** [comment]
This project doesn't own the vim plugin, sorry.  You might want to file an issue there:
https://github.com/maksimr/vim-jsbeautify.
