### ISSUE TITLE
html-beautify has a list of issues

### ISSUE THREAD

**Issue by rdnz** [beautify-web/js-beautify#926]
One of the issues is, it cannot differ tag character in strings with real tag characters.

`"#<this is a test string>"`

will be reformatted as

```
"#
<this is a test string>"
```

It takes tag character as new HTML tag and indents it. This may break some code.

There are a list of this kind of issues, especially when it's reformatting jsp files which contain JSP tags.

**Comment by bitwiseman** [comment]
@rdnz 
So the input for this case would be:
```
<div class="#<this is a test string>" /> 
```
Or maybe it is this construct inside JSP?  Not clear.

**Comment by bitwiseman** [comment]
This is old and not well defined.  Closing.  Please comment with more info if you still see this.
