### ISSUE TITLE
Using jsbeautifyrc is broken

### ISSUE THREAD

**Issue by Leandros** [beautify-web/js-beautify#929]
**Reproduction Rate:**
3/3 - 100%

**Steps to Reproduce:**
- Create empty `.jsbeautifyrc`: `echo "{}" > .jsbeautifyrc`
- Run this command: `js-beautify -r --config .jsbeautifyrc`

**Result:**

```
$ js-beautify -r --config .jsbeautifyrc.2
[SyntaxError: Unexpected token i]
Error while loading beautifier configuration file.
Run `js-beautify -h` for help.
```

**Expected Result:**
js-beautify should properly execute.

**Additional Information:**
You can repeat the step 1 with any valid `jsbeautifyrc`, even the samples in this repository fail.
I'm using version 1.6.2 fresh installed via NPM.

**Comment by bitwiseman** [comment]
I don't see that syntax error. 
That said, the command line you provided is not valid.  The one that would work is:
```
js-beautify.js -r --config .jsbeautifyrc .jsbeautifyrc
```

Or if you want run it on the code in this repo:
```
./js/bin/js-beautify.js -r --config .jsbeautifyrc .jsbeautifyrc
```

I'm not sure where the error you're getting is coming from, but I would still say this is a bug: the beautifier should report that path to the configuration file it fails to load.

**Comment by Leandros** [comment]
It used to work. 

My script ran the beautifier like this:

```
find ./lib/ -type f -name "*.js" -exec js-beautify -r --config .jsbeautifyrc {} \;
```

**Comment by mherodev** [comment]
Experiencing the same bug. I am running js-beautifier within Atom successfully, however running it from the command line is no dice.

**Comment by mherodev** [comment]
Experiencing the same bug. I am running js-beautifier within Atom successfully, however running it from the command line is no bueno.

`$ js-beautify -r --config .jsbeautifyrc src/js/test.js`

**Comment by Leandros** [comment]
You can use an old version of jsbeautifier. This is what I resorted to.

It's still a mystery to me, how someone can break the most simple use case.

**Comment by bitwiseman** [comment]
@mherodev 
> Experiencing the same bug. I am running js-beautifier within Atom successfully, however running it from the command line is no bueno.

How is it "no bueno"?

**Comment by bitwiseman** [comment]
@Leandros - Which older version did you resort to?

**Comment by Leandros** [comment]
I was still on 1.6.2. Which is weird. 
I, however, found out how and why it's broken. I had a malformed `.jsbeautifyrc` in another directory, which was picked up, even though I pointed to a completely different file.

I have two suggestions:

1. Search from the current directory up for a file matching the specified filename, not the other way around.
2. Improve the error messages. They're completely unusable in the newest version, they were, sort of good, back in 1.5.10. The pointed to the error and pointed out what the error was. Only missing was the actual file where the error occurred in (it's printed as `undefined`), that would make finding the error a lot easier.

**Comment by bitwiseman** [comment]
@Leandros - I've added error output.  

I don't understand your first suggestion.  Could you elaborate?

**Comment by bitwiseman** [comment]
@Leandros  - I'm goint to mark this a closed for now. Please respond when you have a chance.
