### ISSUE TITLE
Make ending bracket on a new line

### ISSUE THREAD

**Issue by fab1an** [beautify-web/js-beautify#937]
Is it possible to format HTML/JSX like this:

```
<div
    className="test"
    style={{
        height: "100px"
    }}
>                               <----- on a new line
    Something
</div>
```

At the moment I get

```
<div
     className="test"
     style={{
                height: "100px"                    <----- too much indentation
            }}>                                  <--- ">" symbol not on a new line
  Something
</div>
```

I use the `esformatter-jsx`, which uses js-beautify to format JSX.

Many thanks.

**Comment by bitwiseman** [comment]
It looks like that project does not use js-beautify.  Have you filed an issue in that project?

**Comment by fab1an** [comment]
Oh, I use a plugin for that project `esformatter-jsx`. I filed an issue there: https://github.com/royriojas/esformatter-jsx/issues/67

The README says it forwards all html-formatting to `js-beautify` though…

**Comment by bitwiseman** [comment]
I think the README is out of date.

**Comment by fab1an** [comment]
Why do you think that?

**Comment by callmevlad** [comment]
@bitwiseman It does look like that projects depends on `js-beautify`: https://github.com/royriojas/esformatter-jsx/blob/master/package.json#L60

**Comment by bitwiseman** [comment]
Ah.  Okay.  😄 Well, the formatting you suggest is not currently part of the beautifier.  I've marked it as a future enhancement.

**Comment by fab1an** [comment]
Thanks!

**Comment by fab1an** [comment]
Oh, nevermind I just found out that eslint has a rule for exactly this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md

**Comment by miguelmota** [comment]
+1 for make ending bracket on a new line feature
