### ISSUE TITLE
incorrectly wrapping <mark> in HTML lists

### ISSUE THREAD

**Issue by garretwilson** [beautify-web/js-beautify#938]
If I have the following HTML code:

```html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<title>span test</title>
</head>

<body>
	<ul>
		<li><span>foo</span></li>
		<li><span>bar</span></li>
	</ul>
</body>

</html>
````

Then js-beautify leaves it just the way I have it. However if I use `<mark>` instead of `<span>`:

````html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<title>mark test</title>
</head>

<body>
	<ul>
		<li><mark>foo</mark></li>
		<li><mark>bar</mark></li>
	</ul>
</body>

</html>
````

Then js-beautify incorrectly adds newlines:

````html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8" />
	<title>mark test</title>
</head>

<body>
	<ul>
		<li>
			<mark>foo</mark>
		</li>
		<li>
			<mark>bar</mark>
		</li>
	</ul>
</body>

</html>
````

This is my complete `.jsbeautifyrc` file:

````
{
	"indent_with_tabs": true,
	"preserve_newlines": true,
	"max_preserve_newlines": 2,
	"end_with_newline": true,
	"wrap_line_length": 0
}
````
js-beautify should treat `<mark>` identically to `<span>`. They are both inline phrase elements.

As you know from issue #840 which I filed, you already updated the list of inline elements to include `<mark>`. There must still be something haywire.

**Comment by garretwilson** [comment]
Ack, forgive me for complaining, but this is _extremely_ irritating to have js-beautify make line breaks in the middle of my paragraphs just because I've used a `<mark>` in the middle!! Why is it treating it specially, I wonder?

**Comment by bitwiseman** [comment]
This is part of the already committed changes the happened in #840.  I'm not sure why they might not be present in the environment you're using, but they went into 1.6.0.  If you try your input on the jsbeautifier.org, mark behaves the same as span.

**Comment by garretwilson** [comment]
Well, OK, here we go again... (I try to say that in a happy way and not personally directed at anyone.) :smiley: 

I shall file a bug with atom-beautify and see how much back-and-forth we get before someone claims it.

There is also the chance that I am doing something stupid, as I've been known to do that at times. :smile: So we shall see...
