### ISSUE TITLE
Shorthand generator functions are formatting strangely

### ISSUE THREAD

**Issue by jgeurts** [beautify-web/js-beautify#941]
var foo = {
        * bar() {
            yield 42;
        }
    };

gets formatted like:

    var foo = { *
        bar() {
            yield 42;
        }
    };

Similarly, 

    var foo = {
        bar() {
            return 42;
        },
        * barGen() {
            yield 42;
        }
    };

is formatted as:

    var foo = {
        bar() {
            return 42;
        },
        *
        barGen() {
            yield 42;
        }
    };

Ideally, the star should be on the same line as the generator name, with a space between the star and the generator name

**Comment by mastephens** [comment]
I would definitely like to see this issue resolved. 
Thanks!  
Mike

**Comment by bitwiseman** [comment]
@mastephens - I'm sorry, my time if very limited currently.  Any help you can provide would be great!

**Comment by jgeurts** [comment]
Awesome, thank you!
