### ISSUE TITLE
Directives to Ignore sections of html?

### ISSUE THREAD

**Issue by JianxinMa** [beautify-web/js-beautify#944]
I have two consecutive inline-block div's. Putting space between them will produce a completely different result. So I need directives to ignore some part of HTML.

But it seems like `/* beautify ignore:start */` works only for JS.

**Comment by bitwiseman** [comment]
That is correct.

**Comment by jasjuang** [comment]
+1 for this feature because of the Django template tags

**Comment by codeclown** [comment]
Just bumped into this. It is an actual issue which changes the resulting page in the browser.

Example:

```
<p>Line of text with parentheses (<em>like this</em>) is formatted strangely.</p>
```

Result:

```
<p>Line of text with parentheses (
  <em>like this</em>) is formatted strangely.</p>
```

Browser will show a whitespace/space in place of the line break, so it renders like this:

> Line of text with parentheses ( _like this_) is formatted strangely.

Any way to prevent this from happening?

**Comment by rygnar** [comment]
+1 this would be very nice to have!

**Comment by aiguofer** [comment]
Would love to have this for some ejs syntax as well...

something like 
```
<!-- beautify ignore:start -->
....
<!-- beautify ignore:end -->
```
would be awesome and consistent with js

**Comment by andreyvolokitin** [comment]
@bitwiseman, how hard this can be to implement? Wondering if I can try to do a fork

**Comment by bitwiseman** [comment]
@andreyvolokitin - The HTML beautifier is not the easiest thing to follow. PR always welcome.

**Comment by gabrielmaldi** [comment]
Same as #575

@andreyvolokitin have you had a chance to look into this? Thanks!

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/commit/c4f03cce7e8fa5aa488e33fe480870369167f376
