### ISSUE TITLE
how break line after tag end

### ISSUE THREAD

**Issue by arshtepe** [beautify-web/js-beautify#947]
i have xml

``` xml
    <default>
            <datasource>
                <structure ref=""></structure><select></select></datasource>
            <route ref=""></route>
        </default>
```

what i have after beautify

``` xml
<default>
    <datasource>
        <structure ref=""></structure><select></select></datasource>
    <route ref=""></route>
</default>
```

what i need

``` xml
<default>
    <datasource>
        <structure ref=""></structure>
        <select></select>
    </datasource>
    <route ref=""></route>
</default>
```

js

``` js
beautify(editor.getValue(), {
            e4x: true,
            wrap_line_length: 160,
            break_chained_methods: true,
            unescape_strings: true,
            indent_with_tabs: true
        })

```

but works, if add
unformatted: []

**Comment by bitwiseman** [comment]
There isn't an xml beautifier per se.  At this time, what you describe is the best way to achieve the behavior you're looking for.

**Comment by arshtepe** [comment]
@bitwiseman But in this example i have tags equals to html

**Comment by arshtepe** [comment]
up

**Comment by bitwiseman** [comment]
@arshtepe - 
https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L123
This is the list of unformatted elements.  Are you using the latest jsbeautifier version?  
What kind of file are you running this against?
