### ISSUE TITLE
Cannot get html formatting to work

### ISSUE THREAD

**Issue by DominicTobias** [beautify-web/js-beautify#950]
Hi,

I'm trying to get the formatter to work with a string like this:

```
<button class="button button--blue" type="button">Button</button><button class="button button--blue" type="button">Button With Icon (todo)</button><button class="button button--blue" disabled="" type="button">Disabled Button</button>
```

However passing it through the formatter does nothing (same output):

```js
import jsBeautify from 'js-beautify';

console.log(jsBeautify.html(`<button class="button button--blue" type="button">Button</button><button class="button button--blue" type="button">Button With Icon (todo)</button><button class="button button--blue" disabled="" type="button">Disabled Button</button>`));
```

What am I doing wrong? thanks

**Comment by prettydiff** [comment]
You are doing nothing wrong and the output (being nearly identical to the input) is correct.  You were probably hoping for some white space to be injected between the buttons.  The reason this is not happening is that it would break HTML code by applying white space adjacent to inline tags that is then rendered as white space text on the page to the user.

Consider this example:

    <p>Hello <em>my</em><strong>friend</strong>.</p>

That would render as:

Hello *my***friend**.

If you were to force a space between the `</em>` and the `<strong>` the text would render as:

Hello *my* **friend**.
