### ISSUE TITLE
&:first-of-type:not(:last-child) when prettified insert erroneous white character

### ISSUE THREAD

**Issue by gvocale** [beautify-web/js-beautify#952]
When I prettify the following code in Sublime-HTMLPrettify

`.div { &:first-of-type:not(:last-child) {} } `

the result is:

`.div { &:first-of-type:not(: last-child) {} } `

Which throws an error in sass, because there is a spacing before "last-child".

I have opened an issue in the Sublime-HTMLPrettify Repo (https://github.com/victorporof/Sublime-HTMLPrettify/issues/310), but they told me to file it here as they use this library.

**Comment by gvocale** [comment]
Just to add to this, when I run HTML/CSS/JS Prettify on the following code, extra white spaces gets added, which throws errors in the console.

Before Prettify:

`<feColorMatrix type="matrix" values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0" result="gray"></feColorMatrix>`

After Prettify:
`<feColorMatrix type="matrix " values="0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0.2126 0.7152 0.0722 0 0 0 0 0 1 0 " result="gray "></feColorMatrix>`

**Comment by vorbe** [comment]
I get the same sort of thing:
`.class {
	.class:not(:last-child) {
		color:red;
	}
}

.class:not(:last-child) {
	color:red;
	}`

The latter is fine, but it's the nesting that causes the issue.

**Comment by bitwiseman** [comment]
https://github.com/Glavin001/atom-beautify/issues/827#issuecomment-188760688
