### ISSUE TITLE
if-cases are not rendered correctly in XML

### ISSUE THREAD

**Issue by G-Kevin** [beautify-web/js-beautify#955]
Hi,

Templates in old Burning Board 2 software by Woltlab use if-cases in xml-syntax.

These are not rendered correctly.

This is the source as it should look like

``` html
<tr align="left">
  <td colspan="2" class="tablea" align="center">
      <span class="smallfont">
          <span id="inhalt">
              <img src="./a.jpg" alt="a" />
          </span>
          <if($error !='' )>
              <then>Here is something going on...</then>
          </if>
          <form>
              <input type="file" />
          </form>
      </span>
  </td>
</tr>
```

But it is beautified to:

``` html
<tr align="left">
  <td colspan="2" class="tablea" align="center">
      <span class="smallfont">
          <span id="inhalt">
              <img src="./a.jpg" alt="a" />
          </span>
      <if($error !='' )>
          <then>Here is something going on...</then>
          </if>
          <form>
              <input type="file" />
          </form>
          </span>
  </td>
</tr>
```

Could you please inplement a correct indentation?

**Comment by bitwiseman** [comment]
XML is not fully supported, only html.  

Also, is `<if($error !='' )>` valid XML?  Could you add a link to documentation?

**Comment by G-Kevin** [comment]
I am sorry, but there is no documentation anymore as support was dropped back in 2007. But I can still give you examples.

I don't know whether this valid XML, but this could be a kind of Smarty language?

**Comment by prettydiff** [comment]
That would not be valid XML syntax, specifically: `($error !='' )`.  XML would require that be a quoted attribute value.  This is some form of HTML template syntax, as mentioned earlier *Templates in old Burning Board 2 software by Woltlab*.  That doesn't mean this code is wrong, but just that it isn't valid XML.

**Comment by G-Kevin** [comment]
Would a support for this be possible anyway? Maybe an option would be good to enable this kind of syntax. The beautifier does not throw an error, it just does not indent the code so there would be no negative effects on valid XML code.

**Comment by bitwiseman** [comment]
@G-Kevin 
I don't have the bandwidth to make this happen, but you are welcome to take a swing at updating.  Just be sure to add sufficient tests to match the format you're looking for.  
Cheers!

**Comment by bitwiseman** [comment]
Old and dealing with edge case technology.  Closing.
