### ISSUE TITLE
Bug with css calc() function

### ISSUE THREAD

**Issue by Nessiah** [beautify-web/js-beautify#957]
The formatter is removing the whitespace before the + operator inside a calc function. This white space is actually required for the rule to work, so this effectivelly breaks it.

Example:
`height: calc(100% + 20px);`

Turns into:
`height: calc(100%+ 20px);`

**Comment by vzamanillo** [comment]
Same here, the formater brake the rule.

**Comment by raulfunkie** [comment]
Seems to happen with almost every selector.

What I write:
`li:hover > ol`

When I run Beautify:
`li:hover> ol`

It doesn't really brake this particular declaration, but it happens with the calc() function too as mentioned above.

**Comment by bitwiseman** [comment]
https://github.com/Glavin001/atom-beautify/issues/1100
