### ISSUE TITLE
Error: Insertion of a whitespace character while formatting

### ISSUE THREAD

**Issue by francjohny** [beautify-web/js-beautify#959]
Adds a whitespace after ':' when using :last-child Selector
_Current version of Sublime Text - Build 3114_

![85824736-37ce-11e6-89bf-ecb93323b8cd](https://cloud.githubusercontent.com/assets/10945677/16261162/324580f0-3888-11e6-9a7d-61c05fae3b51.png)

**Comment by bitwiseman** [comment]
#618
