### ISSUE TITLE
CSS Prettify Transform bug: "border-radius: .2rem .2rem 0 0;" => "border-radius: .2rem.2rem00;"

### ISSUE THREAD

**Issue by buildbreakdo** [beautify-web/js-beautify#963]
"border-radius: .2rem .2rem 0 0;"

is transformed to 

"border-radius: .2rem.2rem00;”

Using chrome.

**Comment by bitwiseman** [comment]
Could you give a bit more info about how to repro this? I this part of a larger CSS file?

**Comment by bitwiseman** [comment]
When I beautify the following on http://jsbeautifier.org/ I get unchanged output:
```
<style>
    border-radius: .2rem .2rem 0 0;
</style>
```

**Comment by bitwiseman** [comment]
@buildbreakdo  ?

**Comment by buildbreakdo** [comment]
@bitwiseman Look into reproducing this today, switched libraries and need to revert to repro

**Comment by buildbreakdo** [comment]
@bitwiseman Couldn't reproduce this again unfortunately.. will switch back to using js-beautifier, if I see it again, will be sure to properly document repro steps.

**Comment by bitwiseman** [comment]
@buildbreakdo - Cool, thanks.
