### ISSUE TITLE
<dfn> tag

### ISSUE THREAD

**Issue by Kristinita** [beautify-web/js-beautify#966]
My text formatted:

```
В силу причин
<dfn>а</dfn> и
<dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.
```

I believe that [<dfn> tag should not be moved](http://www.w3schools.com/tags/tag_dfn.asp) to a new line, I think it should be so:

```В силу причин <dfn>а</dfn> и <dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.```

Thanks.

**Comment by bitwiseman** [comment]
What is the tag containing these tags?  That is probably the tag determining whether these tags get moved.

**Comment by Kristinita** [comment]
@bitwiseman , `<ul>` and `<li>`:

```
            <ul type="disc" class="russianletters">Существуют отдельные средства для экспорта/импорта паролей, закладок, однако
                <br />
                <br />
                <li> лично у меня они, бывало, отказывали, когда возникала в них острая необходимость,</li>
                <li> восстанавливают не всё-всё, как было,</li>
                <li> перенос отнимает время.</li>
                <br /> В силу причин
                <dfn>а</dfn> и
                <dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.
            </ul>
```

**Comment by bitwiseman** [comment]
It is the containing element that controls where those elements move to.  If you wrap those in a `<span>` it should behave as your desire.

**Comment by Kristinita** [comment]
I use [Sublime-HTMLPrettify](https://github.com/victorporof/Sublime-HTMLPrettify) plugin for Sublime Text 3. I [wrote](https://github.com/victorporof/Sublime-HTMLPrettify/issues/324) to author of this plugin, he [told](https://github.com/victorporof/Sublime-HTMLPrettify/issues/324#issuecomment-231515268) me to write here.

When I enter the command `command: htmlprettify`, `<dfn>` tag is transferred to the new line, wherever he was. Example:

```
<body>
    Example
    <dfn>Test</dfn> Example
    <dfn>Test</dfn>
</body>
```

In my opinion, the tag [must remain](http://www.w3schools.com/tags/tag_dfn.asp) on the previous line. 

* Operating system and version:  
   Windows 10 Education
* Sublime Text:
   Build 3114

If I have to provide more information, please ask me. Thanks.

**Comment by bitwiseman** [comment]
The `<body>` tag contents are supposed to be reformatted.  

If you'd like the input you mentioned to not be reformatted, try using `<span>`.  Like this:
```html
<body>
    <span>В силу причин <dfn>а</dfn> и <dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.
</span>
</body>
```

**Comment by bitwiseman** [comment]
Have you tried your input on http://jsbeautifier.org/ ?  You input seems to produce the output you are asking for there.

**Comment by Kristinita** [comment]
Yes, my code:

`<body>Sasha<dfn>Sweet</dfn><dfn>Honey</dfn></body>`

In Sublime Text:

`{ "keys": ["ctrl+7", "ctrl+h"], "command": "htmlprettify" },`

![](http://i.imgur.com/JQHO4il.gif)

In [jsbeautifier.org](http://jsbeautifier.org/):

![](http://i.imgur.com/VXJdfGi.gif)
