### ISSUE TITLE
Break on <></>

### ISSUE THREAD

**Issue by arshtepe** [beautify-web/js-beautify#970]
I know that is not valid tag <></>, but if check null in this place https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify-html.js#L875 it is work

**Comment by bitwiseman** [comment]
Good find.  Please submit pull request and tests!  Thanks!

**Comment by arshtepe** [comment]
@bitwiseman  Sorry for issue, i have old version 1.6.2 in 1.6.3 this fixed
