### ISSUE TITLE
Publish the library via cdn

### ISSUE THREAD

**Issue by zxqfox** [beautify-web/js-beautify#971]
https://cdnjs.com/libraries or https://www.cloudflare.com/features-cdn/#how-can-cloudflare-offer-a-free-service would be great.

**Comment by zxqfox** [comment]
Guess, we should just add this to readme:
https://cdn.rawgit.com/beautify-web/js-beautify/master/js/lib/beautify-html.js

**Comment by bitwiseman** [comment]
Great idea thanks!

**Comment by zxqfox** [comment]
I've added https://github.com/cdnjs/cdnjs/issues/8518 but scared about doing it by self.
