### ISSUE TITLE
ES7 tagged template strings - space betwen function and backtick

### ISSUE THREAD

**Issue by memee** [beautify-web/js-beautify#981]
JSBeautify is putting space between template string and function:
```
`const closure = template `${0}``
```

and it should leav it as here

```
`const closure = template`${0}``
```

Specification:

http://www.ecma-international.org/ecma-262/6.0/#sec-tagged-templates

MDN:  

https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/template_strings

**Comment by bitwiseman** [comment]
Please provide a link to the feature specification for this.
