### ISSUE TITLE
collapse-preserve-inline does not preserve simple, single line ("return") statements

### ISSUE THREAD

**Issue by octavian-nita** [beautify-web/js-beautify#982]
Hi guys,

As indicated, when using `"brace_style": "collapse-preserve-inline"` in `.jsbeautifyrc`, simple, single-line statements don't seem to always be preserved. At least one such case is when the 'simple' statement is a `return`: for a function definition such as
```
function foo(arg) {
  if (!arg) { return false; }
  // ...
  return true;
}
```
I get (after beautifying)
```
function foo(arg) {
  if (!arg) {
    return false; }
  // ...
  return true;
}
```
whereas I would have expected no change in the input.

Needless to say, I am using the latest version of js-beautify.

**Comment by bitwiseman** [comment]
yes, this is a bug, there are some places where they are not preserved.   Mostly due to specific keywords.
