### ISSUE TITLE
CSS's newline_between_rules has no effect

### ISSUE THREAD

**Issue by cguillemette** [beautify-web/js-beautify#990]
I looked at the code and it doesn't look like the rule 'newline_between_rules' is applied for CSS.

Anyone else, has this problem?

Thanks

**Comment by bitwiseman** [comment]
Please add repro steps and example input, expected output, and actually output.

**Comment by cguillemette** [comment]
It's been a while, I don't remember - should have posted more details. Thanks.

**Comment by bitwiseman** [comment]
@durz, @smartforcedev, @rontav - You gave this a thumbs up.  Can any of you reproduce this?

**Comment by rontav** [comment]
Sorry about that. I thought that this should do something else. I've tested it and it works like it should.
I guess I should read the docs/inline comments before I vote on issues.

**Comment by bitwiseman** [comment]
Not problem.  Just checking.  😄
