### ISSUE TITLE
Publish to cdnjs

### ISSUE THREAD

**Issue by bitwiseman** [beautify-web/js-beautify#992]
Follow on to #971 from @zxqfox. 

> I've added cdnjs/cdnjs#8518 but scared of doing it by self.

**Comment by PeterDaveHello** [comment]
cdnjs/cdnjs#8518 was merged! I think you can update the document now :smile: 

BTW, CDNJS provides both src and minified version:

e.g.

```
https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify.js
https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify.min.js

https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify-css.js
https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify-css.min.js

https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify-html.js
https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.6.4/beautify-html.min.js

```

**Comment by bitwiseman** [comment]
@PeterDaveHello - Thanks!

**Comment by PeterDaveHello** [comment]
No problem!

**Comment by bitwiseman** [comment]
From https://github.com/cdnjs/cdnjs/pull/8915 : 

> NPM download stats (optional):
> Downloads in the last day: 8553
> Downloads in the last week: 144719
> Downloads in the last month: 485453 (!)

https://cdnjs.com/libraries/js-beautify


Just need to add links to README.md to finish this.

**Comment by PeterDaveHello** [comment]
I just added a badge in #1078
