### ISSUE TITLE
Django Defect with quotes nested inside a markup template tag

### ISSUE THREAD

**Issue by prettydiff** [beautify-web/js-beautify#993]
https://github.com/Glavin001/atom-beautify/issues/1123

**Comment by bitwiseman** [comment]
For reference: 

> # Description
> when i use atom-beautify for Django Templates code
> 
> ```
>     <link rel="stylesheet" href="{% static "css/lightbox.css" %}">
> ```
> 
> add space between `static ""`
> 
> ```
>     <link rel="stylesheet" href="{% static " css/lightbox.css " %}">
> ```
> 
> # Expected Results
> The beautified code should have looked like:
> 
> ```
>     <link rel="stylesheet" href="{% static "css/lightbox.css" %}">
> ```
> # Steps to Reproduce
> 1. Add code to Atom editor
> 2. Run command `Atom Beautify: Beautify Editor`
> 3. This beautified code does not look right!
> 
> # Debug
> Here is a link to the `debug.md` Gist:
> 
> # Checklist
> * [Y] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
> * [Y] I have reloaded (or restarted) Atom to ensure it is not a caching issue
> * [ ]  Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
>   so I know this is not a duplicate issue
> * [ ]  Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by bitwiseman** [comment]
Take a look at 1.9.0-beta2 now up on https://beautifier.io .
It doesn't support django templates yet, but it addresses this issue in other languages.
