### ISSUE TITLE
Preserve small objects inline (Old issue resurfaced)

### ISSUE THREAD

**Issue by Ceyaje** [beautify-web/js-beautify#995]
This:

    var x = { x: 2, y: 4 }

should not turn into this:

    var x = {
        x: 2,
        y: 4
    }

This issue was marked fixed with the solution being to set brace_style to "collapse-preserve-inline". This hasn't worked, and objects are still being spread across multiple lines.

**Comment by bitwiseman** [comment]
How are you running js-beautifier?  Command-line or as a part of another tool?  If part of another tool, please make sure that tool as the latest version.

**Comment by Ceyaje** [comment]
I'm working in Brackets. I'm assuming the code is the same since the version number is the same. I installed it fresh. Is there a different fix for brackets?

**Comment by bitwiseman** [comment]
So, you're using this: https://github.com/brackets-beautify/brackets-beautify ?

**Comment by Ceyaje** [comment]
Ah! I didn't know it was a separate project! I assumed it was the same one

**Comment by ttsirkia** [comment]
This definitely works in Atom using js-beautify with no issues. It must be related to Brackets.

**Comment by Ceyaje** [comment]
You are correct. I just read on the other project that the latest version of brackets-beautify hasn't been uploaded to the servers because of an error. I assumed that since I wasn't getting an update option that it was the most recent. I'm now up to date and it works as expected!

**Comment by bitwiseman** [comment]
☀️ Great!  ☀️

**Comment by ttsirkia** [comment]
@Ceyaje any reason not to close the ticket if the issue is resolved?
